### ISSUE TITLE
Pre-built binaries?

### ISSUE THREAD

**Issue by leonelwilliams** [google/gvisor#10]
Nice project! Would it be possible to have pre-built binaries generated to decrease time needed to get up and running?

**Comment by nlacasse** [comment]
Thanks!  We're still working on a release plan for gVisor, but pre-built binaries will likely be part of that plan.

**Comment by warpfork** [comment]
I'd like to offer a slightly more verbose form of +1 to this...

Even if the release plan isn't fully finalized, a (totally non-final, throws warnings everywhere, etc) binary release would still have a ton of value for me as a reference for early evaluation.  For example, I'm interested in getting an order of magnitude (4MB or 40 or 400?) estimate of just plain how big the binaries are -- this will be useful input for roadmapping whether and in what way I can bundle this with other projects I work on :)

(I'd say I'd look forward to running `ldd` on the binaries as well, but I'd also understand if getting full static linking is a stretch goal for the first release :))

**Comment by prattmic** [comment]
FWIW:

```
$ ldd bazel-bin/runsc/linux_amd64_pure_stripped/runsc
	not a dynamic executable
```

```
$ size bazel-bin/runsc/linux_amd64_pure_stripped/runsc
   text	   data	    bss	    dec	    hex	filename
12357670	 140344	 137536	12635550	 c0cd9e	bazel-bin/runsc/linux_amd64_pure_stripped/runsc
```

```
$ ls -lh bazel-bin/runsc/linux_amd64_pure_stripped/runsc
-r-xr-xr-x 1 mpratt eng 14M May 10 09:27 bazel-bin/runsc/linux_amd64_pure_stripped/runsc
```

**Comment by nlacasse** [comment]
We now have nightly builds.  You can find the latest here:
https://storage.googleapis.com/gvisor/releases/nightly/latest/runsc

I'll be updating the instructions on the README soon.
