### ISSUE TITLE
Failed to overwrite an existing gofer file

### ISSUE THREAD

**Issue by tanjianfeng** [google/gvisor#1006]
Below behavisor is observed in runsc:

```
$ ll /etc/shells
-rw-r--r-- 1 root root 73 Aug 21  2018 /etc/shells
$ ll /etc/issue
-rw-r--r-- 1 root root 26 Aug 20  2018 /etc/issue
$ cat /etc/shells
# /etc/shells: valid login shells
/bin/sh
/bin/bash
/bin/rbash
/bin/dash
$ cat /etc/issue
Ubuntu 18.04.1 LTS \n \l

$ cp /etc/issue /etc/shells
/# ll /etc/shells
-rw-r--r-- 1 root root 26 Oct 14 09:18 /etc/shells  <--- file size is correct.
$ cat /etc/shells
# /etc/shells: valid login                                          <--- file content is not changed but truncated.
```

Note:
- We use /etc/issue and /etc/shells, just to exemplify two files which already exist in the image; cannot reproduce using new files.
- Have to read the file before overwrite it to reproduce.

**Comment by fvoznika** [comment]
What Linux version are you using? If you are before 4.19, you're hitting a limitation of overlayfs. Open files are not updated after they have been modified and copied from the lower to the upper layer. Given that the Sentry caches FDs, they still point to the old file and stale data is read.

You can fix it by upgrading your kernel or using `--overlayfs-stale-read` with [this patch](https://github.com/google/gvisor/pull/982).

**Comment by zhangningdlut** [comment]
> What Linux version are you using? If you are before 4.19, you're hitting a limitation of overlayfs. Open files are not updated after they have been modified and copied from the lower to the upper layer. Given that the Sentry caches FDs, they still point to the old file and stale data is read.
> 
> You can fix it by upgrading your kernel or using `--overlayfs-stale-read` with [this patch](https://github.com/google/gvisor/pull/982).

I write a simple and imperfect patch：
https://github.com/zhangningdlut/gvisor/commit/bc80ba119d48c5e8c275192dd36ca2269f0d7e9d .
We want a quick fix. It can just work, but I am not sure if there are some problems.

**Comment by fvoznika** [comment]
I added a few comments to your change. It will work as long as the file
hasn't been mapped into memory. If you can't wait, my recommendation is to
patch https://github.com/google/gvisor/pull/982 into your branch. I'm
waiting for one more approval and will checkin the fix soon.

**Comment by fvoznika** [comment]
With this fix, you just need to enable `--overlayfs-stale-read` to make it work.

We would like to eventually remove this flag and stop supporting Linux versions without the overlayfs feature to update open FDs after files are copied to the upper layer. Do you have plans to update to Linux 4.19 or above anytime soon?
