### ISSUE TITLE
Convert `atomic.Value` usages for `*T` to `atomic.Pointer[T]`.

### ISSUE THREAD

**Issue by ayushr2** [google/gvisor#10089]
### Description

Similar to https://github.com/google/gvisor/commit/7480450936dc2da5485d2599deea2ef83ae9d391, we can get some perf gains from converting `atomic.Value` to `atomic.Pointer[T]` where possible. `atomic.Value` requires users to cast the result of `.Load()` into the appropriate type. Using `atomic.Pointer[T]` avoids the casting overhead.

Here are the remaining usages of https://cs.opensource.google/search?q=%22atomic.Value%22&sq=&ss=gvisor%2Fgvisor.

**Comment by Deepali1211** [comment]
Please assign to me.
