### ISSUE TITLE
some performance comparison between docker and gvisor

### ISSUE THREAD

**Issue by yanghaichao12** [google/gvisor#102]
i make some performance testing about network and I/O,and that's result:
the bandwidth of docker(by iperf):
![image](https://user-images.githubusercontent.com/20693362/45478713-1cfaf480-b777-11e8-8718-76897e7fe118.png)
the bandwidth of gvisor:
![image](https://user-images.githubusercontent.com/20693362/45478843-7531f680-b777-11e8-9115-8c802eb0419a.png)
the i/o performance of docker:
![image](https://user-images.githubusercontent.com/20693362/45478768-4287fe00-b777-11e8-9c8e-4fd28336c744.png)
the i/o performance of gvisor:
![image](https://user-images.githubusercontent.com/20693362/45478902-9abf0000-b777-11e8-8ee0-a698d84fc3f4.png)
that's so big gap.is it normal? or just  i used the wrong testing methods

**Comment by fvoznika** [comment]
**Network:** Can you provide more information about your setup? I suspect you're running the server inside the container and the client outside in the same machine? If that is the case, docker runs your container as regular processes and they will use the loopback within the same machine. gVisor virtualizes the network and cannot use the loopback in the same way. Though client and server are normally in different machines, thus separating client and server in different machines will make for a more realistic test. Putting them in different machines you'll see gVisor about 20%-100% slower than regular docker, depending on the workload.

**File IO:** Writing 1GB in 1024 blocks requires millions of syscalls. Regular docker makes a direct syscall to the host which just copies the payload into memory and returns quickly. This workload measures how fast syscalls can be made more than it tests how fast files can be written. The cost of each syscall in gVisor is much higher, and it shows in this test. To test how fast an application can write, you need to use more realistic buffer sizes, like 64KB or 1MB. See below:

Docker:
```
root@6a68c7f8fada:/# dd if=/dev/zero bs=65536 count=16384 of=file.out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.690617 s, 1.6 GB/s

root@6a68c7f8fada:/# dd if=/dev/zero bs=1048576 count=1024 of=file.out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.505983 s, 2.1 GB/s
```
gVisor:
```
root@8304fb5dcbda:/# dd if=/dev/zero bs=65536 count=16384 of=file.out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 3.01801 s, 356 MB/s

root@8304fb5dcbda:/# dd if=/dev/zero bs=1048576 count=1024 of=file.out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.538968 s, 2.0 GB/s
```

**Comment by yanghaichao12** [comment]
@fvoznika hi，i tested network again.this time,i set client and server in different physical machine, and get very close transfer speed.
docker
![image](https://user-images.githubusercontent.com/20693362/45660199-2fd04900-bb2a-11e8-848e-18553b19bb60.png)
gVisor
![image](https://user-images.githubusercontent.com/20693362/45660264-7c1b8900-bb2a-11e8-98d8-79e0b1ac0d13.png)
i think this speed limitation is due to physical switch.  thx！

another thing,obviously ,for gVisor,if client and server in seperate physical machine can get better speed than in same physical machine(but different vm),i can't figure out it. is it because of vSwitch？

**Comment by yanghaichao12** [comment]
@fvoznika ok, i'll do more testing,thx
