### ISSUE TITLE
PyTorch CPU doesn't take advantage of all cores unless set_num_threads is called

### ISSUE THREAD

**Issue by thundergolfer** [google/gvisor#10205]
### Description

One of my Modal colleagues observed recently that within our gVisor runtime PyTorch was not taking advantage of available CPU cores. If we ran a simple PyTorch program with an increased amount of CPU `quota`, this did not improve execution time:

```bash
$ modal run -q cpu_request.py --cpu=1
MODAL_CLOUD_PROVIDER: CLOUD_PROVIDER_OCI
OPENBLAS_NUM_THREADS: 1
Runtime: 5.65 seconds

$ modal run -q cpu_request.py --cpu=2
MODAL_CLOUD_PROVIDER: CLOUD_PROVIDER_OCI
OPENBLAS_NUM_THREADS: 2
Runtime: 5.25 seconds

$ modal run -q cpu_request.py --cpu=4
MODAL_CLOUD_PROVIDER: CLOUD_PROVIDER_OCI
OPENBLAS_NUM_THREADS: 4
Runtime: 5.01 seconds

$ modal run -q cpu_request.py --cpu=8
MODAL_CLOUD_PROVIDER: CLOUD_PROVIDER_OCI
OPENBLAS_NUM_THREADS: 8
Runtime: 5.37 seconds
```

Using our `runc` runtime and 8 cores, the computation could be performed in under a second: 

```
$ MODAL_FUNCTION_RUNTIME=runc modal run -q cpu_request.py --cpu=8
MODAL_CLOUD_PROVIDER: CLOUD_PROVIDER_OCI
OPENBLAS_NUM_THREADS: 8
Runtime: 0.82 seconds
```

If `torch.set_num_threads` is used then both gvisor and runc exhibit similar performance. 

### Steps to reproduce

I've narrowed the problem down to how PyTorch is getting the number of threads to use during initialization. 

```dockerfile
# Dockerfile
FROM python:3.11.8-slim-bullseye

RUN pip install torch numpy
COPY <<EOF repro.py
import ctypes
libtorch_cpu = ctypes.CDLL("/usr/local/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so")
print(f"{libtorch_cpu._ZN2at15get_num_threadsEv()=}")
print(f"{libtorch_cpu._ZN2at23get_num_interop_threadsEv()=}")
EOF

ENTRYPOINT ["python3", "repro.py"]
```

This reproduction directly accesses the functions PyTorch uses to report available threads. I did this because importing PyTorch seems to cause side-effect initialization and I wanted to eliminate this. 

**gVisor**

* `get_num_threads` is shown to be too low, `1` or `2`. 
* `get_num_interop_threads` always shows the correct amount of available cores.

**runc**

* `get_num_threads` always shows the correct amount of available cores.
* `get_num_interop_threads` shows the total amount of cores on the system.

We are using the `--cpu-num-from-quota` `runsc` flag. 

### runsc version

```shell
`runsc version release-20230717.0-12-g0244c8c19fb7
spec: 1.1.0-rc.1`
```

### docker version (if using docker)

```shell
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:01 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:01 2023
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0```
```

### uname

`Linux ip-10-1-1-198 5.15.0-1055-aws #60~20.04.1-Ubuntu SMP Thu Feb 22 15:49:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by milantracy** [comment]
I updated the Dockerfile at `Steps to reproduce`

I assume that python version needs to match the path at ctypes.CDLL

```
# Dockerfile
FROM python:3.11.8-slim-bullseye

RUN pip install torch numpy
COPY <<EOF repro.py
import ctypes
libtorch_cpu = ctypes.CDLL("/usr/local/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so")
print(f"{libtorch_cpu._ZN2at15get_num_threadsEv()=}")
print(f"{libtorch_cpu._ZN2at23get_num_interop_threadsEv()=}")
EOF

ENTRYPOINT ["python3", "repro.py"]
```

**Comment by thundergolfer** [comment]
Oh yes thank you. Apologies that's a copy paste error.
