### ISSUE TITLE
runsc without docker

### ISSUE THREAD

**Issue by matti** [google/gvisor#103]
It looks like there are no official docs on how to run gvisor without docker - I found this https://medium.com/@remco_verhoef/sandboxing-with-gvisor-b9979bd424b9 - but I couldn't get the ip.sh stuff working.

I can not test save/restore (#80) without this, see https://gvisor.googlesource.com/gvisor/+/master/g3doc/checkpoint_restore.md for docker incompatibility notes

**Comment by iangudger** [comment]
What problem did you have with ip.sh?

**Comment by matti** [comment]
@iangudger some errors - didnt bother to try again - I really think there should be official docs on this subject

**Comment by matti** [comment]
I don't understand why this project is so secretive - why can't you document how to use runsc?

**Comment by hugelgupf** [comment]
runsc implements the OCI runtime spec. Any guide you can find online on how to use runc standalone should somewhat apply to runsc as well - if you combine those guides with the information in our README, you should be able to figure out pretty quickly.

The code is all there - no secrets. I speculate lack of time leads to lack of documentation, and the short answers we've been giving.

**Comment by nl5887** [comment]
@matti could you send me an email at remco@dutchcoders.io? I'll be happy to help you out, with this issue, and update the documentation accordingly.

**Comment by ianlewis** [comment]
@matti For the record, I think it's valid to have a doc on running it directly with runsc. I'll work on something in the next couple days.

**Comment by matti** [comment]
@ianlewis thank you!

**Comment by matti** [comment]
@nl5887 I did send you an email

**Comment by matti** [comment]
@ianlewis did you have a chance to work on this?

**Comment by ianlewis** [comment]
@matti I didn't get a chance to work on this specifically but I did add a [docs](https://github.com/google/gvisor/tree/master/docs) directory as a WIP place to build out a more scalable set of  docs. guides like the one you are looking for could go there

**Comment by ianlewis** [comment]
@matti FWIW We finally got a website up and wrote a bunch of docs. Hopefully this is something like what you were looking for?
https://gvisor.dev/docs/user_guide/oci/

Let me know if there is anything else you'd like to see added. It's on my list of things to do to write a guide on the networking bits. https://github.com/google/gvisor-website/issues/38

**Comment by ianlewis** [comment]
I'm going to go ahead and close this. Feel free to submit a new issue if there is other doc you want to see added.
