### ISSUE TITLE
Can not specify `gofer.SupportedMountOptions` from OCI spec.

### ISSUE THREAD

**Issue by qiyuanl-db** [google/gvisor#10316]
### Description

It is not clear to me how users can specify `SupportedMountOptions` per mount in `config.json`. Tried following configs, but none succeeded.
```
mounts: [
  {
    destination: $mount.destination,
    source: $mount.source,
    options: ["ro", "rbind"],
    dcache: 0,
    type: "bind",
  },
]
```
and
```
mounts: [
  {
    destination: $mount.destination,
    source: $mount.source,
    options: ["ro", "rbind", "dcache=0"],
    type: "bind",
  },
]
```

**Comment by ayushr2** [comment]
This is an issue with gVisor. I think https://github.com/google/gvisor/pull/10322 should fix it.

**Comment by ayushr2** [comment]
Passing the option in the `options` array is the right way to do it (the second config you attached above).
