### ISSUE TITLE
Metrics server flag no longer exists

### ISSUE THREAD

**Issue by jseba** [google/gvisor#10455]
### Description

I'm trying to do some memory usage debugging and tried to enable the metrics server according to the documentation [here](https://gvisor.dev/docs/user_guide/observability/). But that flag no longer seems to exist and when I tried with the Docker instructions it was also failing the same way, with `flag provided but not defined: -metrics-server`. 

Is the documentation out of date or is the metrics server broken?

### Steps to reproduce

1. Follow https://gvisor.dev/docs/user_guide/observability/ to set up a Docker runtime with the metrics server flag
2. Restart Docker daemon
3. Run a test container with that runtime

### runsc version

```shell
master
```

### docker version (if using docker)

```shell
Client: Docker Engine - Community
 Version:           26.1.1
 API version:       1.45
 Go version:        go1.21.9
 Git commit:        4cf5afa
 Built:             Tue Apr 30 11:48:04 2024
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.1
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.9
  Git commit:       ac2de55
  Built:            Tue Apr 30 11:48:04 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### uname

Linux devbox 6.1.0-18-arm64 #1 SMP Debian 6.1.76-1 (2024-02-01) aarch64 GNU/Linux

**Comment by ayushr2** [comment]
I think you misspelled `--metric-server`: https://github.com/google/gvisor/blob/0bf4e9f6e5d877c25ae5b7c536266fd383dcd709/runsc/config/flags.go#L64

(drop the "s" after "metrics")

**Comment by jseba** [comment]
Well that's embarrassing 🤦. 

Any chance you have a chat somewhere I can ask dumb questions like this in the future? 😄

**Comment by ayushr2** [comment]
No issues :)

> Any chance you have a chat somewhere

We do have https://gitter.im/gvisor/community, but it seems like it is quite inactive. In the meantime, you could use https://groups.google.com/g/gvisor-users for questions.
