### ISSUE TITLE
Running gvisor with shared root filesystem

### ISSUE THREAD

**Issue by Anjali05** [google/gvisor#10476]
### Description

I am trying to run gvisor with the following flags:

```
{
    "runtimes": {
        "runsc": {
            "path": "/usr/local/bin/runsc",
	    "runtimeArgs": [
                "--platform=kvm",
		"--file-access=shared"
            ]
        }
    }
}
```
However, docker daemon is throwing the following error:
```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/moby/d3c904e7db17b152e93d47ba85c7bb39be0c9db7c91adf664166bfd0a4404312/log.json: no such file or directory): /var/lib/docker/runtimes/runsc.X0SBJ1Y9GDSWFG14P5PMC3W4JS-B053F60FZXZMRR6041C629MD0==== did not terminate successfully: exit status 128: W0522 20:13:51.312802   30065 util.go:64] FATAL ERROR: overlay flag is incompatible with shared file access for rootfs
overlay flag is incompatible with shared file access for rootfs
: unknown
```

I am not sure if I am missing anything in the setup. Any help would be highly appreciated!

### runsc version

```shell
runsc version release-20231106.0
spec: 1.1.0-rc.1
```

### docker version (if using docker)

```shell
Docker version 26.1.2, build 211e74b
```

**Comment by ayushr2** [comment]
`--file-access=shared` means that the rootfs should be mounted in "shared" mode. Which means that the container rootfs can change from **outside** of the sandbox. So the sandbox has to do really expensive revalidation work to keep the sandbox-internal state of rootfs in sync with that is there on host.

By default, the rootfs is mounted as an overlay mount. See more about this in this blog: https://gvisor.dev/blog/2023/05/08/rootfs-overlay/. With overlay, we can't do the "revalidation" work mentioned above to sync with host state. Overlay mode assumes that rootfs does not change on host (common case).

So:
1. Do you really want to set this flag? Do you expect rootfs to change externally? If not, do not set `--file-access=shared`.
2. If you do really want to use this, turn off overlay setting with `--overlay2=none` and it should work fine.
