### ISSUE TITLE
Errors While building from Source

### ISSUE THREAD

**Issue by rainfld** [google/gvisor#105]
I'm trying to build gVisor from source using bazel. However, by typing "bazel build runsc", I got following error messages:

ERROR: ~/.cache/bazel/_bazel_llei1/7ebbd2b82372340cc34333219aebd7b3/external/io_bazel_rules_go/go/private/rules/sdk.bzl:37:10: **unexpected keyword 'provides' in call to rule**(implementation: function, test: bool = False, attrs: dict or NoneType = None, outputs: dict or dict-returning function or NoneType = None, executable: bool = False, output_to_genfiles: bool = False, fragments: sequence of strings = [], host_fragments: sequence of strings = [], _skylark_testable: bool = False, toolchains: sequence of strings = [], doc: string = "")
ERROR: error loading package '': Extension file 'go/private/rules/sdk.bzl' has errors
ERROR: error loading package '': Extension file 'go/private/rules/sdk.bzl' has errors
INFO: Elapsed time: 2.834s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

My platform is Ubuntu 16.04.3 LTS with kernel version 4.15.0-34-generic
I installed all the required packages. 
bazel version outputs:
Build label: 0.13.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed May 23 11:17:23 2018 (1527074243)
Build timestamp: 1527074243
Build timestamp as int: 1527074243

**Comment by prattmic** [comment]
I suspect your version of Bazel is too old. Can you try the latest [release](https://github.com/bazelbuild/bazel/releases)?

**Comment by rainfld** [comment]
That works! Thanks a lot @prattmic
