### ISSUE TITLE
Write a test verifying that the CUDA sniffer works

### ISSUE THREAD

**Issue by EtiennePerot** [google/gvisor#10541]
### Description

The sniffer tool is nice but needs a test.

### Is this feature related to a specific bug?

No.

### Do you have a specific solution in mind?

How this could work:

- Add a flag like `--enforce_compatibility=true` which makes the sniffer fail if the program calls any `ioctl` that isn't supported.
- Write a trivial CUDA program that is fully supported, then write a test that runs the sniffer on it (with the `--enforce_compatibility=true` flag) and verify that it runs successfully.
- Add a `--do_invalid_ioctl=true` flag to the trivial CUDA program which makes it do an `ioctl` that doesn't actually exist in the NVIDIA `ioctl` ABI. Write a test that runs the sniffer on it (with the `--enforce_compatibility=true` flag set on the sniffer, and the `--do_invalid_ioctl=true` set on the CUDA program) and verify that the sniffer fails as expected.

This can be added as a GPU-only test in BuildKite.

Tips: [Here is an example of a test for a simple CLI tool](https://github.com/google/gvisor/blob/master/test/metricsviz/metricsviz_cli/metricsviz_cli_test.go). Notice the use of `exec.Command` to spawn the CLI tool during the test, and the BUILD rule for the `go_test` target points to the binary [using the `data` attribute](https://github.com/google/gvisor/blob/45c5479cb26078edca3c054d197b43e1b867e622/test/metricsviz/metricsviz_cli/BUILD#L17). This allows it to get a path to the compiled CLI tool under test using [testutil.FindFile](https://github.com/google/gvisor/blob/45c5479cb26078edca3c054d197b43e1b867e622/test/metricsviz/metricsviz_cli/metricsviz_cli_test.go#L36).

**Comment by EtiennePerot** [comment]
@AC-Dap

**Comment by AC-Dap** [comment]
Fixed by PR https://github.com/google/gvisor/pull/10550
