### ISSUE TITLE
Support all ioctls used by `nvidia-smi`

### ISSUE THREAD

**Issue by EtiennePerot** [google/gvisor#10627]
### Description

`nvidia-smi` is likely the very first workload that prospective gVisor users will try to run when assessing GPU compatibility. gVisor should aim to support as much of it as possible.

Right now it works well enough to not crash, but fails to report some statistics such as wattage usage and cap, or ECC memory status. Need to add support for all `ioctl`s used by `nvidia-smi`.

### Is this feature related to a specific bug?

N/A

### Do you have a specific solution in mind?

Add `nvidia-smi` as a GPU regression test. Then add all `ioctl`s it calls that aren't supported yet.

**Comment by thundergolfer** [comment]
cc @mattnappo as you were about to work on this.

**Comment by EtiennePerot** [comment]
Thanks @mattnappo!
