### ISSUE TITLE
[Feature] Asking for support for termux on android(with termux-glibc)

### ISSUE THREAD

**Issue by fish4terrisa-MSDSM** [google/gvisor#10640]
### Description

I don't have much knowledge of docker or some other container platforms.However, I do know much about proot, a rootless chroot-like program which is widely used to run linux in termux/android. However, proot is using ptrace and have many strange problems and large performance decrease.
It seems that gvisor re-implemented many linux syscalls and even the network,which can make linux running on termux faces less problems. And it's possible to run gvisor without root. 

**So is it possible to port gvisor to termux in order to make it possible for termux users to run linux in termux with less performance cost?**

Now glibc is ported to termux, so we won't need to consider the difference between bionic libc and glibc.

(P.S. I know that this question shouldn't be asked here, but I didn't find another place for me to make a feature request.Do we have a forum or discussion area?)

**Comment by EtiennePerot** [comment]
I haven't used termux, but I can't think of a reason why this wouldn't work. I'd note that gVisor's own TTY emulation is decent (you can run `htop`, `btop`, SSH, etc. just fine) but not always perfect. I can't think of any popular CLI program that's known to be broken in gVisor off the top of my head, but there may still be some missing features.

Can you describe in more details what you'd be looking for in the end state here? That termux spawns a shell running in gVisor by default rather than a proot shell?

> (P.S. I know that this question shouldn't be asked here, but I didn't find another place for me to make a feature request.Do we have a forum or discussion area?)

You can use the mailing list: https://groups.google.com/forum/#!forum/gvisor-users

**Comment by fish4terrisa-MSDSM** [comment]
> I haven't used termux, but I can't think of a reason why this wouldn't work. I'd note that gVisor's own TTY emulation is decent (you can run `htop`, `btop`, SSH, etc. just fine) but not always perfect. I can't think of any popular CLI program that's known to be broken in gVisor off the top of my head, but there may still be some missing features.
> 

I want to use gvisor as a replacement for proot, and act as an rootless chroot. 
Termux doesn't spawn a proot shell. Instead, termux run a normal android binary. A good way to understand this is that termux is a linux distro using bionic libc  (glibc is also ported to termux) and use /data/data/com.termux as the root.

> Can you describe in more details what you'd be looking for in the end state here? That termux spawns a shell running in gVisor by default rather than a proot shell?
> 

In my expaction, maybe we will have a simple tool based on gvisor(gvisor seems to be a backend of other container platforms), which can act like chroot but don't need root , /dev , /proc and even doesn't need some namespace support.
For example, if that program is called `gvisor-chroot`, i want to use it as this:
```
$ id
uid=10312(u0_a312) gid=10312(u0_a312) groups=10312(u0_a312),3003(inet),9997(everybody),20312(u0_a312_cache),50312(all_a312)
$ gvisor-chroot --rootless /data/data/com.termux/files/home/archlinux-rootfs --bind /sdcard:/media/sd --uid 0 --gid 0
[root@localhost]# id
uid=0(root) gid=0(root) group=0(root)
[root@localhost]# cat /etc/os-release
NAME="Arch Linux"                                                                                 
PRETTY_NAME="Arch Linux"                                                                          
ID=arch                                                                                           
BUILD_ID=rolling                                                                                  
ANSI_COLOR="38;2;23;147;209"                                                                      
HOME_URL="https://archlinux.org/"                                                                 
DOCUMENTATION_URL="https://wiki.archlinux.org/"   
SUPPORT_URL="https://bbs.archlinux.org/"                                                          BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"                           
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```
The reason why I don't use docker is that although docker itself is ported to termux, it will only work with root(even in its rootless mode, as some namespace feature is missing for rootless users in termux),and docker is something too heavy for a termux user who only wants to run linux distro in termux.
(This program can also be used as a test suite or a way for programmers to experience gvisor's features.)

> > (P.S. I know that this question shouldn't be asked here, but I didn't find another place for me to make a feature request.Do we have a forum or discussion area?)
> 
> You can use the mailing list: https://groups.google.com/forum/#!forum/gvisor-users

I'll have a try of the mailing list. Maybe I will ask this question in the mailing list again. But first I have to get to know how to **send** mails into the mailing list instead of only **reading** the mailing list.

**Comment by EtiennePerot** [comment]
Your message is now [shown on the mailing list](https://groups.google.com/g/gvisor-users/c/DyIXSbxNOKI), so I am closing this issue and will respond on the mailing list soon.
