### ISSUE TITLE
NV2080_CTRL_CMD_GRMGR_GET_GR_FS_INFO: Missing nvproxy ioctl used by NCCL 

### ISSUE THREAD

**Issue by luiscape** [google/gvisor#10647]
### Description

When running https://github.com/NVIDIA/nccl-tests with [CUDA 12.5.0](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html), the following ioctl is reported missing:

```
runsc.log.20240710-210438.005411.boot.txt:W0710 21:04:41.244107  1128432 frontend.go:497] [  24:  24] nvproxy: unknown control command 0x20803801 (paramsSize=1928)
```

Reference here: https://github.com/NVIDIA/open-gpu-kernel-modules/blob/caa2dd11a0db42e5d6130f627dd15ef404b7597d/src/common/sdk/nvidia/inc/ctrl/ctrl2080/ctrl2080grmgr.h#L57C1-L58C1

### Steps to reproduce

Build image using:
```
FROM nvidia/cuda:12.5.0-devel-ubuntu22.04
RUN apt install git -y
RUN git clone https://github.com/NVIDIA/nccl-tests.git && \
    cd nccl-tests && make
```

Then run any of of the available programs. For example:
```
/nccl-tests/build/all_gather_perf
```
The program will fail reporting that no GPUs are available and gvisor logs will contain the unimplemented version.

We are running the latest supported NVIDIA driver (550.54.15) which comes with CUDA 12.4. Running a 12.4 container works as expected.

This isn't an issue for us but wanted to open ea ticket for completeness.

**Comment by ayushr2** [comment]
@AC-Dap Could you have a look?

**Comment by EtiennePerot** [comment]
@AC-Dap also added a regression test running NCCL tests in ab513ff9bbb61b3b39f924f6f5a1e3bbf87386b4.
