### ISSUE TITLE
Will gVisor implement the cgroup setting related feature?

### ISSUE THREAD

**Issue by YvesChan** [google/gvisor#107]
The current version of gvisor have NOT implemented setting the host cgroup like runc does. Is it better to integrate the cgroup related functions into the runsc? Or using an independent tools to set the cgroup outside?

**Comment by fvoznika** [comment]
We will soon start working on this. The plan is to integrate cgroup related functions into runsc. runsc will setup cgroup on the host and run the sandbox inside it. For multi-container, the cgroup setting will be the aggregation of all containers running inside the sandbox.

**Comment by fvoznika** [comment]
cgroup setting implemented in 29cd05a7c66ee8061c0e5cf8e94c4e507dcf33e0
