### ISSUE TITLE
//test/syscalls/linux:prctl_test fails to build on x86_64 host because of aarch64 dependencies

### ISSUE THREAD

**Issue by alsemenov** [google/gvisor#10709]
### Description

I'd like to build native syscall tests on Linux x86_64 host for Linux x86_64 target for some experiments. I use simple `bazel build` command (see steps to reproduce) and get build failure. I am not good with debugging bazel builds. It seems that building `//test/syscalls/linux:prctl_test` somehow triggers build of `//vdso:vdso` for aarch64 architecture, which seems strange - by default target platform should be equal to host platform. I not sure if aarch64 binaries are really necessary for `//test/syscalls/linux:prctl_test`. BTW, `bazel build //vdso:vdso` completes without errors and builds only x86_64 binaries.

### Steps to reproduce

```bash
$ $ ../bazelisk-linux-amd64 build //test/syscalls/linux:prctl_test
Starting local Bazel server and connecting to it...
INFO: Analyzed target //test/syscalls/linux:prctl_test (326 packages loaded, 16376 targets configured).
ERROR: /home/alsemenov/w/gvisor/vdso/BUILD:17:8: Executing genrule //vdso:vdso failed: (Exit 127): bash failed: error executing Genrule command (from target //vdso:vdso) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
/bin/bash: line 1: /usr/bin/aarch64-linux-gnu-gcc: No such file or directory
Target //test/syscalls/linux:prctl_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 16.737s, Critical Path: 2.01s
INFO: 245 processes: 173 internal, 72 linux-sandbox.
ERROR: Build did NOT complete successfully
```

### uname

Linux alsemenov.local 5.15.0-107-generic #117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### repo state (if built from source)

release-20240624.0-35-gb488752cb

**Comment by ayushr2** [comment]
Try `make build TARGETS=//test/syscalls/linux:prctl_test`. It uses a Docker container with the right bazel version installed to do all the bazel work. It works transparently with the host filesystem, so the build artifacts will be available outside the container on your host. We are aware that invoking a local installation of `bazel` can lead to that error.

**Comment by alsemenov** [comment]
Using `make build TARGETS=//test/syscalls/linux:prctl_test` works fine, thank you
