### ISSUE TITLE
Docs refactor

### ISSUE THREAD

**Issue by ianlewis** [google/gvisor#109]
The current README is great and has a lot of info but it doesn't really scale well and it's unclear where to add additional docs. I would like to refactor it into some docs pages that can be expanded in the future.

Currently there is just a README and some files in the g3docs directory.

Some options:
1. Markdown in the docs/ directory.
2. Use a docs generation tool like [gitbook](https://www.gitbook.com/). Example: https://book.kubebuilder.io/
3. Create a separate repo to hold the docs (maybe create a whole website?)

Proposed docs layout:
- Intro
- User Guide/
- User Guide/Quick Start
- User Guide/Running in Docker
- User Guide/Using the KVM Platform
- Architecture Guide/
- Architecture Guide/Why gVisor?
- Architecture Guide/Technical Architecture
- Contributor Guide/
- Contributor Guide/Building gVisor and Running Tests (Developer workflow?)
- Contributor Guide/Submitting Code and Code Reviews

**Comment by kevinGC** [comment]
I don't know about gitbook specifically, but I like having all the docs together in a coherent format like that. Regarding suggestion 3, I would prefer not to split docs into a separate repo.

**Comment by ranchochen** [comment]
Hi, markdown like guide is cool.

**Comment by ianlewis** [comment]
Closing this since we released https://gvisor.dev/
Contributions can be made to the docs at https://github.com/google/gvisor-website
