### ISSUE TITLE
emacs fails with "Could not open file: /dev/tty"

### ISSUE THREAD

**Issue by chetan-reddy** [google/gvisor#10925]
### Description

When I run `docker run -it --rm --network=none silex/emacs` , I get a working instance of emacs.
But when I try with `runsc` , it fails immediately

> $ docker run -it --rm --runtime=runsc --network=none silex/emacs
emacs: Could not open file: /dev/tty

I tried with podman as well and got the exact same results. 

### Steps to reproduce

> $ docker run -it --rm --runtime=runsc --network=none silex/emacs
emacs: Could not open file: /dev/tty

### runsc version

```shell
runsc version release-20240916.0
spec: 1.1.0-rc.1
```

### docker version (if using docker)

```shell
Client:
 Version:           20.10.24+dfsg1
 API version:       1.41
 Go version:        go1.19.8
 Git commit:        297e128
 Built:             Thu May 18 08:38:34 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.24+dfsg1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       5d6db84
  Built:            Thu May 18 08:38:34 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20~ds1
  GitCommit:        1.6.20~ds1-1+b1
 runc:
  Version:          1.1.5+ds1
  GitCommit:        1.1.5+ds1-1+deb12u1
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### uname

Linux mee 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux

**Comment by nlacasse** [comment]
We just need to plumb the `host.TTYFileDescription` into `/dev/tty` device.  It currently always returns `EIO` from open:

https://github.com/google/gvisor/blob/master/pkg/sentry/devices/ttydev/ttydev.go#L38

I hacked together #10934 , and verified that emacs runs (*shudder*).  I need to think more about the right way to do this. That PR is not the right way.

@chetan-reddy Can you patch #10934 and check that it works for you?  I only moved the cursor around and CxCc

**Comment by chetan-reddy** [comment]
@nlacasse I wasn't able to compile that exact PR commit, but I was able to cherry-pick your change onto an older commit on the go branch (e9d8c6f70) and can verify that emacs now works. Thanks for the fix!

**Comment by nlacasse** [comment]
Awesome!  I need to figure out the right way to do this, but it's good to know that this is the correct approach.  I'll spend more time on this in the next week or so.

**Comment by nlacasse** [comment]
Hi @chetan-reddy , I think this should be fixed properly now, so you can drop the hacky patch.  Please let me know if it doesn't work.
