### ISSUE TITLE
container stuck, it should complete. can see processes running.

### ISSUE THREAD

**Issue by PSKP-95** [google/gvisor#10992]
### Description

I am running a simple container in containerd with gvisor. but it is not outputting anything. & got stuck.

Here are commands I am trying to run,

![image](https://github.com/user-attachments/assets/76e9a389-668e-44c5-90bf-943068148759)

Processes should print files and folders and exit

![image](https://github.com/user-attachments/assets/453ed868-d86e-482a-afe3-402f3569fb5a)

### Steps to reproduce

- Installed containerd using getting started guide (https://github.com/containerd/containerd/blob/main/docs/getting-started.md)
- Installed gvisor following https://gvisor.dev/docs/user_guide/containerd/quick_start/

### runsc version

```shell
runsc version release-20240930.0
spec: 1.1.0-rc.1
```

### docker version (if using docker)

```shell
$ sudo ctr version
Client:
  Version:  v1.7.22
  Revision: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
  Go version: go1.22.7

Server:
  Version:  v1.7.22
  Revision: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
  UUID: 9d8c7a79-4d14-4110-81de-a46f1a46cc87
```

### uname

Linux ip-172-21-148-200.eu-central-1.compute.internal 6.1.109-118.189.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Sep 10 08:59:12 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### runsc debug logs (if available)

```shell
The documentation doesn't specify how to capture debug logs in containerd. Could you please provide guidance on how to do this? I'm happy to provide any additional information if needed. Thanks!
```

**Comment by ayushr2** [comment]
Can't say much without runsc debug logs. To specify runsc flags, see https://gvisor.dev/docs/user_guide/containerd/configuration/. The last section "Example: Enable shim and gVisor debug logging" should have instructions.

**Comment by PSKP-95** [comment]
Got working with crictl. Thanks.
