### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by crazyfrankie** [google/gvisor#11021]
When `docker run --runtime=runsc --rm hello-world` fails with `docker: Error response from daemon: unknown or invalid runtime name: runsc`

**Comment by milantracy** [comment]
What is your git branch name when you build runsc?

Could you share steps to reproduce  the issue?

**Comment by EtiennePerot** [comment]
Did you follow the [Docker setup guide](https://gvisor.dev/docs/user_guide/quick_start/docker/)?

Did you restart Docker after that? (`systemctl restart docker`)

If so, please report the output of the `docker info` command, and the contents of `/etc/docker/daemon.json`.

**Comment by milantracy** [comment]
> Did you follow the [Docker setup guide](https://gvisor.dev/docs/user_guide/quick_start/docker/)?
> 
> Did you restart Docker after that? (`systemctl restart docker`)
> 
> If so, please report the output of the `docker info` command, and the contents of `/etc/docker/daemon.json`.

It looks like the right answer to me. 

You have to add an entry to your docker daemon config which points to the absolute path to the runsc you build, then restart the docker daemon to apply the change

**Comment by crazyfrankie** [comment]
> 当您构建 runsc 时，您的 git 分支名称是什么？
> 
> 您能分享重现该问题的步骤吗？



> What is your git branch name when you build runsc?
> 
> Could you share steps to reproduce the issue?

**Comment by crazyfrankie** [comment]
> What is your git branch name when you build runsc?
> 
> Could you share steps to reproduce the issue?

I follow the [quick start](https://gvisor.dev/docs/user_guide/quick_start/docker/).
Then I create `/etcdocker/daemon.json`  with 
```
{
  "runtimes": {
    "runsc": {
      "path": "/usr/local/bin/runsc",
      "runtimeArgs": []
    }
  },
}
```
Then I restart docker.

**Comment by crazyfrankie** [comment]
> Did you follow the [Docker setup guide](https://gvisor.dev/docs/user_guide/quick_start/docker/)?
> 
> Did you restart Docker after that? (`systemctl restart docker`)
> 
> If so, please report the output of the `docker info` command, and the contents of `/etc/docker/daemon.json`.

Yes,I follow [quick start](https://gvisor.dev/docs/user_guide/quick_start/docker/),then I `sudo systemctl restart docker`.
And I don't now why `docker info --format '{{ .SecurityOptions }}'` output is `[name=seccomp,profile=unconfined name=cgroupns]`,but document says it maybe `[name=seccomp,profile=default name=cgroupns]`

**Comment by milantracy** [comment]
> > What is your git branch name when you build runsc?
> > Could you share steps to reproduce the issue?
> 
> I follow the [quick start](https://gvisor.dev/docs/user_guide/quick_start/docker/). Then I create `/etc/docker/daemon.json` with
> 
> ```
> {
>   "runtimes": {
>     "runsc": {
>       "path": "/usr/local/bin/runsc",
>       "runtimeArgs": []
>     }
>   },
> }
> ```
> 
> Then I restart docker.

**Your JSON format is incorrect**, I don't think you can actually restart docker and applied the new config

I copied your docker config, which lead to 
```shell
docker sudo systemctl restart docker
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xeu docker.service" for details.
➜  docker dockerd
unable to configure the Docker daemon with file /etc/docker/daemon.json: invalid character '}' looking for beginning of object key string
➜  docker cat daemon.json
{
  "runtimes": {
    "runsc": {
      "path": "/usr/local/bin/runsc",
      "runtimeArgs": []
    }
  },
}
```

You have to remove  trailing comma after `runtimes` like


```
--- a/daemon.json
+++ b/daemon.json
@@ -4,5 +4,5 @@
       "path": "/usr/local/bin/runsc",
       "runtimeArgs": []
     }
-  },
+  }
 }
```

=======================
> Above should let your run easy examples


I would recommend using `sudo runsc install` instead of manually updating daemon.config unless you know what you are doing

**Comment by milantracy** [comment]
I will close the bug, feel free to let me know how it goes

**Comment by milantracy** [comment]
You don't configure your docker correctly, docker daemon config is at /etc/docker/deamon.json. Please see https://docs.docker.com/engine/daemon/

You config file is not read by docker daemon

**Comment by crazyfrankie** [comment]
Thanks for the correction, now I have deleted the original file and copied the [](https://docs.docker.com/engine/daemon/)provided file contents to the new one `daemon.json` and re-executed `sudo runsc install`.At the same time, `dockerd --validate --config-file /etc/docker/daemon. json `was used to check the configuration format, and the output was OK.But restarting docker still fails.
This is `sudo systemctl status docker.service`
```
× docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/docker.service.d
             └─override.conf, proxy.conf
     Active: failed (Result: exit-code) since Fri 2024-10-11 15:30:20 CST; 2min 8s ago
TriggeredBy: × docker.socket
       Docs: https://docs.docker.com
    Process: 8057 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
   Main PID: 8057 (code=exited, status=1/FAILURE)
        CPU: 83ms

10月 11 15:30:20 qiyi systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
10月 11 15:30:20 qiyi systemd[1]: Stopped Docker Application Container Engine.
10月 11 15:30:20 qiyi systemd[1]: docker.service: Start request repeated too quickly.
10月 11 15:30:20 qiyi systemd[1]: docker.service: Failed with result 'exit-code'.
10月 11 15:30:20 qiyi systemd[1]: Failed to start Docker Application Container Engine.
```
And this is my new `/etc/docker/daemon.json`
```
{
    "allow-nondistributable-artifacts": [],
    "api-cors-header": "",
    "authorization-plugins": [],
    "bip": "",
    "bridge": "",
    "builder": {
        "gc": {
            "defaultKeepStorage": "10GB",
            "enabled": true,
            "policy": [
                {
                    "filter": [
                        "unused-for=2200h"
                    ],
                    "keepStorage": "10GB"
                },
                {
                    "filter": [
                        "unused-for=3300h"
                    ],
                    "keepStorage": "50GB"
                },
                {
                    "all": true,
                    "keepStorage": "100GB"
                }
            ]
        }
    },
    "cgroup-parent": "",
    "containerd": "/run/containerd/containerd.sock",
    "containerd-namespace": "docker",
    "containerd-plugins-namespace": "docker-plugins",
    "data-root": "",
    "debug": true,
    "default-address-pools": [
        {
            "base": "172.30.0.0/16",
            "size": 24
        },
        {
            "base": "172.31.0.0/16",
            "size": 24
        }
    ],
    "default-cgroupns-mode": "private",
    "default-gateway": "",
    "default-gateway-v6": "",
    "default-network-opts": {},
    "default-runtime": "runc",
    "default-shm-size": "64M",
    "default-ulimits": {
        "nofile": {
            "Hard": 64000,
            "Name": "nofile",
            "Soft": 64000
        }
    },
    "dns": [],
    "dns-opts": [],
    "dns-search": [],
    "exec-opts": [],
    "exec-root": "",
    "experimental": false,
    "features": {
        "cdi": true,
        "containerd-snapshotter": true
    },
    "fixed-cidr": "",
    "fixed-cidr-v6": "",
    "group": "",
    "host-gateway-ip": "",
    "hosts": [],
    "icc": false,
    "init": false,
    "init-path": "/usr/libexec/docker-init",
    "insecure-registries": [],
    "ip": "0.0.0.0",
    "ip-forward": false,
    "ip-masq": false,
    "ip6tables": false,
    "iptables": false,
    "ipv6": false,
    "labels": [],
    "live-restore": true,
    "log-driver": "json-file",
    "log-format": "text",
    "log-level": "",
    "log-opts": {
        "cache-compress": "true",
        "cache-disabled": "false",
        "cache-max-file": "5",
        "cache-max-size": "20m",
        "env": "os,customer",
        "labels": "somelabel",
        "max-file": "5",
        "max-size": "10m"
    },
    "max-concurrent-downloads": 3,
    "max-concurrent-uploads": 5,
    "max-download-attempts": 5,
    "mtu": 0,
    "no-new-privileges": false,
    "node-generic-resources": [
        "NVIDIA-GPU=UUID1",
        "NVIDIA-GPU=UUID2"
    ],
    "pidfile": "",
    "proxies": {
        "http-proxy": "http://127.0.0.1:7897",
        "https-proxy": "https://127.0.0.1:7897",
        "no-proxy": "localhost,127.0.0.1"
    },
    "raw-logs": false,
    "registry-mirrors": [],
    "runtimes": {
        "cc-runtime": {
            "path": "/usr/bin/cc-runtime"
        },
        "custom": {
            "path": "/usr/local/bin/my-runc-replacement",
            "runtimeArgs": [
                "--debug"
            ]
        },
        "runsc": {
            "path": "/usr/local/bin/runsc"
        }
    },
    "seccomp-profile": "/etc/docker/default.json",
    "selinux-enabled": false,
    "shutdown-timeout": 15,
    "storage-driver": "",
    "storage-opts": [],
    "swarm-default-advertise-addr": "",
    "userland-proxy": false,
    "userland-proxy-path": "/usr/libexec/docker-proxy",
    "userns-remap": ""
}
```

**Comment by milantracy** [comment]
try 

```
$ sudo systemctl restart docker.socket
$ sudo systemctl restart docker.service
```

**to restart the docker daemon and docker socket**

let me know how it goes for you

-----


I have no idea where you get your /etc/docker/daemon.json

here is my daemon.json, which just works with gVisor

```shell
chjing@dev:~$ docker run --runtime=runsc -it ubuntu dmesg
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
d1fbec07a2e5: Pull complete 
Digest: sha256:ee6860ab126bb8291052401af00acad20d69c16e46579a47dac1c57cd4688446
Status: Downloaded newer image for ubuntu:latest
[    0.000000] Starting gVisor...
[    0.320124] Moving files to filing cabinet...
[    0.739955] Checking naughty and nice process list...
[    0.861634] Digging up root...
[    1.200872] Reading process obituaries...
[    1.463089] Creating bureaucratic processes...
[    1.958524] Recruiting cron-ies...
[    2.085852] Searching for socket adapter...
[    2.359919] Letting the watchdogs out...
[    2.737414] Singleplexing /dev/ptmx...
[    3.089731] Mounting deweydecimalfs...
[    3.362236] Setting up VFS...
[    3.747754] Setting up FUSE...
[    4.104880] Ready!
chjing@dev:~$ cat /etc/docker/daemon.json
{
    "runtimes": {
        "runsc": {
            "path": "/usr/local/bin/runsc"
        }
    }
}
```

**Comment by crazyfrankie** [comment]
Thank you, milantracy, I see my problem.

I've been running the command to view runtimes as a regular user, but since I didn't add a user group, today when I use `sudo docker info | grep -i "Runtimes"`, runsc appears as expected

**Comment by crazyfrankie** [comment]
Thank you, milantracy, I see my problem.

I've been running the command to view runtimes as a regular user, but since I didn't add a user group, today when I use `sudo docker info | grep -i "Runtimes"`, runsc appears as expected.

However, I use `sudo usermod -aG docker $USER`. After logging in again, I still cannot use `docker info | grep -i "Runtimes"` to get the runtimes containing runsc.

**Comment by EtiennePerot** [comment]
It may be the case that your `docker` command is aliased to something else in your regular user's shell configuration. Some software (such as Colima) will hijack it. Check `which docker`, `realpath $(which docker)`, `sha1sum $(which docker)` and `alias | grep docker`, and contrast this to `sudo which docker`, `sudo realpath $(sudo which docker)`, `sudo sha1sum $(sudo which docker)`.

Another possibility is that your regular user's shell configuration is causing `docker` to talk to a different Docker daemon than the one with `sudo`. Check if you have the `DOCKER_HOST` environment variable set, for example (`env | grep DOCKER_HOST`). Another way to find out is to `strace` your docker binary and see where it's connecting to. `strace -ff --trace=connect docker info` should show `connect(6, {sa_family=AF_UNIX, sun_path="/var/run/docker.sock"}, 23) = 0` for example, which tells you it's connecting to the Docker daemon at `/var/run/docker.sock`.

**Comment by milantracy** [comment]
> Thank you, milantracy, I see my problem.
> 
> I've been running the command to view runtimes as a regular user, but since I didn't add a user group, today when I use `sudo docker info | grep -i "Runtimes"`, runsc appears as expected.
> 
> However, I use `sudo usermod -aG docker $USER`. After logging in again, I still cannot use `docker info | grep -i "Runtimes"` to get the runtimes containing runsc.

if `sudo docker info | grep -i "Runtimes"` works, `sudo docker run --runtime=runsc -it ubuntu dmesg` will just work.

fwiw, it has nothing to do with gVisor, you have to follow https://docs.docker.com/engine/install/ubuntu/ and https://docs.docker.com/engine/install/linux-postinstall/ to make sure docker is properly configured.  

https://github.com/docker/cli/issues might be a better place to help you configure your docker, or debug docker client issue.
