### ISSUE TITLE
'process/user/umask' from the OCI runtime spec not honoured

### ISSUE THREAD

**Issue by BinaryKhaos** [google/gvisor#11022]
### Description

The OCI runtime spec defines an optional value 'process/user/umask' that allows setting the umask for the newly started process in the container. It is honoured by crun and runc, for example, but not by runsc.

### Steps to reproduce

1. podman run --rm --runtime=runsc --umask=0027 alpine:latest /bin/sh -c umask
0022

2. podman run --rm --runtime=runc --umask=0027 alpine:latest /bin/sh -c umask
0027

3. podman run --rm --runtime=crun --umask=0027 alpine:latest /bin/sh -c umask
0027

### runsc version

runsc version release-20241007.0
spec: 1.1.0-rc.1

### uname

Linux TARDIS 6.11.3-gentoo-241010-r1 #1 SMP PREEMPT_DYNAMIC Thu Oct 10 16:36:50 CEST 2024 x86_64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz GenuineIntel GNU/Linux

**Comment by ayushr2** [comment]
#11024 should fix this. I tested your reproducer locally.

**Comment by BinaryKhaos** [comment]
Thanks, very much appreciated. Can confirm, latest nightly works like a charm and also fixes a crash I was seeing with the KVM platform on Linux.
