### ISSUE TITLE
How to implement `/proc/sys/kernel/pid_max`

### ISSUE THREAD

**Issue by pawalt** [google/gvisor#11120]
### Description

I'm interested in implementing `/proc/sys/kernel/pid_max`, and I'm looking to get some feedback before I go about implementing it. If the team would accept a simple PR adding a static value (if such a value exists), I can pretty easily add it [here](https://github.com/google/gvisor/blob/892ba3d7f6524e5abe25a2724d95b0efb3765765/pkg/sentry/fsimpl/proc/tasks_sys.go#L55). Is it the case that [this](https://github.com/google/gvisor/blob/892ba3d7f6524e5abe25a2724d95b0efb3765765/pkg/sentry/fsimpl/cgroupfs/pids.go#L35) is the true PID max on GVisor? If so, I'll PR this in.

Otherwise, I'm curious how max PID is handled in GVisor - I can't find relevant code or docs on this. Let me know, and I'll see what I can work up!

**Comment by avagin** [comment]
> If the team would accept a simple PR adding a static value (if such a value exists), I can pretty easily add it [here](https://github.com/google/gvisor/blob/892ba3d7f6524e5abe25a2724d95b0efb3765765/pkg/sentry/fsimpl/proc/tasks_sys.go#L55).

I think kernel.TasksLimit is what you are looking for:
https://cs.opensource.google/gvisor/gvisor/+/master:pkg/sentry/kernel/task_start.go;l=350

It should be ok to add it `there`. Why do you need it?

**Comment by pawalt** [comment]
@avagin We have a user running `pulseaudio` in a container, and `pulseaudio` segfaults if this file is not provided.
