### ISSUE TITLE
Sysctl validation fails on container checkpoint restore

### ISSUE THREAD

**Issue by pawalt** [google/gvisor#11248]
### Description

We're attempting to upgrade our gVisor version to pull in some new fixes, but in doing so, we're seeing validation failures on checkpoint restore. In particular, we're seeing this error related to sysctl validation:

```
starting container: restoring container "ta-01JE9T1CYP1RK3DHNC021PYWWF": Sysctl does not match across checkpoint restore for container: __no_name_0, checkpoint map[] restore map[]
```

This is surprising because the maps look identical (empty). We've printed out the validation struct for debugging and found the same:

```
W1204 21:43:24.925623       1 restore.go:349] struct map map[Rlimits:[[{Type:RLIMIT_NOFILE Hard:65536 Soft:65536}] [{Type:RLIMIT_NOFILE Hard:65536 Soft:65536}]] Root:[0xc00090ccc0 0xc0002918f0] Seccomp:[<nil> <nil>] Sysctl:[map[] map[]] User:[{UID:0 GID:0 Umask:<nil> AdditionalGids:[] Username:} {UID:0 GID:0 Umask:<nil> AdditionalGids:[] Username:}]]
```

After doing `git bisect` to search for the failure, this is the offending commit, although it's unclear why this is failing. The `reflect.DeepEqual` looks fine to me:
https://github.com/google/gvisor/commit/6bae0a7b387bdd671df527c80ba8757eb32b130d#diff-fd7331ec23936a663a0ebb244a70358d1f3f2ff8b4e3c814831725c3aa2afa51R186

We also had an issue with root paths, but looks like [that's been fixed](https://github.com/google/gvisor/commit/f2abd313672cff1b2afcd030b0d562af20bd7795)!

cc @thundergolfer @cweld510 

### Steps to reproduce

Checkpoint a container and try to restore from it.

### runsc version

```shell
runsc --version 
runsc version release-20241202.0-12-gf2abd313672c-dirty
spec: 1.1.0-rc.1
```

### docker version (if using docker)

```shell

```

### kubectl (if using Kubernetes)

```shell
uname -a
Linux ip-10-1-4-158.ec2.internal 5.15.0-207.156.6.el9uek.x86_64 #2 SMP Thu Jun 6 02:32:40 PDT 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### repo state (if built from source)

git describe                            release-20241202.0-12-gf2abd3136

### runsc debug logs (if available)

```shell
W1204 21:57:16.989169  1663127 util.go:64] FATAL ERROR: starting container: restoring container "ta-01JE9TTSGNZXRNYAJJHSZNCDZV": failed to validate restore spec: Sysctl does not match across checkpoint restore for container: __no_name_0, checkpoint map[] restore map[]
D1204 21:57:16.989218  1663127 container.go:794] Destroy container, cid: ta-01JE9TTSGNZXRNYAJJHSZNCDZV
D1204 21:57:16.989255  1663127 container.go:1091] Destroying container, cid: ta-01JE9TTSGNZXRNYAJJHSZNCDZV
D1204 21:57:16.989267  1663127 sandbox.go:1654] Destroying root container by destroying sandbox, cid: ta-01JE9TTSGNZXRNYAJJHSZNCDZV
D1204 21:57:16.989274  1663127 sandbox.go:1350] Destroying sandbox "ta-01JE9TTSGNZXRNYAJJHSZNCDZV"
D1204 21:57:16.990117  1663127 sandbox.go:1360] Killing sandbox "ta-01JE9TTSGNZXRNYAJJHSZNCDZV"
D1204 21:57:17.005622  1663127 container.go:1105] Killing gofer for container, cid: ta-01JE9TTSGNZXRNYAJJHSZNCDZV, PID: 1663144
D1204 21:57:17.006503  1663127 cgroup_v2.go:176] Deleting cgroup "/sys/fs/cgroup/modal.slice/modal-containers.slice/container-ta-01JE9TTSGNZXRNYAJJHSZNCDZV.scope"
D1204 21:57:17.006667  1663127 hook.go:63] Executing hook {Path:/usr/bin/python3 Args:[python3 -S -c """Implements POSIX-platform OCI container lifecycle hooks.
```

**Comment by ayushr2** [comment]
I think this can happen because `reflect.DeepEqual()` considers `nil` map and an allocated empty map different. But both are printed by `fmt` package as `map[]`. Can you confirm if one of the specs has a `nil` Sysctl?

**Comment by pawalt** [comment]
@ayushr2 I made this change to test this:

```go
func validateStruct(field, cName string, oldS, newS any) error {
	if !reflect.DeepEqual(oldS, newS) {
		log.Warningf("first argument for %s is nil: %v", field, oldS == nil)
		log.Warningf("second argument for %s is nil: %v", field, newS == nil)
		return validateError(field, cName, oldS, newS)
	}
	return nil
}
```

And it doesn't look like they're nil:
```
(modal) ➜  modal git:(pawalt/new_gvizzyz) rg 'Sysctl' /tmp/runsc
/tmp/runsc/runsc.log.20241204-232210.724506.boot.txt
1925:W1204 23:22:10.922040       1 restore.go:473] validateStructMap: map[Rlimits:[[{Type:RLIMIT_NOFILE Hard:65536 Soft:65536}] [{Type:RLIMIT_NOFILE Hard:65536 Soft:65536}]] Seccomp:[<nil> <nil>] Sysctl:[map[] map[]] User:[{UID:0 GID:0 Umask:<nil> AdditionalGids:[] Username:} {UID:0 GID:0 Umask:<nil> AdditionalGids:[] Username:}]]
1926:W1204 23:22:10.922071       1 restore.go:382] first argument for Sysctl is nil: false
1927:W1204 23:22:10.922077       1 restore.go:383] second argument for Sysctl is nil: false
```

**Comment by pawalt** [comment]
I also printed out their types:
```
W1204 23:28:00.565178       1 restore.go:475] validateStructMap: map[Rlimits:[[{Type:RLIMIT_NOFILE Hard:65536 Soft:65536}] [{Type:RLIMIT_NOFILE Hard:65536 Soft:65536}]] Seccomp:[<nil> <nil>] Sysctl:[map[] map[]] User:[{UID:0 GID:0 Umask:<nil> AdditionalGids:[] Username:} {UID:0 GID:0 Umask:<nil> AdditionalGids:[] Username:}]]
W1204 23:28:00.565209       1 restore.go:382] first argument for Sysctl is nil: false
W1204 23:28:00.565215       1 restore.go:383] second argument for Sysctl is nil: false
W1204 23:28:00.565219       1 restore.go:384] Type of oldS: map[string]string
W1204 23:28:00.565246       1 restore.go:385] Type of newS: map[string]string
```

**Comment by ayushr2** [comment]
Welcome to Golang! https://go.dev/play/p/4-8xpHhLtMf

A nil map received in an `any` variable is not nil. Since the interface has a concrete type attached to it (the map).

Add the check closer to https://github.com/google/gvisor/blob/f2abd313672cff1b2afcd030b0d562af20bd7795/runsc/boot/restore.go#L448 with the actual fields.

**Comment by pawalt** [comment]
@ayushr2 wow you learn something new every day:

```go
	log.Warningf("new sysctl is nil: %v", newLinux.Sysctl == nil)
	log.Warningf("old sysctl is nil: %v", oldLinux.Sysctl == nil)
	validateStructMap["Sysctl"] = [2]any{oldLinux.Sysctl, newLinux.Sysctl}
```

and the prints
```
W1205 14:53:58.400061       1 restore.go:456] new sysctl is nil: false
W1205 14:53:58.400075       1 restore.go:457] old sysctl is nil: true
```

I added the following and it's fixed this issue. Not sure if you folks have a cleaner way of doing this:
```go
	log.Warningf("old sysctl is nil: %v", oldLinux.Sysctl == nil)
	if oldLinux.Sysctl == nil {
		oldLinux.Sysctl = make(map[string]string)
	}
	if newLinux.Sysctl == nil {
		newLinux.Sysctl = make(map[string]string)
	}
```

**Comment by ayushr2** [comment]
I was considering of writing a similar fix. However, this behavior of `reflect.DeepEqual()` considering nil and empty maps different extends beyond just `Linux.Sysctl` field. There can be a lot of maps in various parts of the OCI spec which can hit this issue. Similarly, nil and zero-length slices are considered unequal. I am trying to think of a more general solution.

A nil `Linux.Sysctl` can occur when it is not defined in the OCI spec. And an empty one can occur if you have something like:
```
"linux": {
    "sysctl": {},
...
```

In the meantime, can you add ^ to your restore OCI spec to mitigate this issue?

**Comment by ayushr2** [comment]
> We're attempting to upgrade our gVisor version to pull in some new fixes

Separately, our checkpoint images are not backward compatible. It means that a checkpoint image can only be restored by the runsc version that generated it. If you are upgrading, you will need to invalidate your current library of images.

**Comment by pawalt** [comment]
thanks @ayushr2 !
