### ISSUE TITLE
Add option to disable container spec validation when restoring checkpoints

### ISSUE THREAD

**Issue by cweld510** [google/gvisor#11307]
### Description

We recently upgraded to a gvisor version containing extra validation of the container spec used when restoring checkpoints (i.e. all the logic [here](https://github.com/google/gvisor/blob/master/runsc/boot/restore.go#L417)). Unfortunately, at the same time, we also discovered that we were inadvertently varying the container spec between checkpoint and restore in lots of subtle ways that, although technically incorrect, weren't causing any obvious bugs in our application. For example, varying the arguments to the container's init process between checkpoint and restore doesn't actually cause anything to break, because we consume the arguments into memory just once, before the checkpoint occurs. The new validation logic turns those small variances in the container spec into big failures that cause production issues.

Is it reasonable to add an option to disable the container spec validation? I'm fully aware that varying the container spec between checkpoint and restore is technically wrong, and I intend to fix it -- but in the interim, it would be nice to disable the validation to maintain stability.

**Comment by EtiennePerot** [comment]
Seems fine to me so long as it's flag-gated behind a scary-sounding flag, and that the behavior for the now-not-validated fields is consistent (will they all effectively inherit the pre-checkpoint values?)

**Comment by pawalt** [comment]
@EtiennePerot yes my understanding is they'll effectively inherit the pre-checkpoint flag. I think it makes sense to put this behind a scary flag and to still emit a warning or error-level log so we can alert on validation errors.

**Comment by cweld510** [comment]
I've created https://github.com/google/gvisor/pull/11323 for this change - let me know if it's acceptable!

For the now-not-validated fields, I believe two things may happen. For fields that don't have any semantic effect at restore time, gvisor will behave according to the values given at checkpoint time. For other fields, differences in the checkpoint/restore specs will still cause loud restore failures in subcomponents of the kernel (e.g. a missing bind mount will cause filesystem restoration to fail).

**Comment by cweld510** [comment]
Thanks @EtiennePerot for the help and review!

**Comment by nybidari** [comment]
@cweld510 FYI we are introducing a new flag which adds levels (such as ignore/warning/enforce) for the spec validation logic during restore. [These changes](https://github.com/google/gvisor/pull/11348) will be submitted in the next one or two days.  This will be a breaking change for users of "unsafe-skip-restore-spec-validation" flag. You can use the new flag ("restore-spec-validation") with setting "warning" or "ignore" to skip spec validation.

**Comment by cweld510** [comment]
Sounds good -- thanks for the heads-up!

**Comment by ayushr2** [comment]
The `restore-spec-validation` flag was introduced in https://github.com/google/gvisor/commit/1c38b6cbed2cb357aa7b48e7c33e5dce5b5b8cbd.
