### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by hazcod** [google/gvisor#114]
Hello,

Are there any plans/estimates on releasing a gvisor release?
I'm curious to see what commit the guys @ google use.

I would like to start playing around, but I don't want to pick the latest nightly just 'because'.

**Comment by ianlewis** [comment]
Hi, we update the version we use at Google pretty often so it wouldn't be all that useful to tell you what version we are using.

We have been updating often to support for containerd and Kubernetes and some things are still in flux. I think we'll start cutting releases on github after support for those is more stable but we're still discussing how to do releases at the moment.

For now, you can use the latest nightly. We have pretty extensive automated tests so it should stay fairly stable.

**Comment by liusdu** [comment]
Hi @nlacasse @ianlewis  any update?

**Comment by nlacasse** [comment]
We now cut releases (roughly) weekly.
https://github.com/google/gvisor/releases

The master branch is also tagged with each release.  While we try to keep HEAD stable, the releases go through an additional level of scrutiny, and we ensure that they pass all test suites.

We're working on making automated release notes, so users can tell what new features or bug fixes are in each release.

**Comment by hazcod** [comment]
@nlacasse semantic versioning is a godsend here.
