### ISSUE TITLE
TCP stack needs to RST to all incoming segments when in CLOSE state

### ISSUE THREAD

**Issue by iyermi** [google/gvisor#1153]
TCP stack needs to RST to all incoming segments when in CLOSE state.

I see that this is not the case for in-flight segments within the stack.

**Comment by Liloyoung** [comment]
Am 07.11.2019 23:15 schrieb iyermi <notifications@github.com>:TCP stack needs to RST to all incoming segments when in CLOSE state.
I see that this is not the case for in-flight segments within the stack.
