### ISSUE TITLE
Any guidance about porting gVisor to a MIPS architecture?

### ISSUE THREAD

**Issue by xieyuheng** [google/gvisor#1170]
Can developers of gVisor provide some guidance about porting gVisor to a MIPS architecture?

**Comment by madscout12** [comment]
Detailed answer coming, but a good place to start is to look at the work lubinszARM has done to port it to ARM: https://github.com/google/gvisor/pulls/lubinszARM

**Comment by prattmic** [comment]
I've outlined the general work required for a new arch port inhttps://github.com/google/gvisor/issues/63#issuecomment-393258143.

As Zach mentioned, you can take a look at the [ongoing commits](https://github.com/google/gvisor/search?o=desc&q=arm&s=committer-date&type=Commits) to port to ARM64, but note that the port is not yet complete.

@xiaobo55x @lubinszARM

**Comment by lubinsz** [comment]
@xieyuheng 
Hi, maybe you can enable the ptrace platform firstly for your porting.

**Comment by xieyuheng** [comment]
Thanks for the informations.
I opened this issue for a friend, but he moved into other topics.
I am closing this, and hope it can help other in the future.
