### ISSUE TITLE
Port overlayfs to VFS2

### ISSUE THREAD

**Issue by fvoznika** [google/gvisor#1199]
Implement Sentry internal overlay. This is the equivalent of `sentry/fs/overlay` with VFS2 interfaces.

**Comment by fvoznika** [comment]
Remaining work:
- Rename support
- Investigate few remaining test failures

**Comment by fvoznika** [comment]
This can be considered done, apart from 3 TODOs left in the code.

**Comment by pkit** [comment]
@fvoznika interesting, but the naming could be better. Essentially it just makes read-only mounts writable through tmpfs layer.
I wouldn't call it support for "overlayfs"...
