### ISSUE TITLE
Cgroups access?

### ISSUE THREAD

**Issue by qrpike** [google/gvisor#12]
Does this runtime require cgroups to be enabled at the kernel level? I am trying to run containers on a linux build that has very little support for anything.

Thanks,

**Comment by fvoznika** [comment]
Right now, it doesn't use cgroups. Having said that, cgroup support is in our short term work list.

**Comment by sureshsankaran** [comment]
@fvoznika can you please share approximate ETA when can we expect cgroups support for gvisor ?

**Comment by fvoznika** [comment]
The best estimate I have right now is sometime in Q3'18.
