### ISSUE TITLE
PageTables was meant to be general and archPageTables arch-specific. 

### ISSUE THREAD

**Issue by avagin** [google/gvisor#1206]
PageTables was meant to be general and archPageTables arch-specific. But https://github.com/google/gvisor/pull/891 makes PageTables arch-specific. That's perhaps OK, but we shouldn't have both

**Comment by avagin** [comment]
Cc: @lubinszARM

**Comment by lubinsz** [comment]
Hi @avagin 
I see. Thanks for your suggestion. 
I will optimize the code. Thanks.

**Comment by lubinsz** [comment]
Hi @avagin 
I have finished the code.
Please check it.
Thanks

**Comment by ianlewis** [comment]
@avagin @lubinszARM was this addressed in #891 and can we close this issue?

**Comment by lubinsz** [comment]
@ianlewis @avagin I think we can close it :)
