### ISSUE TITLE
file-access=shared mount folder not sync to host

### ISSUE THREAD

**Issue by happyrainbowxd** [google/gvisor#124]
Hello, 
I found a problem about docker bind mount with gvisor.
When mount a folder to gvisor, If host mount folder file changed, it will not sync to docker mount folder, but when docker mount folder changed, it will changed to host.

**Environment:**

Linux ubuntu 3.19.0-26-generic #28~14.04.1-Ubuntu SMP Wed Aug 12 14:09:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Docker version 18.03.1-ce, build 9ee9f40

**Reproduce:**
daemon.json                                                                                                                                                          
{
    "runtimes": {
        "runsc": {
            "path": "/usr/local/bin/runsc",
            "runtimeArgs": [
                "--debug-log-dir=/tmp/runsc",
                "--debug",
                "--strace",
                "--network=host",
                "--file-access=shared"
            ]
       }
    }
}

`docker run --runtime=runsc -it -v /mnt/test:/mnt/test:rw ubuntu:latest`

On docker container:
`echo "container_write" >> /mnt/test/a`
On host:
`echo "host_write" >> /mnt/test/a`

On docker container: 
```
root@c201f4d7d6c1:/# cat /mnt/test/a
container_write
```
On host:
```
root@ubuntu:~# cat /mnt/test/a
container_write
host_write
```

BTW, on container I saw the file size is changed. But it cannot be read, because "EOF" offset is not update.

```
root@c201f4d7d6c1:/# ls -ln /mnt/test/a
-rw-r--r-- 1 0 0 27 Jan  4 05:19 /mnt/test/a
```

Thanks in advance.

**Comment by fvoznika** [comment]
The problem here is that file size is cached and it's not refreshed when the size changes. We need to check if the cache needs to be refreshed when the file is open. Possibly also when the read hits EOF using the cached length to ensure there is no more data to read.

**Comment by happyrainbowxd** [comment]
@fvoznika 
Thanks for point out the problem.
@doodlesbykumbi 
I found a possible way to fix this problem,
if you call "truncate" on container with this file, the cached file size and content will update immediately, reopen this file again, all the content from host site written can be read. 
so maybe we can trace this function then update the volume mounting procedure to fix this.                                                                                                                                                  
```
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <unistd.h>
#include <sys/types.h>
int main(void)
{
        FILE *fp = fopen("/mnt/test/a","rb");
        fseek(fp,0,SEEK_END);
        int size = ftell(fp);
        truncate("/mnt/test/a",size);
        printf("%d\n",size);
        rewind(fp);
        char *buffer = new char [size+1];
        buffer[size] = '\x00';
        int rsize = fread(buffer,1,size,fp);
        printf("%d\n",rsize);
        printf("%s\n",buffer);
        delete [] buffer;
        return 0;
}
```
call truncate will trigger gvisor/pkg/sentry/syscalls/linux/sys_file.go
func Truncate(t *kernel.Task, args arch.SyscallArguments) (uintptr, *kernel.SyscallControl, error)

Thanks in advance.

**Comment by doodlesbykumbi** [comment]
@fvoznika Thanks. Yup, definitely interested. I'll pick one of those first issues up.

I'd got something working for this issue but I guess too late 🤷‍♂️ Is your work in review public visible somewhere ?

**Comment by fvoznika** [comment]
Yes, you can see it in Gerrit: https://gvisor-review.googlesource.com/c/gvisor/+/13720

**Comment by happyrainbowxd** [comment]
@fvoznika Thank you, I've tested, It works fine now : )!

BTW, "file-access=exclusive" have the same bug, but little difference is both host and container not sync, and the file size is also not changed, do you have any idea?

**Comment by happyrainbowxd** [comment]
Thank you, @fvoznika I think this issues is totally solved :)
