### ISSUE TITLE
Add support for TCP send buffer auto-tuning.

### ISSUE THREAD

**Issue by hbhasker** [google/gvisor#1252]
gVisor today uses a fixed snd buffer (default of 1MB), which works fine over low latency but can severely limit throughput on high bandwidth high latency links or as they say Long fat pipes. Linux/FreeBSD both support auto-tuning of snd buffers. gVisor now supports recv buffer auto-tuning but not send buffer.

**Comment by nybidari** [comment]
Autotuning of send buffer is now supported in gVisor.
