### ISSUE TITLE
"useradd: UID 0 is not unique" when running bazel docker container as root

### ISSUE THREAD

**Issue by younaman** [google/gvisor#1267]
Hello everyone, when I try to compile gVIsor with source code,I have a lot of problems,Here is my ERROR report:
docker run -d --rm --name gvisor-bazel \
	--user 0:0 \
	-v "/root/.cache/bazel:/root/.cache/bazel/" \
	-v "/root/gvisor-master/gvisor-master:/root/gvisor-master/gvisor-master" \
	--workdir "/root/gvisor-master/gvisor-master" \
	--tmpfs /tmp:rw,exec \
	--privileged \
	gvisor-bazel \
	sh -c "while :; do sleep 100; done" && \
docker exec --user 0:0 -i gvisor-bazel sh -c "groupadd --gid 0 --non-unique gvisor && useradd --uid 0 --gid 0 -d /root gvisor"
ba808741b7539262c482257fcc2a60ff8ef5fa88969b09489d415aac4b7506bb
useradd: UID 0 is not unique
Makefile:15: recipe for target 'bazel-server-start' failed
make[2]: *** [bazel-server-start] Error 4
make[2]: Leaving directory '/root/gvisor-master/gvisor-master'
Makefile:28: recipe for target 'bazel-server' failed
make[1]: *** [bazel-server] Error 2
make[1]: Leaving directory '/root/gvisor-master/gvisor-master'
Makefile:39: recipe for target 'runsc' failed
make: *** [runsc] Error 2
I want to know how to fix the problem,if you have any suggestions,please tell me,thanks a lot!

**Comment by younaman** [comment]
After that,I try to compile it using bazel,but I still have some problems:
ERROR: An error occurred during the fetch of repository 'com_github_google_subcommands':
   failed to fetch com_github_google_subcommands: fetch_repo: github.com/google/subcommands@v0.0.0-20190508160503-636abe8753b8: Get https://proxy.golang.org/github.com/google/subcommands/@v/v0.0.0-20190508160503-636abe8753b8.info: dial tcp 216.58.200.49:443: i/o timeout
ERROR: /root/gvisortest/gvisor-master/gvisor-master/runsc/BUILD:6:1: //runsc:runsc depends on @com_github_google_subcommands//:go_default_library in repository @com_github_google_subcommands which failed to fetch. no such package '@com_github_google_subcommands//': failed to fetch com_github_google_subcommands: fetch_repo: github.com/google/subcommands@v0.0.0-20190508160503-636abe8753b8: Get https://proxy.golang.org/github.com/google/subcommands/@v/v0.0.0-20190508160503-636abe8753b8.info: dial tcp 216.58.200.49:443: i/o timeout
ERROR: Analysis of target '//runsc:runsc' failed; build aborted: no such package '@com_github_google_subcommands//': failed to fetch com_github_google_subcommands: fetch_repo: github.com/google/subcommands@v0.0.0-20190508160503-636abe8753b8: Get https://proxy.golang.org/github.com/google/subcommands/@v/v0.0.0-20190508160503-636abe8753b8.info: dial tcp 216.58.200.49:443: i/o timeout
I want to know should I change the WORKSPACE file?And how could I make it work properly?

**Comment by amscanne** [comment]
The second one looks like a transient network error. Bazel will pull a lot of dependencies initially (and keep them cached). Do you get the same error if you retry?

**Comment by younaman** [comment]
Yes，I tried many times，maybe because I am in China. So，if I want to get all repositry to my local. How could I change the MAKEFILE?&nbsp;



---Original---

**Comment by amscanne** [comment]
Maybe it's a GOPROXY issue. Can you try:

GOPROXY=off bazel build //runsc

**Comment by ianlewis** [comment]
The issue in the first error message is because we try to create a user with the same UID as the user executing `make` so it fails when running as root as that user already exists in the container.

We fixed the issue for GIDs in https://github.com/google/gvisor/commit/e31686500db56a5fcd4070561643d702a94da0c3  but the issue exists for UIDs.

You can work around the issue by running make as a user other than root.

**Comment by younaman** [comment]
Thanks Alot! I use the VPN and now the bazel compile is OK!I am sorry I repeat so late!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Adin Scannell"<notifications@github.com&gt;; 
发送时间: 2019年11月26日(星期二) 凌晨1:46
收件人: "google/gvisor"<gvisor@noreply.github.com&gt;; 
抄送: "杨男子"<952508578@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [google/gvisor] Compile fail of gVisor  (#1267)




Maybe it's a GOPROXY issue. Can you try:
 
GOPROXY=off bazel build //runsc

**Comment by ianlewis** [comment]
The "UID 0 is not unique" issue should be fixed now.
