### ISSUE TITLE
hostfs files cannot be re-opened with greater permissions after SetPermissions

### ISSUE THREAD

**Issue by amscanne** [google/gvisor#1334]
If a file is read-only, Lookup will open the host file O_RDONLY.

If the app comes along later and SetPermission's it read-write, the inode should re-open the host file O_RDWR, otherwise the app won't be able to write with a new FD.

**Comment by ayushr2** [comment]
I believe the same issue exists for pkg/sentry/fsimpl/host/ in VFS2.
