### ISSUE TITLE
panic: ptrace set fpregs failed: no such process

### ISSUE THREAD

**Issue by amscanne** [google/gvisor#1335]
syzbot has found the following crash on:

HEAD commit:    34af9a61741f Fix data race on inotify.Watch.mask.
git tree:       https://gvisor.googlesource.com/gvisor master
console output: https://syzkaller-buganizer.googleplex.com/text?tag=CrashLog&id=5ad3861cb76e1747afd1b4aeca2571f058a1201e
kernel config:  https://syzkaller-buganizer.googleplex.com/text?tag=Config&id=63db77d6dace8270ed4516eac4b00a4b3c5e0746
dashboard link: https://syzkaller.appspot.com/bug?extid=7734894e73f3a03a4807
compiler:       [bazel release 0.14.1]

Unfortunately, I don't have any reproducer for this crash yet.

See http://go/syzbot for details on how to handle this bug.

panic: ptrace set fpregs failed: no such process

goroutine 459 [running]:
gvisor.googlesource.com/gvisor/pkg/sentry/platform/ptrace.(*subprocess).switchToApp(0xc42015d560, 0xc420726780, 0xc7fa60, 0xc42033bb00, 0x404800)
	pkg/sentry/platform/ptrace/subprocess.go:440 +0x9ce
gvisor.googlesource.com/gvisor/pkg/sentry/platform/ptrace.(*context).Switch(0xc420726780, 0xc79dc0, 0xc42015d560, 0xc7fa60, 0xc42033bb00, 0x7fcaffffffff, 0xc420dcdeb0, 0x6f105d, 0x0, 0x0)
	pkg/sentry/platform/ptrace/ptrace.go:102 +0x71
gvisor.googlesource.com/gvisor/pkg/sentry/kernel.(*runApp).execute(0x0, 0xc420472400, 0xc6d860, 0x0)
	pkg/sentry/kernel/task_run.go:207 +0x17d
gvisor.googlesource.com/gvisor/pkg/sentry/kernel.(*Task).run(0xc420472400, 0x56)
	pkg/sentry/kernel/task_run.go:95 +0x174
created by gvisor.googlesource.com/gvisor/pkg/sentry/kernel.(*Task).Start
	pkg/sentry/kernel/task_start.go:251 +0x100

**Comment by ayushr2** [comment]
We track syzkaller issues using this maillist: https://groups.google.com/g/gvisor-syzkaller.
