### ISSUE TITLE
KVM VirtualAddressBits and PhysicalAddressBits should use ring0.Init cpuid

### ISSUE THREAD

**Issue by amscanne** [google/gvisor#1338]

**Comment by ayushr2** [comment]
cc @avagin 

IIUC, VirtualAddressBits and PhysicalAddressBits are initialized using `cpuid.FeatureSet` in `ring0.Init()`. Is that what this issue refers to? If so, can we close this?

**Comment by avagin** [comment]
Fixed by 266cabd008
