### ISSUE TITLE
Add nogo automation for code style and constraints

### ISSUE THREAD

**Issue by amscanne** [google/gvisor#1340]
This includes all constraints documented in the contributing guide:
https://github.com/google/gvisor/blob/master/CONTRIBUTING.md

**Comment by ayushr2** [comment]
@amscanne what constraints are mentioned in [CONTRIBUTING.md](https://github.com/google/gvisor/blob/master/CONTRIBUTING.md)?

We have nogo automation now (thanks to you). Can we close this?
