### ISSUE TITLE
Set CPU number according to CPU quota

### ISSUE THREAD

**Issue by ernado** [google/gvisor#1391]
Currently, CPU number equals to `countCpuset`.
Probably it would be useful to optionally set this number according to available CPU quota, this could help sandboxed application to spawn threads more efficiently (e.g. not spawning 64 threads for 2 CPU quota on 64-core host).

Reference:
https://github.com/uber-go/automaxprocs

Use cases:
* cgroups-unaware CPU intensive applications like FFmpeg
* "optimal" GOMAXPROCS without configuration

If maintainers are interested in this feature, I can work on implementation.

**Comment by hbhasker** [comment]
I believe this will be an useful feature to add. 

+1 from me.

**Comment by tanjianfeng** [comment]
We are also interested in setting the correct GOMAXPROCS for sentry. But in your PR, I did not see where you set it into sentry go runtime, or something I missed?

**Comment by ernado** [comment]
I'm not setting the GOMAXPROCS explicitly, I'm setting the CPU number for runtime which is GOMAXPROCS default, @tanjianfeng

I can add explicit change to GOMAXPROCS, but it seems to be slightly out of scope and I'm not sure if it really needed.

**Comment by tanjianfeng** [comment]
IMO, your patch is configuring: 1) how many cores will be presented to apps (ApplicationCores); instead of that 2) how many cores the sentry go runtime sees.

When I read, "optimal" GOMAXPROCS without configuration, I was thinking you also target 2), no?

**Comment by ernado** [comment]
Actually the 1) is exactly what I need, because many applications are threading based on perceived core number.

Sorry for confusion with sentry GOMAXPROCS.
Can we just set it to cpu-num?

**Comment by tanjianfeng** [comment]
> Actually the 1) is exactly what I need, because many applications are threading based on perceived core number.
> 
> Sorry for confusion with sentry GOMAXPROCS.
> Can we just set it to cpu-num?

Yeah, no problem. Let's focus on 1) in this issue and PR. Thanks!

**Comment by fvoznika** [comment]
This creates divergence with `runc` behavior. `--cpus` controls only the quota, while `--cpuset-cpus` controls the number of CPUs visible to the container:

```shell
docker run --rm --cpus=2 alpine nproc
6
docker run --rm --cpuset-cpus=0-1 alpine nproc
2
```

Can you use `--cpuset-cpus` to control the number of CPUs exposed to the container? Note, I'm not opposed to the idea, just want to understand the use case.

**Comment by hbhasker** [comment]
I believe most cgroups are constrained by quota more often than cpuset-cpus. cpuset-cpu's is ideal as despite this change it allows the application threads to still be scheduled to any core which can still cause issues. But I believe to get optimal performance we need both i.e to restrict the num cpus visible to the app to match the quota and preferably set cpuset-cpus to restrict the sandbox to prevent threads being scheduled on all cores.

**Comment by ernado** [comment]
> This creates divergence with runc behavior. 

That's true, and that's why this feature is behind a flag.

My use case is to set CPU number without explicitly pinning a container to specific CPU cores.

I can use the `--cpuset-cpus`, but it will require me to manually assign CPUs to container. While being optimal way to do so, it requires additional work and management and I want to avoid that. Retrospectively, users expect "CPU quota" setting to somehow magically limit number of spawned CPU-bound threads, but in reality naive application will just spawn 64 threads even having the quota of 0.5, which will lead to scheduling and throttling nightmare.

All I want to achieve is an option that will allow me to automatically reduce visible CPU count based on CPU quota. Do you think that it is excessive and we should just use cpuset that is automated in some way?

**Comment by fvoznika** [comment]
That makes sense, thanks for clarifying. I added a small comment to your PR, looks good otherwise.
