### ISSUE TITLE
Implement setns

### ISSUE THREAD

**Issue by ianlewis** [google/gvisor#140]
Syscall support for:
- setns

**Comment by liusdu** [comment]
@ianlewis  Let me look at this if no one did it before~

**Comment by gdsoumya** [comment]
Hi @ianlewis, I am interested to take this issue for [GSoC 2021](https://gvisor.dev/community/gsoc_2021/). I have been going through the code base looking for the existing implementations of clone(2) and unshare(2) and found [task_clone.go](https://github.com/google/gvisor/blob/master/pkg/sentry/kernel/task_clone.go) and [sys_thread.go](https://github.com/google/gvisor/blob/master/pkg/sentry/syscalls/linux/sys_thread.go).  I am still trying to understand the architecture, it would be really great if you can tell me whether I am going in the right direction and also if there are any resources that you'd suggest which might help me with the task. Thanks.

**Comment by avagin** [comment]
https://github.com/google/gvisor/commit/46115504ec3221fb9d9863ad4999a1244baea6fc
