### ISSUE TITLE
Support setting the SO_LINGER socket option

### ISSUE THREAD

**Issue by RyanHeacock** [google/gvisor#1400]
This is would be useful to better manage the behavior of sockets on `close` or `shutdown`, whether we want to wait for a timeout or force a reset by turning linger off and closing the socket.

From the man page:
When enabled, a `close` or `shutdown` will not return until
              all queued messages for the socket have been successfully sent
              or the linger timeout has been reached.

Get SO_LINGER is already supported.

**Comment by majek** [comment]
I stumbled on this as well. I use SO_LINGER (1,0), specifically golang's SetLinger(0) to force sending RST instead of FIN.
https://golang.org/pkg/net/#TCPConn.SetLinger

This is very useful.

**Comment by hbhasker** [comment]
@iangudger is looking at implementing it. The linux implementation seems to be the following

- zero timeout -> send reset immediately
> 0 close/shutdown block for upto SO_LINGER timeout to flush all pending data. If timeout is hit and socket is not in a CLOSED state then send an ACTIVE RST.

**Comment by tamird** [comment]
Done in b26f7503b545e106ea0934d2153aed54ee4374d3.

**Comment by tamird** [comment]
Fixed (again) in b6d165fe98b908a7aa97e3fadd61ddd3731be915.
