### ISSUE TITLE
typo "contaners" in runsc/cmd/list.go 

### ISSUE THREAD

**Issue by martencassel** [google/gvisor#143]
A typo was found: "contaners"

runsc/cmd/list.go
@@ -42,7 +42,7 @@ func (*List) Name() string {

 // Synopsis implements subcommands.Command.Synopsis.	// Synopsis implements subcommands.Command.Synopsis.
func (*List) Synopsis() string {	func (*List) Synopsis() string {
	return "list contaners started by runsc with the given root"		return "list containers started by runsc with the given root"
}

**Comment by avagin** [comment]
https://gvisor-review.git.corp.google.com/c/gvisor/+/15980
