### ISSUE TITLE
Is it feasible to apply AMD-SEV technology to gvisor

### ISSUE THREAD

**Issue by ALEXSmind** [google/gvisor#1438]
gVisor can prevent potential attackers from escaping from the sandbox and damaging the system outside the sandbox. AMD-SEV technology  can prevent the system infected by malicious program from stealing customer data. gVisor and AMD-SEV provide protection in two different directions.

So I want to apply AMD-SEV technology to gVisor. If possible, the container will be safer and more reliable.

I've made some attempts, but I've met some difficulties at present.
When AMD-SEV takes effect, guest code and data need to be encrypted with a different key from host. The special design of gVisor makes the code and data of host and guest mixed together, which is difficult to separate and encrypt alone.

I tried to copy the code and data (such as .text, .ro_data, .rw_data, .bss of runsc from the origin region) to another place (shadow region), and change the rip value from uint64(reflect.ValueOf(ring0.Start).Pointer()) to uint64(reflect.ValueOf(ring0.Start).Pointer() + shadowregionoffset). 

In this way, it is convenient to encrypt the guest code and data with the guest's own key without destroying the host code and data. 

But there is a problem here. I can't find a proper time to copy data (.rw_data and .bss). There are always some up-to-date data required by the guest, which will change after copying and before running into the guest mode. It is impossible to synchronize to the shadow region during copying. This will eventually lead to the failure of guest running.

I would be very grateful if someone could give me some advice.

Thanks a lot!

**Comment by EtiennePerot** [comment]
Hi @ALEXSmind, sorry that this issue got no response. AMD-SEV support has been considered in the past since it opens up some new use cases for gVisor. It is indeed a challenge, but feels like it should be possible at least for some gVisor platforms. No one has fully fleshed this out yet.

**Comment by bronzeMe** [comment]
> Hi @ALEXSmind, sorry that this issue got no response. AMD-SEV support has been considered in the past since it opens up some new use cases for gVisor. It is indeed a challenge, but feels like it should be possible at least for some gVisor platforms. No one has fully fleshed this out yet.

Is there a plan for gVisor to support Intel TDX and AMD SEV? similar to [oak](https://github.com/project-oak/oak)

**Comment by EtiennePerot** [comment]
No one is working on this at this time. Patches welcome as always :)
