### ISSUE TITLE
Flow (HHVM) "Out of shared memory"

### ISSUE THREAD

**Issue by jmillikin-stripe** [google/gvisor#146]
Flow (https://flow.org/, type checker for JavaScript) has an assertion in its memory manager that the filesystem used for temp files is larger than a size (flag-configured). This check is implemented with `statvfs()`, and fails under gVisor because the computed size is zero.

Flow code implementing the check: https://github.com/facebook/flow/blob/v0.95.1/hack/heap/hh_shared.c#L643-L654

Reduced test case:
```c
#include <stdio.h>
#include <sys/statvfs.h>
  
int main() {                                                                                        
  struct statvfs stats;                                                                             
  int rc = statvfs("/tmp", &stats);                                                                 
  if (rc == -1) {
    fprintf(stderr, "statvfs failed\n");                                                            
    return 1;                                                                                       
  }                                                                                                 
  printf("stats.f_bsize: %lu\n", stats.f_bsize);                                                    
  printf("stats.f_bavail: %lu\n", stats.f_bavail);                                                  
  return 0;
}   
```

Output of above with `runc`:
```
$ ./bazel-bin/statvfs
stats.f_bsize: 4096
stats.f_bavail: 1994878
```

Output of above with `runsc`:
```
$ ./bazel-bin/statvfs
stats.f_bsize: 4096
stats.f_bavail: 0
```

**Comment by amscanne** [comment]
Thanks for this report.

We've hit this with applications before, and I'll add a little context. I believe this is technically an incorrect check. On a tmpfs filesystem, size=0 means unlimited. (Memory used for tmpfs files is still charged to the containing cgroup, but there is no independent limit for the tmpfs mount.) Linux will exhibit the same behavior if you mount with size=0, but it defaults to size=physical/2. (So based on runc output, this would probably be a 16gb machine?)

That all said, this seems common enough that we already had planned to just change the default (and have an internal bug) and avoid the whole issue. The change is pretty simple, so I'll try to get this out quickly.

**Comment by prattmic** [comment]
It looks like this is also in the fallback path for lack of memfd support. @mrahatm is working on memfd in https://gvisor-review.git.corp.google.com/c/gvisor/+/13220, so getting that in should also resolve things.

**Comment by prattmic** [comment]
To follow-up, flow seems to work fine with https://gvisor-review.git.corp.google.com/c/gvisor/+/13220.

```
$ flow init
$ flow check
Found 0 errors
```

**Comment by prattmic** [comment]
I filed https://github.com/facebook/hhvm/issues/8470 to make the HHVM folks aware of the issue with their check, but the best way forward for us is to get `memfd_create` in, plus potentially reporting a non-zero size by default.

For reference of the special case, see the [tmpfs docs](https://www.kernel.org/doc/Documentation/filesystems/tmpfs.txt): "If nr_blocks=0 (or size=0), blocks will not be limited in that instance".

**Comment by jmillikin-stripe** [comment]
Thanks for the triage and investigation! I'll wait for memfd support and/or sized tmpfs to land.

**Comment by mrahatm** [comment]
This should be fixed by 06ec97a3f823f1f5d928fc9c2beb3a11c2c88487.

**Comment by prattmic** [comment]
```
root@d7dab7a5574b:/tmp# /flow/flow init
root@d7dab7a5574b:/tmp# /flow/flow check
Found 0 errors
```

**Comment by TrevorSundberg** [comment]
Hopefully I'm not just missing something, but it seems like this behavior is either back again or was never fixed. I installed the nightly version and ran the min-repro above and it still printed 0.
```bash
runsc --version
runsc version release-20200127.0-132-ge07eacc99f00
spec: 1.0.1-dev
```
And to be extra sure I was running the right version:
```bash
which runsc
/usr/local/bin/runsc
```
```json
{
    "runtimes": {
        "runsc": {
            "path": "/usr/local/bin/runsc",
            "runtimeArgs": [
            ]
        }
    }
}
```
And the result:
```
docker run --runtime=runsc --rm test
stats.f_bsize: 4096
stats.f_bavail: 0
```

I do understand that this is technically correct behavior, but it seems like @amscanne  hinted that the behavior was going to be changed.

> Thanks for this report.
> 
> We've hit this with applications before, and I'll add a little context. I believe this is technically an incorrect check. On a tmpfs filesystem, size=0 means unlimited. (Memory used for tmpfs files is still charged to the containing cgroup, but there is no independent limit for the tmpfs mount.) Linux will exhibit the same behavior if you mount with size=0, but it defaults to size=physical/2. (So based on runc output, this would probably be a 16gb machine?)
> 
> That all said, this seems common enough that we already had planned to just change the default (and have an internal bug) and avoid the whole issue. The change is pretty simple, so I'll try to get this out quickly.

For reference, we are running Chrome inside of gVisor and it checks for the size of `/dev/shm`. Please correct me if I'm missing something about this bug being closed. Thank you for your time :)

**Comment by prattmic** [comment]
The issue with HHVM was fixed by implementing memfd_create(2), which made HHVM avoid a fallback that had this tmpfs size issue. The change @amscanne hasn't been made.

That said, we expect Chrome to work in gVisor, so I'm surprised to see this pop up. Could you open a new issue with additional repro steps and logs for the failure to help verify this is the issue?

**Comment by TrevorSundberg** [comment]
Chrome does run, however they have a code path that is discarding decoded images that are typically stored in `/dev/shm` because it thinks the remaining size is 0. Everything works, but it's a performance issue. We have our own compiled version so we added a workaround to treat 0 as infinite.
