### ISSUE TITLE
How to manully switch gVisor from GR0 to HR3?

### ISSUE THREAD

**Issue by younaman** [google/gvisor#1488]
Hello everyone,I am trying to trigger gVisor switch from GR0 to HR3 manully,in the KVM mode,a syscall from sentry to host will trigger the switch from GUEST Ring0 to Host Ring3.But now,I want to make this switch manully,or trigger this switch manully,so is there anyone knows how to make this switch?If you have the code demmo,that's much better!Thans a lot!

**Comment by younaman** [comment]
Is there anyone how to switch it manually?I want to switch the mode,and try to find out if the gVisor could send syscalls to the host if needed.Thanks a lot!

**Comment by amscanne** [comment]
Any system call or fault will trigger a switch back to host mode.

I don't believe there's any way to do it without a system call or fault, but there's a hot path that you can use via the -1 system call. There's a function kvm.redpill.

Note that the switch back is quite expensive, so it doesn't seem worthwhile to make it faster by avoiding the ~50ns the system call might add. (It will trigger a VM exit and copy all register and floating point state out of the guest.)

**Comment by younaman** [comment]
> Any system call or fault will trigger a switch back to host mode.
> 
> I don't believe there's any way to do it without a system call or fault, but there's a hot path that you can use via the -1 system call. There's a function kvm.redpill.
> 
> Note that the switch back is quite expensive, so it doesn't seem worthwhile to make it faster by avoiding the ~50ns the system call might add. (It will trigger a VM exit and copy all register and floating point state out of the guest.)

Thanks alot! I wanna try to use the -1 system call.If I want to switch the mode,you means that I just call the -1 syscall in the container and the mode will change?I notice the kvm.redpill,but I don't know how to trigger it manually in the container?
