### ISSUE TITLE
Some Questions about gVisor logs

### ISSUE THREAD

**Issue by younaman** [google/gvisor#1506]
Hello everyone,I am a green hand in gVisor,I make some trubble in gVisor container,but when I try to read the log in /var/log/messages or syslog to locate the problem,I couldn't find the error logs!
I am very interested in the log system of gVIsor,so,is there anyone could tell me where the gVisor log is?And,When does the gVisor write logs to system's log?Could I do something to test it?Such as do something bad and trigger the log system write logs to the OS not only the container?Thanks alot if you could give me some suggestions!

**Comment by prattmic** [comment]
See https://gvisor.dev/docs/user_guide/debugging/ about enabling logging to a custom location.

Note that `--debug` and `--strace` are only required to enable additional logging. Just `--debug-log` is sufficient to log at the standard level to a custom folder.

Also note that this is outside the container. gVisor does not expose its logs to the sandboxed application, as that may reveal privileged information to untrusted code. (e.g., kernel pointers for ASLR bypass)
