### ISSUE TITLE
Remove package kernel dep from package strace

### ISSUE THREAD

**Issue by amscanne** [google/gvisor#155]
The strace package is passed the Task so it can use t.CopyIn. It would be fine with just a context.Context, as it can use usermem.CopyObjectIn.

This will allow the kernel package to import the strace package, avoiding some interfaces.

**Comment by fvoznika** [comment]
The dependency strace=>kernel grew over time. strace also depends on task's FD table and FSContext. It could be fixed with some interfaces the other way, but then we're trading an interface for another, and kernel.Stracer is likely cleaner.
