### ISSUE TITLE
netlink: add generic input netlink attribute handling

### ISSUE THREAD

**Issue by prattmic** [google/gvisor#1611]
For netlink responses including attributes, [netlink.Message.PutAttr](https://pkg.go.dev/gvisor.dev/gvisor@v0.0.0-20200118174625-b75a6be0ea24/pkg/sentry/socket/netlink?tab=doc#Message.PutAttr) and friends provide a clean way to serialize attributes.

Until #1121, we didn't support any requests that include input netlink attributes, and thus have no support for parsing them. #1121 performs one-off parsing, which is fine for a single case, but as we keep adding more such requests, we should add a cleaner mechanism similar to [netlink.Message.PutAttr](https://pkg.go.dev/gvisor.dev/gvisor@v0.0.0-20200118174625-b75a6be0ea24/pkg/sentry/socket/netlink?tab=doc#Message.PutAttr).

cc @tanjianfeng

**Comment by googleanivia** [comment]
I am adding `RTM_NEWADDR` in another PR. It includes a generic parsing of netlink message/attrs. You can check this PR: https://github.com/google/gvisor/pull/1498
In this file: `pkg/sentry/socket/netlink/message.go`
