### ISSUE TITLE
Getting an Arm64 CI for gVisor

### ISSUE THREAD

**Issue by lubinszARM** [google/gvisor#1626]
Hi all,

Since  more and more arm64 codes are being merged. It would be good to have a CI setup for arm64, so that future stuff doesn't break on it.

Tasks:
* [ ] cross-building
* [ ] add a Arm64 server into Kokoro ?
* [ ] setup syscall test with ptrace on Arm64
* [ ] setup syscall test with kvm on Arm64
* [ ] e2e test on Arm64
* [ ] image test on Arm64
....

Known issues:
1, Regarding ptrace platform, it seems that  the kernel provided by Travis is too old. Because we just added the sysemu feature to the Linux kernel in last year. The kernel version should bigger than 5.3.

2, Regarding kvm platform, the nested virtualization is a problem. At present, officially announced that arm8.3 hardware will support this feature.
Currently, as far as I know, there is no such arm64 server using Arm8.3.

cc @xiaobo55x @avagin @prattmic

**Comment by prattmic** [comment]
Looks like we already have https://github.com/google/gvisor/issues/1231. Perhaps move this list there?

**Comment by avagin** [comment]
packet.net suggests arm64 bare metal servers:
https://www.packet.com/cloud/servers/c1-large-arm/

**Comment by lubinszARM** [comment]
> Looks like we already have #1231. Perhaps move this list there?

Sorry.  Let me move this list.
