### ISSUE TITLE
Hang on POLLRDNORM and futex

### ISSUE THREAD

**Issue by Downchuck** [google/gvisor#1659]
I'm seeing a program hang on POLLRDNORM that works in just about any environment I've tried it in except for gVisor.

The trace hangs at the poll:
[strace.txt](https://github.com/google/gvisor/files/4102248/strace.txt)

Here is the program continuing when not using gVisor (just standard docker):
```
...
read(16, 0x7ffda77f5d90, 100)           = -1 EAGAIN (Resource temporarily unavailable)
futex(0x2144098, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x2144240, FUTEX_WAKE_PRIVATE, 1) = 1
poll([{fd=3, events=POLLRDNORM}, {fd=16, events=POLLRDNORM}], 2, -1) = 1 ([{fd=16, revents=POLLRDNORM}])
read(16, "\1", 100)                     = 1
read(16, 0x7ffda77f5d90, 100)           = -1 EAGAIN (Resource temporarily unavailable)
futex(0x214409c, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x2144240, FUTEX_WAKE_PRIVATE, 1) = 1
pipe([20, 21])                          = 0
```

Seems like that poll just has a really bad time, as the strace does not print out the equals sign ( `) = 1 ([{fd=16 ... `)

```
runsc version release-20200115.0
spec: 1.0.1-dev
```
```
Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:24:29 2019
```

```
Linux notebook 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux
```

**Comment by prattmic** [comment]
gVisor doesn't currently support POLLRDNORM (or POLLRDBAND, POLLWRNORD, POLLWRBAND).

POLLRDNORM is getting ignored, so that poll is effectively just waiting for the FD to be closed.

POLLRDNORM is equivalent to POLLIN, so in theory adding support shouldn't be too complex.

**Comment by Downchuck** [comment]
@prattmic Where would I try for implementation -- is this blocked by any other of the file system work?

**Comment by prattmic** [comment]
This isn't blocked on any other FS work, though we are currently in the middle of a rewrite of the VFS layer (https://github.com/google/gvisor/milestone/1), meaning there are currently dual FS implementations that will complicate things a bit.

From a quick look, POLLRDNORM and POLLWRNORM are (almost?) identical, so they could probably be handled at the syscall layer (https://cs.opensource.google/gvisor/gvisor/+/master:pkg/sentry/syscalls/linux/sys_poll.go), around waiter.EventMaskFromLinux and waiter.EventMask.ToLinux.

POLLRDBAND and POLLWRBAND seem to only be used by a subset of Linux files (notably, sockets), so they would need more invasive support through the VFS.

**Comment by ayushr2** [comment]
https://github.com/google/gvisor/commit/e7ca2a51a89a8ff2c9f5adfdfa5b51be1b3faeb3
