### ISSUE TITLE
shellinabox does not work as expected

### ISSUE THREAD

**Issue by amscanne** [google/gvisor#166]
I believe this may be caused by a bug or deficiency in the pseudo-terminal implementation. You can recreate using runsc by running a image created with the following Dockerfile:

FROM ubuntu
EXPOSE 8080
RUN apt-get update && apt-get install -y shellinabox
CMD ["shellinaboxd", "--debug", "--port", "8080", "--disable-ssl", "--service", "/:root:root:/:SHELL"]

The programs do not run because they can't read anything from the controlling terminal?

**Comment by ayushr2** [comment]
I confirmed that this application works in gVisor today.
