### ISSUE TITLE
netstack: enable buffer size autotuning in gonet 

### ISSUE THREAD

**Issue by majek** [google/gvisor#1666]
From https://github.com/rootless-containers/rootlesskit/pull/101

> d) ModerateRecvBuf to true won't really work as gonet API is not configured to invoke the endpoint.ModerateRecvBuf after Read(). The way auto-tuning works is gvisor invokes the API after it copies bytes to user-space. Right now setting it to true will not do anything unless the API is called. That said there is no real reason to use auto-tuning since its all onhost connection and a buffer of a couple of MB is more than enough to hit 10Gbits/s.

As far as I understand the concept of gonet.Conn, there isn't really any reason not to call ModerateRecvBuf inside gonet. With this in place, we could have gonet actually taking advantage of buffer size autotuning.

**Comment by hbhasker** [comment]
Sorry this fell off the radar. I have a change that should land in a day or two that will enable calling ModerateRecvBuf in gonet. But it would still require the feature to be explicitly enabled in the Stack for it to have any effect.

An example of enabling it is shown below where s is the stack instance.

   // Enable Receive Buffer Auto-Tuning.                                                                                                                                                                                                                                                                                                                                  
        if err := s.SetTransportProtocolOption(tcp.ProtocolNumber, tcpip.ModerateReceiveBufferOption(*moderateRecvBuf)); err != nil {
                return nil, fmt.Errorf("SetTransportProtocolOption failed: %v", err)
        }
