### ISSUE TITLE
ptrace platform treats 32-bit syscalls as 64-bit syscalls

### ISSUE THREAD

**Issue by amscanne** [google/gvisor#167]
e.g., exit_group from compatibility mode (252) looks like this:

I0724 14:22:17.040598   33365 x:0] [   6] 32bit_gunit_tes E ioprio_get(0x7f2b92451818, 0x40001000)
I0724 14:22:17.040617   33365 x:0] [   6] 32bit_gunit_tes X ioprio_get(0x7f2b92451818, 0x40001000) = 0x0 errno=1 (operation not permitted) (1.606Âµs)

**Comment by avagin** [comment]
It is possible to use PTRACE_GET_SYSCALL_INFO to determine whether it was 32-bit syscall or 64-bit syscall.
http://man7.org/linux/man-pages/man2/ptrace.2.html
