### ISSUE TITLE
iptables support for Istio

### ISSUE THREAD

**Issue by amscanne** [google/gvisor#170]
Istio iptables configuration is done in this file: https://github.com/istio/istio/blob/master/tools/deb/istio-iptables.sh

In short, it needs many nat and mangle settings to redirect incoming and outcoming traffic to Envoy proxy.

**Comment by schnie** [comment]
Hey there, I'm looking to implement Istio and gVisor on GKE and came across this page https://cloud.google.com/kubernetes-engine/docs/how-to/sandbox-pods.

This page says gVisor is incompatible with Istio. Is this why? Came across this issue trying to figure out what exactly is incompatible here.

**Comment by fvoznika** [comment]
Yes, this is the reason why. Istio uses iptables to forward container traffic to the envoy sidecar, and gVisor doesn't support iptables at the moment. We're currently working on it...

**Comment by schnie** [comment]
Thanks for the info! Do you know if it's possible to use Istio for a single namespace on a different node pool, from the one that gVisor is enabled and being used in? It makes sense that there would be issues for a sandboxed pod that has the envoy sidecar, but can gVisor be used on a pod that does not have an envoy sidecar, even though Istio is running elsewhere in the cluster?

**Comment by kevinGC** [comment]
If I understand correctly, yes that would be possible. As long as Istio itself isn't running in a gVisor pod, I don't anticipate an issue.

(and iptables are coming!)

**Comment by dimberman** [comment]
@kevinGC Is there any active work being done on the IP Tables? Would love to have both istio + gvisor when possible :).

**Comment by sjmiller609** [comment]
Looks like @kevinGC is working on it?
https://github.com/google/gvisor/pull/279/files
https://github.com/google/gvisor/pull/668/files

**Comment by ivans3** [comment]
Is using the Istio CNI a solution to this problem? Then the iptables rules in the pod's netns will be created by the istio-CNI DaemonSet which runs with the NET_ADMIN and without gvisor

**Comment by fvoznika** [comment]
@ivans3 Istio CNI doesn't work because it tries to setup the network inside the pod's network namespace. In case of gVisor, the network is virtualized inside the sandbox and changing iptable rules in the host will not have the desired effect. The sidecar proxy runs as a sidecar inside the sandbox and the iptable rules need to be set inside of it too.

There is work going on to support Istio without sidecards, running the proxy as another pod alongside the sandbox. This would be the ideal solution, as it fully isolates the proxy from the sandbox.

**Comment by ivans3** [comment]
@fvoznika thanks for the explanation, appreciate it! Looking forward to the upcoming feature!

**Comment by kevinGC** [comment]
Heads up: Istio is supported in gVisor. Make sure to run with `runsc` flag `--net-raw=true` (required to setup the `iptables` rules Istio relies on).

More generally, we support a chunk of `iptables` chains (`PREROUTING`, `INPUT`, and `OUTPUT`), tables (`filter` and `nat`), and other features (e.g. TCP and UDP matching).

**Comment by ivans3** [comment]
Thanks so much!

**Comment by nsoubelet** [comment]
> Heads up: Istio is supported in gVisor. Make sure to run with `runsc` flag `--net-raw=true` (required to setup the `iptables` rules Istio relies on).
> 
> More generally, we support a chunk of `iptables` chains (`PREROUTING`, `INPUT`, and `OUTPUT`), tables (`filter` and `nat`), and other features (e.g. TCP and UDP matching).

Hi @kevinGC, I am struggling to find, in the context of Kubernetes+Containerd, where to specify `--net-raw=true`.
I tested it by adding `NET_RAW` in `securityContext` but does not work so I guess it can be also configured in the node. I failed to find more information in the documentation.

Can it be specified in `/etc/containerd/runsc.toml`? Or there is another way to do this?

Thanks

**Comment by ianlewis** [comment]
@nsoubelet As you may have surmised, you can add the flag in `/etc/containerd/runsc.toml` as outlined in https://gvisor.dev/docs/user_guide/containerd/configuration/ (assuming that's the right path for the shim's configuration).

```
[runsc_config]
  net-raw = "true"
```

**Comment by nsoubelet** [comment]
Great, thanks @ianlewis I'll try that.
