### ISSUE TITLE
runsc events' per container

### ISSUE THREAD

**Issue by amscanne** [google/gvisor#172]
Runsc should provide container stats for containers inside the sandbox.

The stats should be at least contain cpu and memory usage.

Should probably provided with `runsc events --stats`

**Comment by Random-Liu** [comment]
Here is the minimum stats we need for Kubernetes integration https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.proto#L1241.

**Comment by ianlewis** [comment]
This issue came up on a stackoverflow question. Reporting pod CPU metrics are currently blocking the use of HorizontalPodAutoscaler.

**Comment by almottier** [comment]
Hello, any update on this ?

**Comment by kevinGC** [comment]
This is on our roadmap. I'm hoping to get to it the next few months.

**Comment by almottier** [comment]
Will you expose storage stats too ?

**Comment by kevinGC** [comment]
We'll probably want to add per-container versions of the current `--stat` report first. Are you referring to the `Bklio` field of https://godoc.org/github.com/containerd/go-runc#Stats or something else?

**Comment by ianlewis** [comment]
CRI returns container stats which includes file system usage. In the context of Kubernetes that's what we would need.
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.proto#L1276-L1286

Unfortunately, containerd's cri implementation seems to aggregate filesystem usage stats itself directly from each filesystem type and assumes the mounts are visible from a mount namespace on the host. That may make it difficult for us to provide those stats.
https://github.com/containerd/containerd/tree/master/snapshots

That said, I'm not aware of much that uses those stats.

@almottier What is your use case?

**Comment by almottier** [comment]
I am using resources limits, for example:

```
resources:
  limits:
    memory: "65Mi"
    cpu: "75m"
    ephemeral-storage: "4Gi"
```

But it looks `cpu` and `ephemeral-storage` are not supported yet.

**Comment by ianlewis** [comment]
Resource limits aren't affected by support for container stats. Those are used to set the resource limits on the sandbox which should work. The difference between normal containers and gvisor is that resource limits are enforced by host cgroups at the Pod level rather than the container level. Maybe you're looking for https://github.com/google/gvisor/issues/190 ?

**Comment by almottier** [comment]
Thank you for the clarification! 
Btw, is it the unsupported CPU container stat which affects the `kubectl top pods` always returning `0m` ?

**Comment by cerenarpaci** [comment]
Hi, what is the update on this?

**Comment by fvoznika** [comment]
It's in the backlog. We hope to pick it up sometime in Jan/21.

**Comment by cerenarpaci** [comment]
Hi, is there any update on this?

**Comment by kevinGC** [comment]
#5070 adds CPU usage accounting. More to come, but is there a specific stat you're looking for @cerenarpaci?

**Comment by cerenarpaci** [comment]
> #5070 adds CPU usage accounting. More to come, but is there a specific stat you're looking for @cerenarpaci?

Hi @kevinGC - thanks a lot for the quick response. I am looking for memory usage  stats.
