### ISSUE TITLE
Error creating mount with source ".../hostname": broken pipe: unknown.

### ISSUE THREAD

**Issue by fvoznika** [google/gvisor#1765]
This error can happen running any image with kernel between 5.1 and 5.3.15, 5.4.2, or 5.5. This happens because root runs with more strict `RLIMIT_MEMLOCK` limit. Go 1.14 attempts to [mlock thread stacks](https://github.com/golang/go/issues/35777) to workaround a Linux kernel bug, trips over the limit, and dies. You'll find messages like these in the gofer log:

```
runtime: mlock of signal stack failed: 12
runtime: increase the mlock limit (ulimit -l) or
runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
fatal error: mlock failed
```

To workaround it, add the following line to  the `[Service]` section in `/lib/systemd/system/containerd.service`:
```
LimitMEMLOCK=infinity
```
Then run: `systemctl daemon-reload && systemctl restart containerd`

**Comment by ayushr2** [comment]
#151 and #2255 have added good docs and friendly messages. This is a kernel bug. Not sure what more we can do.
