### ISSUE TITLE
gVisor freezing on futex when kvm backend used

### ISSUE THREAD

**Issue by mplebanski** [google/gvisor#177]
docker_version: Docker version 18.09.4, build d14af54266
uname: Linux hostname 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
command: docker run --rm --runtime=runsc -ti ubuntu /bin/bash

My docker config:

```json
{
    "runtimes": {
        "runsc": {
            "runtimeArgs": [
                "--platform=kvm"
            ], 
            "path": "/usr/local/bin/runsc"
        }
    }
}
```

`runsc` is available under `$PATH`. 

It works when configured to use `ptrace`:

```json
{
    "runtimes": {
        "runsc": {
            "runtimeArgs": [
                "--platform=ptrace"
            ], 
            "path": "/usr/local/bin/runsc"
        }
    }
}
```

Find strace logs attached:

[docker_logs.txt](https://github.com/google/gvisor/files/3029159/docker_logs.txt)

It freezes like this on every run.

**Comment by amscanne** [comment]
Note that those logs are just the strace logs from "docker run" itself, which connects to the Docker daemon via a unix socket and doesn't do anything interesting.

Would it be possible to attach the debugging logs per the README?

**Comment by mplebanski** [comment]
OK, config used:

```json
{
    "runtimes": {
        "runsc": {
            "path": "/usr/local/bin/runsc",
            "runtimeArgs": [
                "--debug-log=/tmp/runsc/",
                "--debug",
                "--strace"
            ]
       }
    }
}
```

Logs:



[runsc.log.20190403-103417.425823.boot.txt](https://github.com/google/gvisor/files/3037650/runsc.log.20190403-103417.425823.boot.txt)
[runsc.log.20190403-103417.336041.gofer.txt](https://github.com/google/gvisor/files/3037651/runsc.log.20190403-103417.336041.gofer.txt)
[runsc.log.20190403-103417.334220.create.txt](https://github.com/google/gvisor/files/3037652/runsc.log.20190403-103417.334220.create.txt)
