### ISSUE TITLE
Remove dependency on gcloud in benchmark

### ISSUE THREAD

**Issue by tanjianfeng** [google/gvisor#1793]
Since commit cb3906ae0057 ("Add tools for generating images.), below error shows:

$bazel run :benchmarks -- list
INFO: Invocation ID: f376daf5-ba61-43f1-9035-022ab6a3c6cd
...
INFO: Analyzed target //benchmarks:benchmarks (1 packages loaded, 6 targets configured).
INFO: Found 1 target...
ERROR: /path/to/gvisor/tools/images/BUILD:9:1: Executing genrule //tools/images:zone failed (Exit 127)
/bin/bash: gcloud: command not found
Target //benchmarks:benchmarks failed to build

**Comment by zkoopmans** [comment]
This is mine. This is part of a benchmark suite that I'm writing, and I've been focusing on getting it working internally. 

There will always be a gcloud option, but I'll fix it to not require that image for just running the tool.

**Comment by zkoopmans** [comment]
https://github.com/google/gvisor/pull/1861

**Comment by tanjianfeng** [comment]
> You can preview the changes here: #1861

I've tested in my env, it works like a charm. Thanks for the fix.
