### ISSUE TITLE
netstack: how to dump endpoint state?

### ISSUE THREAD

**Issue by elmarco** [google/gvisor#1847]
slirp/qemu can provide quite useful details of ongoing connections:
```
(qemu) info usernet
Hub 0 (user.0):
  Protocol[State]    FD  Source Address  Port   Dest. Address  Port RecvQ SendQ
  TCP[ESTABLISHED]   46       10.0.2.15 58894  172.217.16.132    80     0     0
  UDP[223 sec]       45       10.0.2.15 35765      72.5.72.15   123     0     0
  UDP[222 sec]       44       10.0.2.15 47712   96.245.170.99   123     0     0
  UDP[222 sec]       43       10.0.2.15 54531     74.6.168.72   123     0     0
```
I am looking for a way to implement something similar for slirpnetstack. I found stack.RegisteredEndpoints() could list the existing endpoints, unfortunately, TransportEndpoint interface is quite limited.

Should I add a String() method to TransportEndpoint and implement a human-friendly debug string in the various transports?

Eventually, it would be nice to have a machine-friendly way to export those details as well (as a consumer of the module), so other GetInfo() method would be nice.

Any other idea? thanks

**Comment by prattmic** [comment]
cc @iangudger @hbhasker

**Comment by hbhasker** [comment]
See https://github.com/google/gvisor/blob/4a73bae269ae9f52a962ae3b08a17ccaacf7ba80/pkg/sentry/fs/proc/net.go#L553 for an example of how to do this. gVisor relies on the higher level netstack.go socket interface but most of those calls call the corresponding Endpoint interface.

It should be possible to write something that uses the RegisteredEndpoints and dumps them out in a similar way.

**Comment by iangudger** [comment]
It should also be noted that in most cases, types that implement `stack.TransportEndpoint` also implement `tcpip.Endpoint`. For a quick and dirty version, you could just do an interface conversion type assertion.

**Comment by elmarco** [comment]
thanks, not sure I ended up with the cleanest code yet, but that works for me.
