### ISSUE TITLE
tmux.Lock may block forever under race conditions

### ISSUE THREAD

**Issue by zhiqiangxu** [google/gvisor#1871]
for {
		if v := atomic.LoadInt32(&m.v); v >= 0 && atomic.SwapInt32(&m.v, -1) == 1 {
			return
		}

		// the original lock holder may have already unlocked before ChanReceive is called
		<-m.ch
	}

`tmux.Lock` may miss the release signal under race conditions. I considered similar situations in https://github.com/zhiqiangxu/util/blob/master/wm/max.go, in order to do it in a lock-free manner, a dedicated G is required, like what runtime does for deadlock check.

**Comment by hbhasker** [comment]
Could you elaborate or demonstrate the issue with a test? It's not clear to me why tmux will miss a release.

**Comment by zhiqiangxu** [comment]
> Could you elaborate or demonstrate the issue with a test? It's not clear to me why tmux will miss a release.

It may happen that before this line is run in Goroutine 1:

`<-m.ch`

the default case has finished in Goroutine 2:
```
select {
	case m.ch <- struct{}{}:
	default:
	}
```

**Comment by hbhasker** [comment]
The channel is usually buffered and of size 1. It can miss if one uses an unbuffered channel.

**Comment by zhiqiangxu** [comment]
> The channel is usually buffered and of size 1. It can miss if one uses an unbuffered channel.

Correct ! I missed that the channel has buffer size of 1..
