### ISSUE TITLE
critest: privilege escalation

### ISSUE THREAD

**Issue by zhuangqh** [google/gvisor#189]
## Problem

critest v1.12

**should allow privilege escalation when false**

```
• Failure in Spec Teardown (AfterEach) [4.790 seconds]
[k8s.io] Security Context
/root/go/src/github.com/kubernetes-sigs/cri-tools/pkg/framework/framework.go:72
  NoNewPrivs
  /root/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/security_context.go:673
    should allow privilege escalation when false [AfterEach]
    /root/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/security_context.go:709

    expected log "Effective uid: 0\n" (stream="stdout") not found in logs [{timestamp:{wall:531788930 ext:63688680097 loc:0x145e220} stream:stdout log:Effective uid: 1000
    }]
    Expected
        <bool>: false
    to be true

    /root/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:544
```

## Version

containerd 1.2 + containerd-shim-runsc-v1
runsc commit  0b768871

**Comment by ianlewis** [comment]
Could you maybe create this bug on the shim repo? CRI related issues should probably be handled there https://github.com/google/gvisor-containerd-shim/issues/new

**Comment by fvoznika** [comment]
gVisor currently ignores the setuid/setgid bit in executables. Once setuid/setgid is implemented, we can plumb NoNewPrivs through.

**Comment by zhuangqh** [comment]
> gVisor currently ignores the setuid/setgid bit in executables. Once setuid/setgid is implemented, we can plumb NoNewPrivs through.

thanks for your reply. I've created an issue on the shim repo https://github.com/google/gvisor-containerd-shim/issues/24.  close...
