### ISSUE TITLE
docker give error when i use --runtime=runsc

### ISSUE THREAD

**Issue by wuqixuan** [google/gvisor#19]
sudo docker run --runtime=runsc -it ubuntu:latest /bin/bash
docker: Error response from daemon: invalid character 'l' in literal false (expecting 'a').

**Comment by fvoznika** [comment]
Please, follow [these instruction](https://github.com/google/gvisor#debugging) and attach the logs in /tmp/runsc. What version of docker are you running?

**Comment by wuqixuan** [comment]
Thank you very much, i used the latest docker, it's working.

**Comment by qq843700497** [comment]
I0507 15:36:32.406081   74991 x:0] ***************************
I0507 15:36:32.406174   74991 x:0] Args: [/root/go/src/gvisor/bazel-bin/runsc/linux_amd64_pure_stripped/runsc --debug-log-dir=/tmp/runsc --debug --strace --root /var/run/docker/runtime-runsc/moby --log /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/e93c939184a4b9a7f949e878fdc391b605663b90c7eba84d6b7d1ca9aeaef46d/log.json --log-format json create --bundle /var/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/e93c939184a4b9a7f949e878fdc391b605663b90c7eba84d6b7d1ca9aeaef46d --pid-file /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/e93c939184a4b9a7f949e878fdc391b605663b90c7eba84d6b7d1ca9aeaef46d/init.pid e93c939184a4b9a7f949e878fdc391b605663b90c7eba84d6b7d1ca9aeaef46d]
I0507 15:36:32.406193   74991 x:0] PID: 74991
I0507 15:36:32.406198   74991 x:0] UID: 0, GID: 0
I0507 15:36:32.406202   74991 x:0] Configuration:
I0507 15:36:32.406206   74991 x:0]              RootDir: /var/run/docker/runtime-runsc/moby
I0507 15:36:32.406210   74991 x:0]              Platform: ptrace
I0507 15:36:32.406221   74991 x:0]              FileAccess: proxy, overlay: false
I0507 15:36:32.406227   74991 x:0]              Network: sandbox, logging: false
I0507 15:36:32.406232   74991 x:0]              Strace: true, max size: 1024, syscalls: []
I0507 15:36:32.406237   74991 x:0] ***************************
D0507 15:36:32.407330   74991 x:0] Spec: &{Version:1.0.1 Process:0xc42016c340 Root:0xc42016a4e0 Hostname:e93c939184a4 Mounts:[{Destination:/proc Type:proc Source:proc Options:[nosuid noexec nodev]} {Destination:/dev Type:tmpfs Source:tmpfs Options:[nosuid strictatime mode=755 size=65536k]} {Destination:/dev/pts Type:devpts Source:devpts Options:[nosuid noexec newinstance ptmxmode=0666 mode=0620 gid=5]} {Destination:/sys Type:sysfs Source:sysfs Options:[nosuid noexec nodev ro]} {Destination:/sys/fs/cgroup Type:cgroup Source:cgroup Options:[ro nosuid noexec nodev]} {Destination:/dev/mqueue Type:mqueue Source:mqueue Options:[nosuid noexec nodev]} {Destination:/etc/resolv.conf Type:bind Source:/var/lib/docker/containers/e93c939184a4b9a7f949e878fdc391b605663b90c7eba84d6b7d1ca9aeaef46d/resolv.conf Options:[rbind rprivate]} {Destination:/etc/hostname Type:bind Source:/var/lib/docker/containers/e93c939184a4b9a7f949e878fdc391b605663b90c7eba84d6b7d1ca9aeaef46d/hostname Options:[rbind rprivate]} {Destination:/etc/hosts Type:bind Source:/var/lib/docker/containers/e93c939184a4b9a7f949e878fdc391b605663b90c7eba84d6b7d1ca9aeaef46d/hosts Options:[rbind rprivate]} {Destination:/dev/shm Type:bind Source:/var/lib/docker/containers/e93c939184a4b9a7f949e878fdc391b605663b90c7eba84d6b7d1ca9aeaef46d/mounts/shm Options:[rbind rprivate]}] Hooks:0xc42001e5f0 Annotations:map[] Linux:0xc420186000 Solaris:<nil> Windows:<nil>}
D0507 15:36:32.407387   74991 x:0] Spec.Hooks: &{Prestart:[{Path:/proc/74732/exe Args:[libnetwork-setkey e93c939184a4b9a7f949e878fdc391b605663b90c7eba84d6b7d1ca9aeaef46d 95d458bb99f3f917cce79bb5da08da9fe6ee75f2374107e7d9bd74df65a86481] Env:[] Timeout:<nil>}] Poststart:[] Poststop:[]}
D0507 15:36:32.407399   74991 x:0] Spec.Linux: &{UIDMappings:[] GIDMappings:[] Sysctl:map[] Resources:0xc42005ef60 CgroupsPath:/docker/e93c939184a4b9a7f949e878fdc391b605663b90c7eba84d6b7d1ca9aeaef46d Namespaces:[{Type:mount Path:} {Type:network Path:} {Type:uts Path:} {Type:pid Path:} {Type:ipc Path:}] Devices:[] Seccomp:0xc42005ad00 RootfsPropagation: MaskedPaths:[/proc/kcore /proc/keys /proc/latency_stats /proc/timer_list /proc/timer_stats /proc/sched_debug /proc/scsi /sys/firmware] ReadonlyPaths:[/proc/asound /proc/bus /proc/fs /proc/irq /proc/sys /proc/sysrq-trigger] MountLabel: IntelRdt:<nil>}
D0507 15:36:32.407423   74991 x:0] Spec.Process: &{Terminal:false ConsoleSize:<nil> User:{UID:0 GID:0 AdditionalGids:[] Username:} Args:[/hello] Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=e93c939184a4] Cwd:/ Capabilities:0xc420080300 Rlimits:[] NoNewPrivileges:false ApparmorProfile: OOMScoreAdj:0xc420182428 SelinuxLabel:}
D0507 15:36:32.407487   74991 x:0] Spec.Root: &{Path:/var/lib/docker/devicemapper/mnt/ae5081bca40fe23a45a2d9b3a05956cc4fd255e32088da6db95a05fdb73c6bc1/rootfs Readonly:false}
D0507 15:36:32.407502   74991 x:0] Create sandbox "e93c939184a4b9a7f949e878fdc391b605663b90c7eba84d6b7d1ca9aeaef46d" in root dir: /var/run/docker/runtime-runsc/moby
D0507 15:36:32.407578   74991 x:0] Starting gofer: /root/.cache/bazel/_bazel_root/5d93485aaf716d98afd7bcf6742e970a/execroot/__main__/bazel-out/k8-fastbuild/bin/runsc/linux_amd64_pure_stripped/runsc [--debug=true --debug-log-dir=/tmp/runsc --log=/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/e93c939184a4b9a7f949e878fdc391b605663b90c7eba84d6b7d1ca9aeaef46d/log.json --log-format=json --root=/var/run/docker/runtime-runsc/moby --strace=true gofer --bundle /var/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/e93c939184a4b9a7f949e878fdc391b605663b90c7eba84d6b7d1ca9aeaef46d --io-fds=3 --io-fds=4 --io-fds=5 --io-fds=6]
I0507 15:36:32.408215   74991 x:0] Gofer started, pid: 74996
I0507 15:36:32.408274   74991 x:0] Sandbox will be started in empty IPC and UTS namespaces
I0507 15:36:32.408283   74991 x:0] Sandbox will be started in the current PID namespace
I0507 15:36:32.408287   74991 x:0] Sandbox will be started in empty mount namespace
I0507 15:36:32.408292   74991 x:0] Sandbox will be started in the container's network namespace: {Type:network Path:}
I0507 15:36:32.408299   74991 x:0] Sandbox will be started in empty user namespace
D0507 15:36:32.408303   74991 x:0] Starting sandbox: /root/.cache/bazel/_bazel_root/5d93485aaf716d98afd7bcf6742e970a/execroot/__main__/bazel-out/k8-fastbuild/bin/runsc/linux_amd64_pure_stripped/runsc [/root/.cache/bazel/_bazel_root/5d93485aaf716d98afd7bcf6742e970a/execroot/__main__/bazel-out/k8-fastbuild/bin/runsc/linux_amd64_pure_stripped/runsc --debug=true --debug-log-dir=/tmp/runsc --log=/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/e93c939184a4b9a7f949e878fdc391b605663b90c7eba84d6b7d1ca9aeaef46d/log.json --log-format=json --root=/var/run/docker/runtime-runsc/moby --strace=true boot --bundle /var/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/e93c939184a4b9a7f949e878fdc391b605663b90c7eba84d6b7d1ca9aeaef46d --controller-fd=3 --console=false --io-fds=4 --io-fds=5 --io-fds=6 --io-fds=7]
D0507 15:36:32.408333   74991 x:0] Destroy sandbox "e93c939184a4b9a7f949e878fdc391b605663b90c7eba84d6b7d1ca9aeaef46d"
D0507 15:36:32.408341   74991 x:0] Killing gofer for sandbox "e93c939184a4b9a7f949e878fdc391b605663b90c7eba84d6b7d1ca9aeaef46d"
W0507 15:36:32.408359   74991 x:0] FATAL ERROR: error creating sandbox: fork/exec /root/.cache/bazel/_bazel_root/5d93485aaf716d98afd7bcf6742e970a/execroot/__main__/bazel-out/k8-fastbuild/bin/runsc/linux_amd64_pure_stripped/runsc: invalid argument

===================================
docker version 18.03.0-ce
docker run --runtime=runsc hello-world    
docker: Error response from daemon: OCI runtime create failed: /var/lib/docker/runtimes/runsc did not terminate sucessfully: unknown.
