### ISSUE TITLE
gVisor IO performance

### ISSUE THREAD

**Issue by Anjali05** [google/gvisor#192]
I am runninng IO measurement(using dd) in gVisor in both kvm and ptrace mode. I am getting a better IO than runc and IO is almost same for kvm and ptrace. According to my understanding the gVisor performance should be worse than runc or is it what is expected? If so, can someoce clarify as to why it could be happening?

**Comment by amscanne** [comment]
What do you mean by I/O?

There's one known case of better performance than native, which is large writes to internal memory-backed files. Because we represent the block sequences for user memory are range-based, rather than page-based, writing large blocks of memory actually involves fewer lookups.

What other kinds of experiments are you looking to do? Happy to help out or provide guidance where needed.

**Comment by Anjali05** [comment]
@amscanne 
I am measuring the IO throughput using this command
dd if=/dev/urandom of=/tmp/ioload.log bs=512kB count=100 conv=fdatasync oflag=dsync
For gVisor(both kvm+ptrace), I am getting around 184 MB/sec and for runc its around 54MB/sec. 

Is this because of what you mentioned?

**Comment by amscanne** [comment]
That gap seems way too big for that. I suspect this is a result of runsc not respecting the sync semantics. If you drop those flags I suspect you will see much different results.

**Comment by prattmic** [comment]
Note as well that /tmp inside gVisor is usually a tmpfs, while on most Linux distros it is usually an on-disk filesystem (ext4). Comparing gVisor tmpfs to Linux tmpfs is likely a better comparison (/dev/shm/ should be a tmpfs on both).

**Comment by Anjali05** [comment]
@amscanne  @prattmic I will try without the sync flag. I am still curious as to why kvm and ptrace have the same IO. I went through their logs(.gofer file) but I do not see any difference in the way they are doing the syscalls. Can you elaborate on that?

**Comment by amscanne** [comment]
The kvm mode does not run a hardware virtualized VM: the sentry runs in the host and as the guest OS.

The two platforms are likely similar because with a blocksize of 512kb, the time reading urandom and writing data likely dominates any platform costs.

**Comment by Anjali05** [comment]
@amanda-tait So the container runs inside sentry in kvm platform and in the ptrace mode sentry only intercepts the syscalls made by container which runs as a normal container? Is this the difference between the two platforms? Does the kvm mode use QEMU or some other hypervisor?

**Comment by amscanne** [comment]
QEMU is the user-space application that uses the kernel's KVM extensions to run hardware virtualized machines. The sentry also uses the kernel's KVM extensions to run code in a guest context. In both cases the kernel is the actual hypervisor.

The difference between the two is the hardware context in which the untrusted code is executed and how calls and traps are intercepted. For ptrace mode, code runs in a host context (but certainly looks nothing like a "normal container") and the kernel is responsible for trapping. For kvm mode, the code runs in a guest context and the sentry traps directly in the guest context.

**Comment by Anjali05** [comment]
@amscanne  What's the role of the sentry in the ptrace mode if the trapping is done by the kernel?

**Comment by amscanne** [comment]
The trapping is done by the kernel but the implementation of everything that an application sees and interacts with is within the sentry. By trapping, I mean that when the application executes the syscall instruction, hits a fault, etc. the host kernel sees that, puts the execution stub in a wait state, notifies the sentry, which then picks it up again There are no processes on the host system that directly correspond to the application processes, even in ptrace mode.

**Comment by WhoisZihan** [comment]
Hi, is there any statistic about IO performance breakdown? By logging in the code, I find that the `Open` system call actually involves 2 RPC call to gofer, but read & write can be somewhat optimized.

I wonder if there is any measurement about the time cost of each component involved during a `Open/Read/Write` call (under KVM platform)? It seems gVisor currently takes a different caching strategy from linux.

**Comment by ianlewis** [comment]
I'm going to close this issue since it's old but feel free to reach out on our gitter channel if you have more questions: https://gitter.im/gvisor/community
