### ISSUE TITLE
systemd-cgroup support

### ISSUE THREAD

**Issue by joost14** [google/gvisor#193]
Hello, 

I'm trying to setup Kubernetes(kubeadm) + CRI-O + runsc. I'm enabling the runtimes through the alpha feature gate RuntimeClass (crio is dropping support for `untrusted-workload`). I've got it to work with some other runtimes already, but I'm having some issues when trying to run runsc. 

The error when I'm starting the pod is the following: 
`kubelet, k8sworker01  Failed create pod sandbox: rpc error: code = Unknown desc = container create failed: flag provided but not defined: -systemd-cgroup`

Crio config file: 
```
  [crio.runtime.runtimes.runsc]
  runtime_path = "/usr/local/bin/runsc"
```

I was wondering if anyone got runsc working with kubernetes and crio yet. 

Edit: when switching the cgroup-manager within the crio config from systemd to groupfs the container wont start at all. Error: 
`kubelet, k8sworker01  Failed create pod sandbox: rpc error: code = Unknown desc = cri-o configured with cgroupfs cgroup manager, but received systemd slice as parent: /kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pode9fd6274_59d1_11e9_af90_9e3c8464d679.slice
`

Edit2:
Solved it by changing systemd to cgroupfs in crio.conf and in '/etc/default/kubelet': 
' KUBELET_EXTRA_ARGS=--cgroup-driver=cgroupfs' 

That leaves me with the following question; is 'systemd' not supported yet for gvisor?

**Comment by kevinGC** [comment]
I believe this is the kubelet and runtime (cri-o) not agreeing on how to manage cgroups for the pod, not something that gVisor doesn't have support for. Based on [this doc](https://github.com/filbranden/kubernetes-community/blob/009f067c6bc106d062a416d0a1537de5ffa8c023/contributors/design-proposals/node/cgroup-driver-kubelet-and-runtime.md), it some Linux distros require extra configuration.

**Comment by joost14** [comment]
Hi @kevinGC, 

Thanks for the information. Though it is still a bit strange that kata and runc work just fine when using systemd. So this issue may only is the case when using kubelet and crio?

**Comment by fvoznika** [comment]
`runsc` doesn't implement the `-systemd-cgroup` flag. `runsc` implements cgroups using cgroupfs, as you noted when you set `KUBELET_EXTRA_ARGS=--cgroup-driver=cgroupfs`. Is that something that works for you?

**Comment by joost14** [comment]
Hi @fvoznika, 

I know `runsc` doesn't implement the flag. I was just wondering if `systemd` was compatible with `runsc `or if it is just some configuration error on my part.

**Comment by sdeoras** [comment]
I got the same error trying to make `runsc` work with `cri-o`. We use `systemd` as `cgroup-driver` so I am interested to know if it is possible to make `runsc` work with this setup? Thanks.

**Comment by 25077667** [comment]
Hi all,

I also meet this problem, but I'm not using the kube. How can I solve it?
I use the raw docker on Archlinux  .
This is my platform:
![](https://imgur.com/OL6fyid.png)

And this is the error message:
![](https://imgur.com/yIV0f5C.png)

**Comment by wtfismyip** [comment]
@25077667   I ran into this issue both on Debian 11 and Ubuntu 21.10 with normal Docker. Adding `systemd.unified_cgroup_hierarchy=false systemd.legacy_systemd_cgroup_controller=false` to the kernel boot options fixed it for me.

**Comment by avagin** [comment]
> Possibly solved by these?

@arno01 these pr-s added the support of cgroupv2, but the systemd cgroup-driver isn't implemented yet. It doesn't mean that you can't use gvisor on systemd systems, but you will need to change the default systemd cgroup-drive to cgroupfs.

**Comment by git-noise** [comment]
Hello,
Is there any plan to support systemd cgroups in the future (or near future)?

Using cgroupfs may not be an easy option as I believe it is not recommended with kubeadm as mentioned here: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/ ?

While possible to run both in parallel, it seems also not recommended: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/#using-the-cgroupfs-driver

Many thanks,
