### ISSUE TITLE
network  compatibility testing with cpython tool

### ISSUE THREAD

**Issue by chuangxueli** [google/gvisor#194]
hi
I'm doing some ’compatibility testing with cpython test cases.The testing steps are below:
1,run the gvisor with --network=host,
sudo docker run --runtime=runsc  -it -v /mnt/cpython/:/test  ubuntu /bin/bash
2,then run the command ./python  ./Lib/test/test_socket.py in bash
3,check the test result,there are many failed items.These failed items are about the MsgFlag.MSG_CTRUNC issues, which are not handled after the recvmsg has been returned:
FAIL: testCmsgTrunc1 (__main__.RecvmsgSCMRightsStreamTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./Lib/test/test_socket.py", line 3398, in testCmsgTrunc1
    self.checkTruncatedHeader(self.doRecvmsg(self.serv_sock, len(MSG), 1))
  File "./Lib/test/test_socket.py", line 3371, in checkTruncatedHeader
    self.checkFlags(flags, eor=True, checkset=socket.MSG_CTRUNC,
  File "./Lib/test/test_socket.py", line 2483, in checkFlags
    self.assertEqual(flags & mask, checkset & mask)
AssertionError: <MsgFlag.0: 0> != <MsgFlag.MSG_CTRUNC: 8>

======================================================================
FAIL: testCmsgTrunc2Int (__main__.RecvmsgSCMRightsStreamTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./Lib/test/test_socket.py", line 3407, in testCmsgTrunc2Int
    self.checkTruncatedHeader(self.doRecvmsg(self.serv_sock, len(MSG),
  File "./Lib/test/test_socket.py", line 3371, in checkTruncatedHeader
    self.checkFlags(flags, eor=True, checkset=socket.MSG_CTRUNC,
  File "./Lib/test/test_socket.py", line 2483, in checkFlags
    self.assertEqual(flags & mask, checkset & mask)
AssertionError: <MsgFlag.0: 0> != <MsgFlag.MSG_CTRUNC: 8>

4,I have followed the codes in pkg/sentry/syscalls/linux/sys_socket.go and pkg/sentry/socket/unix/unix.go,found that the RecvMsg not set the msg.Flags when it returned.
Thus all the msg.Flags are zero when read from the recvmsg.
So  do you have plan to support the msg.Flags  in the socket of the sentry?
thanks
   chuangxueli

**Comment by ayushr2** [comment]
I believe this is fixed. Because we run python runtime tests as presubmits. From the `test_socket` test suite, [these tests](https://github.com/google/gvisor/blob/d353f07ba5bb62d0b58ba741e3f6d88774c35a79/test/runtimes/proctor/lib/python.go#L78-L122) fail on gVisor currently and are excluded. This list does not include `RecvmsgSCMRightsStreamTest`. So it must be working.
