### ISSUE TITLE
Add flag to drop net_raw from capability set

### ISSUE THREAD

**Issue by fvoznika** [google/gvisor#198]
The flag is enabled by default. If enabled, it drops net_raw capability from container in create. This is to protect docker users from getting net_raw by default without realizing it. It can be dangerous to give raw socket access untrusted containers as it gives too much access to the host network and services reachable by the container. So the administrator must enable it explicitly to give raw socket access to containers.

The flag doesn't apply to `runsc exec` because exec doesn't acquire any new capability by default. This makes `docker exec --privileged` gain net_raw capability as expect and makes debugging of restricted containers possible.

**Comment by kevinGC** [comment]
Fixed in https://github.com/google/gvisor/commit/43dff57b878edb5502daf486cbc13b058780dd56.
