### ISSUE TITLE
msghdr flag MSG_TRUNC not set

### ISSUE THREAD

**Issue by iangudger** [google/gvisor#200]
recvmsg should set the flags field in the passed msghdr with MSG_TRUNC when appropriate. It currently always sets flags to 0.

**Comment by chuangxueli** [comment]
yes,we are also following this question,and the control data is not delivered to the lower layer in socket

**Comment by iangudger** [comment]
@chuangxueli If you are having a problem with control messages, please file a separate issue. This issue is only about setting the MSG_TRUNC flag. I have a CL out which fixes this issue if you want to try it: gvisor.dev/cl/16881
