### ISSUE TITLE
A problem encountered when running syscall tests

### ISSUE THREAD

**Issue by lubinszARM** [google/gvisor#2034]
Hi @avagin 
It looks like that there is something wrong with the current syscall test.
Looks like the test cases will be skipped when I try to run some specific syscall test.

My test steps:
1, Platform: x86 + ubuntu18.04
2, My test command:
bazel test //test/syscalls:clock_getres_test_native --test_output=streamed
or
bazel test //test/syscalls:clock_getres_test_runsc_ptrace --test_output=streamed

3, The output looks strange:
Failed to match any benchmarks against regex: ^$
Failed to match any benchmarks against regex: ^$
PASS
Target //test/syscalls:clock_getres_test_native up-to-date:
  bazel-bin/test/syscalls/clock_getres_test_native-runner
INFO: Elapsed time: 72.065s, Critical Path: 29.05s
INFO: 1539 processes: 1539 linux-sandbox.
INFO: Build completed successfully, 1592 total actions
//test/syscalls:clock_getres_test_native                                 PASSED in 0.1s

INFO: Build completed successfully, 1592 total actions

4, No test output in bazel-testlogs/test/syscalls/fork_test_native

My questions: 
1, Why is there the ERROR output: Failed to match any benchmarks against regex: ^$
2, If I removed all related code about filterBenchmark, it seems that it will find 0 test cases.
The output is like following:
Note: Google Test filter = ^ClockGetres.Timespec$
[==========] Running 0 tests from 0 test suites.
[==========] 0 tests from 0 test suites ran. (0 ms total)
[  PASSED  ] 0 tests.

Thanks.

**Comment by lubinszARM** [comment]
cc @xiaobo55x

**Comment by xiaobo55x** [comment]
I tried to make a little change to the code, and it can run the syscall test cases like before.
```
diff --git a/test/runner/gtest/gtest.go b/test/runner/gtest/gtest.go
index f96e241..21244b4 100644
--- a/test/runner/gtest/gtest.go
+++ b/test/runner/gtest/gtest.go
@@ -71,8 +71,8 @@ func (tc TestCase) Args() []string {
                }
        }
        return []string{
-               fmt.Sprintf("%s=^%s$", filterTestFlag, tc.FullName()),
-               fmt.Sprintf("%s=^$", filterBenchmarkFlag),
+               fmt.Sprintf("%s=%s", filterTestFlag, tc.FullName()),
+               fmt.Sprintf("%s=.", filterBenchmarkFlag),
        }
 }
```

**Comment by xiaobo55x** [comment]
cc @amscanne
