### ISSUE TITLE
docker run --runtime=runsc hello-world failed

### ISSUE THREAD

**Issue by wuqixuan** [google/gvisor#21]
I can run hello-world with runc, but runsc failed. 

$sudo docker run --runtime=runsc hello-world
error reading spec: error unmarshaling spec from file "/var/run/docker/libcontainerd/bab9e5f444815a1a612eef51c2637d146ec84bb5ed882310d8909b4b0e900f3a/config.json": json: cannot unmarshal array into Go struct field Process.capabilities of type specs.LinuxCapabilities
 {"ociVersion":"1.0.0-rc2-dev","platform":{"os":"linux","arch":"amd64"},"process":{"consoleSize":{"height":0,"width":0},"user":{"uid":0,"gid":0},"args":["/hello"],"env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","HOSTNAME=bab9e5f44481"],"cwd":"/","capabilities":["CAP_CHOWN","CAP_DAC_OVERRIDE","CAP_FSETID","CAP_FOWNER","CAP_MKNOD","CAP_NET_RAW","CAP_SETGID","CAP_SETUID","CAP_SETFCAP","CAP_SETPCAP","CAP_NET_BIND_SERVICE","CAP_SYS_CHROOT","CAP_KILL","CAP_AUDIT_WRITE","CAP_SYS_RESOURCE","CAP_SYS_MODULE","CAP_SYS_PTRACE","CAP_SYS_PACCT","CAP_NET_ADMIN","CAP_SYS_ADMIN"]},"root":{"path":"/home/docker/overlay/60442221f3ecdcf8f4fd2db4ebcda9d13c8b705c84d4410f3740c7c9fa1411a8/merged"},"hostname":"bab9e5f44481","mounts":[{"destination":"/proc","type":"proc","source":"proc","options":["nosuid","noexec","nodev"]},{"destination":"/dev","type":"tmpfs","source":"tmpfs","options":["nosuid","strictatime","mode=755"]},{"destination":"/dev/pts","type":"devpts","source":"devpts","options":["nosuid","noexec","newinstance","ptmxmode=0666","mode=0620","gid=5"]},{"destination":"/sys","type":"sysfs","source":"sysfs","options":["nosuid","noexec","nodev","ro"]},{"destination":"/dev/mqueue","type":"mqueue","source":"mqueue","options":["nosuid","noexec","nodev"]},{"destination":"/sys/fs/cgroup","type":"cgroup","source":"cgroup","options":["ro","nosuid","noexec","nodev"]},{"destination":"/etc/resolv.conf","type":"bind","source":"/home/docker/containers/bab9e5f444815a1a612eef51c2637d146ec84bb5ed882310d8909b4b0e900f3a/resolv.conf","options":["rbind","rprivate"]},{"destination":"/etc/hostname","type":"bind","source":"/home/docker/containers/bab9e5f444815a1a612eef51c2637d146ec84bb5ed882310d8909b4b0e900f3a/hostname","options":["rbind","rprivate"]},{"destination":"/etc/hosts","type":"bind","source":"/home/docker/containers/bab9e5f444815a1a612eef51c2637d146ec84bb5ed882310d8909b4b0e900f3a/hosts","options":["rbind","rprivate"]},{"destination":"/dev/shm","type":"bind","source":"/home/docker/containers/bab9e5f444815a1a612eef51c2637d146ec84bb5ed882310d8909b4b0e900f3a/shm","options":["rbind","rprivate"]}],"hooks":{"prestart":[{"path":"/usr/bin/dockerd-1.12.6","args":["libnetwork-setkey","bab9e5f444815a1a612eef51c2637d146ec84bb5ed882310d8909b4b0e900f3a","2813e5d5164ba3526568ffd397e2074766a65f2290e686165c22087394efecd1"]}]},"annotations":{"__BlkBufferWriteBps":"0","__BlkBufferWriteSwitch":"0","__BlkFileLevelSwitch":"0","__BlkFileThrottlePath":"","__BlkMetaWriteTps":"0","__ali_network_alinet":"libnetwork-setkey bab9e5f444815a1a612eef51c2637d146ec84bb5ed882310d8909b4b0e900f3a 2813e5d5164ba3526568ffd397e2074766a65f2290e686165c22087394efecd1","__ali_network_bridge":"docker0","__ali_network_endpoint_id":"713d54c1415be0b263534fe558d5e80314baa72f6a6b7f0cc6f83697d8e8445d","__ali_network_gateway":"192.168.5.1","__ali_network_mac":"02:42:c0:a8:05:02","__ali_network_prefix":"24","__ali_network_type":"bridge","__cput_bvt_warp_ns":"-2","__intel_rdt.l3_cbm":"","__memory_extra_in_bytes":"0","__memory_force_empty_ctl":"-1","__memory_wmark_ratio":"0"},"linux":{"resources":{"devices":[{"allow":false,"access":"rwm"},{"allow":true,"type":"c","major":1,"minor":5,"access":"rwm"},{"allow":true,"type":"c","major":1,"minor":3,"access":"rwm"},{"allow":true,"type":"c","major":1,"minor":9,"access":"rwm"},{"allow":true,"type":"c","major":1,"minor":8,"access":"rwm"},{"allow":true,"type":"c","major":5,"minor":0,"access":"rwm"},{"allow":true,"type":"c","major":5,"minor":1,"access":"rwm"},{"allow":false,"type":"c","major":10,"minor":229,"access":"rwm"}],"disableOOMKiller":false,"oomScoreAdj":0,"memory":{"swappiness":18446744073709551615},"cpu":{"ScheLatSwitch":null},"pids":{"limit":0},"blockIO":{"blkioWeight":0,"ThrottleBufferWriteBpsDevice":null,"ThrottleDeviceIdleTime":null,"ThrottleDeviceLatencyTarget":null}},"cgroupsPath":"/docker/bab9e5f444815a1a612eef51c2637d146ec84bb5ed882310d8909b4b0e900f3a","namespaces":[{"type":"mount"},{"type":"network"},{"type":"uts"},{"type":"pid"},{"type":"ipc"},{"type":"cgroup"}],"devices":[{"path":"/dev/fuse","type":"c","major":10,"minor":229,"fileMode":438,"uid":0,"gid":0}],"maskedPaths":["/proc/kcore","/proc/latency_stats","/proc/timer_list","/proc/timer_stats","/proc/sched_debug"],"readonlyPaths":["/proc/asound","/proc/bus","/proc/fs","/proc/irq","/proc/sys","/proc/sysrq-trigger"]}}

docker: Error response from daemon: containerd: container not started.

**Comment by fvoznika** [comment]
What Docker version are you using?

**Comment by wuqixuan** [comment]
Thank you very much, i use the latest docker, then it's working.
