### ISSUE TITLE
Netstack supports scope

### ISSUE THREAD

**Issue by caleb-letsgo** [google/gvisor#2122]
Does netstack currently support 32 bits?

Does netstack support Windows and MAC /ios?

**Comment by hbhasker** [comment]
Netstack is mostly written with assumptions that it's running on a 64bit system. Netstack could be made to run on windows or MAC/iOS but the lower link layer bits will need work to make it work on these systems.

**Comment by prattmic** [comment]
There is an open PR for 32-bit support in netstack, but it has languished for a while: https://github.com/google/gvisor/pull/814

**Comment by caleb-letsgo** [comment]
OK，thanks!
