### ISSUE TITLE
Improve runsc profile collection

### ISSUE THREAD

**Issue by prattmic** [google/gvisor#220]
The ability to collect sentry profiles with runsc is currently quite limited:

* Only CPU and heap profiles are supported.
* Profiling can only be enabled after startup with `runsc debug`. There is no way to enable profiling when the sandbox starts.

We should add more profile types (tracing, block, mutex, etc: https://godoc.org/runtime/pprof#Profile), and the ability to create them at startup.

**Comment by moricho** [comment]
Hi!
I worked on this issue and made a PR. At first, I implemented more profile option for `runsc debug`.
If I have time, I'd like to tackle with the issue to enable profiling when sandbox starts.

ref: https://github.com/google/gvisor/pull/1951
