### ISSUE TITLE
go_stateify mishandles build tags

### ISSUE THREAD

**Issue by Maronee** [google/gvisor#222]
Hello I am looking at possibly porting gvisor for the the IBM s390x architecture. 
I have been running bazel build on most packages to see where it errors out and many packages need the cpuid package to be working. 
From what I understand the cpuid.go file contains definitions for the x86 feature sets and the feature set struct definition itself. Bazel then uses that file with a autogenerated cpuid file to compile it. My compile output looks like this:

```
root@2e7cb99bde06:~/gvisor# bazel build pkg/cpuid --verbose_failures
INFO: Analysed target //pkg/cpuid:cpuid (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /root/gvisor/pkg/cpuid/BUILD:5:1: GoCompile pkg/cpuid/linux_s390x_stripped/cpuid%/gvisor.googlesource.com/gvisor/pkg/cpuid.a~partial.a failed (Exit 1) builder failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/48ac5191077528b915da9f8563e070af/sandbox/processwrapper-sandbox/1/execroot/__main__ && \
  exec env - \
    CGO_ENABLED=1 \
    GOARCH=s390x \
    GOOS=linux \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=/usr/bin:/bin \
  bazel-out/host/bin/external/go_sdk/builder compile -sdk external/go_sdk -installsuffix linux_s390x -src pkg/cpuid/cpuid.go -src bazel-out/s390x-fastbuild/bin/pkg/cpuid/cpuid_state_autogen.go -src pkg/cpuid/cpu_amd64.s -arc 'gvisor.googlesource.com/gvisor/pkg/log=gvisor.googlesource.com/gvisor/pkg/log=bazel-out/s390x-fastbuild/bin/pkg/log/linux_s390x_stripped/log%/gvisor.googlesource.com/gvisor/pkg/log.a=' -arc 'gvisor.googlesource.com/gvisor/pkg/state=gvisor.googlesource.com/gvisor/pkg/state=bazel-out/s390x-fastbuild/bin/pkg/state/linux_s390x_stripped/state%/gvisor.googlesource.com/gvisor/pkg/state.a=' -o 'bazel-out/s390x-fastbuild/bin/pkg/cpuid/linux_s390x_stripped/cpuid%/gvisor.googlesource.com/gvisor/pkg/cpuid.a~partial.a' -package_list bazel-out/host/bin/external/go_sdk/packages.txt -asmhdr bazel-out/s390x-fastbuild/bin/pkg/cpuid/linux_s390x_stripped/cpuid%/go_asm.h -p gvisor.googlesource.com/gvisor/pkg/cpuid -- -trimpath .)
Execution platform: @bazel_tools//platforms:host_platform

Use --sandbox_debug to see verbose messages from the sandbox: builder failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/48ac5191077528b915da9f8563e070af/sandbox/processwrapper-sandbox/1/execroot/__main__ && \
  exec env - \
    CGO_ENABLED=1 \
    GOARCH=s390x \
    GOOS=linux \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=/usr/bin:/bin \
  bazel-out/host/bin/external/go_sdk/builder compile -sdk external/go_sdk -installsuffix linux_s390x -src pkg/cpuid/cpuid.go -src bazel-out/s390x-fastbuild/bin/pkg/cpuid/cpuid_state_autogen.go -src pkg/cpuid/cpu_amd64.s -arc 'gvisor.googlesource.com/gvisor/pkg/log=gvisor.googlesource.com/gvisor/pkg/log=bazel-out/s390x-fastbuild/bin/pkg/log/linux_s390x_stripped/log%/gvisor.googlesource.com/gvisor/pkg/log.a=' -arc 'gvisor.googlesource.com/gvisor/pkg/state=gvisor.googlesource.com/gvisor/pkg/state=bazel-out/s390x-fastbuild/bin/pkg/state/linux_s390x_stripped/state%/gvisor.googlesource.com/gvisor/pkg/state.a=' -o 'bazel-out/s390x-fastbuild/bin/pkg/cpuid/linux_s390x_stripped/cpuid%/gvisor.googlesource.com/gvisor/pkg/cpuid.a~partial.a' -package_list bazel-out/host/bin/external/go_sdk/packages.txt -asmhdr bazel-out/s390x-fastbuild/bin/pkg/cpuid/linux_s390x_stripped/cpuid%/go_asm.h -p gvisor.googlesource.com/gvisor/pkg/cpuid -- -trimpath .)
Execution platform: @bazel_tools//platforms:host_platform

Use --sandbox_debug to see verbose messages from the sandbox
compile: error running compiler: exit status 2
/root/.cache/bazel/_bazel_root/48ac5191077528b915da9f8563e070af/sandbox/processwrapper-sandbox/1/execroot/__main__/bazel-out/s390x-fastbuild/bin/pkg/cpuid/cpuid_state_autogen.go:9:10: undefined: FeatureSet
/root/.cache/bazel/_bazel_root/48ac5191077528b915da9f8563e070af/sandbox/processwrapper-sandbox/1/execroot/__main__/bazel-out/s390x-fastbuild/bin/pkg/cpuid/cpuid_state_autogen.go:10:10: undefined: FeatureSet
/root/.cache/bazel/_bazel_root/48ac5191077528b915da9f8563e070af/sandbox/processwrapper-sandbox/1/execroot/__main__/bazel-out/s390x-fastbuild/bin/pkg/cpuid/cpuid_state_autogen.go:22:10: undefined: FeatureSet
/root/.cache/bazel/_bazel_root/48ac5191077528b915da9f8563e070af/sandbox/processwrapper-sandbox/1/execroot/__main__/bazel-out/s390x-fastbuild/bin/pkg/cpuid/cpuid_state_autogen.go:23:10: undefined: FeatureSet
/root/.cache/bazel/_bazel_root/48ac5191077528b915da9f8563e070af/sandbox/processwrapper-sandbox/1/execroot/__main__/bazel-out/s390x-fastbuild/bin/pkg/cpuid/cpuid_state_autogen.go:35:39: undefined: FeatureSet
Target //pkg/cpuid:cpuid failed to build
INFO: Elapsed time: 0.425s, Critical Path: 0.05s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

From this outpud I can figure out it uses these sources: 
-src pkg/cpuid/cpuid.go 
-src bazel-out/s390x-fastbuild/bin/pkg/cpuid/cpuid_state_autogen.go 
-src pkg/cpuid/cpu_amd64.s

I understand the last part is wrong for my hardware platfrom, but the featureSet struct is defined in cpuid.go, can anyone tell me why I am getting the 

> undefined: FeatureSet

 error for the autegenerated code?

I am ruinning this with on:
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"

inside a docker container with

bazel version
Starting local Bazel server and connecting to it...
Build label: 0.24.1- (@non-git)

and

go version
go version go1.12.4 linux/s390x

**Comment by prattmic** [comment]
It looks like this is a deficiency in [go_stateify](https://github.com/google/gvisor/tree/master/tools/go_stateify).

The `go_library` in the CPUID package is https://github.com/google/gvisor/blob/master/pkg/cpuid/BUILD#L3: https://github.com/google/gvisor/blob/master/tools/go_stateify/defs.bzl#L83-L107

Notably, it passes *all* source files to the code generation tool. The tool generates code for save/restore of FeatureSet, adding methods to `cpuid_state_autogen.go`.

But FeatureSet is defined in `cpuid.go`, which has an x86 build tag. `cpuid_state_autogen.go` has no build tag. So on s390, the former is ignored and the latter isn't, causing the build error.

We need to do one of the following:
  * Make go_stateify properly respect build tags (and filename suffixes), generating code only for source files relevant to the build.
  * Or make it create multiple output files, each with the same build tags as the original source, so the later build tool can ignore them.

**Comment by Maronee** [comment]
Thank you for the reply. 
Would you happen to have a quick workaround for it, even if it only works for the targeted 390x environment? I want to further explore the dependencies for the rest of the code.

**Comment by prattmic** [comment]
If you remove "+stateify savable" from FeatureSet (https://github.com/google/gvisor/blob/master/pkg/cpuid/cpuid.go#L499), then the code generation won't create anything. Save/restore won't work, but you're not there yet.
