### ISSUE TITLE
Optimize TCP loopback

### ISSUE THREAD

**Issue by iangudger** [google/gvisor#223]
We currently do full TCP over the loopback. We could significantly improve performance if we directly connected the endpoints and exchanged buffers.

**Comment by Mikezhangzw** [comment]
do you have any progress in optimization of tcp loopback?

**Comment by hbhasker** [comment]
This is not the right way to optimize loopback as this will break too many tools where loopback traffic will be invisible to say tcpdump etc. We do not intend to do this. There are other optimizations to improve stack performance in general which are in progress. Going to close this.
