### ISSUE TITLE
kvm platform does not start

### ISSUE THREAD

**Issue by targetnull** [google/gvisor#228]
First, the ptrace platform runs well so it must have something to do with the kvm platform.

My `daemon.json` is as follows
```
{
    "runtimes": {
        "runsc": {
            "path": "/usr/local/bin/runsc",
            "runtimeArgs": [
                "--network=host",
                "--strace",
                "--debug-log=/tmp/runsc",
                "--debug",
                "--platform=kvm"
            ]
        }
    }
}
```

Then I run the command `sudo docker run --runtime=runsc hello-world` and I get
> docker: Error response from daemon: OCI runtime create failed: /var/lib/docker/runtimes/runsc did not terminate sucessfully: unknown.
ERRO[0000] error waiting for container: context canceled 

Thie log is as follows
```
I0511 15:18:17.580699       1 x:0] Platform: kvm
I0511 15:18:17.580864       1 x:0] region: virtual [bdc00000,407e800000)
I0511 15:18:17.580887       1 x:0] region: virtual [407e800000,c000000000)
I0511 15:18:17.580896       1 x:0] region: virtual [f0a0a1f000,1efa3a1f000)
I0511 15:18:17.580904       1 x:0] region: virtual [1efa3a1f000,3eda9a1f000)
I0511 15:18:17.580912       1 x:0] region: virtual [3eda9a1f000,7e9b5a1f000)
I0511 15:18:17.580919       1 x:0] region: virtual [7e9b5a1f000,fe1cda1f000)
I0511 15:18:17.580930       1 x:0] region: virtual [fe1cda1f000,1fd1fda1f000)
I0511 15:18:17.580940       1 x:0] region: virtual [1fd1fda1f000,3fb25da1f000)
I0511 15:18:17.580948       1 x:0] region: virtual [3fb25da1f000,7f731da1f000)
I0511 15:18:17.580955       1 x:0] region: virtual [7f731fcd1000,7ff2a14d1000)
I0511 15:18:17.580964       1 x:0] physicalRegion: virtual [1000,bdc00000) => physical [100001000,1bdc00000)
I0511 15:18:17.580990       1 x:0] physicalRegion: virtual [c000000000,f0a0a1f000) => physical [200000000,32a0a1f000)
I0511 15:18:17.580997       1 x:0] physicalRegion: virtual [7f731da1f000,7f731fcd1000) => physical [331da1f000,331fcd1000)
I0511 15:18:17.581005       1 x:0] physicalRegion: virtual [7ff2a14d1000,7ffffffff000) => physical [33214d1000,407ffff000)
D0511 15:18:17.581279       1 x:0] The maximum number of vCPUs is 288.
fatal error: run failed

goroutine 1 [running, locked to thread]:
runtime.throw(0xcef9f0, 0xa)
        GOROOT/src/runtime/panic.go:617 +0x72 fp=0xc000009930 sp=0xc000009900 pc=0x42d342
gvisor.googlesource.com/gvisor/pkg/sentry/platform/kvm.bluepillHandler(0xc0000099c0)
        pkg/sentry/platform/kvm/bluepill_unsafe.go:118 +0x47d fp=0xc0000099b0 sp=0xc000009930 pc=0xa0f47d
gvisor.googlesource.com/gvisor/pkg/sentry/platform/kvm.sighandler(0x7, 0x0, 0xc000002000, 0x0, 0x8000, 0x20, 0xc000038a70, 0x2, 0xc000038bd0, 0x0, ...)
        pkg/sentry/platform/kvm/bluepill_amd64.s:79 +0x24 fp=0xc0000099c0 sp=0xc0000099b0 pc=0xa16184
runtime: unexpected return pc for runtime.sigreturn called from 0x7
stack: frame={sp:0xc0000099c0, fp:0xc0000099c8} stack=[0xc0001f6000,0xc0001fe000)

runtime.sigreturn(0x0, 0xc000002000, 0x0, 0x8000, 0x20, 0xc000038a70, 0x2, 0xc000038bd0, 0x0, 0xff, ...)
        bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib%/src/runtime/sys_linux_amd64.s:449 fp=0xc0000099c8 sp=0xc0000099c0 pc=0x45cc70

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
        GOROOT/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        GOROOT/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        GOROOT/src/os/signal/signal_unix.go:29 +0x41
W0511 15:18:17.610617       1 x:0] FATAL ERROR: P9 server returned error. Gofer is shutting down. FD: 8, err: EOF
D0511 23:18:17.610638    7915 x:0] Destroy sandbox "553e2dd61ac2fa401837d49161dadfad65e4e8a2a6ace7324d40b267ce51394a"
P9 server returned error. Gofer is shutting down. FD: 8, err: EOF
D0511 23:18:17.610676    7915 x:0] Killing sandbox "553e2dd61ac2fa401837d49161dadfad65e4e8a2a6ace7324d40b267ce51394a"
W0511 23:18:17.610757    7915 x:0] error destroying sandbox: <nil>
D0511 23:18:17.610775    7915 x:0] Restoring cgroup "/sys/fs/cgroup/freezer"
D0511 23:18:17.610852    7915 x:0] Destroy container "553e2dd61ac2fa401837d49161dadfad65e4e8a2a6ace7324d40b267ce51394a"
D0511 23:18:17.610871    7915 x:0] Killing gofer for container "553e2dd61ac2fa401837d49161dadfad65e4e8a2a6ace7324d40b267ce51394a", PID: 7920
W0511 23:18:17.711652    7915 x:0] FATAL ERROR: creating container: waiting for sandbox to start: EOF
```

My cpu info is
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
stepping	: 10
microcode	: 0x9e
cpu MHz		: 700.022
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips	: 3984.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```

Does anybody knows what might be the problem? Thanks.

**Comment by caoshen000** [comment]
I have the same problem. What I should  do if I want to run gvisor with kvm platform.

Thanks

**Comment by amscanne** [comment]
The error is from the KVM_RUN ioctl failing. It's hard to know why without more information. Let me see if I can post some KVM debugging instructions that include how to dump the full VM state (that's really what's needed).

**Comment by targetnull** [comment]
Hi guys, is there any update so far? I am using ptrace as a workaround. I'd be happy to know debugging instructions.

**Comment by targetnull** [comment]
@ianlewis A nice ping for current status? Any progress so far :)

**Comment by chrisdlangton** [comment]
I have the same problem. Sticking with runsc alone for now.

I would really like to find a runsc-kvm solution to try and stop the malware from breaking out as often

But this is clearly too niche a requirement.. Working with containers these past 6 years I am still suprised to find the ecosystem is just too immature. It is crazy to me that running processes directly on the VM host is the only place where the security primitives are available and not "coming soon" for years like the case of managing syscalls via seccomp in kube.. we might see it in 1.18 late 2020, or it might get bump yet another 3 or more milestones.. who knows when GKE, EKS, Openshift will adopt after Kube releases that feature, if it is adopted at all..

Anyway I digress.

I would really like to see runsc-kvm - theoretically is possible but not yet properly supported or requires undocumented configurations? Hopefully not requiring more development..

**Comment by mahurabhi** [comment]
Is there an update on this issue ? Even I am facing the same error when trying to start a container with gVisor KVM based runtime. 
![Screenshot from 2020-06-24 18-59-32](https://user-images.githubusercontent.com/63021211/85754291-efc4cf80-b6da-11ea-81a8-54f77964dbde.png)

**Comment by amscanne** [comment]
Are these reports coming from the same kind of HW? I.e. what's the output of /proc/cpuinfo? Just want to know if it's something distinct.

**Comment by mahurabhi** [comment]
These are the platform details: 
![Screenshot from 2020-06-25 12-33-40](https://user-images.githubusercontent.com/63021211/85760843-3832bc00-b6e0-11ea-9d93-e142ee1d9cbd.png)

**Comment by amscanne** [comment]
Hm, nothing strange here ... would it be possible to include the debug outputs from the failure?

**Comment by mahurabhi** [comment]
This the log from the .create debug log file: 

D0625 11:13:15.238348    4081 specutils.go:58] Spec.Process: &{Terminal:false ConsoleSize:<nil> User:{UID:0 GID:0 AdditionalGids:[] Username:} Args:[/hello] Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr>
D0625 11:13:15.238363    4081 specutils.go:59] Spec.Root: &{Path:/var/lib/docker/overlay2/d5b748239952cf6372a4841ec2414c4d3d4c5366962e5a40af287081040ac0ba/merged Readonly:false}
D0625 11:13:15.238371    4081 specutils.go:60] Spec.Mounts: [{Destination:/proc Type:proc Source:/run/containerd/io.containerd.runtime.v1.linux/moby/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7e>
D0625 11:13:15.238393    4081 container.go:273] Create container "69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9" in root dir: /var/run/docker/runtime-runsc-debug/moby
D0625 11:13:15.238464    4081 container.go:312] Creating new sandbox for container "69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9"
D0625 11:13:15.238480    4081 cgroup.go:242] Creating cgroup "/docker/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9"
D0625 11:13:15.259314    4081 cgroup.go:334] Joining cgroup "/sys/fs/cgroup/net_prio/docker/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9"
D0625 11:13:15.259369    4081 cgroup.go:334] Joining cgroup "/sys/fs/cgroup/devices/docker/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9"
D0625 11:13:15.259395    4081 cgroup.go:334] Joining cgroup "/sys/fs/cgroup/systemd/docker/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9"
D0625 11:13:15.259418    4081 cgroup.go:334] Joining cgroup "/sys/fs/cgroup/blkio/docker/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9"
D0625 11:13:15.259441    4081 cgroup.go:334] Joining cgroup "/sys/fs/cgroup/cpu/docker/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9"
D0625 11:13:15.259479    4081 cgroup.go:334] Joining cgroup "/sys/fs/cgroup/memory/docker/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9"
D0625 11:13:15.259509    4081 cgroup.go:334] Joining cgroup "/sys/fs/cgroup/pids/docker/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9"
D0625 11:13:15.259539    4081 cgroup.go:334] Joining cgroup "/sys/fs/cgroup/freezer/docker/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9"
D0625 11:13:15.259565    4081 cgroup.go:334] Joining cgroup "/sys/fs/cgroup/perf_event/docker/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9"
D0625 11:13:15.259641    4081 cgroup.go:334] Joining cgroup "/sys/fs/cgroup/rdma/docker/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9"
D0625 11:13:15.259670    4081 cgroup.go:334] Joining cgroup "/sys/fs/cgroup/cpuset/docker/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9"
D0625 11:13:15.259699    4081 cgroup.go:334] Joining cgroup "/sys/fs/cgroup/hugetlb/docker/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9"
D0625 11:13:15.259727    4081 cgroup.go:334] Joining cgroup "/sys/fs/cgroup/net_cls/docker/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9"
D0625 11:13:15.259844    4081 container.go:980] Starting gofer: /proc/self/exe [--root=/var/run/docker/runtime-runsc-debug/moby --debug=true --log=/run/containerd/io.containerd.runtime.v1.linux/moby/69b>
I0625 11:13:15.260576    4081 container.go:984] Gofer started, PID: 4086
I0625 11:13:15.260708    4081 sandbox.go:414] Creating sandbox process with addr: runsc-sandbox.69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9
I0625 11:13:15.260748    4081 sandbox.go:540] Sandbox will be started in new mount, IPC and UTS namespaces
I0625 11:13:15.260762    4081 sandbox.go:552] Sandbox will be started in a new PID namespace
I0625 11:13:15.260783    4081 sandbox.go:561] Sandbox will be started in the container's network namespace: {Type:network Path:}
I0625 11:13:15.260879    4081 sandbox.go:604] Sandbox will be started in new user namespace
D0625 11:13:15.260986    4081 sandbox.go:720] Donating FD 3: "/run/containerd/io.containerd.runtime.v1.linux/moby/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9/log.json"
D0625 11:13:15.261007    4081 sandbox.go:720] Donating FD 4: "/tmp/runsc/runsc.log.20200625-111315.260648.boot"
D0625 11:13:15.261020    4081 sandbox.go:720] Donating FD 5: "control_server_socket"
D0625 11:13:15.261031    4081 sandbox.go:720] Donating FD 6: "|0"
D0625 11:13:15.261042    4081 sandbox.go:720] Donating FD 7: "/run/containerd/io.containerd.runtime.v1.linux/moby/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9/config.json"
D0625 11:13:15.261058    4081 sandbox.go:720] Donating FD 8: "|1"
D0625 11:13:15.261068    4081 sandbox.go:720] Donating FD 9: "sandbox IO FD"
D0625 11:13:15.261078    4081 sandbox.go:720] Donating FD 10: "sandbox IO FD"
D0625 11:13:15.261089    4081 sandbox.go:720] Donating FD 11: "sandbox IO FD"
D0625 11:13:15.261100    4081 sandbox.go:720] Donating FD 12: "sandbox IO FD"
D0625 11:13:15.261110    4081 sandbox.go:720] Donating FD 13: "/dev/kvm"
D0625 11:13:15.261126    4081 sandbox.go:720] Donating FD 14: "/dev/stdin"
D0625 11:13:15.261136    4081 sandbox.go:720] Donating FD 15: "/dev/stdout"
D0625 11:13:15.261147    4081 sandbox.go:720] Donating FD 16: "/dev/stderr"
D0625 11:13:15.261158    4081 sandbox.go:723] Starting sandbox: /proc/self/exe [runsc-sandbox --root=/var/run/docker/runtime-runsc-debug/moby --debug=true --log=/run/containerd/io.containerd.runtime.v1.>
D0625 11:13:15.261188    4081 sandbox.go:724] SysProcAttr: &{Chroot: Credential:0xc000276e10 Ptrace:false Setsid:true Setpgid:false Setctty:false Noctty:false Ctty:0 Foreground:false Pgid:0 Pdeathsig:si>
I0625 11:13:15.265314    4081 sandbox.go:742] Sandbox started, PID: 4095
D0625 11:13:15.351899    4081 sandbox.go:812] Destroy sandbox "69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9"
D0625 11:13:15.351952    4081 sandbox.go:814] Killing sandbox "69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9"
W0625 11:13:15.352058    4081 sandbox.go:125] error destroying sandbox: <nil>
D0625 11:13:15.352090    4081 cgroup.go:324] Restoring cgroup "/sys/fs/cgroup/memory/system.slice/containerd.service"
D0625 11:13:15.352249    4081 container.go:710] Destroy container "69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9"
D0625 11:13:15.352306    4081 container.go:811] Killing gofer for container "69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b3988fd9", PID: 4086
W0625 11:13:15.452940    4081 error.go:48] FATAL ERROR: creating container: waiting for sandbox to start: EOF
W0625 11:13:15.453257    4081 main.go:345] Failure to execute command, err: 1

**Comment by mahurabhi** [comment]
and this is from the .boot log file 
`W0625 15:13:15.278347       1 specutils.go:92] AppArmor profile "docker-default" is being ignored
W0625 15:13:15.278361       1 specutils.go:98] noNewPrivileges ignored. PR_SET_NO_NEW_PRIVS is assumed to always be set.
W0625 15:13:15.278367       1 specutils.go:103] Seccomp spec is being ignored
D0625 15:13:15.278378       1 specutils.go:48] Spec: &{Version:1.0.1-dev Process:0xc00024a750 Root:0xc0002374c0 Hostname:69b7b765b619 Mounts:[{Destination:/proc Type:proc Source:/run/containerd/io.conta>
D0625 15:13:15.278414       1 specutils.go:49] Spec.Hooks: &{Prestart:[{Path:/proc/1696/exe Args:[libnetwork-setkey -exec-root=/var/run/docker 69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef83b39>
D0625 15:13:15.278424       1 specutils.go:50] Spec.Linux: &{UIDMappings:[] GIDMappings:[] Sysctl:map[] Resources:0xc00011a660 CgroupsPath:/docker/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7ef8>
D0625 15:13:15.278459       1 specutils.go:53] Spec.Linux.Resources.Memory: &{Limit:<nil> Reservation:<nil> Swap:<nil> Kernel:<nil> KernelTCP:<nil> Swappiness:<nil> DisableOOMKiller:0xc0002399fe}
D0625 15:13:15.278467       1 specutils.go:54] Spec.Linux.Resources.CPU: &{Shares:0xc000239a00 Quota:<nil> Period:<nil> RealtimeRuntime:<nil> RealtimePeriod:<nil> Cpus: Mems:}
D0625 15:13:15.278473       1 specutils.go:55] Spec.Linux.Resources.BlockIO: &{Weight:0xc000239a08 LeafWeight:<nil> WeightDevice:[] ThrottleReadBpsDevice:[] ThrottleWriteBpsDevice:[] ThrottleReadIOPSDev>
D0625 15:13:15.278484       1 specutils.go:56] Spec.Linux.Resources.Network: <nil>
D0625 15:13:15.278488       1 specutils.go:58] Spec.Process: &{Terminal:false ConsoleSize:<nil> User:{UID:0 GID:0 AdditionalGids:[] Username:} Args:[/hello] Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr>
D0625 15:13:15.278501       1 specutils.go:59] Spec.Root: &{Path:/var/lib/docker/overlay2/d5b748239952cf6372a4841ec2414c4d3d4c5366962e5a40af287081040ac0ba/merged Readonly:false}
D0625 15:13:15.278506       1 specutils.go:60] Spec.Mounts: [{Destination:/proc Type:proc Source:/run/containerd/io.containerd.runtime.v1.linux/moby/69b7b765b61965598feb850bed149844ae8bd8ab3f50bb280cf7e>
I0625 15:13:15.278617       1 loader.go:459] Platform: kvm
I0625 15:13:15.278679       1 physical_map.go:124] region: virtual [bdc00000,407e800000)
I0625 15:13:15.278689       1 physical_map.go:124] region: virtual [407e800000,c000000000)
I0625 15:13:15.278693       1 physical_map.go:124] region: virtual [c780766000,10741366000)
I0625 15:13:15.278696       1 physical_map.go:124] region: virtual [10741366000,20644366000)
I0625 15:13:15.278700       1 physical_map.go:124] region: virtual [20644366000,4044a366000)
I0625 15:13:15.278703       1 physical_map.go:124] region: virtual [4044a366000,80056366000)
I0625 15:13:15.278707       1 physical_map.go:124] region: virtual [80056366000,ff86e366000)
I0625 15:13:15.278710       1 physical_map.go:124] region: virtual [ff86e366000,1fe89e366000)
I0625 15:13:15.278714       1 physical_map.go:124] region: virtual [1fe89e366000,3fc8fe366000)
I0625 15:13:15.278718       1 physical_map.go:124] region: virtual [3fc8fe366000,7f89be366000)
I0625 15:13:15.278723       1 physical_map.go:124] region: virtual [7f89e5038000,7fc9a5c38000)
I0625 15:13:15.278728       1 physical_map.go:173] physicalRegion: virtual [1000,bdc00000) => physical [100001000,1bdc00000)
I0625 15:13:15.278732       1 physical_map.go:173] physicalRegion: virtual [c000000000,c780766000) => physical [200000000,980766000)
I0625 15:13:15.278739       1 physical_map.go:173] physicalRegion: virtual [7f89be366000,7f89e5038000) => physical [9be366000,9e5038000)
I0625 15:13:15.278742       1 physical_map.go:173] physicalRegion: virtual [7fc9a5c38000,7ffffffff000) => physical [a25c38000,407ffff000)
D0625 15:13:15.279095       1 machine.go:193] The maximum number of vCPUs is 288.
fatal error: run failed
`

**Comment by Junjie-Wen** [comment]
Has the problem been resolved? I also encountered the same problem after using -- platform=kvm
![image](https://github.com/google/gvisor/assets/57980153/8bc30c92-de39-4c50-8274-a0db4fbcb794)
