### ISSUE TITLE
Python's packages (installed with --user) are not visible in sandbox when using runsc

### ISSUE THREAD

**Issue by ustiugov** [google/gvisor#2295]
Dear gVisor team,

Python interpreter does not see the packages that were installed with `pip install --user` when invoked with `runsc`. Interestingly, when invoked with `docker --runtime=runsc`, python's `import grpc` works properly. Steps to reproduce are described in the bottom.

*   `runsc --version`:  runsc version release-20200219.0-261-g32a133537e61 
spec: 1.0.1-dev

*   `docker version` or `docker info` if more relevant:
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

*   Linux iccluster077 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - release-20200219.0-261-g32a13353
*   Detailed reproduction steps

```
mkdir rootfs
docker export $(docker create ustiugov/helloworld:runner_workload) | tar -xf - -C rootfs
sudo runsc spec
sudo sed -i 's;"sh";"python", "/server.py";' config.json
sudo runsc run python_server
Traceback (most recent call last):
  File "/server.py", line 19, in <module>
    import grpc
ModuleNotFoundError: No module named 'grpc'
```
The packages are located in `rootfs/root/.local/lib/python3.8/site-packages/`

An equivalent Docker command that works:
```
docker run --runtime=runsc ustiugov/helloworld:runner_workload
```

**Comment by amscanne** [comment]
@fvoznika Is this possibly the caching issue?

**Comment by fvoznika** [comment]
It's possible. Prior to 4.19, overlayfs doesn't update open FDs after a file is changed. Please set `--overlayfs-stale-read` to [runsc configuration](https://gvisor.dev/docs/user_guide/debugging/) and check if the problem goes away.
