### ISSUE TITLE
Failed to build in docker container centos:7

### ISSUE THREAD

**Issue by llitfkitfk** [google/gvisor#23]
```
[root@c3f456871892 gvisor]# bazel build runsc
Analyzing: target //runsc:runsc (7 packages loaded)
INFO: Analysed target //runsc:runsc (171 packages loaded).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/8efa14feb181cf4b8ae1b0ddb1bac0e9/external/com_google_protobuf/BUILD:64:1: C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed (Exit 1)
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
Target //runsc:runsc failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 79.678s, Critical Path: 0.09s
INFO: 7 processes: 6 local, 1 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by llitfkitfk** [comment]
[root@c3f456871892 gvisor]# bazel build runsc
INFO: Analysed target //runsc:runsc (0 packages loaded).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/8efa14feb181cf4b8ae1b0ddb1bac0e9/external/com_google_protobuf/BUILD:64:1: undeclared inclusion(s) in rule '@com_google_protobuf//:protobuf_lite':
this rule is missing dependency declarations for the following files included by 'external/com_google_protobuf/src/google/protobuf/stubs/atomicops_internals_x86_msvc.cc':
  '/usr/include/stdc-predef.h'
  '/usr/include/c++/4.8.5/algorithm'
  '/usr/include/c++/4.8.5/utility'
  '/usr/include/c++/4.8.5/x86_64-redhat-linux/bits/c++config.h'
  '/usr/include/bits/wordsize.h'
  '/usr/include/c++/4.8.5/x86_64-redhat-linux/bits/os_defines.h'
  '/usr/include/features.h'
  '/usr/include/sys/cdefs.h'
  '/usr/include/gnu/stubs.h'
  '/usr/include/gnu/stubs-64.h'
  '/usr/include/c++/4.8.5/x86_64-redhat-linux/bits/cpu_defines.h'
  '/usr/include/c++/4.8.5/bits/stl_relops.h'
  '/usr/include/c++/4.8.5/bits/stl_pair.h'
  '/usr/include/c++/4.8.5/bits/move.h'
  '/usr/include/c++/4.8.5/bits/concept_check.h'
  '/usr/include/c++/4.8.5/type_traits'
  '/usr/include/c++/4.8.5/initializer_list'
  '/usr/include/c++/4.8.5/bits/stl_algobase.h'
  '/usr/include/c++/4.8.5/bits/functexcept.h'
  '/usr/include/c++/4.8.5/bits/exception_defines.h'
  '/usr/include/c++/4.8.5/bits/cpp_type_traits.h'
  '/usr/include/c++/4.8.5/ext/type_traits.h'
  '/usr/include/c++/4.8.5/ext/numeric_traits.h'
  '/usr/include/c++/4.8.5/bits/stl_iterator_base_types.h'
  '/usr/include/c++/4.8.5/bits/stl_iterator_base_funcs.h'
  '/usr/include/c++/4.8.5/debug/debug.h'
  '/usr/include/c++/4.8.5/bits/stl_iterator.h'
  '/usr/include/c++/4.8.5/bits/stl_algo.h'
  '/usr/include/c++/4.8.5/cstdlib'
  '/usr/include/stdlib.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h'
  '/usr/include/bits/waitflags.h'
  '/usr/include/bits/waitstatus.h'
  '/usr/include/endian.h'
  '/usr/include/bits/endian.h'
  '/usr/include/bits/byteswap.h'
  '/usr/include/bits/types.h'
  '/usr/include/bits/typesizes.h'
  '/usr/include/bits/byteswap-16.h'
  '/usr/include/xlocale.h'
  '/usr/include/sys/types.h'
  '/usr/include/time.h'
  '/usr/include/sys/select.h'
  '/usr/include/bits/select.h'
  '/usr/include/bits/sigset.h'
  '/usr/include/bits/time.h'
  '/usr/include/bits/select2.h'
  '/usr/include/sys/sysmacros.h'
  '/usr/include/bits/pthreadtypes.h'
  '/usr/include/alloca.h'
  '/usr/include/bits/stdlib-float.h'
  '/usr/include/bits/stdlib.h'
  '/usr/include/c++/4.8.5/bits/algorithmfwd.h'
  '/usr/include/c++/4.8.5/bits/stl_heap.h'
  '/usr/include/c++/4.8.5/bits/stl_tempbuf.h'
  '/usr/include/c++/4.8.5/bits/stl_construct.h'
  '/usr/include/c++/4.8.5/new'
  '/usr/include/c++/4.8.5/exception'
  '/usr/include/c++/4.8.5/bits/atomic_lockfree_defines.h'
  '/usr/include/c++/4.8.5/bits/exception_ptr.h'
  '/usr/include/c++/4.8.5/bits/nested_exception.h'
  '/usr/include/c++/4.8.5/ext/alloc_traits.h'
  '/usr/include/c++/4.8.5/bits/alloc_traits.h'
  '/usr/include/c++/4.8.5/bits/memoryfwd.h'
  '/usr/include/c++/4.8.5/bits/ptr_traits.h'
  '/usr/include/c++/4.8.5/random'
  '/usr/include/c++/4.8.5/cmath'
  '/usr/include/math.h'
  '/usr/include/bits/huge_val.h'
  '/usr/include/bits/huge_valf.h'
  '/usr/include/bits/huge_vall.h'
  '/usr/include/bits/inf.h'
  '/usr/include/bits/nan.h'
  '/usr/include/bits/mathdef.h'
  '/usr/include/bits/mathcalls.h'
  '/usr/include/bits/mathinline.h'
  '/usr/include/c++/4.8.5/cstdio'
  '/usr/include/stdio.h'
  '/usr/include/libio.h'
  '/usr/include/_G_config.h'
  '/usr/include/wchar.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h'
  '/usr/include/bits/stdio_lim.h'
  '/usr/include/bits/sys_errlist.h'
  '/usr/include/bits/stdio.h'
  '/usr/include/bits/stdio2.h'
  '/usr/include/c++/4.8.5/string'
  '/usr/include/c++/4.8.5/bits/stringfwd.h'
  '/usr/include/c++/4.8.5/bits/char_traits.h'
  '/usr/include/c++/4.8.5/bits/postypes.h'
  '/usr/include/c++/4.8.5/cwchar'
  '/usr/include/bits/wchar.h'
  '/usr/include/bits/wchar2.h'
  '/usr/include/c++/4.8.5/cstdint'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdint.h'
  '/usr/include/stdint.h'
  '/usr/include/c++/4.8.5/bits/allocator.h'
  '/usr/include/c++/4.8.5/x86_64-redhat-linux/bits/c++allocator.h'
  '/usr/include/c++/4.8.5/ext/new_allocator.h'
  '/usr/include/c++/4.8.5/bits/localefwd.h'
  '/usr/include/c++/4.8.5/x86_64-redhat-linux/bits/c++locale.h'
  '/usr/include/c++/4.8.5/clocale'
  '/usr/include/locale.h'
  '/usr/include/bits/locale.h'
  '/usr/include/c++/4.8.5/iosfwd'
  '/usr/include/c++/4.8.5/cctype'
  '/usr/include/ctype.h'
  '/usr/include/c++/4.8.5/bits/ostream_insert.h'
  '/usr/include/c++/4.8.5/bits/cxxabi_forced.h'
  '/usr/include/c++/4.8.5/bits/stl_function.h'
  '/usr/include/c++/4.8.5/backward/binders.h'
  '/usr/include/c++/4.8.5/bits/range_access.h'
  '/usr/include/c++/4.8.5/bits/basic_string.h'
  '/usr/include/c++/4.8.5/ext/atomicity.h'
  '/usr/include/c++/4.8.5/x86_64-redhat-linux/bits/gthr.h'
  '/usr/include/c++/4.8.5/x86_64-redhat-linux/bits/gthr-default.h'
  '/usr/include/pthread.h'
  '/usr/include/sched.h'
  '/usr/include/bits/sched.h'
  '/usr/include/bits/timex.h'
  '/usr/include/bits/setjmp.h'
  '/usr/include/c++/4.8.5/x86_64-redhat-linux/bits/atomic_word.h'
  '/usr/include/c++/4.8.5/ext/string_conversions.h'
  '/usr/include/c++/4.8.5/cerrno'
  '/usr/include/errno.h'
  '/usr/include/bits/errno.h'
  '/usr/include/linux/errno.h'
  '/usr/include/asm/errno.h'
  '/usr/include/asm-generic/errno.h'
  '/usr/include/asm-generic/errno-base.h'
  '/usr/include/c++/4.8.5/bits/functional_hash.h'
  '/usr/include/c++/4.8.5/bits/hash_bytes.h'
  '/usr/include/c++/4.8.5/bits/basic_string.tcc'
  '/usr/include/c++/4.8.5/limits'
  '/usr/include/c++/4.8.5/bits/random.h'
  '/usr/include/c++/4.8.5/vector'
  '/usr/include/c++/4.8.5/bits/stl_uninitialized.h'
  '/usr/include/c++/4.8.5/bits/stl_vector.h'
  '/usr/include/c++/4.8.5/bits/stl_bvector.h'
  '/usr/include/c++/4.8.5/bits/vector.tcc'
  '/usr/include/c++/4.8.5/x86_64-redhat-linux/bits/opt_random.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/x86intrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/ia32intrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/mmintrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/xmmintrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/mm_malloc.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/emmintrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/immintrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/fxsrintrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/adxintrin.h'
  '/usr/include/c++/4.8.5/bits/random.tcc'
  '/usr/include/c++/4.8.5/numeric'
  '/usr/include/c++/4.8.5/bits/stl_numeric.h'
  '/usr/include/c++/4.8.5/functional'
  '/usr/include/c++/4.8.5/typeinfo'
  '/usr/include/c++/4.8.5/tuple'
  '/usr/include/c++/4.8.5/array'
  '/usr/include/c++/4.8.5/stdexcept'
  '/usr/include/c++/4.8.5/bits/uses_allocator.h'
  '/usr/include/c++/4.8.5/iostream'
  '/usr/include/c++/4.8.5/ostream'
  '/usr/include/c++/4.8.5/ios'
  '/usr/include/c++/4.8.5/bits/ios_base.h'
  '/usr/include/c++/4.8.5/bits/locale_classes.h'
  '/usr/include/c++/4.8.5/bits/locale_classes.tcc'
  '/usr/include/c++/4.8.5/streambuf'
  '/usr/include/c++/4.8.5/bits/streambuf.tcc'
  '/usr/include/c++/4.8.5/bits/basic_ios.h'
  '/usr/include/c++/4.8.5/bits/locale_facets.h'
  '/usr/include/c++/4.8.5/cwctype'
  '/usr/include/wctype.h'
  '/usr/include/c++/4.8.5/x86_64-redhat-linux/bits/ctype_base.h'
  '/usr/include/c++/4.8.5/bits/streambuf_iterator.h'
  '/usr/include/c++/4.8.5/x86_64-redhat-linux/bits/ctype_inline.h'
  '/usr/include/c++/4.8.5/bits/locale_facets.tcc'
  '/usr/include/c++/4.8.5/bits/basic_ios.tcc'
  '/usr/include/c++/4.8.5/bits/ostream.tcc'
  '/usr/include/c++/4.8.5/istream'
  '/usr/include/c++/4.8.5/bits/istream.tcc'
  '/usr/include/c++/4.8.5/map'
  '/usr/include/c++/4.8.5/bits/stl_tree.h'
  '/usr/include/c++/4.8.5/bits/stl_map.h'
  '/usr/include/c++/4.8.5/bits/stl_multimap.h'
  '/usr/include/c++/4.8.5/set'
  '/usr/include/c++/4.8.5/bits/stl_set.h'
  '/usr/include/c++/4.8.5/bits/stl_multiset.h'
  '/usr/include/assert.h'
  '/usr/include/c++/4.8.5/cstddef'
  '/usr/include/string.h'
  '/usr/include/bits/string3.h'
  '/usr/include/sys/param.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/limits.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/syslimits.h'
  '/usr/include/limits.h'
  '/usr/include/bits/posix1_lim.h'
  '/usr/include/bits/local_lim.h'
  '/usr/include/linux/limits.h'
  '/usr/include/bits/posix2_lim.h'
  '/usr/include/bits/xopen_lim.h'
  '/usr/include/signal.h'
  '/usr/include/bits/signum.h'
  '/usr/include/bits/siginfo.h'
  '/usr/include/bits/sigaction.h'
  '/usr/include/bits/sigcontext.h'
  '/usr/include/bits/sigstack.h'
  '/usr/include/sys/ucontext.h'
  '/usr/include/bits/sigthread.h'
  '/usr/include/bits/param.h'
  '/usr/include/linux/param.h'
  '/usr/include/asm/param.h'
  '/usr/include/asm-generic/param.h'
  '/usr/include/byteswap.h'
Target //runsc:runsc failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.599s, Critical Path: 0.31s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by loveharmful** [comment]
I had the same issue, running `env CC=/usr/bin/gcc bazel build runsc` allowed the build to complete. (via https://github.com/tensorflow/tensorflow/issues/14380#issuecomment-362787829)

**Comment by dreampuf** [comment]
I wrote some instructions for the build.
https://gist.github.com/dreampuf/6446936e84dc5c965ec947fb4080b032

**Comment by llitfkitfk** [comment]
Success to build

@dreampuf Thanks👍
