### ISSUE TITLE
sentry memory leak 

### ISSUE THREAD

**Issue by zhangningdlut** [google/gvisor#232]
We have  encountered a problem.
We start a container with runsc, and run some program, like this
```
i=10000
while [ $i -gt 0 ]  
do  
    ps aux  
    let i=$i-1 
done  
```
or some more  complicated programs.
Then the RssAnon of runsc-sandbox ( In /proc/${pid}/status) will increase and when the program is stopped, the RssAnon will not decrease.
Even the freeosmemory does't  work.
The heapidle is very large.

Haven't  you encountered this problem?

**Comment by nlacasse** [comment]
Thank you for reporting.  I will investigate.

**Comment by nixprime** [comment]
Can you try passing the environment variable `GODEBUG=madvdontneed=1` to runsc? (If you're using docker, I believe you can do this by changing `"path": ".../runsc"` to `"path": "GODEBUG=madvdontneed=1 .../runsc"` in `/etc/docker/daemon.json`. Go 1.12 uses `MADV_FREE` in preference to `MADV_DONTNEED` to release memory to the host Linux kernel when available; the former is faster, but means that the host kernel only reclaims that memory (and consequently drives RSS and similar metrics down) when necessary.

**Comment by nlacasse** [comment]
Unfortunately passing the GODEBUG flag through Docker like @nixprime suggested does not work.

However, I think we can use the new `runsc do` command to run this.  I added the TESTONLY flag to prevent `runsc` from fork/execing itself and dropping the env vars.

unshare -Ur /path/to/runsc --network=none --overlay --TESTONLY-unsafe-nonroot do ./repro.sh

I'm running this now with and without the GODEBUG flag and will post the outcome.

**Comment by tanjianfeng** [comment]
Just for record, we can add env variable at callSelfAsNobody().

**Comment by nlacasse** [comment]
I ran both sandboxes for a while, and they seemed to stabilize (or at least start growing very slowly) at RssAnon: ~600mb.

**Comment by zhangningdlut** [comment]
I tried "GODEBUG=madvdontneed=1", it seems that the freeosmemory can work.

And I add  memory.soft_limit_in_bytes in the cgroup, the RssAnon can be decreased slowly, but
the overall trend is growing.

**Comment by zhangningdlut** [comment]
I found an another situation.
When I stop the test case in container, and use freeosmemory to free memory, then the  "heapidle" and RssAnon of runsc will dicrease.
And after few seconds, the RssAnon and heapidle will be increased to before soon.


> Can you try passing the environment variable `GODEBUG=madvdontneed=1` to runsc? (If you're using docker, I believe you can do this by changing `"path": ".../runsc"` to `"path": "GODEBUG=madvdontneed=1 .../runsc"` in `/etc/docker/daemon.json`. Go 1.12 uses `MADV_FREE` in preference to `MADV_DONTNEED` to release memory to the host Linux kernel when available; the former is faster, but means that the host kernel only reclaims that memory (and consequently drives RSS and similar metrics down) when necessary.
