### ISSUE TITLE
Can not run gVisor with kvm platform AMD(EPYC) 

### ISSUE THREAD

**Issue by caoshen000** [google/gvisor#233]
Hi.
I can not run gvisor with kvm platform AMD(EPYC) and this is the  detail #226 

I try to debug with this issue and I find these code could cause gVisor crash
in /pkg/sentry/platform/kvm/machine_amd64.go
```
62     m.retryInGuest(func(){
63          ring0.SetCPUIDFaulting(true)
64     })
```
I found it read/write some MSR like _MSR_PLATFORM_INFO or MSR_MISC_FEATURES
in /pkg/sentry/platform/ring0/kernel_amd64.go

```
func SetCPUIDFaulting(on bool) bool {
   if remsr(_MSR_PLATFORM_INFO)&_PLATFORM_INFO_CPUID_FAULT !=0
   {
    deatures := rdmsr(_MSR_MISC_FEATURES)
    ...
    }
}
```
I can not find  MSR_PLATFORM_INFO in  AMD Register Reference(not sure)
I only could find this MSR in Intel platform

Any comment?
thanks

**Comment by amscanne** [comment]
This may make sense. I think we need to check the CPU vendor before reading the MSR.

**Comment by ayushr2** [comment]
cc @avagin

**Comment by avagin** [comment]
There were a number of fixes in the KVM platform. Feel free to reopen it if the issue is reproduced.
