### ISSUE TITLE
OCI spec: mount type is optional for bind mounts

### ISSUE THREAD

**Issue by fvoznika** [google/gvisor#2330]
the [rule for type field](https://github.com/opencontainers/runtime-spec/blob/master/config.md#mounts) in mount is strange. If option is bind, then type is optional. In runsc today [type is required](https://github.com/google/gvisor/blob/ecc3d01d181a6ae6d3cc72531542d9ea5fe3e376/runsc/boot/fs.go#L783).

> type (string, OPTIONAL) The type of the filesystem to be mounted.
> Linux: filesystem types supported by the kernel as listed in /proc/filesystems (e.g., "minix", "ext2", "ext3", "jfs", "xfs", "reiserfs", "msdos", "proc", "nfs", "iso9660"). For bind mounts (when options include either bind or rbind), the type is a dummy, often "none" (not listed in /proc/filesystems).
>

**Comment by ianlewis** [comment]
Does this cause problems when using bind mounts with Docker? or is this issue just for spec completeness?

**Comment by fvoznika** [comment]
Just completeness. Someone bumped into this crafting OCI spec by hand.

**Comment by fvoznika** [comment]
The fix had to be rolled back because it broken the handling for EmptyDir in Kubernetes. It preserves `bind` and `rbind` options when the mount is redirected to `tmpfs`. The fix made `tmpfs` be "wrongly" ignored in this case.

**Comment by moricho** [comment]
@fvoznika 

> It preserves bind and rbind options when the mount is redirected to tmpfs. The fix made tmpfs be "wrongly" ignored in this case.

Does that means `bind` and `rbind` options should be ignored when mount type is equal to `tmpfs`? (not to be redirected to `bind` type)

**Comment by fvoznika** [comment]
It's better to fix emptydir handling in gvisor-containerd-shim to remove `[r]bind` option when converting the mounting to internal tmpfs. This way we don't need to special case `tmpfs` here.

https://github.com/google/gvisor-containerd-shim/issues/61
