### ISSUE TITLE
Add support for mounting Unix sockets

### ISSUE THREAD

**Issue by jmillikin-stripe** [google/gvisor#235]
We want to run a gVisor sandbox without network access (`--network=none`), and implement restricted access to a few hardened upstreams by mounting in Unix sockets. This pattern works in Docker because the sockets and container exist in the same kernel, but gVisor's filesystem sidecar doesn't seem to support mounting Unix sockets.

https://github.com/google/gvisor/issues/33#issuecomment-386668249 suggests this was intentional, for security. Would it be possible to relax that restriction, either by default or with a CLI flag?

Alternatively, is there any recommended way to add a "network gopher" that could run outside the sandbox and proxy TCP traffic?

**Comment by iangudger** [comment]
I think @prattmic was looking into this recently.

**Comment by prattmic** [comment]
Relaxing this restriction is something that we've considered recently, at least for connecting to existing UDS (as opposed to binding new sockets). Would only being able to connect work for your use-case? 

Also note that it wouldn't be possible to send in-sandbox file descriptors over such a UDS to a process outside the sandbox, though I doubt you are trying to do that.

**Comment by adunham-stripe** [comment]
I think that @jmillikin-stripe may not be near a laptop this week, so I'll jump in here and expand a bit: @jmillikin-stripe, please keep me honest!

I'm pretty sure that we'd only be using the "connect to existing UDS" features, and we're not interested in passing file descriptors over it. The main use-case here is being able to proxy and filter traffic leaving a container in a useful manner; one thing that we've done with regular Docker is to run the container with `--network none`, and send all traffic via a CONNECT proxy on a Unix socket mounted into the container. This lets us allow/denylist domains to connect to via a single interface (listening on the Unix socket on the host), and make much stronger isolation guarantees (i.e. "no Docker networking") compared to e.g. trying to wire something up with `iptables`.

**Comment by prattmic** [comment]
Thanks for the details, I think that is a very reasonable use case. It will need a bit more investigation, but I think it is something we should be able to allow, especially if it is something that one of you want to look into hooking up.

We do also have all the pieces to allow a custom network gofer (netgofer), but no API for it at the moment. And for this kind of fairly simple use case that would likely be overkill vs a simple UDS.

**Comment by adunham-stripe** [comment]
> especially if it is something that one of you want to look into hooking up.

I'm interested in looking into this, but I'll admit to being unfamiliar with gVisor's codebase. I found [this chunk of code](https://github.com/google/gvisor/blob/master/pkg/p9/handlers.go#L251-L256), which does not check for `.IsSocket()`, but I'm not sure if I'm barking up the wrong tree here. I'm happy to dig further, but before I do that: any suggestions/pointers?

**Comment by prattmic** [comment]
I'm happy to help figure out our codebase. :) BTW, we've just recently set up a [Gitter channel](https://gitter.im/gvisor/community) if you want to join for more real-time questions.

Connecting to a socket generally goes through the `connect(2)` syscall, not `open(2)`, which will ultimately become a [Tlconnect](https://github.com/google/gvisor/blob/master/pkg/p9/handlers.go#L1268) 9p RPC [1].

The good news is that the sentry (sandbox kernel) side already supports connecting to UDS through a gofer. It's just not supported by the gofer used in runsc.

In the sentry both the fs and networking paths are fairly complicated and UDS combines both, so for posterity, here is the flow of connecting to a gofer-backed UDS:

[linux.Connect](https://github.com/google/gvisor/blob/master/pkg/sentry/syscalls/linux/sys_socket.go#L261) (`connect(2)` syscall handler) -> [unix.SocketOperations.Connect](https://github.com/google/gvisor/blob/master/pkg/sentry/socket/unix/unix.go#L345) -> [transport.connectionedEndpoint.Connect](https://github.com/google/gvisor/blob/master/pkg/sentry/socket/unix/transport/connectioned.go#L342) -> [gofer.endpoint.BidirectionalConnect](https://github.com/google/gvisor/blob/master/pkg/sentry/fs/gofer/socket.go#L77) -> [e.file.Connect](https://github.com/google/gvisor/blob/master/pkg/sentry/fs/gofer/socket.go#L96) which is just a Tlconnect 9p call.

I don't think you should need to change any of the sentry code. On the gofer side, we'll call [p9.File.Connect](https://github.com/google/gvisor/blob/master/runsc/fsgofer/fsgofer.go#L1001), which is where we need an implementation.

We have pretty extensive UDS tests in our [syscall tests](https://github.com/google/gvisor/tree/master/test/syscalls/linux). I'll have to think about the best way to hook up these gofer-backed sockets to those tests.

Hopefully this should help you get a prototype working, and we can see where to go from there (should this be behind a flag, etc).

[1] N.B. Tlconnect is a custom extension we've added to 9p. It's not standard: https://github.com/google/gvisor/blob/master/pkg/p9/version.go#L126

**Comment by prattmic** [comment]
Note that this feature still has some issues:

* Connecting to the wrong kind of socket may crash the gofer.
* Unsafe use of unet.Socket that may cause the garbage collector to close the socket FD.

I'll be sending out fixes for these (and more complete tests) soon.
