### ISSUE TITLE
Why is the VDSO page in Sentry.GR0 unmapped?

### ISSUE THREAD

**Issue by ZeyuMi** [google/gvisor#240]
Hi,

I found that the VDSO page in Sentry.GR0 is unmapped. So trying to access page triggers a page fault, which is then forwarded to Sentry.HR3.

I just wonder the rationale behind this design. What would happen if I map this page to Sentry.GR0?

Thanks in advance.

**Comment by amscanne** [comment]
The vvar page (shared data region used by the VDSO) is marked as I/O memory. In previous versions of Linux, the PTE was installed without any VMA at all. It is therefore not mappable into the guest. I can't remember exactly what happens, but I believe you will get an MMIO emulation failure when the sentry tries to access it.

The sentry's view of time should be consistent with the application anyways. All timekeeping should use sentry/kernel/time and the clocks package.

**Comment by ZeyuMi** [comment]
Thanks for your reply!

I still have a question here. Why is the VDSO page in Sentry.HR3 mapped while that page in Sentry.GR0 is not? My guess is that the Sentry.HR3 deliberately configures this mapping in order to make the view of time is consistent. Am I right?

**Comment by amscanne** [comment]
In general the sentry does not use the VDSO. Any incidental use while in GR0 will result in a transition back to HR3 (and manifest as a performance hit). That's okay as long as it's not in any hot paths.

We could unmap the VDSO from HR3, but it might cause strange failures and make debugging challenging. I imagine standard system time would be used incidentally by features outside the hot path: e.g. CPU profiling, go tracing, control RPCs, etc.

**Comment by ZeyuMi** [comment]
Thanks a lot!
