### ISSUE TITLE
stack smashing detected on Arm64

### ISSUE THREAD

**Issue by nibon7** [google/gvisor#2486]
When I run ```docker run --runtime runsc -ti ubuntu:latest bash``` on Arm64, it failed with error
```
*** stack smashing detected ***: <unknown> terminated
```
runsc.log.XXX.boot shows
```
D0418 05:58:43.054717    2386 task_exit.go:338] [   1] Init process terminating, killing namespace
D0418 05:58:43.054727    2386 task_exit.go:221] [   1] Transitioning from exit state TaskExitInitiated to TaskExitZombie
D0418 05:58:43.054739    2386 task_exit.go:221] [   1] Transitioning from exit state TaskExitZombie to TaskExitDead
I0418 05:58:43.054754    2386 boot.go:261] application exiting with {Code:0 Signo:11}
I0418 05:58:43.054808    2386 watchdog.go:206] Stopping watchdog
I0418 05:58:43.054821    2386 watchdog.go:210] Watchdog stopped
I0418 05:58:43.054831    2386 main.go:330] Exiting with status: 11
```

* docker config
```json
{
      "runtimes": {
                "runsc": {
                        "path": "/usr/bin/runsc",
                        "runtimeArgs": [
                                "--debug",
                                "--strace",
                                "--debug-log=/tmp/runsc/"
                        ]
                }
        }
}
```
*   `runsc --version`
```
runsc version release-20200323.0-182-ge838290e671c-dirty
spec: 1.0.1-dev
```
*   `docker version`
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:06 2020
 OS/Arch:           linux/arm64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:44 2020
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
*   `uname -a` 
```
Linux localhost.localdomain 5.4.0 #1 SMP Mon Apr 6 09:56:06 CST 2020 aarch64 aarch64 aarch64 GNU/Linux
```
*   runsc.log.20200418-135842.279801.create
[runsc.log.20200418-135842.279801.create.txt](https://github.com/google/gvisor/files/4496151/runsc.log.20200418-135842.279801.create.txt)

* runsc.log.20200418-135842.375153.gofer
[runsc.log.20200418-135842.375153.gofer.txt](https://github.com/google/gvisor/files/4496152/runsc.log.20200418-135842.375153.gofer.txt)

* runsc.log.20200418-135842.376579.boot
[runsc.log.20200418-135842.376579.boot.txt](https://github.com/google/gvisor/files/4496153/runsc.log.20200418-135842.376579.boot.txt)

* runsc.log.20200418-135842.454192.start
[runsc.log.20200418-135842.454192.start.txt](https://github.com/google/gvisor/files/4496154/runsc.log.20200418-135842.454192.start.txt)

* runsc.log.20200418-135843.207068.delete
[runsc.log.20200418-135843.207068.delete.txt](https://github.com/google/gvisor/files/4496155/runsc.log.20200418-135843.207068.delete.txt)

**Comment by amscanne** [comment]
I see the version is *-dirty, are your local modifications significant?

It appears to detect stack smashing as a result of the SIGCHILD being delivered:
I0418 05:58:43.047303    2386 strace.go:578] [   3] groups E exit_group(0x0)
I0418 05:58:43.047316    2386 strace.go:616] [   3] groups X exit_group(0x0) = 0x0 (940ns)
D0418 05:58:43.047325    2386 task_exit.go:221] [   3] Transitioning from exit state TaskExitNone to TaskExitInitiated
I0418 05:58:43.047381    2386 strace.go:584] [   1] bash E read(0x3 pipe:[1], 0xff4ac82691b8, 0x80)
D0418 05:58:43.047484    2386 task_exit.go:221] [   3] Transitioning from exit state TaskExitInitiated to TaskExitZombie
D0418 05:58:43.047498    2386 task_signals.go:457] [   2] No task notified of signal 17
D0418 05:58:43.047520    2386 task_exit.go:221] [   3] Transitioning from exit state TaskExitZombie to TaskExitDead
I0418 05:58:43.047538    2386 strace.go:625] [   2] bash X wait4(0xffffffffffffffff, 0xff4ac8268d50, 0x0, null) = 0x3 (15.746421ms)
I0418 05:58:43.047715    2386 strace.go:587] [   2] bash E rt_sigaction(SIGINT, 0xff4ac8268ab8 {Handler: 0xd84a1b9d3f60, Flags: 0x0, Restorer: 0x70, Mask: []}, 0xff4ac8268b50, 0x8)
I0418 05:58:43.047739    2386 strace.go:625] [   2] bash X rt_sigaction(SIGINT, 0xff4ac8268ab8 {Handler: 0xd84a1b9d3f60, Flags: 0x0, Restorer: 0x70, Mask: []}, 0xff4ac8268b50 {Handler: 0xd84a1b9b76f8, Flags: 0x0, Restorer: 0x70, Mask: []}, 0x8) = 0x0 (5.39µs)
I0418 05:58:43.047785    2386 strace.go:587] [   2] bash E rt_sigprocmask(SIG_SETMASK, 0xff4ac8268e68 [], 0x0, 0x8)
D0418 05:58:43.047797    2386 task_block.go:223] [   2] Interrupt queued
I0418 05:58:43.047806    2386 strace.go:625] [   2] bash X rt_sigprocmask(SIG_SETMASK, 0xff4ac8268e68 [], null, 0x8) = 0x0 (9.259µs)
D0418 05:58:43.047817    2386 task_signals.go:220] [   2] Signal 17: delivering to handler
I0418 05:58:43.047984    2386 strace.go:587] [   2] bash E wait4(0xffffffffffffffff, 0xff4ac8267990, 0x1, 0x0)
I0418 05:58:43.047998    2386 strace.go:625] [   2] bash X wait4(0xffffffffffffffff, 0xff4ac8267990, 0x1, 0x0) = 0x0 errno=10 (no child processes) (1.51µs)
I0418 05:58:43.048236    2386 strace.go:584] [   2] bash E writev(0x2 host:[1], 0xff4ac8267760 {base=0xfeb5d79b46f8, len=4, "*** "}, {base=0xfeb5d79b46d0, len=23, "stack smashing detected"}, {base=0xfeb5d79b46fe, len=6, " ***: "}, {base=0xfeb5d79b46e8, len=9, "<unknown>"}, {base=0xfeb5d79b4706, len=12, " terminated\n"}, 0x5)
I0418 05:58:43.048283    2386 strace.go:622] [   2] bash X writev(0x2 host:[1], ..., 0x5) = 0x36 (27.66µs)

But the handler doesn't seem to run?? I would expect an EINTR and rtsigreturn call after that, but it seems to return to wait call directly. (In which case, yes -- it's stack will be clobbered with the signal frame.)

**Comment by nibon7** [comment]
I applied the following two commits, and it works.
[Arm64 signal#2: VDSO support for signal ](https://github.com/google/gvisor/pull/1818/commits/fe001edb14e6e879ab4ebca0d2ac71d770ac8cce)
[Arm64 signal#3: signal support in arch module](https://github.com/google/gvisor/pull/1819/commits/5eb41c8fbabac090251fbfb43bd9c814124aa575)
