### ISSUE TITLE
pids.limit cgroup limit is not working

### ISSUE THREAD

**Issue by majek** [google/gvisor#2489]
According to OCI spec:
https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#pids

If  we had such section in config.json, under linux/resources:
```
    "linux": {
        "resources": {
            "pids": {
                "limit": 32771
            }
```

Then we should have cgroup pids should be limited using the usual `pids.max` toggle.

I believe this setting is ignored and not adhered to by runsc.

**Comment by fvoznika** [comment]
Yeah, PID limit should be considered when setting up cgroups. I'll send a fix soon...
