### ISSUE TITLE
Memory Cgroup support / OOM behaviour

### ISSUE THREAD

**Issue by majek** [google/gvisor#2520]
I tried to restrict my container to not use to much memory. Of course OCI spec defines this:
https://github.com/tianon/oci-runtime-spec/blob/master/config-linux.md#memory

It turns out swap is hard, so for this exercise let's disable swap:
```
swapoff -a
```
And use this config in config.json
```
            "disableOOMKiller": false,
            "memory": {
                "limit": 1073741824
            },
```
Ok.... with this running, we can run a container and run python in it:
```
root@runsc:~# python3
>>> a = 'a' * 1024*1024*1024*2
```

I would expect the correct reaction, like on host:
```
>>> a = 'a' * 1024*1024*1024*1024
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError
``` 
Instead, gvisor dies.  This is due to the way how memory cgroup work. Instead of failing on mmap, like on host, memory cgroup seems to trigger OOM killer. OOM killer sends SIGKILL to victim. Gvisor seem to catch that and close everything down.

```
$ dmesg
[264974.823372] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=gv,mems_allowed=0,oom_memcg=/cloudchamber/hackme/gv,task_memcg=/cloudchamber/hackme/gv,task=exe,pid=12729,uid=65534
[264974.823440] Memory cgroup out of memory: Killed process 12729 (exe) total-vm:858156kB, anon-rss:6212kB, file-rss:19764kB, shmem-rss:7144kB, UID:65534 pgtables:392kB oom_score_adj:0
```

Considering that runsc has knowledge of all memory allocations by the guest perhaps we could do better than clean up whole container on one process running oom.

FTR: I Don't see anything interesting in gvisor logs
```
runsc.log.20200423-154447.322838.start:I0423 15:44:47.395569   12765 main.go:330] Exiting with status: 0
runsc.log.20200423-154447.131206.create:I0423 15:44:47.243597   12720 main.go:330] Exiting with status: 0
```

**Comment by ianlewis** [comment]
> Considering that runsc has knowledge of all memory allocations by the guest perhaps we could do better than clean up whole container on one process running oom.

Right now I think runsc just runs itself in the cgroup and calls it good. We don't impose any memory limits based on the memory limits given to runsc. Given that the sentry itself is also limited by the cgroup, If the sentry imposed the same limits, I would think that we would fairly commonly run into the host's cgroup limit before any limitations that the sentry imposes would be hit. That is unless we reserve some fixed overhead for the sentry or something like that.

Is there a specific case were you think this is particularly problematic?

**Comment by amscanne** [comment]
The host example:

> >>> a = 'a' * 1024*1024*1024*1024
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError

.. doesn’t seem related to memory limit enforcement. (Linux will happily allow you to allow you to “allocate” much more than your limit, it will just be lazily populated and you may eventually trigger the OOM killer.)

Unless I’m missing something or misunderstanding, there must be something different in the default python environment here. Maybe RLIMIT_AS?

The examples are also different, which may be the reason: 1 TB in the host example and 2 GB in the runsc example. It’s possible that the 1 TB case is tripping some other limit that python is actually catching (before it actually tries to do that and get killed) and throwing a “MemoryError”.

We’ll support in-sandbox memory limits and “cgroups” one day, but it’ll be a while. FWIW, the thread issue is more severe IMO. There’s a well-defined behavior for thread exhaustion (EAGAIN), but if your cgroup is over limit then _something_ is going to get reaped (which in practice may not be meaningfully different from the whole sandbox being nuked).

**Comment by majek** [comment]
Ok thanks for pushback. Indeed, I think this is at least three separate things:

(1) SIGKILL to any process cleans up the whole container, which I dont think is right
https://github.com/google/gvisor/issues/2533

(2) mmap always succeeds even for stupid values
https://github.com/google/gvisor/issues/2534

(3) memory cgroup counts both runsc and guests, which increases chances of runsc-gofer/runsc-sandbox getting the SIGKILL from OOM killer
https://github.com/google/gvisor/issues/2535

I'm closing this ticket.
