### ISSUE TITLE
tmpfs ignores "size=" parameter, runsc crashes on large file in /tmp

### ISSUE THREAD

**Issue by majek** [google/gvisor#2536]
To my understanding /tmp is internally mounted as emulated "tmpfs". I tried restricting its size, and failed.

I added this to config.json
```
        {
            "destination": "/tmp",
            "type": "tmpfs",
            "source": "tmpfs",
            "options": [
                "nosuid",
                "strictatime",
                "mode=755",
                "size=65536k"
            ]
        },
```
as per OCI spec. .boot log says
```
I0424 13:42:50.018497   27556 fs.go:875] Mounted "/tmp/xxxx/proc" to "/proc" type: proc, internal-options: []
D0424 13:42:50.018509   27556 fs.go:645] Mounting "/tmp/xxx/tmpfs" to "/tmp", type: tmpfs, options: [nosuid strictatime mode=755 size=65536k]
W0424 13:42:50.018523   27556 fs.go:223] ignoring unknown mount option "nosuid"
W0424 13:42:50.018540   27556 fs.go:223] ignoring unknown mount option "strictatime"
W0424 13:42:50.018548   27556 fs.go:223] ignoring unknown mount option "mode=755"
W0424 13:42:50.018555   27556 fs.go:223] ignoring unknown mount option "size=65536k"
```

Notice: *ignoring unknown mount option "size"*. This is pretty bad. Doing this inside the guest
```
cd /tmp
dd if=/dev/zero of=file.bin bs=1M count=9999999
```
Will crash the guest with OOM. I would expect to get some kind of "No space left on device" message.

**Comment by hbhasker** [comment]
https://github.com/google/gvisor/blob/master/pkg/sentry/fs/tmpfs/tmpfs.go#L35 I guess we never got around to it.

**Comment by Wonderfall** [comment]
Yeah, `runsc` seems to ignore `tmpfs-size` when mounting a `tmpfs` volume via Docker.
At least one can set `--memory` (which is recommended in general) and it won't affect the host.

```
docker run -ti --rm --runtime=runsc --mount type=tmpfs,destination=/tmp,tmpfs-size=5M --memory 20M alpine sh
cd /tmp && dd if=/dev/zero of=file.bin bs=1M count=9999999
```

The guest crashes when it hits the 20M memory limit. The same but with runc, as expected:

```
dd: error writing 'file.bin': No space left on device
-rw-r--r--    1 root     root        5.0M Mar 30 15:56 file.bin
```

**Comment by fvoznika** [comment]
@Wonderfall, that's correct. @sshambhavi-252 is working on tracking tmpfs memory usage and applying the limits from docker.

As for the crash, this can happen when the memory allocation that hits OOM is coming from gVisor's kernel. That's because the Go runtime doesn't allow applications to handle OOM and panics when it happens.

**Comment by ayushr2** [comment]
tmpfs size limit should now be supported. Relevant commits:
- https://github.com/google/gvisor/commit/5b538f75e447d934ac81a1bfc167306ef8f55814
- https://github.com/google/gvisor/commit/7bc837137cff470e384d8d4e879990c5661879ba
- https://github.com/google/gvisor/commit/49ae54c01067e77f1b1cd80e65358bf12a526456
- https://github.com/google/gvisor/commit/ce91143bdc77ccdebf7aaae9ee8eb4843aa5f880

Thanks @sshambhavi-252 for your work!
