### ISSUE TITLE
collect2: fatal error: cannot find 'ld'

### ISSUE THREAD

**Issue by richardweinberger** [google/gvisor#26]
On Linux the build fails:

$ bazel build --verbose_failures runsc
INFO: Analysed target //runsc:runsc (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/rw/homerw_old/work/gvisor/vdso/BUILD:8:1: Executing genrule //vdso:vdso failed (Exit 1): bash failed: error executing command 
  (cd /home/rw/.cache/bazel/_bazel_rw/5842f54b5499609ce9d6a4a0b7803cf7/execroot/__main__ && \
  exec env - \
    PATH=/opt/make/bin/:/opt/make/bin/:/home/rw/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; /usr/bin/gcc  -I. -O2 -std=c++11 -fPIC -fuse-ld=gold -m64 -shared -nostdlib -Wl,-soname=linux-vdso.so.1 -Wl,--hash-style=sysv -Wl,--no-undefined -Wl,-Bsymbolic -Wl,-z,max-page-size=4096 -Wl,-z,common-page-size=4096 -Wl,-Tvdso/vdso.lds -o bazel-out/k8-fastbuild/genfiles/vdso/vdso.so vdso/vdso.cc vdso/vdso_time.cc && bazel-out/host/bin/vdso/check_vdso --check-data --vdso bazel-out/k8-fastbuild/genfiles/vdso/vdso.so ')

Use --sandbox_debug to see verbose messages from the sandbox
collect2: fatal error: cannot find 'ld'
compilation terminated.
Target //runsc:runsc failed to build
INFO: Elapsed time: 0.622s, Critical Path: 0.41s
FAILED: Build did NOT complete successfully

```

```

**Comment by hugelgupf** [comment]
What distro are you on? 

You may have to install the gold linker, e.g.

```
apt-get install binutils-gold
```

on Ubuntu.

**Comment by richardweinberger** [comment]
Installing gold did the trick, thanks!
I'm on OpenSUSE Leap.

**Comment by baibai841** [comment]
do you solute this question?  I also meet it

**Comment by milantracy** [comment]
@baibai841 you may want to try https://github.com/google/gvisor/issues/26#issuecomment-386379835 to install gold linker.

let me know if that works for you. Otherwise, can you create a new issue to let us know how to reproduce it?
