### ISSUE TITLE
Add stub support for TCP_SYNCNT option

### ISSUE THREAD

**Issue by hbhasker** [google/gvisor#2625]
TCP_SYNCNT controls the number of retransmits of the SYN that happen during a connect. Exact description is below.

Netstack does not really bound the SYN retransmits using a count but just uses an exponential backoff and it bounds by time. We could for now stub this out and leave a proper implementation for later.

This sockopt not being supported breaks py-amqp.

See: https://github.com/google/gvisor/issues/1441#issuecomment-624751383 for more details

TCP_SYNCNT (since Linux 2.4)
Set the number of SYN retransmits that TCP should send before
aborting the attempt to connect. It cannot exceed 255. This
option should not be used in code intended to be portable.

**Comment by majek** [comment]
Looking forward. A quick note that interaction of TCP_SYN_CNT with TCP_USER_TIMEOUT  is weird (and buggy depending on kernel) https://blog.cloudflare.com/when-tcp-sockets-refuse-to-die/

**Comment by hbhasker** [comment]
Thanks for the reference. I saw that article earlier as well. Anyway the plan is not to implement it's functionality for now just to stub out the option so that py-AMQP does not fail

**Comment by hbhasker** [comment]
hah! didn't realize you authored the article:)
