### ISSUE TITLE
Missing netstack license

### ISSUE THREAD

**Issue by ijc** [google/gvisor#27]
Many files under `pkg/` have a header:
```
// Copyright 2016 The Netstack Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
```

However there is no `LICENSE` file (nor any similarly named files) in those subdirectories and the top-level `LICENSE` has an Apache 2.0 license.

I think you need to include a copy of https://github.com/google/netstack/blob/master/LICENSE?

**Comment by hugelgupf** [comment]
@nlacasse weren't we going to relicense Netstack to be Apache, as well?

**Comment by TheMacNerd** [comment]
Guide for the missing MIT Open source license.

https://meta.stackexchange.com/questions/271080/the-mit-license-clarity-on-using-code-on-stack-overflow-and-stack-exchange
