### ISSUE TITLE
gVisor container couldn't set hugetlb manually?

### ISSUE THREAD

**Issue by younaman** [google/gvisor#2713]
Hello everyone,I am trying to manually set hugetlb limit for my Docker&gVisor Container:
1.I set the hugepage_size to 2M and 1024 hugepages totally.
2.I start my Docker Container,vim the /sys/fs/cgroup/hugetlb/docker/DockerID/hugetlb.2MB.limit_in_bytes file,and write 1073741824,which means my Docker Container could use 512 2M hugepages totaly.
3.But,when I start my gVisor Container and try to do the same thing for it,I couldn't find the /sys/fs/cgroup/hugetlb/docker/gVisorID directories!
My OS is ubuntu 18.04 with kernel 5.3.0-51-generic,could anyone give me some suggestions about this situation?Is the gVisor don't support hugetlb set?If the gVisor support it,how could I write the limit?

**Comment by fvoznika** [comment]
gVisor doesn't support huge pages for applications running inside the sandbox. However, I think we could support huge pages for the entire Sandbox using `MFD_HUGETLB` with memfd_create(2).

Could you share a bit more about the application you're running and why huge pages are beneficial in your case?

**Comment by amscanne** [comment]
@fvoznika I think this is a different issue. The cgroup hugetlb limit is not being passed on to the sandbox.

**Comment by fvoznika** [comment]
That's possible. It's not clear to me whether step 2) and 3) are executed inside or outside the sandbox. Outside makes more sense, then we need to add hugetlb to [cgroup.controllers](https://github.com/google/gvisor/blob/05c89af6edde6158844d4debfe68bc598fec4418/runsc/cgroup/cgroup.go#L41). However, gVisor will not allocate huge pages unless transparent huge pages is enabled.

@younaman can you clarify?

**Comment by younaman** [comment]
Hello everyone!Thanks to your answers! @fvoznika My code is very simple,because I am trying to use the huge page,so I write a C code,using mmap(to use 2M memory at once) to trigger the usage of hugepage,I try the code in my docker container and gVisor container so it's inside the sandbox.I enabled the transparent hugepage in my Host OS

**Comment by younaman** [comment]
So my questions is:
(1) Can I use hugepage by calling mmap syscall in gVisor Container?(I have enabled transparent page in my Host)
(2)Can I pass my Cgroup limit of hugetlb to gVisor Container?In the other hand,pass the limit to gVisor userspace kernel?

**Comment by amscanne** [comment]
(1) gVisor should allocate memory and create mappings that will work with THP.
(2) These will be passed through with #2732.

**Comment by fvoznika** [comment]
With 4cc9ca9e6c4e82fa2e8062b00d8d76ae48f0b073, the sandbox now registers with hugetlb cgroup. Please try it and reopen if you still have problems.
