### ISSUE TITLE
go: some files have executable permission on `go` branch

### ISSUE THREAD

**Issue by zchee** [google/gvisor#2722]
**Description**

I've known this issue for a long time, but I didn't realize that the gVisor repository enabled the GitHub issue feature, so I'll post it.
And note that this is not a bug report for the gVisor implementation.

---

The `go` branch is maintained separately for _go-gettable_ from the mainline, But **some files have executable permission**.
I think the current state is not intended by the gVisor team, also it's noisy a bit on the terminal with `$LS_COLORS` :(

**Steps to reproduce**

`find` command assume GNU findutils.

```console
$ git clone -- https://github.com/google/gvisor $(go env GOPATH)/src/gvisor.dev/gvisor
$ cd $(go env GOPATH)/src/gvisor.dev/gvisor
$ git rev-parse --verify HEAD
f2f2dec7280e37696550185f291d51cf9e47e281
$ git checkout origin/go
$ git rev-parse --verify HEAD
bae1520437ecbd3dd217880cb51eb24b59d26f51
$ find . -type f -executable -path './*' -and -not -iwholename '*.git*' | wc -l
673
```

**Environment**

Since I use darwin OS, runsc cannot be built natively. so there is nothing to describe for the environment.

**Comment by zchee** [comment]
I'd seen this commit https://github.com/google/gvisor/commit/cbfb55869e4d00ddd1ede096ba01adf2713e08b1, cc @amscanne ?

**Comment by amscanne** [comment]
Strange, I guess bazel :gopath generates executable files. This is a relatively simple fix, will do shortly.

**Comment by zchee** [comment]
@amscanne thanks!
