### ISSUE TITLE
Implement /dev/fuse

### ISSUE THREAD

**Issue by mrahatm** [google/gvisor#2752]
Create a stub implementation of `/dev/fuse` which can be opened for an FD backed by the sentry FUSE filesystem (the FS can be stubbed out at this point). See the [`memdev`](https://github.com/google/gvisor/blob/master/pkg/sentry/devices/memdev/memdev.go) package for an example of implementing simple character devices in VFS2, and [`devtmpfs`](https://github.com/google/gvisor/blob/master/pkg/sentry/fsimpl/devtmpfs/devtmpfs.go) for how to wire it up to a VFS2 filesystem, specifically [`devtmpfs.Accessor.UserspaceInit`](https://github.com/google/gvisor/blob/master/pkg/sentry/fsimpl/devtmpfs/devtmpfs.go#L163).

**Comment by ridwanmsharif** [comment]
Completed in #3083
