### ISSUE TITLE
Mount a trivial FUSE filesystem

### ISSUE THREAD

**Issue by mrahatm** [google/gvisor#2753]
Expand the stub sentry FUSE client to support mounting a trivial filesystem.

Follow along with [`fuse_mount`](https://libfuse.github.io/doxygen/fuse-3_88_80_2include_2fuse_8h.html#a04baffd979b06663ae9590e34a48b55f) until `fusermount` can successfully complete the handshake and mount a filesystem.

The [`hello`](https://github.com/libfuse/libfuse/blob/master/example/hello.c) example filesystem from `libfuse` may be a convenient, trivial filesystem to try mount.

**Comment by mrahatm** [comment]
Depends on #2752.

**Comment by ridwanmsharif** [comment]
Done in #3024
