### ISSUE TITLE
host syscalls used by gVisor

### ISSUE THREAD

**Issue by younaman** [google/gvisor#2917]
Hello everyone,I have knew that Sentry itsellf use a whitelisted syscall(53),and gofer uuse some host syscalls too.I want to know what these syscalls is,so where can I find the default syscalls allowed by sentry/gofer?Can I find the related file in source code?Thanks alot if you could give me any suggestions!

**Comment by tanjianfeng** [comment]
sandbox: https://github.com/google/gvisor/blob/master/runsc/boot/filter/config.go#L28
gofer: https://github.com/google/gvisor/blob/master/runsc/fsgofer/filter/config.go#L27

**Comment by younaman** [comment]
@tanjianfeng I have found it!Thanks alot!
