### ISSUE TITLE
runsc doesn't set $HOME

### ISSUE THREAD

**Issue by ianlewis** [google/gvisor#293]
[Per POSIX](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html) the HOME environment variable should be set to the user's home directory. Currently the HOME environment variable is missing with runsc.

```
$ docker run --rm -ti alpine sh
> echo $HOME
/root

$ docker run --rm --runtime=runsc -ti alpine sh
> echo $HOME
```

- runsc should set the environment variable by default based on the UID specified in the OCI bundle and /etc/passwd in the filesystem (could but under nested mounts).
- If no /etc/passwd is present the default is HOME=/
- If HOME variable is set by the OCI bundle it is honored.

**Comment by AngleNet** [comment]
Seems to be a bug, is anyone working on this issue now?

**Comment by ianlewis** [comment]
Yah, I have a PR out now: https://github.com/google/gvisor/pull/325

It was basically just never implemented 😑
