### ISSUE TITLE
Use inclusive terminology

### ISSUE THREAD

**Issue by prattmic** [google/gvisor#2972]
In particular, removing blacklist/whitelist and master/slave where possible. There has been discussion about these terms in many projects and it is clear that many are made to feel unwelcome by these terms. It is a very minor thing we can do to remove them.

This would be following [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=981129), [Python](https://bugs.python.org/issue34605), [Go](https://go-review.googlesource.com/c/go/+/236857), [GitHub](https://twitter.com/natfriedman/status/1271253144442253312) and many other projects (and soon, I hope, [Linux](https://lore.kernel.org/lkml/20200611062550.20113-1-sjpark@amazon.com/)).

**Comment by kevinGC** [comment]
We should discuss how to handle cases where we re-use Linux terminology
when implementing the gVisor equivalent. For example, our PTY
implementation uses master and slave, as those terms are part of the
PTY/TTY interface and documentation.

**Comment by prattmic** [comment]
Indeed, I intentionally skipped over the PTY code earlier because it is the probably the hardest one, with lots of uses and clarity needed w.r.t. the Linux interface.

For PTYs, a few options I've seen:

* Go uses 'control TTY' / 'process TTY': https://go-review.googlesource.com/c/go/+/236857/6/src/os/signal/internal/pty/pty.go
* `ptmx` / `pts` or `pty`: https://twitter.com/brau_ner/status/1279691047807913984

FWIW, I don't think we need to follow Linux naming specifically, though we probably do want a reference somewhere to what Linux calls this thing.

**Comment by prattmic** [comment]
This is now official Google open source policy: https://opensource.google/docs/releasing/preparing/#inclusive

**Comment by prattmic** [comment]
Linux guidelines and alternatives: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=49decddd39e5f6132ccd7d9fdc3d7c470b0061bb

Further suggestions can be found in this thread: https://lore.kernel.org/lkml/159389297140.2210796.13590142254668787525.stgit@dwillia2-desk3.amr.corp.intel.com/

**Comment by ianlewis** [comment]
I think following the Linux terminology will keep clarity; we can have our own terminology temporarily but I would update it to match Linux terminology at some point.
