### ISSUE TITLE
Run hello-world with kvm platform on Arm64

### ISSUE THREAD

**Issue by lubinszARM** [google/gvisor#3019]
* [x]   docker run --runtime=runsc-kvm --rm hello-world

Hardware platform: 
* [x]   thunderx2
* [x]   AMPERE EMAG
* [x]   Neoverse N1

**Comment by lubinszARM** [comment]
root@gviosr-ci-arm64-01:/tmp/runsc# !dock
docker run --runtime=runsc-kvm --rm hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (arm64v8)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

**Comment by lubinszARM** [comment]
[runsc.log.20200618-100252.380154.boot.txt](https://github.com/google/gvisor/files/4797999/runsc.log.20200618-100252.380154.boot.txt)

**Comment by lubinszARM** [comment]
goos: linux
goarch: arm64
BenchmarkApplicationSyscall
BenchmarkApplicationSyscall-56                    447864              2405 ns/op
BenchmarkKernelSyscall
BenchmarkKernelSyscall-56                        6878755               171 ns/op
BenchmarkWorldSwitchToUserRoundtrip
BenchmarkWorldSwitchToUserRoundtrip-56             71779             15857 ns/op
PASS

**Comment by lubinszARM** [comment]
Without enhance internal patch:

goos: linux
goarch: arm64
BenchmarkApplicationSyscall
BenchmarkApplicationSyscall-56                    510801              2333 ns/op
BenchmarkKernelSyscall
BenchmarkKernelSyscall-56                        6701257               173 ns/op
BenchmarkWorldSwitchToUserRoundtrip
BenchmarkWorldSwitchToUserRoundtrip-56             74188             15989 ns/op
PASS

**Comment by akhare-ampere** [comment]
Hi @lubinszARM 
I am trying to repeat your results with KVM, but keep getting "panic: error setting KVM_ARM_VCPU_INIT failed: invalid argument" on Ampere system.  I'm running Ubuntu 20.04 with 5.4 kernel and have just recently synced to repo tip.  Are there other patches still in progress for this issue?

BTW, great work on all the ARM64 support!

Thanks,
Arjun

**Comment by lubinszARM** [comment]
> Hi @lubinszARM
> I am trying to repeat your results with KVM, but keep getting "panic: error setting KVM_ARM_VCPU_INIT failed: invalid argument" on Ampere system. I'm running Ubuntu 20.04 with 5.4 kernel and have just recently synced to repo tip. Are there other patches still in progress for this issue?
> 
> BTW, great work on all the ARM64 support!
> 
> Thanks,
> Arjun

Hi @akhare-ampere ,
I still have a few patches that have not been uploaded for kvm platform. 
I am currently solving a vdso/time problem under the kvm platform.
And the biggest difference between thunderx2 and Ampere is that the VCPU in Ampere can't be initialized as '_KVM_ARM_TARGET_GENERIC_V8' which is what your log shows.

**Comment by lubinszARM** [comment]
Since we can run some typical applications with the kvm platform on Arm64(hello-world, ffmpeg...), so I want to close this issue.
