### ISSUE TITLE
Support sticky bit (I_SVTX) in fsimpl/kernfs

### ISSUE THREAD

**Issue by dean-deng** [google/gvisor#3027]

**Comment by ayushr2** [comment]
@dean-deng bump from preventing this from closing

**Comment by fvoznika** [comment]
@ayushr2, is the sticky bit needed for any of the filesystems that use kernfs?

**Comment by ayushr2** [comment]
Kernfs users define their own inodes which implement rename and rmdir. Any kernfs user which supports a writable directory should be handling the sticky bit themselves and kernfs.

The only TODOs relating to this are in `kernfs.OrderedChildren` which is a directory inode (partial) implementation. `kernfs.OrderedChildren` is a utility that can be embedded in inode implementations. The only directory inode which is writable and embeds `kernfs.OrderedChildren` is `kernfs.syntheticDirectory`.

So the work left to be done here is handling the sticky bit in `kernfs.syntheticDirectory`.

**Comment by fvoznika** [comment]
Except for FUSE, the other implementations are read-only. So I think we could simply document this restriction and move this bug over to FUSE.

**Comment by ayushr2** [comment]
`kernfs.syntheticDirectory` is also writable (it can create nested directories inside it, can be RmDir'd and Renamed). `kernfs` uses it when `ForSyntheticMountpoint` option is enabled. So will need to handle the sticky bit there.

FUSE defines its own `Rename` and `RmDir` implementations (overriding `kernfs.OrderedChildren`'s implementation). See `pkg/sentry/fsimpl/fuse/fusefs.go`. So FUSE should not be affected by this bug.

I can take ownership and fix it for the (very unlikely) case of `kernfs.syntheticDirectory`.

**Comment by ayushr2** [comment]
I guess the right approach would be to subsume `InodeAttrs` into `OrderedChildren` and then `OrderedChildren` can do its own sticky bit related checks.
