### ISSUE TITLE
runsc install need support podman

### ISSUE THREAD

**Issue by unknowndevQwQ** [google/gvisor#3053]
**Description**

`runsc install` is able to edit `/etc/docker/daemon.json` to enable Docker to replace runc with runsc.
Would be great if podman supports this feature.

**Is this feature related to a specific bug?**

No. By the way, does gVisor depend on Docker just for the reason that Docker uses runsc as its runtime?

**Do you have a specific solution in mind?**

To replace the runtime of podman, just add `runtime = "/path/to/runsc"` to `/etc/containers/libpod.conf`

**Comment by amscanne** [comment]
> No. By the way, does gVisor depend on Docker just for the reason that Docker uses runsc as its runtime?

Nope, this is just a convenience because Docker is a common path. I think this feature sounds good.

**Comment by unknowndev233** [comment]
> Nope, this is just a convenience because Docker is a common path. I think this feature sounds good.

should docker not be written in the dependency list?

**Comment by amscanne** [comment]
I'm not sure I understand the question: docker is not a dependency. You can use runsc by itself via "runsc do" or via the manual podman configuration. The install happens only if an existing /etc/docker/daemon.json is present: https://github.com/google/gvisor/blob/master/runsc/debian/postinst.sh#L21

**Comment by unknowndev233** [comment]
> I'm not sure I understand the question: docker is not a dependency. You can use runsc by itself via "runsc do" or via the manual podman configuration. The install happens only if an existing /etc/docker/daemon.json is present: https://github.com/google/gvisor/blob/master/runsc/debian/postinst.sh#L21

Why is the "docker" in the requirement list?
![image](https://user-images.githubusercontent.com/52807407/87224030-6f79bc00-c3b4-11ea-969d-d6e2193710b1.png)

**Comment by ianlewis** [comment]
> Why is the "docker" in the requirement list?

Those are the requirements for installing from source. There is a note just above the requirements:

_"For the purposes of these instructions, bazel and other build dependencies are wrapped in a build container."_

**Comment by ianlewis** [comment]
FWIW, I don't think Podman really requires runtimes to be installed like `daemon.json`. Podman normally just takes the binary name (on $PATH) or path. `runsc install` simply adds `runsc` as a named runtime to Docker. It doesn't replace the default runtime. If I understand correctly setting `runtime = "/path/to/runsc"` for Podman would replace the default runtime used by Podman so functionality would be a bit different between the two.

It's also worth noting that libpod.conf has been replaced by containers.conf
https://podman.io/blogs/2020/12/11/remove-varlink-libpod-conf-notice.html

**Comment by unknowndev233** [comment]
https://github.com/containers/common/pull/510

Recent versions of podman should not require additional configuration to recognize runsc

**Comment by unknowndevQwQ** [comment]
fixed by https://github.com/containers/common/pull/510
