### ISSUE TITLE
Can't load source file when using dlv

### ISSUE THREAD

**Issue by Kellermaan** [google/gvisor#3265]
**Description**

I have followed the https://gvisor.dev/docs/user_guide/debugging/ to debug gvisor. When I use dlv to attach the sandbox process, it looks normal. When using _**list**_ command it shows:

> runtime.futex() src/runtime/sys_linux_amd64.s:568 (PC: 0x46a0e3)
Warning: debugging optimized function
Command failed: open src/runtime/sys_linux_amd64.s: no such file or directory

I think the problem is that dlv can't find the source code. (for the source code path, it's a relative path)
I don't know what I missed to cause the problem.

**Steps to reproduce**

Just follow the debug procedure.
https://gvisor.dev/docs/user_guide/debugging/

**Environment**

Please include the following details of your environment:

runsc version release-20200622.1-151-g87c33be9af4a-dirty
spec: 1.0.1-dev

**Comment by iangudger** [comment]
@fvoznika I think you have successfully used dlv?

**Comment by Kellermaan** [comment]
@iangudger It doesn't show the code.

**Comment by fvoznika** [comment]
You an use config substitute-path to redirect source code lookup to the
correct path:

Changes the value of a configuration parameter.

config substitute-path <from> <to>
config substitute-path <from>
