### ISSUE TITLE
Waiting on a container after it exited returns an internal error

### ISSUE THREAD

**Issue by ianlewis** [google/gvisor#3276]
After the changes in https://github.com/google/gvisor-containerd-shim/pull/28, the call to runtime. Wait [here](https://github.com/google/gvisor-containerd-shim/blob/e83ba107367ac3a25725d8857c2ba3cc9adbeb71/pkg/v1/proc/init.go#L237) now uses context.Background. We've observed this causing failures when attempting to Wait on a very short-lived container, since the container will then not be around to wait, and the exit status will be reported as internalErrorCode (128).

There does not appear to be a mechanism to detect this race condition through the shim; there's no error type returned that we could use to detect this, and it's not possible distinguish between an exit status of 128 returned legitimately by the wait operation and one returned by the shim.

Any suggestions on how to distinguish between these two cases ("real" 128 exit status vs. "race condition and can't wait" 128 exit status)?

Originally reported by @adunham-stripe at https://github.com/google/gvisor-containerd-shim/issues/48

**Comment by fvoznika** [comment]
I believe this issue is fixed. There has been many fixed in this area (e.g. c47f8afe2334c1395a2acd9ebf5191aa4554907c, 62b0e845b7301da7d0c75eb812e9cd75ade05b74, 1e472a85729b723c0d737d5e1c68c875a158d6a6, etc). Please reopen if it still occurs.
