### ISSUE TITLE
How can make Sentry call a kernel module in hosts?

### ISSUE THREAD

**Issue by lizhi16** [google/gvisor#3325]
**Description**

To get the memory access frequency of a task in the container, we design a kernel module to profile the access pattern of the task. In gvisor, we want to call this kernel module to help us optimize the memory swap in/out for a task. But it seems gvisor has very strong isolation, we can't simply use "os/exec" to call the kernel module in "sandbox". Could you please give some advice about how to call the kernel module in Sentry?

**Is this feature related to a specific bug?**

No

**Do you have a specific solution in mind?**

Please include any details about a solution that you have in mind, including any
alternatives considered.

**Comment by ianlewis** [comment]
How are you supposed to call your kernel module? What to do you want to use os/exec for?

**Comment by lizhi16** [comment]
> How are you supposed to call your kernel module? What to do you want to use os/exec for?

Actually, we use a file to transform info between the kernel module and the user level. The kernel module will write the results into this file. And we want to send the info in this file to Sentry. Thus, we implement "exec.Command" to read this file in Sentry. But it doesn't work. I think it is because "nobody" user doesn't have the privilege to execute bash commands. 

So we have a question that how can Sentry read a file in hosts? or get info from hosts?

Thanks for your help!

**Comment by fvoznika** [comment]
There are a few things that make exec.Command difficult to use:
1. seccomp rules will prevent execve(2)
1. The sandbox is in a terminal chroot with no access to binaries and files
1. User nobody is restricted

What you could do instead is to open the file outside the sandbox and then donate the FD to the sandbox. This can be done before the sandbox is created, in `runsc create` for example. This is already done for many files, here is a good example to follow: https://cs.opensource.google/search?q=spec-fd&sq=&ss=gvisor
