### ISSUE TITLE
Go github action fails with "Input required and not supplied: token" for forks

### ISSUE THREAD

**Issue by ianlewis** [google/gvisor#3326]
The Go Github Action workflow doesn't work on forks since it requires a Github access token. It fails with the error message below:

```
##[error]Input required and not supplied: token
```

I think we could ignore it for forks because it's should only be required to avoid rate limiting IIUC

**Comment by amscanne** [comment]
Oh yeah, I forgot about this.

We could actually just make some of those steps optional and add alternates. We only need the token because of the branch protection rules. We can't actually add an App (GitHub Actions) in the branch protection rules, which is pretty crummy.
