### ISSUE TITLE
MountFuseFilesystem tests failing

### ISSUE THREAD

**Issue by dean-deng** [google/gvisor#3360]
I 0724 03:04:27.287679  0 [ RUN      ] MountTest.MountFuseFilesystem
I 0724 03:04:27.287680  0 third_party/gvisor/test/syscalls/linux/mount.cc:349: Failure
I 0724 03:04:27.287681  0 Value of: _expr_result
I 0724 03:04:27.287682  0 Expected: is OK
I 0724 03:04:27.287690  0   Actual: PosixError(errno=1 Operation not permitted) mount failed

I 0724 03:04:27.276466  0 [ RUN      ] MountTest.MountFuseFilesystemNoDevice
I 0724 03:04:27.276467  0 third_party/gvisor/test/syscalls/linux/mount.cc:333: Failure
I 0724 03:04:27.276468  0 Value of: mount("", dir.path().c_str(), "fuse", 0, "")
I 0724 03:04:27.276469  0 Expected: -1 (failure), with errno PosixError(errno=22 Invalid argument)
I 0724 03:04:27.276470  0   Actual: -1 (of type int), with errno PosixError(errno=1 Operation not permitted)

**Comment by craig08** [comment]
Closed by #3368
