### ISSUE TITLE
ImageTests: TomcatTest failing on VFS2

### ISSUE THREAD

**Issue by zkoopmans** [google/gvisor#3365]
In //test/image/image_test.go, TestTomcat fails.

Tomcat server container fails to start and test fails.

Steps to reproduce

With docker/runsc installed with "vfs2" flag enabled:
make load-basic-images
bazel test --test_arg='--runtime=RUNTIME' --test_filter=Tomcat -- //test/image:image_test

Environment

Please include the following details of your environment:

docker 19.03.5
runsc --vfs2

**Comment by ayushr2** [comment]
This has been fixed. I think #3395 was the fix.
