### ISSUE TITLE
Integration Tests: TestWorkingDirCreation/tmp fails

### ISSUE THREAD

**Issue by zkoopmans** [google/gvisor#3369]
In //test/e2e:integration_test TestWorkingDirCreation/tmp and TestWorkingDirCreation/tmp-readonly fail.

Steps to reproduce

With docker/runsc installed with "vfs2" flag enabled:
make load-basic-images
bazel test --test_arg='--runtime=RUNTIME' --test_filter=Creation/tmp -- //test/e2e:integration_test

Environment
docker 19.03.5
runsc --vfs2

**Comment by ayushr2** [comment]
Can repro with `docker run --runtime={CLIENT}-vfs2-d -it -w=/tmp/foo/bar ubuntu bash`
