### ISSUE TITLE
Integration Tests: TestTmpMount and TestTmpFile fails in VFS2

### ISSUE THREAD

**Issue by zkoopmans** [google/gvisor#3370]
In //test/e2e:integration_test TestTmpMount and TestTmpFile fail in vfs2.

Steps to reproduce

With docker/runsc installed with "vfs2" flag enabled:
make load-basic-images
bazel test --test_arg='--runtime=RUNTIME' --test_filter=TestTmp -- //test/e2e:integration_test

Environment
docker 19.03.5
runsc --vfs2

**Comment by fvoznika** [comment]
Fixed by 3be26a271cd0fc9618fbcb34e1a2a84c4f234c86
