### ISSUE TITLE
Integration Tests: TestCheckpointRestore fails on vfs2

### ISSUE THREAD

**Issue by zkoopmans** [google/gvisor#3373]
In //test/e2e:integration_test TestCheckpointRestore fail with vfs2.

The test hangs indefinitely and somehow corrupts docker (e.g. docker daemon doesn't respond to 'docker ps' and `sudo service docker restart` hangs after running test). 

Steps to reproduce

With docker/runsc installed with "vfs2" flag enabled:
make load-basic-images
bazel test --test_arg='--runtime=RUNTIME' --test_filter=Checkpoint -- //test/e2e:integration_test

Environment
docker 19.03.5
runsc --vfs2

**Comment by mrahatm** [comment]
Generally, we don't expect this to succeed until SR works in VFS2. 

Specifically, the symptom sounds similar to the deadlock we're observing with syscall S/R tests with VFS2.
