### ISSUE TITLE
New releases not available in storage.googleapis

### ISSUE THREAD

**Issue by danielfoehrKn** [google/gvisor#3381]
**Description**

Hi,
I am consuming `runsc` release binaries like [stated in the documentation](https://gvisor.dev/docs/user_guide/install/#specific-release) from `https://storage.googleapis.com/gvisor/releases/release/${yyyymmdd}`

However, newer binaries for newer releases are not available.
The latest binary available is `20200522.0`.

**Steps to reproduce**

```
curl https://storage.googleapis.com/gvisor/releases/release/20200622.1/runsc
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: gvisor/releases/release/20200622.1/runsc</Details></Error>
```
 
**Environment**

Please include the following details of your environment:

*   `runsc -v`
*   `docker version` or `docker info` (if available)
*   `kubectl version` and `kubectl get nodes` (if using Kubernetes)
*   `uname -a`
*   `git describe` (if built from source)
*   `runsc` debug logs (if available)

**Comment by amscanne** [comment]
There's likely be a hiccup in the CI/CD pipeline. Working on it now. I will see if I can backfill any missing releases.

**Comment by danielfoehrKn** [comment]
Thanks @amscanne

**Comment by danielfoehrKn** [comment]
Are there updates on this topic @amscanne ?

**Comment by amscanne** [comment]
Releases should be publishing again, there's already one from August. The backfill will be a bit annoying (the signing key can only be used by the release job, which only runs off the master branch). If there's a specific need, I can figure it out (just reopen the bug), but assuming having releases published on a ongoing basis solves the problem, I'll close this for now. Thanks for the report!
