### ISSUE TITLE
Invite to gvisor developers at the (HPC) SEA conference 2019

### ISSUE THREAD

**Issue by davidedelvento** [google/gvisor#34]
Folks,

Sorry for reaching out via the issue tracker, that's the best way I can think of on a Friday PM regarding how to reach you. By the way, your project looks really interesting. Feel free to close this issue and contact me by email in reply: https://staff.ucar.edu/users/ddvento

---

You may have heard of [The first containers in HPC Symposium at the SEA conference 2018](https://sea.ucar.edu/conference/2018/containers) which has been a great success. As first event, we limited it to container technology geeks but for the second one in 2019 we will invite application developers (i.e. containers users) also. As a matter of fact, we intended the event to be a one-off, but given to popular demand, there will be a second symposium and it'll be made a staple of our conference.

I have a small survey (about when to have the event) which I will give to you privately if you are interested in participating.

**Comment by fvoznika** [comment]
Thanks for the invitation. You can send the survey to my username @google.com and I'll redirect to the rest of the team.

In the future, please use gvisor-users@googlegroups.com.
