### ISSUE TITLE
May be 'bazel test //...' to run test cases using 'bazel'?

### ISSUE THREAD

**Issue by AngleNet** [google/gvisor#341]
System setup:
 1. Ubuntu 18.04.1 LTS
 2. bazel version: 0.26.1

Reproduce steps:
 1. git clone https://github.com/google/gvisor
 2. install all dependencies
 3. run `bazel test ...` according to the README

Expected outputs:
 1. running test cases

Actual outputs:
 ERROR: Skipping '../..': Bad target pattern '../..': package name component contains only '.' characters
 WARNING: Target pattern parsing failed.
 ERROR: Bad target pattern '../..': package name component contains only '.' characters
 INFO: Elapsed time: 0.158s
 INFO: 0 processes.
 FAILED: Build did NOT complete successfully (0 packages loaded)
 FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by AngleNet** [comment]
When run tests with `bazel test //...`, it goes as expected.

**Comment by amscanne** [comment]
Where does the ../.. come from? Are you literally just typing ‘bazel test ...’ or something else?

**Comment by AngleNet** [comment]
I just type literally `bazel test ...`

**Comment by hugelgupf** [comment]
Some shells replace free-standing "..." with ../.. to allow "cd ..."

All I can think of here.

**Comment by AngleNet** [comment]
Seems like a problem of zsh. Found same issue from tensorflow: https://github.com/tensorflow/models/issues/1464. Closing this.
