### ISSUE TITLE
fsync.go：async  and waiter.go： q    deadlock

### ISSUE THREAD

**Issue by GuhuangLS** [google/gvisor#346]
Hi We find a deadlock. 
one path:Pkg/waiter/waiter.go: Notiry() get the “q.mu.RLock” at 1st, then call “e.Callback.Callback()” which is in pkg/sentry/kernel/fasync/fsync.go to get “a.mu.Lock”;
The other path:fasync.go:Unregister() get the “a.mu.Lock()”, then call “w.EventUnregister” which is in Pkg/waiter/waiter.go to get q.mu.Lock().
When two path are concurrence， deadlock is come up.

The log is:
goroutine one:
```
gvisor.googlesource.com/gvisor/pkg/waiter.(*Queue).EventUnregister(0xc01453c390, 0xc00023ac68)
    pkg/waiter/waiter.go:178 +0x3a
gvisor.googlesource.com/gvisor/pkg/sentry/socket/unix/transport.(*baseEndpoint).EventUnregister(0xc006e64cb0, 0xc00023ac68)
    pkg/sentry/socket/unix/transport/unix.go:744 +0x38
gvisor.googlesource.com/gvisor/pkg/sentry/socket/unix.(*SocketOperations).EventUnregister(0xc0084c2c80, 0xc00023ac68)
    pkg/sentry/socket/unix/unix.go:444 +0x3e
gvisor.googlesource.com/gvisor/pkg/sentry/fs.(*File).EventUnregister(0xc001746e10, 0xc00023ac68)
    pkg/sentry/fs/file.go:209 +0x3e
gvisor.googlesource.com/gvisor/pkg/sentry/kernel/fasync.(*FileAsync).Unregister(0xc00023ac60, 0xffd420, 0xc001746e10)
    pkg/sentry/kernel/fasync/fasync.go:105 +0x80
gvisor.googlesource.com/gvisor/pkg/sentry/fs.(*File).DecRef.func1()
    pkg/sentry/fs/file.go:158 +0x116
```
goroutine two:
```
gvisor.googlesource.com/gvisor/pkg/sentry/kernel/fasync.(*FileAsync).Callback(0xc00023ac60, 0xc00023ac68)
    pkg/sentry/kernel/fasync/fasync.go:49 +0x31
gvisor.googlesource.com/gvisor/pkg/waiter.(*Queue).Notify(0xc01453c390, 0xc000230001)
    pkg/waiter/waiter.go:189 +0x71
gvisor.googlesource.com/gvisor/pkg/sentry/socket/unix/transport.(*connectedEndpoint).CloseNotify(0xc00d537ea0)
    pkg/sentry/socket/unix/transport/unix.go:672 +0x3a
gvisor.googlesource.com/gvisor/pkg/sentry/socket/unix/transport.(*connectionedEndpoint).Close(0xc006e64d20)
    pkg/sentry/socket/unix/transport/connectioned.go:230 +0x199
gvisor.googlesource.com/gvisor/pkg/sentry/socket/unix.(*SocketOperations).DecRef.func1()
    pkg/sentry/socket/unix/unix.go:79 +0x33
gvisor.googlesource.com/gvisor/pkg/refs.(*AtomicRefCount).DecRefWithDestructor(0xc0084c2cd0, 0xc0018dfc90)
    pkg/refs/refcounter.go:295 +0x188
gvisor.googlesource.com/gvisor/pkg/sentry/socket/unix.(*SocketOperations).DecRef(0xc0084c2cd0)
    pkg/sentry/socket/unix/unix.go:78 +0x50
gvisor.googlesource.com/gvisor/pkg/sentry/socket/unix.(*SocketOperations).Release(0xc0084c2cd0)
    pkg/sentry/socket/unix/unix.go:87 +0x2b
gvisor.googlesource.com/gvisor/pkg/sentry/fs.(*File).DecRef.func1()
    pkg/sentry/fs/file.go:147 +0x76
```

We modify it like this, is it ok?
```
--- a/pkg/sentry/kernel/fasync/fasync.go
+++ b/pkg/sentry/kernel/fasync/fasync.go
@@ -35,6 +35,7 @@ func New() fs.FileAsync {
// +stateify savable
type FileAsync struct {
mu sync.Mutex `state:"nosave"`
+ listMu sync.Mutex `state:"nosave"`
e waiter.Entry
requester *auth.Credentials

@@ -80,8 +81,8 @@ func (a *FileAsync) Callback(e *waiter.Entry) {
//
// The file must not be currently registered.
func (a *FileAsync) Register(w waiter.Waitable) {
- a.mu.Lock()
- defer a.mu.Unlock()
+ a.listMu.Lock()
+ defer a.listMu.Unlock()

if a.e.Callback != nil {
panic("registering already registered file")
@@ -95,8 +96,8 @@ func (a *FileAsync) Register(w waiter.Waitable) {
//
// The file must be currently registered.
func (a *FileAsync) Unregister(w waiter.Waitable) {
- a.mu.Lock()
- defer a.mu.Unlock()
+ a.listMu.Lock()
+ defer a.listMu.Unlock()

if a.e.Callback == nil {
panic("unregistering unregistered file")
```

**Comment by AngleNet** [comment]
HI，how to reproduce this？Could you paste it here ？

**Comment by iangudger** [comment]
Correct me if I am wrong, but it appears that you are suggesting adding an additional mutex to protect FileAsync.e. If so, use of the new mutex needs to be added to (*FileAsync).Callback which also uses FileAsync.e. Doing so causes the deadlock to no longer be fixed. As a result, I think this requires a more complicated fix.

Does this reliably reproduce? If so, would it be possible for you to provide a reproducer syscall test or the sequence of syscalls which reproduces the deadlock?

**Comment by GuhuangLS** [comment]
> HI，how to reproduce this？Could you paste it here ？
I ‘m getting the reproduction way;

**Comment by GuhuangLS** [comment]
> Correct me if I am wrong, but it appears that you are suggesting adding an additional mutex to protect FileAsync.e. If so, use of the new mutex needs to be added to (*FileAsync).Callback which also uses FileAsync.e. Doing so causes the deadlock to no longer be fixed. As a result, I think this requires a more complicated fix.
> 
> Does this reliably reproduce? If so, would it be possible for you to provide a reproducer syscall test or the sequence of syscalls which reproduces the deadlock?

Hi   @iangudger
       The share reource is divided two part; 
        One part is register/unregister, use one mutext to protect multipath  register/unregister call;
        The other part is FileAsync resource which contains requester /recipientT, use the other mutex to protect occurence set /callback；
         The callback and reg/unreg use different mutex, and use the same queue mutex(waiter.go), then no deadlock exist;
          Above is my analyzation；

**Comment by iangudger** [comment]
@GuhuangLS, I wasn't arguing that your patch didn't fix the deadlock. As far as I can tell it does fix it. I am just concerned that it introduces a data race on a.e.Callback. Interfaces in Go loose their memory safety with unsynchronized reads and writes.

I have an alternative proposal that I think fixes the issue without introducing any unsafety. I will send out a change soon.

**Comment by GuhuangLS** [comment]
> @GuhuangLS, I wasn't arguing that your patch didn't fix the deadlock. As far as I can tell it does fix it. I am just concerned that it introduces a data race on a.e.Callback. Interfaces in Go lose their memory safety with unsynchronized reads and writes.
> 
> I have an alternative proposal that I think fixes the issue without introducing any unsafety. I will send out a change soon.

@iangudger   
   Got it！ thanks.
   wait for your patch.

**Comment by iangudger** [comment]
@GuhuangLS, can you test #349 with your workload to see if it fixes the problem?

**Comment by GuhuangLS** [comment]
> @GuhuangLS, can you test #349 with your workload to see if it fixes the problem?

@iangudger   Ok;  I'll do it at once;
