### ISSUE TITLE
Docker container w/ runsc doesn't work with host fifos

### ISSUE THREAD

**Issue by ulfjack** [google/gvisor#3501]
**Description**

When I run a docker container w/ runsc, I am unable to access host fifos from within the container, and `ls` shows unknown flags, user and group ids.

**Steps to reproduce**

```
$ cd /tmp
$ mkfifo foobar
$ docker run --runtime=runsc --mount=type=bind,src=/tmp,dst=/tmp -it ubuntu /bin/bash
$ cd /tmp
$ ls -l
ls: cannot access 'foobar': Operation not permitted
-????????? ? ?    ?          ?            ?  foobar
$ cat foobar
cat: foobar: Operation not permitted
```

There are other files owned by the same user / group that do not result in "Operation not permitted".

If I try to only bind-mount the fifo itself, I get even more unusual behavior:
```
$ docker run --runtime=runsc --mount=type=bind,src=/tmp/foobar,dst=/tmp/foobar -it ubuntu /bin/bash
docker: Error response from daemon: OCI runtime start failed: starting container: starting root container: starting sandbox: mount submount "/tmp/foobar": creating mount with source "/tmp/foobar": input/output error: you may be encountering a Linux kernel bug; see https://gvisor.dev/faq#memlock for more details: unknown.
ERRO[0000] error waiting for container: context canceled 
```

**Environment**

```
$ runsc -version
runsc version release-20200522.0
spec: 1.0.1-dev

$ docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Tue Jun 23 22:26:12 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Thu Jun 18 08:26:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        

$ uname -a
Linux hostname 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ianlewis** [comment]
While I think there's a good reason we don't support host fifos we could probably handle them a bit more gracefully.

**Comment by ulfjack** [comment]
Anything I can help with?

**Comment by fvoznika** [comment]
gVisor doesn't allow operations on a fifo sitting on the host to prevent the untrusted application running inside the sandbox to inadvertently access the host. All operations return `EPERM`, including `lstat(2)`. If you could tell us what you're trying to do, we might be able to find an alternative solution.

**Comment by ulfjack** [comment]
I have a workaround, but I wanted to report that the error messages could be better.

We are using a fifo to control container shutdown. Specifically, we want the container to shut down when the controlling process exits. We create a fifo and open it from our main process. If the main process exits, the fifo is closed by the kernel, and that signals the process inside the container to exit as well.

**Comment by fvoznika** [comment]
Good to know you have a workaround. The error codes that we can return are limited and EPERM is the more appropriate error in this case.

**Comment by ulfjack** [comment]
I don't understand why statting the file should return EPERM. It seems fine for processes to know that it exists.
