### ISSUE TITLE
Binary release of containerd-shim-runsc-v1?

### ISSUE THREAD

**Issue by erulabs** [google/gvisor#3665]
**Description**

Hello! The containerd quickstart guide [here](https://gvisor.dev/docs/user_guide/containerd/quick_start/) refers to to the installation guide and mentions requiring `runsc` and `containerd-shim-runsc-v1`. However, the [installation guide](https://gvisor.dev/docs/user_guide/install/)  only mentions binary releases for `runsc`.

Is there any binary release available for download for `containerd-shim-runsc-v1`?  The older codebase https://github.com/google/gvisor-containerd-shim had downloads available, but there doesn't seem to be any releases available at https://storage.googleapis.com/gvisor/releases/master/latest/containerd-shim-runsc-v1 (for example). Looking around at codebases using gvisor makes me think most people are still using the old `google/gvisor-containerd-shim` `0.0.4` release - most likely because of the lack of documentation / release binaries.

**Do you have a specific solution in mind?**

It would be very nice if the release process for `runsc` also built and packaged a binary for `containerd-shim-runsc-v1`!

Is there currently a CI system for releasing `runsc` binaries, or is this done manually?

Thanks very much!

**Comment by ianlewis** [comment]
Currently the apt package includes the shim but it's not included in the point releases that go in GCS. We have a change out to do that that should get merged shortly.

https://github.com/google/gvisor/pull/3580

**Comment by amscanne** [comment]
The releases are all automated via the CI system. The shim binaries should start to appear in the buckets and as part of the apt packages shortly!

**Comment by khs1994** [comment]
@amscanne how to download it, please tell me link

**Comment by danielfoehrKn** [comment]
As far as I can tell, a  shim binary release is not available yet @amscanne ?
I was checking
 - wget https://storage.googleapis.com/gvisor/releases/release/20200818.0/containerd-shim-runsc-v1.linux-amd64
 - wget https://storage.googleapis.com/gvisor/releases/release/20200818.0/shim/v2/containerd-shim-runsc-v1.linux-amd64

Is there a convenient way to browse / query the repository for releases?

**Comment by ianlewis** [comment]
I think this has been fixed so it should get picked up in the next build 🤞

**Comment by khs1994** [comment]
ping @ianlewis how to download, link ?

**Comment by khs1994** [comment]
* https://storage.googleapis.com/gvisor/releases/release/20200914.0/containerd-shim-runsc-v1
* https://storage.googleapis.com/gvisor/releases/release/20200914.0/gvisor-containerd-shim


now can download shim.

**Comment by ianlewis** [comment]
These get uploaded when we do a release and it took a while for one to get out. This should be fixed now.

**Comment by khs1994** [comment]
@danielfoehrKn this repo shim + containerd work ?
