### ISSUE TITLE
runsc will crash after a SIGINT signal

### ISSUE THREAD

**Issue by mangokingTW** [google/gvisor#38]
Hello guys,
I find an interesting behavior of gVisor.
When I ran a docker in ```docker run --runtime=runsc -it ubuntu /bin/bash```,
it crashed by following steps:
```
[root@container gvisor]# docker run --runtime=runsc -it ubuntu /bin/bash
root@313125f6e36d:/# ^C
root@313125f6e36d:/# ls
[root@container gvisor]#
```
This problem is not occurred at anytime but frequently.

OS: CentOS 7
docker version: 18.03.1-ce
kernel version: Linux  4.16.7-1.el7.elrepo.x86_64 x86_64 x86_64 x86_64 GNU/Linux

**Comment by newmanwang** [comment]
Seems like gvisor queued pointer of struct SignalInfo with signo set to SIGSEGV into task's pending signal queue, but value of this SignalInfo was modified concurrently by sentry before delivered to task.  I think gvisor should queue value of struct SignalInfo instead. I am fixing it
