### ISSUE TITLE
conainerD with gvisor not working(failed to connect: dial unix: missing address)

### ISSUE THREAD

**Issue by chiraggupta06** [google/gvisor#3820]
Hi Team,
**I am getting an issue of "FATA[0000] run pod sandbox failed: rpc error: code = Unknown desc = failed to create containerd task: io.containerd.runsc.v1: failed to connect: dial unix: missing address" with  containerD + gvisor.**

creating sandbox:
root@node1:~# crictl runp --runtime runsc sandbox.json
FATA[0000] run pod sandbox failed: rpc error: code = Unknown desc = failed to create containerd task: io.containerd.runsc.v1: failed to connect: dial unix: missing address
: exit status 1: unknown

conatinerD version:
root@node1:~# containerd --version
**containerd containerd.io 1.2.13 7ad184331fa3e55e52b890ea95e65ba581ae3429**

runsc version:
root@node1:~# runsc --version
**runsc version release-20200818.0
spec: 1.0.1-dev**

on this setup(VM based setup): 
**gvisor is working fine with docker**
  root@node1:~# docker run -ti --runtime runc alpine uname -a
  Linux 2ac130e19b4c 4.4.0-186-generic #216-Ubuntu SMP Wed Jul 1 05:34:05 UTC 2020 x86_64 Linux
  root@node1:~#
  root@node1:~# docker run -ti --runtime runsc alpine uname -a
  Linux e466d82ea12d 4.4.0 #1 SMP Sun Jan 10 15:06:54 PST 2016 x86_64 Linux
  root@node1:~# docker run --runtime=runsc -it ubuntu dmesg
  Unable to find image 'ubuntu:latest' locally
  latest: Pulling from library/ubuntu
  54ee1f796a1e: Pull complete
  f7bfea53ad12: Pull complete
  46d371e02073: Pull complete
  b66c17bbf772: Pull complete
  Digest: sha256:31dfb10d52ce76c5ca0aa19d10b3e6424b830729e32a89a7c6eee2cda2be67a5
  Status: Downloaded newer image for ubuntu:latest
  [ 0.000000] Starting gVisor...
  [ 0.571137] Mounting deweydecimalfs...
  [ 0.832009] Synthesizing system calls...
  [ 1.059481] Letting the watchdogs out...
  [ 1.489105] Consulting tar man page...
  [ 1.820284] Searching for socket adapter...
  [ 1.884739] Gathering forks...
  [ 2.009269] Daemonizing children...
  [ 2.260721] Rewriting operating system in Javascript...
  [ 2.623649] Constructing home...
  [ 3.005637] Waiting for children...
  [ 3.243660] Ready!
**conainerd is wokring fine without gvisor**
**conainerD + gvisor --> not working**

I am following https://gvisor.dev/docs/user_guide/containerd/quick_start/

linux version:
root@node1:~# uname -a
Linux node1 4.4.0-186-generic #216-Ubuntu SMP Wed Jul 1 05:34:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

/etc/cni.net.d 
total 16
drwxr-xr-x 2 kube root 4096 Sep  1 06:35 ./
drwxr-xr-x 3 kube root 4096 Aug 27 09:13 ../
-rw-r--r-- 1 root root  250 Sep  1 06:35 10-bridge.conf
-rw-r--r-- 1 root root   66 Sep  1 06:29 99-loopback.conf
root@node1:/etc/cni/net.d#

root@node1:/etc/cni/net.d# cat 10-bridge.conf
{
  "cniVersion": "0.3.1",
  "name": "mynet",
  "type": "bridge",
  "bridge": "cni0",
  "isGateway": true,
  "ipMasq": true,
  "ipam": {
    "type": "host-local",
    "subnet": "10.22.0.0/16",
    "routes": [
      { "dst": "0.0.0.0/0" }
    ]
  }
}
root@node1:/etc/cni/net.d# cat 99-loopback.conf
{
  "cniVersion": "0.3.1",
  "name": "lo",
  "type": "loopback"
}

root@node1:/etc/cni/net.d# cat /etc/crictl.yaml
runtime-endpoint: unix:///run/containerd/containerd.sock

runtime-endpoint: unix:///run/containerd/containerd.sock
root@node1:/etc/cni/net.d# cat /etc/containerd/config.toml
disabled_plugins = ["restart"]
[plugins.linux]
  shim_debug = true
[plugins.cri.containerd.runtimes.runsc]
  runtime_type = "io.containerd.runsc.v1"

**Kubernetes setup(on top of VM):**
root@master1:~# kubectl get nodes
NAME      STATUS   ROLES    AGE     VERSION
master1   Ready    master   4d21h   v1.13.0
node1     Ready    node     4d21h   v1.13.0

Regards,
Chirag Gupta

**Comment by chiraggupta06** [comment]
/var/log/syaslog :
Sep  1 07:03:16 node1 containerd[14696]: time="2020-09-01T07:03:16.052002668Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx1-sandbox,Uid:hdishd83djaidwnduwk28bcsb,Namespace:default,Attempt:1,} failed, error" error="failed to create containerd task: io.containerd.runsc.v1: failed to connect: dial unix: missing address
Sep  1 07:03:16 node1 containerd[14696]: : exit status 1: unknown"
Sep  1 07:03:17 node1 kubelet[3194]: I0901 07:03:17.200275    3194 setters.go:72] Using node IP: "192.168.110.72"
Sep  1 07:03:23 node1 kernel: [2561482.445627] xt_physdev: using --physdev-out in the OUTPUT, FORWARD and POSTROUTING chains for non-bridged traffic is not supported anymore.

**Comment by chiraggupta06** [comment]
Hi @ianlewis Did you get the chance to look into this?

Thanks.

**Comment by krahul29** [comment]
@ianlewis ,
Following the instructions from https://gvisor.dev/docs/user_guide/containerd/quick_start/
 I am trying containerd  run with gvisor , the creation of sandbox is failing for reference providing the logs 

Host Machine details:
`Linux cks-high-2 4.15.0-108-generic #109-Ubuntu SMP Fri Jun 19 11:33:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
`

Containerd version:
containerd containerd.io 1.2.13 7ad184331fa3e55e52b890ea95e65ba581ae3429

runc installed through  apt (https://gvisor.dev/docs/user_guide/install/)
runsc version :
` $runc --version
runc version 1.0.0-rc10
commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
spec: 1.0.1-dev
`

`
$ SANDBOX_ID=$(sudo crictl -D runp --runtime runsc sandbox.json )
`
```
DEBU[0000] RunPodSandboxRequest: &RunPodSandboxRequest{Config:&PodSandboxConfig{Metadata:&PodSandboxMetadata{Name:nginx-sandbox,Uid:hdishd83djaidwnduwk28bcsb,Namespace:default,Attempt:1,},Hostname:,LogDirectory:/tmp,DnsConfig:nil,PortMappings:[],Labels:map[string]string{},Annotations:map[string]string{},Linux:&LinuxPodSandboxConfig{CgroupParent:,SecurityContext:nil,Sysctls:map[string]string{},},},RuntimeHandler:runsc,}
DEBU[0000] RunPodSandboxResponse: nil
FATA[0000] run pod sandbox failed: rpc error: code = Unknown desc = failed to create containerd task: io.containerd.runsc.v1: failed to connect: dial unix: missing address
: exit status 1: unknown
```

**Comment by chiraggupta06** [comment]
Hi @krahul29 . Are you also going to try it with kubernetes?

**Comment by krahul29** [comment]
> Hi @krahul29 . Are you also going to try it with kubernetes?

@chiraggupta06 , am also trying to  run the pods with gvisor  and yet gone to that par .  Trying explore with containerd and gvisor.  Just started 1 day back.  Yep  will implementing in kubernetes too.

**Comment by ianlewis** [comment]
In any case, I think it's a containerd 1.2 issue rather than a gVisor issue. When I figure out what's causing it I'll see if we can provide guidance on how to avoid it in the docs.

**Comment by chiraggupta06** [comment]
Thanks @ianlewis  for looking into this. seems like the issue is with 1.2 so I am also trying to upgrade the containerd to 1.4  to cross verify but somehow i am not able to find the way to upgrade it. Can you help.

**Comment by chiraggupta06** [comment]
@ianlewis i am able to upgrade the version of container to 1.3.6 byb downloading and replacing with existing one.

1. wget https://github.com/containerd/containerd/releases/download/v1.3.6/containerd-1.3.6-linux-amd64.tar.gz

2. root@node1:~# which containerd
/usr/bin/containerd

3.  root@node1:~# containerd --version
containerd github.com/containerd/containerd v1.3.6 be75852b8d7849474a20192f9ed1bf34fdd454f1

also i am able to create sandbox and container and can see gvisor is working with it.
root@node1:~# sudo crictl exec ${CONTAINER_ID} dmesg | grep -i gvisor
[    0.000000] Starting gVisor...


root@node1:~# sudo crictl runp --runtime runsc sandbox.json
c33b7a67a268e2aef21da7e99004cb7df869bca1fe7c54dbfbb4df9da3e230af

now i am trying it with kubernetes and will share the results

**Comment by krahul29** [comment]
@chiraggupta06 , Thanks for help now, able to  and downloaded the version 1.4.0
```
$ containerd --version
containerd github.com/containerd/containerd v1.4.0 09814d48d50816305a8e6c1a4ae3e2bcc4ba725a
```
```
$ sudo crictl exec 50dac3df9432e dmesg
[   0.000000] Starting gVisor...
[   0.226150] Searching for needles in stacks...
[   0.238810] Constructing home...
[   0.250789] Generating random numbers by fair dice roll...
[   0.284196] Feeding the init monster...
[   0.442004] Searching for socket adapter...
[   0.641131] Consulting tar man page...
[   1.028022] Rewriting operating system in Javascript...
[   1.188204] Segmenting fault lines...
[   1.274405] Letting the watchdogs out...
[   1.434840] Creating process schedule...
[   1.448846] Ready!
```
@chiraggupta06 , Thanks a lot, i think the kubernetes main site  docs (https://kubernetes.io/docs/setup/production-environment/container-runtimes/#install-containerd)  the and lack of containerd  documentation raised this incompatible issue.  Thanks for solving it.

**Comment by chiraggupta06** [comment]
Hi @krahul29  Have you tried  it with kubenetes?

@ianlewis  i have tried it with kubernetes and getting below error :

  Warning  FailedCreatePodSandBox  14s (x19 over 4m7s)  kubelet, node1  Failed to create pod sandbox: rpc error: code = Unknown desc = RuntimeHandler "runsc" not supported

**Comment by chiraggupta06** [comment]
root@node1:~# crictl exec ${CONTAINER_ID} dmesg | grep -i gvisor
[    0.000000] Starting gVisor...
root@node1:~# crictl exec ${CONTAINER_ID} dmesg
[    0.000000] Starting gVisor...
[    0.584337] Feeding the init monster...
[    0.951746] Granting licence to kill(2)...
[    1.431145] Reading process obituaries...
[    1.596769] Preparing for the zombie uprising...
[    2.022156] Gathering forks...
[    2.394900] Mounting deweydecimalfs...
[    2.606453] Forking spaghetti code...
[    2.735920] Consulting tar man page...
[    2.992911] Creating cloned children...
[    3.130947] Segmenting fault lines...
[    3.391701] Ready!

**Comment by ianlewis** [comment]
See: https://github.com/google/gvisor-containerd-shim/issues/46
Also: https://github.com/google/gvisor/issues/3277

If you used kubeadm and Docker was installed on that node kubeadm uses Docker rather than containerd. You'll need to update the kubelet flags set my kubeadm in order to have it use containerd.

**Comment by ianlewis** [comment]
I'm going to close this. Feel free to reopen if it's still an issue.

**Comment by krahul29** [comment]
> @ianlewis i am able to upgrade the version of container to 1.3.6 byb downloading and replacing with existing one.
> 
> 1. wget https://github.com/containerd/containerd/releases/download/v1.3.6/containerd-1.3.6-linux-amd64.tar.gz
> 2. root@node1:~# which containerd
>    /usr/bin/containerd
> 3. root@node1:~# containerd --version
>    containerd github.com/containerd/containerd v1.3.6 be75852b8d7849474a20192f9ed1bf34fdd454f1
> 
> also i am able to create sandbox and container and can see gvisor is working with it.
> root@node1:~# sudo crictl exec ${CONTAINER_ID} dmesg | grep -i gvisor
> [ 0.000000] Starting gVisor...
> 
> root@node1:~# sudo crictl runp --runtime runsc sandbox.json
> c33b7a67a268e2aef21da7e99004cb7df869bca1fe7c54dbfbb4df9da3e230af
> 
> now i am trying it with kubernetes and will share the results

Hi @chiraggupta06 , Yep implemented in kubernetes too and working as expected.

**Comment by chiraggupta06** [comment]
Great @krahul29 !! can you share the steps as i am facing the issues with kuberntes. i am trying it with kubeadm and at the time of pod creation, it is giving me an error of unknown run time

**Comment by krahul29** [comment]
@chiraggupta06 , Followed the steps.

1. Install the containerd in the system
2. Install the kubeadm. kubectl and rest
3. Create an file for kubelet service configured with containerd ,  step is provided in link  as `step -4` (https://github.com/containerd/cri/blob/master/docs/installation.md)
4. Kubeadm init
5. `gvisor ` installed from the gvisor site  https://gvisor.dev/docs/user_guide/containerd/quick_start/

The configuration for the containerd to use runtime is same as in above link
 
https://github.com/containerd/cri/tree/master/contrib/ansible
https://github.com/containerd/cri/blob/master/docs/installation.md
