### ISSUE TITLE
FUSE leads to sentry panic for customized errors

### ISSUE THREAD

**Issue by jinmouil** [google/gvisor#3891]
There are several places in the FUSE code that may return customized errors, such as: https://github.com/google/gvisor/blob/1ab097b08fc16d67b90f094a4316883c289ef77f/pkg/sentry/fsimpl/fuse/connection.go#L336

Ideally an errorno that has the same behavior of existing Linux implementation should be used. A failed syscall should not crash the whole sentry.

**Comment by ayushr2** [comment]
I believe this is now fixed? See https://github.com/search?q=repo%3Agoogle%2Fgvisor+path%3A%2F%5Epkg%5C%2Fsentry%5C%2Ffsimpl%5C%2Ffuse%5C%2F%2F+%22fmt.Errorf%28%22&type=code.
