### ISSUE TITLE
Cannot install specific apt release

### ISSUE THREAD

**Issue by krahul29** [google/gvisor#3899]
Trying to install a specific release through `apt` 
Adding repo is failing 
sudo add-apt-repository "deb https://storage.googleapis.com/gvisor/releases 20200818 main"

Error : 404 not found  release 

Unable to install a specific release
doc: https://gvisor.dev/docs/user_guide/install/
Thanks

**Comment by ianlewis** [comment]
Thanks for the report. It looks like those date based releases aren't getting created. In the mean time you can install the nightly distribution and install the specific version there.

```
$ sudo add-apt-repository "deb https://storage.googleapis.com/gvisor/releases nightly main"
...

$ apt list -a runsc
Listing... Done
runsc/nightly,now 20200818.0-141-gf3172c3a11dd amd64 [installed]

$ apt install runsc=20200818.0-141-gf3172c3a11dd
...
```

**Comment by krahul29** [comment]
@ianlewis  Thanks for response.. i have followed  directly  downloaded  links at the end of this page. Please also include the containerd-shim-runsc-v1  link also in link https://gvisor.dev/docs/user_guide/install/.

**Comment by ianlewis** [comment]
Yeah, the shim isn't being uploaded there and is a separate issue #3665 😞
