### ISSUE TITLE
Feature request: runsc --version

### ISSUE THREAD

**Issue by chanwit** [google/gvisor#39]
Need a kind of version number, probably in the form of git commit.
This would be great when reporting bugs back to the project.

**Comment by chanwit** [comment]
@hugelgupf @fvoznika I'm about to submit patch to Gerrit. Am I allowed to do so? Already registered there by username at gmail dot com.

**Comment by chanwit** [comment]
CLA is signed.

**Comment by hugelgupf** [comment]
Go for it.

**Comment by chanwit** [comment]
@hugelgupf never mind. Done by tweaking `.git/config`.

Here's the changes:
https://gvisor-review.googlesource.com/c/gvisor/+/2020

**Comment by nlacasse** [comment]
The git revision is now displayed in the debug block at the beginning of the output.
