### ISSUE TITLE
Maybe Add support for a local routing table similar to Linux.

### ISSUE THREAD

**Issue by hbhasker** [google/gvisor#3911]
While investigating https://github.com/google/gvisor/issues/3876#issuecomment-691084094 we realized that linux has a local routing table that alters what IP's can be bound. We don't have the equivalent in gVisor. For example in linux the following works

ip route add local 192.0.2.0/24 dev <nic>

ping 192.0.2.1 
...

This for example does not add the address to NIC but installs a route in the local routing table. One of the implications of this is that it allows the IP to be bound. eg After the ip route above one can do

nc -l 192.0.2.1 8080 

and connect to it on the same host using for example

telnet 192.0.2.1 8080

In case of bind for example it skips the address check if the IP is in the local routing table.

https://github.com/torvalds/linux/blob/47ec5303d73ea344e84f46660fff693c57641386/net/ipv4/af_inet.c#L483 &

https://github.com/torvalds/linux/blob/47ec5303d73ea344e84f46660fff693c57641386/net/ipv4/af_inet.c#L493

In Netstack we had the AddAddressRange to a nic which sort of worked in the same way except the IP's were added to the nic explicitly. Which means if one was to do ifconfig those IPs will show up as assigned to the specific nic in gVisor but not in linux.

Maybe to keep compat with linux we should add support for a local routing table.

The routing table in gVisor is also rather simple in the sense we don't really have multiple tables there is just the main routing table and we don't have the equivalent of a local routing table at all.

**Comment by hbhasker** [comment]
NOTE:Another thing about the linux local routing table is that it relies on that to decide what IP's are accepted locally. This is different from gVisor where we sort of have checks in ipv4/v6 code to explicitly decide if we an address is a IP broadcast/multicast address for a given IP subnet etc.'

eg for loopback
ip route show table local |grep 127.
broadcast 127.0.0.0 dev lo proto kernel scope link src 127.0.0.1 
local 127.0.0.0/8 dev lo proto kernel scope host src 127.0.0.1 
local 127.0.0.1 dev lo proto kernel scope host src 127.0.0.1 
broadcast 127.255.255.255 dev lo proto kernel scope link src 127.0.0.1 

These rules are added by linux automatically when the loopback device is brought up. The node-local table is usually maintained directly by the kernel and outside of explicitly adding multiple IPs that we want to be accepted locallly etc this table is usually not manipulated by users.

Similarly the following installs broadcast routes as well as shown below.

 sudo ip addr add  192.0.2.0/24 brd + dev lo

 ip route show table local | grep 192.0.
local 192.0.2.0 dev lo proto kernel scope host src 192.0.2.0 
broadcast 192.0.2.0 dev lo proto kernel scope link src 192.0.2.0 
local 192.0.2.0/24 dev lo proto kernel scope host src 192.0.2.0 
broadcast 192.0.2.255 dev lo proto kernel scope link src 192.0.2.0

**Comment by hbhasker** [comment]
Reference to original commints

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4465b469008bc03b98a1b8df4e9ae501b6c69d4b

&
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ab79ad14a2d51e95f0ac3cef7cd116a57089ba82

**Comment by ghanan94** [comment]
cc: @ghanan94
