### ISSUE TITLE
stack.FindNetworkEndpoint incorrectly accesses nic.mu.endpoints without locking nic.mu

### ISSUE THREAD

**Issue by hbhasker** [google/gvisor#3916]
See: https://github.com/google/gvisor/blob/d35f07b36a40ee94b3a5b588a5fa62572753c620/pkg/tcpip/stack/stack.go#L2030

Further we could probably simplify the function now as each NIC only has 1 network endpoint for each kind (v4/v6) and not 1 per address assigned to the NIC.

**Comment by ghanan94** [comment]
Obsolete as of #3788
