### ISSUE TITLE
Support removing an address via netlink

### ISSUE THREAD

**Issue by ghanan94** [google/gvisor#3921]
Adding an address is supported but removing is not yet supported. 

https://github.com/google/gvisor/blob/665b614e4a6e715bac25bea15c5c29184016e549/pkg/sentry/socket/netlink/route/protocol.go#L486

Related: Issue #578

**Comment by ianlewis** [comment]
This was fixed in https://github.com/google/gvisor/commit/59e2c9f16a9a4cce2ecf8b6449a47316fdf76ca2
