### ISSUE TITLE
sniffer should handle IPv6 extension headers

### ISSUE THREAD

**Issue by tamird** [google/gvisor#3930]
With the sniffer enabled, I see logs like:

```
recv fe80::447f:e5ff:fe4f:fa92 -> ff02::16 unknown transport protocol: 0
```
a bit of searching finds the destination adress is `header.IPv6AllRoutersMulticastAddress` which is used in `(*stack.ndpState).startSolicitingRouters`.

We should figure out why the sniffer can't parse this packet (hopefully we're not crafting it incorrectly).

**Comment by ghanan94** [comment]
The all routers multicast address is `ff02::2`; `ff02:16` is the All MLDv2 routers multicast address. See `Link-Local Scope Multicast Addresses` at https://www.iana.org/assignments/ipv6-multicast-addresses/ipv6-multicast-addresses.xhtml, or https://tools.ietf.org/html/rfc3810#section-11

The IPv6 fixed header's Next Header field will have a value of `0` when the first extension header is the Hop-By-Hop extension header.

I see thee same logs while running fuchsia with packet logging on qemu. Using wireshark I can confirm that the packet below is in fact an MLD packet with a Hop-By-Hop extension header with the Router Alert option (see https://tools.ietf.org/html/rfc3810#section-5 which requires this): 
```
Internet Protocol Version 6, Src: fe80::d030:6eff:fe41:737, Dst: ff02::16
    0110 .... = Version: 6
    .... 0000 0000 .... .... .... .... .... = Traffic Class: 0x00 (DSCP: CS0, ECN: Not-ECT)
        .... 0000 00.. .... .... .... .... .... = Differentiated Services Codepoint: Default (0)
        .... .... ..00 .... .... .... .... .... = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    .... .... .... 0000 0000 0000 0000 0000 = Flow Label: 0x00000
    Payload Length: 36
    **Next Header: IPv6 Hop-by-Hop Option (0)**
    Hop Limit: 1
    Source: fe80::d030:6eff:fe41:737
    Destination: ff02::16
    **IPv6 Hop-by-Hop Option**
        Next Header: ICMPv6 (58)
        Length: 0
        [Length: 8 bytes]
        **Router Alert**
            Type: Router Alert (0x05)
            Length: 2
            Router Alert: MLD (0)
        PadN
            Type: PadN (0x01)
            Length: 0
            PadN: <none>
Internet Control Message Protocol v6
    **Type: Multicast Listener Report Message v2 (143)**
    Code: 0
    Checksum: 0x2b67 [correct]
    [Checksum Status: Good]
    Reserved: 0000
    Number of Multicast Address Records: 1
    Multicast Address Record Changed to include: ff02::fb
        Record Type: Changed to include (3)
        Aux Data Len: 0
        Number of Sources: 0
        Multicast Address: ff02::fb
```

Also this is a received packet (probably from some other device on the network that _does_ implement MLD). We need to update the sniffer to either:
1) report extension headers or,
2) skip the extension headers and report the transport later header.
