### ISSUE TITLE
gVisor Networking

### ISSUE THREAD

**Issue by Anjali05** [google/gvisor#400]
I am bench marking the network bandwidth of gVisor lately. I was using the host networking for one of the tests, my host has a 10Gbps ethernet link. When I run a single container with host networking I get bandwidth of around 3.5-4 Gbps. I was expecting it to be equal to the host or runsc(which is also equal to the host). Is this what is expected? If so, why?

**Comment by hbhasker** [comment]
Could you explain the setup a bit more, also which gVisor platform are you using KVM or ptrace? Also did you mean runc is equal to the host or runsc w/ sandbox network?

**Comment by Anjali05** [comment]
@hbhasker I am using runsc in kvm mode and I have enabled network pass through with --network=host in the daemon.json file in docker. For runc with a single container running on the host I get around 7.5-8Gbps and with runsc+kvm I get around 4 Gbps. Although when I increase the number of containers the aggragate bandwidth for all the instances increase but I was expecting a single container with runsc+kvm to be atleast equal to runc/host.

**Comment by amscanne** [comment]
How are you measuring? iperf?

The limiting factor here may be the kernel<->user transitions. The fact that runc (natively) can't hit 10Gbps supports this. The host transition for --network=host is expensive and may be the limiting factor here. I'd be very curious what you can push with --network=sandbox and GSO enabled.

**Comment by Anjali05** [comment]
@amscanne Yes, I am using iperf3. With runc I am able to get 10Gbps aggregate when I increase the number of instances or sometimes even around 9Gbps for a single instance. What is the --network=sandbox mode? Isn't this the default one without network passthrough? Is there any monitoring tool that can be used to find whats the bottleneck here?

**Comment by amscanne** [comment]
Are you not able to get a higher aggregate with runsc?

Yes, the --network=sandbox mode is the default without passthrough. I'm curious how much worse it performs in this scenario with the passthrough mode.

The best way to see bottlenecks would be to run perf. If you use "perf record -e cycles --call-graph fp" then you should be able to see where time is going with "perf report" or even generate a flame graph [1].

[1] https://github.com/brendangregg/FlameGraph

**Comment by Anjali05** [comment]
@amscanne The aggregate increases but for a single instance shouldn't this be about the same as runc and not so low?

**Comment by amscanne** [comment]
If the network is the bottleneck, then you would expect it to be the same as runc (e.g. if you were saturating the link). If there's some other bottleneck (e.g. how fast the sandbox traps into host mode), then that would be the limiting factor. Even the runc, the network does not appear to be the bottleneck.

**Comment by Anjali05** [comment]
@hbhasker @amscanne Whats a good way to debug the gvisor networking code. I have been using delve but I find it not very useful for networking. Is there any packet tracer/profilers you guys use for networking.

**Comment by ianlewis** [comment]
Hi, since this issue is old and it's a question I'm going to close it. If you are still having issues or want to learn more, I encourage you to reach out on our gitter channel: https://gitter.im/gvisor/community
