### ISSUE TITLE
Arm64 kvm: initial support for ffmpeg related tests on Ampere Altra Server (arm64 neoverse-n1)

### ISSUE THREAD

**Issue by lubinszARM** [google/gvisor#4056]
Ampere hopes to be able to run the ffmpeg program on N1 kvm,
I record this feature requirement here.

 * [x]   docker run --runtime=runsc-kvm --rm hello-world
 * [x]   debug method:  dieTrampoline 
 * [x]   TX2: docker run --runtime=runsc-kvm --rm -it   -v $(pwd):/config   linuxserver/ffmpeg   -i /config/vp92-2-20-10bit-yuv420.webm   /config/output.webm
 * [x]   Ampere/Altra: docker run --runtime=runsc-kvm --rm -it   -v $(pwd):/config   linuxserver/ffmpeg   -i /config/vp92-2-20-10bit-yuv420.webm   /config/output.webm
 * [x]   Deliver patches to upstream
 * [x]   benchmarks testing:
           make sudo TARGETS=//test/benchmarks/media:media_test ARGS="--runtime=myrunsc -test.v -test.bench=."

**Comment by lubinszARM** [comment]
@adamliyi

**Comment by adamliyi** [comment]
@akhare-ampere , Hi Arjun, the ffmpeg enabling is tracked in this issue.

**Comment by lubinszARM** [comment]
root@entos-thunderx2-04:/go/src/github.com/FFmpeg/FFmpeg/ffmpeg-samples/vp9-test-vectors# uname -m
aarch64

**Comment by lubinszARM** [comment]
root@entos-thunderx2-04:/go/src/github.com/FFmpeg/FFmpeg/ffmpeg-samples/vp9-test-vectors# !dock
docker run --runtime=runsc-kvm --rm -it   -v $(pwd):/config   linuxserver/ffmpeg   -i /config/vp92-2-20-10bit-yuv420.webm   /config/output.webm
ffmpeg version 4.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-ffprobe --enable-avresample --enable-gpl --enable-libaom --enable-libass --enable-libfdk_aac --enable-libfreetype --enable-libkvazaar --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libxml2 --enable-libx264 --enable-libx265 --enable-libxvid --enable-nonfree --enable-openssl --enable-small --enable-stripping --enable-version3
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, matroska,webm, from '/config/vp92-2-20-10bit-yuv420.webm':
  Metadata:
    encoder         : libwebm-0.2.1.0
  Duration: 00:00:00.18, start: 0.000000, bitrate: 564 kb/s
    Stream #0:0(eng): Video: vp9, yuv420p10le(tv), 160x90, SAR 1:1 DAR 16:9, 50 fps, 50 tbr, 1k tbn, 1k tbc (default)
Stream mapping:
  Stream #0:0 -> #0:0 (vp9 (native) -> vp9 (libvpx-vp9))
Press [q] to stop, [?] for help
[libvpx-vp9 @ 0xd6e87b222a80] v1.8.2  0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A
[libvpx-vp9 @ 0xd6e87b222a80] Neither bitrate nor constrained quality specified, using default CRF of 32
Output #0, webm, to '/config/output.webm':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0(eng): Video: vp9 (libvpx-vp9), yuv420p10le,

**Comment by lubinszARM** [comment]
cc @avagin

**Comment by lubinszARM** [comment]
[root@land-am1p-2 sample]# !time
time docker run --runtime=runsc-kvm --rm -it -v $(pwd):/config linuxserver/ffmpeg -i /config/vp92-2-20-10bit-yuv420.webm /config/output.webm


real    0m3.351s
user    0m0.034s
sys     0m0.011s

**Comment by lubinszARM** [comment]
Relates issue: https://github.com/google/gvisor/issues/63

**Comment by lubinszARM** [comment]
[bblu@land-am1p-2 gvisor]$ make sudo TARGETS=//test/benchmarks/media:media_test ARGS="--runtime=myrunsc -test.v -test.bench=."
Loading:
Loading: 0 packages loaded
DEBUG: /home/bblu/.cache/bazel/_bazel_bblu/7f60106c8acb4aa08e55fa787d63d8f5/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /home/bblu/.cache/bazel/_bazel_bblu/7f60106c8acb4aa08e55fa787d63d8f5/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: rbe_default not using checked in configs; Bazel version 3.4.1 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"], "1.0.0": ["9.0.0", "10.0.0"], "1.0.1": ["10.0.0"], "1.1.0": ["10.0.0"], "1.2.0": ["10.0.0"], "1.2.1": ["10.0.0"], "2.0.0": ["10.0.0"], "2.1.0": ["10.0.0"], "2.1.1": ["10.0.0", "11.0.0"], "2.2.0": ["11.0.0"], "3.0.0": ["11.0.0"]}
Analyzing: target //test/benchmarks/media:media_test (0 packages loaded, 0 targets configured)
WARNING: /home/bblu/.cache/bazel/_bazel_bblu/7f60106c8acb4aa08e55fa787d63d8f5/external/remote_java_tools_linux/BUILD:671:11: in hdrs attribute of cc_library rule @remote_java_tools_linux//:combiners: Artifact 'external/remote_java_tools_linux/java_tools/src/tools/singlejar/zip_headers.h' is duplicated (through '@remote_java_tools_linux//:transient_bytes' and '@remote_java_tools_linux//:zip_headers'). Since this rule was created by the macro 'cc_library', the error might have been caused by the macro implementation
INFO: Analyzed target //test/benchmarks/media:media_test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //test/benchmarks/media:media_test up-to-date:
  bazel-bin/test/benchmarks/media/linux_arm64_stripped/media_test
INFO: Elapsed time: 0.498s, Critical Path: 0.10s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
goos: linux
goarch: arm64
BenchmarkFfmpeg
BenchmarkFfmpeg-8              1        5426416494 ns/op
PASS

**Comment by lubinszARM** [comment]
Hi @adamliyi @akhare-ampere 

Can we close this issue?
I think we can now do some basic tests on neoverse-n1 for ffmpeg testing.

Let's move forward, and aggregate all bugs into an enhancement issue for Ampere Altra.

Thanks.

**Comment by lubinszARM** [comment]
cc @ianlewis
