### ISSUE TITLE
The nightly build binaries contain commit IDs that do not exist on Github

### ISSUE THREAD

**Issue by chanwit** [google/gvisor#44]
As far as I understand, they are 2 different git trees.
The first one is on Github, `github.com/google/gvisor`. Another one is on Google Source, where Gerrit is located. Both trees are public, have the same sequence of commits, but different commit IDs.

Nightly build binaries seem to build from Google Source's tree, not from Github. To me, I don't have problem with this, as I know where it find it. But I'm not sure if it might confuse other users, when they might be trying to find a commit that does not exist on Github.

What do you think about this?

**Comment by nlacasse** [comment]
Yes, that is something we need to change, and will require a force-push to the GitHub repo.

The googlesource repo is the authoritative open-source gVisor repo.  Code submissions must go through there, and the nightly releases are built from there.  The GitHub repo is intended to be a mirror, and the commit hashes should ideally line up, but something is not right with the current mirror setup.

**Comment by nlacasse** [comment]
I found the source of the divergence and did a force-push to the GitHub repo.  The commit IDs are aligned now, and should remain aligned moving forward.

**Comment by chanwit** [comment]
Cheers!

**Comment by nlacasse** [comment]
Github and Googlesource diverged again here:

https://gvisor.googlesource.com/gvisor/+/17a0fa3af05dbb147cdd3d5ec898d31812a0ea66
https://github.com/google/gvisor/commit/3cc81871e44b50ac771c36f144ee4b9e8dabfb61

Looks like the "Change-Id" line was removed from the github commit message.  Need to figure out why that happened.

**Comment by nlacasse** [comment]
This should be fixed now.
