### ISSUE TITLE
For incoming TCP segments, hold the packet buffer

### ISSUE THREAD

**Issue by ghananigans** [google/gvisor#4417]
Currently, TCP segments hold a vectorised view and some other link/network layer information as distinct members.

All of these will be available in the packet buffer so the segment should just hold a packet buffer instead of these members which are obtained from the packet buffer.

**Comment by ghanan94** [comment]
cc: @hbhasker

**Comment by hbhasker** [comment]
That is the plan with the buffer cleanup worked being done. It's not just TCP we should be doing this for UDP as well. But this is not a short term goal and will take time to materialize. I will dedupe this against the issue tracking  buffer work.
