### ISSUE TITLE
Task.MountNamespaceVFS2() and MountNamespace.Root() should not take a reference

### ISSUE THREAD

**Issue by dean-deng** [google/gvisor#4438]
Not every use of these functions needs a reference, so we end up taking one just to drop it again. This is also quite error-prone, since it is not obvious that a reference is acquired. There are multiple reference leaks (e.g. github.com/google/gvisor/pull/4432) because we forgot to call DecRef.

**Comment by manninglucas** [comment]
We haven't had issues with MountNamespace taking a reference recently. IMO acquiring a reference is the correct behavior when operating on a ref counted object. Closing.
