### ISSUE TITLE
Deduplicate TCP state data structures

### ISSUE THREAD

**Issue by ghanan94** [google/gvisor#4466]
The TCP endpoint seems to duplicate a lot of members and structures that are available in already exposed structures.

For example, `TCPEndpointState` https://github.com/google/gvisor/blob/6768e6c59ec252854a1633e184b69dc5723ac3f3/pkg/tcpip/stack/stack.go#L282 seems to duplicate a lot of fields present in `tcp.endpoint` https://github.com/google/gvisor/blob/6768e6c59ec252854a1633e184b69dc5723ac3f3/pkg/tcpip/transport/tcp/endpoint.go#L363

This is made clear when the tcp endpoint dumps its state to the exposed structures @ `tcp.(*endpoint).completeState` https://github.com/google/gvisor/blob/6768e6c59ec252854a1633e184b69dc5723ac3f3/pkg/tcpip/transport/tcp/endpoint.go#L2916

Instead of duplicating this state, we should embed the exposed types in `tcp.endpoint`. This will also make `tcp.(*endpoint).completeState` the implementation for pretty trivial.

**Comment by hbhasker** [comment]
This was done intentionally. We don't want the internal state members of TCP endpoints being exported outside the package. The complete state is meant for probing and uses all public members so that they can be serialized etc.

**Comment by ghanan94** [comment]
they won't be exported though. Internally they will still be stored as a private member and that way we can just return the member by value
