### ISSUE TITLE
Use Neighbor Cache in GetLinkAddress when available

### ISSUE THREAD

**Issue by puradox** [google/gvisor#4529]
A recent change to how routes operate (#4508) requires GetLinkAddress to be able to work with the neighbor cache (#2234). This involves adding logic to use the neighbor cache within GetLinkAddress if it is available and if `UseNeighborCache` is set to `true`.

**Comment by ghanan94** [comment]
Fixed by 2814a032be7b34e4cc0c0607dba8030e74e11208
