### ISSUE TITLE
Latest version of shim hang when using with containerd

### ISSUE THREAD

**Issue by dqminh** [google/gvisor#4544]
**Description**

When using latest version of shim from source with containerd, the container can't be started. It seems to hang when creating the task. This works with older version of shim from https://github.com/google/gvisor-containerd-shim/pull/28

**Steps to reproduce**

1. Run containerd
2. Install containerd-shim-runsc-v1 from gvisor
3. Run the following
```
ctr image pull docker.io/library/debian:latest
ctr run --rm --runtime io.containerd.runsc.v1 docker.io/library/debian:latest demo echo CLOUD
```
expects to see status code = 0, and `CLOUD` output

**Environment**

Please include the following details of your environment:
 ```
runsc version release-20200928.0-105-g51913ba400cc
spec: 1.0.1-dev
```
```
containerd github.com/containerd/containerd v1.4.0-42-gefa0e809 efa0e809135e440995c6e92ca21b3545659d906b
```

**Comment by ianlewis** [comment]
Hmm, we haven't tested using ctr with the --runtime flag. I can reproduce it and had some odd initial observations.

It seems to run the right shim and the shim executes runsc but even though I set up the runtime ConfigPath and options in runsc.toml...
```
ianlewis@gvisor-containerd:~$ cat /etc/containerd/
config.toml  runsc.toml   
ianlewis@gvisor-containerd:~$ cat /etc/containerd/config.toml 
disabled_plugins = ["restart"]
[plugins.linux]
  shim_debug = true
[plugins.cri.containerd.runtimes.runsc]
  runtime_type = "io.containerd.runsc.v1"
[plugins.cri.containerd.runtimes.runsc.options]
  TypeUrl = "io.containerd.runsc.v1.options"
  ConfigPath = "/etc/containerd/runsc.toml"
```
```
ianlewis@gvisor-containerd:~$ cat /etc/containerd/runsc.toml 
[runsc_config]
debug = "true"
debug-log = "/var/log/runsc/%ID%/runsc.%TIMESTAMP%.%COMMAND%.log"
```

... the config doesn't seem to be used. I don't get flags on runsc that enable debug logging.
```
ianlewis@gvisor-containerd:~$ ps aux | grep runsc
root      3714  0.0  0.1  51420  3856 pts/0    S+   04:34   0:00 sudo ctr run --rm --runtime io.containerd.runsc.v1 docker.io/library/debian:latest demo echo CLOUD
root      3715  0.0  0.6 267220 24616 pts/0    Sl+  04:34   0:00 ctr run --rm --runtime io.containerd.runsc.v1 docker.io/library/debian:latest demo echo CLOUD
root      3729  0.0  0.3 1320068 13936 ?       Sl   04:34   0:00 /usr/bin/containerd-shim-runsc-v1 -namespace default -address /run/containerd/containerd.sock -publish-binary /bin/containerd
root      3746  0.0  0.4 727220 16972 ?        Sl   04:34   0:00 runsc-gofer --root=/run/containerd/runsc/default --log=/run/containerd/io.containerd.runtime.v2.task/default/demo/log.json --log-format=json --log-fd=3 gofer --bundle /run/containerd/io.containerd.runtime.v2.task/default/demo --spec-fd=4 --mounts-fd=5 --io-fds=6 --apply-caps=false --setup-root=false
nobody    3747  0.0  0.4 1775804 17920 ?       Ssl  04:34   0:00 runsc-sandbox --root=/run/containerd/runsc/default --log=/run/containerd/io.containerd.runtime.v2.task/default/demo/log.json --log-format=json --log-fd=3 boot --bundle=/run/containerd/io.containerd.runtime.v2.task/default/demo --controller-fd=4 --mounts-fd=5 --spec-fd=6 --start-sync-fd=7 --io-fds=8 --stdio-fds=9 --stdio-fds=10 --stdio-fds=11 --cpu-num 1 demo
ianlewis  3897  0.0  0.0  12944   936 pts/1    S+   04:40   0:00 grep --color=auto runsc
```

Everything works as expected if [using crictl](https://gvisor.dev/docs/user_guide/containerd/quick_start/) so I suspect there is some difference with how the shim is invoked when using ctr.

**Comment by ianlewis** [comment]
Another observation is that runsc doesn't exit when the container is deleted via crt.

The initial `ctr run` command hangs as initially reported. So I kill it and remove the container via `ctr`...
```
ianlewis@gvisor-containerd:~$ sudo ctr run --rm --runtime io.containerd.runsc.v1 docker.io/library/debian:latest demo echo CLOUD
^C
ianlewis@gvisor-containerd:~$ sudo ctr containers rm demo
```

... and the shim exits but the runsc process isn't cleaned up.

```
ianlewis@gvisor-containerd:~$ ps aux | grep runsc
root      3746  0.0  0.4 727220 16972 ?        Sl   04:34   0:00 runsc-gofer --root=/run/containerd/runsc/default --log=/run/containerd/io.containerd.runtime.v2.task/default/demo/log.json --log-format=json --log-fd=3 gofer --bundle /run/containerd/io.containerd.runtime.v2.task/default/demo --spec-fd=4 --mounts-fd=5 --io-fds=6 --apply-caps=false --setup-root=false
nobody    3747  0.0  0.4 1775804 17920 ?       Ssl  04:34   0:00 runsc-sandbox --root=/run/containerd/runsc/default --log=/run/containerd/io.containerd.runtime.v2.task/default/demo/log.json --log-format=json --log-fd=3 boot --bundle=/run/containerd/io.containerd.runtime.v2.task/default/demo --controller-fd=4 --mounts-fd=5 --spec-fd=6 --start-sync-fd=7 --io-fds=8 --stdio-fds=9 --stdio-fds=10 --stdio-fds=11 --cpu-num 1 demo
ianlewis  3954  0.0  0.0  12944   924 pts/1    S+   04:44   0:00 grep --color=auto runsc
```

**Comment by ianlewis** [comment]
After some debugging it seems that the Create call on container creation never returns.
https://github.com/google/gvisor/blob/master/pkg/shim/v2/service.go#L344

runsc's debug logs show that the watchdog doesn't get started

```
W1028 06:55:43.109496    7630 log.go:338] Watchdog.Start() not called within 30s:
goroutine 10 [running]:
gvisor.dev/gvisor/pkg/log.Stacks(0xc000086e01, 0x48eb4a, 0xbfde635bc684780f, 0xc000086e30)
	pkg/log/log.go:314 +0xa5
gvisor.dev/gvisor/pkg/log.TracebackAll(0xc000274180, 0x26, 0x0, 0x0, 0x0)
	pkg/log/log.go:337 +0x2a
gvisor.dev/gvisor/pkg/sentry/watchdog.(*Watchdog).doAction(0xc000220280, 0x0, 0x0, 0xc000086f90)
	pkg/sentry/watchdog/watchdog.go:367 +0xdf
gvisor.dev/gvisor/pkg/sentry/watchdog.(*Watchdog).waitForStart(0xc000220280)
	pkg/sentry/watchdog/watchdog.go:249 +0x1ab
created by gvisor.dev/gvisor/pkg/sentry/watchdog.New
	pkg/sentry/watchdog/watchdog.go:189 +0x1ba

goroutine 1 [chan receive]:
gvisor.dev/gvisor/runsc/boot.(*Loader).WaitForStartSignal(...)
	runsc/boot/loader.go:1033
gvisor.dev/gvisor/runsc/cmd.(*Boot).Execute(0xc0000bb8c0, 0x13c8e80, 0xc000046008, 0xc0001c2840, 0xc0001c8f80, 0x2, 0x2, 0x0)
	runsc/cmd/boot.go:252 +0x723
github.com/google/subcommands.(*Commander).Execute(0xc000098000, 0x13c8e80, 0xc000046008, 0xc0001c8f80, 0x2, 0x2, 0x0)
	external/com_github_google_subcommands/subcommands.go:200 +0x2f9
github.com/google/subcommands.Execute(...)
	external/com_github_google_subcommands/subcommands.go:481
gvisor.dev/gvisor/runsc/cli.Main(0x13ab140, 0x23)
	runsc/cli/main.go:230 +0x13d2
main.main()
	runsc/main.go:23 +0x39

goroutine 6 [chan receive, locked to thread]:
gvisor.dev/gvisor/pkg/sentry/platform/ptrace.newSubprocess.func1(0x120b550, 0xc00007ad20, 0xc00007ad80)
	pkg/sentry/platform/ptrace/subprocess.go:176 +0x18f
created by gvisor.dev/gvisor/pkg/sentry/platform/ptrace.newSubprocess
	pkg/sentry/platform/ptrace/subprocess.go:160 +0x13b

goroutine 7 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	GOROOT/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc00020fb30, 0x0)
	GOROOT/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc00020fb20)
	GOROOT/src/sync/cond.go:56 +0x9d
gvisor.dev/gvisor/pkg/sentry/pgalloc.(*MemoryFile).findReclaimable(0xc00020f500, 0x0, 0x0, 0xc00004e700)
	pkg/sentry/pgalloc/pgalloc.go:1117 +0x86
gvisor.dev/gvisor/pkg/sentry/pgalloc.(*MemoryFile).runReclaim(0xc00020f500)
	pkg/sentry/pgalloc/pgalloc.go:1042 +0x77
created by gvisor.dev/gvisor/pkg/sentry/pgalloc.NewMemoryFile
	pkg/sentry/pgalloc/pgalloc.go:331 +0x1a4

goroutine 8 [select]:
gvisor.dev/gvisor/pkg/sentry/kernel.(*Timekeeper).startUpdater.func1(0xc0001cd880, 0xc00024e050)
	pkg/sentry/kernel/timekeeper.go:218 +0x1a3
created by gvisor.dev/gvisor/pkg/sentry/kernel.(*Timekeeper).startUpdater
	pkg/sentry/kernel/timekeeper.go:188 +0xbf

goroutine 9 [select]:
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).nextWaker(0xc000220198, 0x1, 0x0)
	pkg/sleep/sleep_unsafe.go:192 +0x6a
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).Fetch(0xc000220198, 0x1, 0x0, 0x0)
	pkg/sleep/sleep_unsafe.go:227 +0x38
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*processor).start(0xc000220180, 0xc00021ae8c)
	pkg/tcpip/transport/tcp/dispatcher.go:96 +0x1d6
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*dispatcher).init
	pkg/tcpip/transport/tcp/dispatcher.go:161 +0x167

goroutine 11 [syscall]:
syscall.Syscall6(0x10f, 0xc0000486d0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	src/syscall/asm_linux_amd64.s:41 +0x5
gvisor.dev/gvisor/pkg/unet.(*Socket).wait(0xc000250870, 0xffffffffffffff00, 0x0, 0x0)
	pkg/unet/unet_unsafe.go:55 +0x9a
gvisor.dev/gvisor/pkg/unet.(*ServerSocket).Accept(0xc00000ead8, 0x0, 0x0, 0x0)
	pkg/unet/unet.go:539 +0x11a
gvisor.dev/gvisor/pkg/control/server.(*Server).serve(0xc000245080)
	pkg/control/server/server.go:99 +0x32
gvisor.dev/gvisor/pkg/control/server.(*Server).StartServing.func1(0xc000245080)
	pkg/control/server/server.go:87 +0x2b
created by gvisor.dev/gvisor/pkg/control/server.(*Server).StartServing
	pkg/control/server/server.go:86 +0x92
```

[runsc.20201028-065513.048301.boot.log](https://github.com/google/gvisor/files/5450182/runsc.20201028-065513.048301.boot.log)

**Comment by ianlewis** [comment]
It looks like we may be running into a similar issue to https://github.com/golang/go/issues/13155
A closer version that for Wait: https://groups.google.com/g/golang-nuts/c/cwEk8lfV_e8

When using ctr this way the `runsc create` command doesn't have Stdout or Stderr attached so we call it using cmdOutput which stores combined Stdout and Stderr into a buffer.
https://github.com/google/gvisor/blob/62b0e845b7301da7d0c75eb812e9cd75ade05b74/pkg/shim/runsc/runsc.go#L124

I'm guessing that we don't close stdin/stdout when forking with `runsc create` and we end up waiting forever. It works when you run it with `crictl` because it runs the StartCloser code below which closes stdout/stderr.
https://github.com/google/gvisor/blob/62b0e845b7301da7d0c75eb812e9cd75ade05b74/pkg/shim/runsc/runsc.go#L136

**Comment by ianlewis** [comment]
This only happens when run via ctr so moving to p2.

**Comment by ianlewis** [comment]
Added a bug last week for the config issue: https://github.com/containerd/containerd/issues/4727

**Comment by jseba** [comment]
This issue also happens when using the containerd client APIs and the Gvisor runtime shim, not just from ctr. I spent some time tracking down a root cause and I believe I found it:

https://github.com/google/gvisor/blob/07a78ecb2918905af030a8cf81ee86ddd1c622c5/pkg/shim/proc/init.go#L130-L134

In this block, the IO is only hooked up if the sandbox flag is set, but I don't understand why. If I move the line `opts.IO = p.io` outside the if block, then I'm able to create and run a gvisor container with both the containerd APIs and ctr.

**Comment by jeremie-stripe** [comment]
To confirm what previous reports have hinted at, when trying to use gVisor through containerd directly (i.e. without kubernetes) the hang can be worked around by trying to mimick the annotations that kubernetes would set aka when creating your OCI container manifest you can insert the container type annotations like so:
```go
import (
	"github.com/containerd/containerd"
	"github.com/containerd/containerd/cio"
	"github.com/containerd/containerd/namespaces"
	"github.com/containerd/containerd/oci"
)

const (
	// Those constants can also be referenced via https://pkg.go.dev/github.com/containerd/cri/pkg/annotations

	// ContainerType is the container type (sandbox or container) annotation
	ContainerType = "io.kubernetes.cri.container-type"
	// ContainerTypeSandbox represents a pod sandbox container
	ContainerTypeSandbox = "sandbox"
	// ContainerTypeContainer represents a container running within a pod
	ContainerTypeContainer = "container"
)

annotations := make(map[string]string)
annotations[ContainerType] = ContainerTypeSandbox

container, err := client.NewContainer(
	...,
	containerd.WithNewSpec(
		...
		oci.WithAnnotations(annotations),
	),
)
```
which makes it work.

**Comment by ianlewis** [comment]
Yeah, gVisor needs the annotations to know which sandbox a container is being created in. runsc will do the right thing when the annotations aren't present and create a new sandbox, but the shim kind of assumes those annotations are set. We can probably fix this to better handle this scenario.

That said, because of https://github.com/containerd/containerd/issues/4727 the shim will ignore it's config file at `/etc/containerd/runsc.toml`. containerd doesn't really support "runtimes" properly outside of CRI so using gVisor via `ctr` or containerd API isn't something we can truly support.

**Comment by ianlewis** [comment]
Right now the code in the shim strictly needs the annotation to work right. Probably we can fix this to set `p.Sandbox` to `true` when the annotations aren't set.
https://github.com/google/gvisor/blob/07a78ecb2918905af030a8cf81ee86ddd1c622c5/pkg/shim/service.go#L964

I'll try to find a bit of time this week to make the change and test.

**Comment by jseba** [comment]
> containerd doesn't really support "runtimes" properly outside of CRI so using gVisor via `ctr` or containerd API isn't something we can truly support.

Can you provide more insight as to why containerd doesn't support runtimes properly? They have a ["first class"](https://github.com/containerd/containerd/tree/main/runtime/v2) runtime shim plugin API that is undergoing refactoring to better support runtimes that need custom API extensions and allow the shims to be managed directly from the supported containerd client APIs (not CRI).

We're beginning investment into using the runtime shim API (and not via CRI) and would definitely appreciate any hurdles or blockers that you know of off hand if we need to pivot our plans or plan for extra engineering effort.

**Comment by benmcrae** [comment]
@jseba I'd be interested to know if you made any progress with your investment? I've just stumbled across the same issue - spent the last few days trying to workout why gvisor won't work and finally realised the runsc shim is not directly compatible with containerd without CRI :/

**Comment by jseba** [comment]
We're not using the runsc shim directly, we're writing our own shim entirely. I'm not sure what the runsc shim is doing that requires the CRI annotations to be present on the container config

**Comment by ianlewis** [comment]
> > containerd doesn't really support "runtimes" properly outside of CRI so using gVisor via `ctr` or containerd API isn't something we can truly support.
> 
> Can you provide more insight as to why containerd doesn't support runtimes properly? They have a ["first class"](https://github.com/containerd/containerd/tree/main/runtime/v2) runtime shim plugin API that is undergoing refactoring to better support runtimes that need custom API extensions and allow the shims to be managed directly from the supported containerd client APIs (not CRI).

The main issue with containerd's native APIs is that we required something that linked containers from a single Kubernetes Pod together since gVisor runs all Pod containers in a single sandbox. This could be achieved via the new containerd Sandbox API but I don't think gVisor has supported using that yet. It also wouldn't be usable on older versions of containerd which we will need to continue to support.

Containerd also didn't support setting the shim config path correctly if the container is started by ctr because the shim config path is part of the "cri" config. See: https://github.com/containerd/containerd/issues/4727
