### ISSUE TITLE
Missing pkt.Data.Clone() for received UDP packets

### ISSUE THREAD

**Issue by rip-create-your-account** [google/gvisor#4551]
**Description**

UDP endpoint doesn't create copy of the slice backing vv for received packets. This violates the rule of `nic.DeliverNetworkPacket()`

> Note that the ownership of the slice backing vv is retained by the caller.

**Steps to reproduce**

Below is a program that injects one UDP packet and modifies the slice backing the vv before payload is read from the endpoint. In the backing vv the view "ab" is changed to view "cd" which becomes the view that `ep.Read()` returns.

``` golang
package main

import (
	"net"

	"gvisor.dev/gvisor/pkg/tcpip"
	"gvisor.dev/gvisor/pkg/tcpip/buffer"
	"gvisor.dev/gvisor/pkg/tcpip/header"
	"gvisor.dev/gvisor/pkg/tcpip/link/channel"
	"gvisor.dev/gvisor/pkg/tcpip/network/ipv4"
	"gvisor.dev/gvisor/pkg/tcpip/stack"
	"gvisor.dev/gvisor/pkg/tcpip/transport/udp"
	"gvisor.dev/gvisor/pkg/waiter"
)

func main() {
	c1 := channel.New(1, 1500, "")
	c1ID := tcpip.NICID(1)

	bindAddress := tcpip.FullAddress{
		NIC:  c1ID,
		Addr: tcpip.Address(net.IPv4(10, 0, 0, 1).To4()),
		Port: 22222,
	}

	// create the stack
	s := stack.New(stack.Options{
		NetworkProtocols:   []stack.NetworkProtocolFactory{ipv4.NewProtocol},
		TransportProtocols: []stack.TransportProtocolFactory{udp.NewProtocol},
	})

	for _, err := range []*tcpip.Error{
		s.CreateNIC(c1ID, c1),
		s.AddAddress(c1ID, ipv4.ProtocolNumber, bindAddress.Addr),
	} {
		if err != nil {
			panic(err)
		}
	}

	var wq waiter.Queue
	ep, err := s.NewEndpoint(udp.ProtocolNumber, ipv4.ProtocolNumber, &wq)
	if err != nil {
		panic(err)
	}

	if err := ep.Bind(bindAddress); err != nil {
		panic(err)
	}

	payload := buffer.NewViewFromBytes([]byte("ab"))

	// Build packet
	pkt := stack.NewPacketBuffer(stack.PacketBufferOptions{
		ReserveHeaderBytes: header.IPv4MinimumSize + header.UDPMinimumSize,
		Data:               payload.ToVectorisedView(),
	})
	header.UDP(pkt.TransportHeader().Push(header.UDPMinimumSize)).Encode(&header.UDPFields{
		DstPort: bindAddress.Port,
		Length:  uint16(payload.Size()),
	})
	ip := header.IPv4(pkt.NetworkHeader().Push(header.IPv4MinimumSize))
	ip.Encode(&header.IPv4Fields{
		DstAddr:     bindAddress.Addr,
		Protocol:    uint8(header.UDPProtocolNumber),
		TotalLength: header.IPv4MinimumSize + header.UDPMinimumSize + uint16(payload.Size()),
		IHL:         header.IPv4MinimumSize,
	})
	ip.SetChecksum(^ip.CalculateChecksum())

	// Make a clone of the packet that can be injected
	payloadVV := pkt.Views()
	pktClone := stack.NewPacketBuffer(stack.PacketBufferOptions{
		Data: buffer.NewVectorisedView(pkt.Size(), payloadVV),
	})

	c1.InjectLinkAddr(ipv4.ProtocolNumber, "", pktClone)

	// Now change the payload view to a garbage one in the backing vv.
	payloadVV[1] = buffer.View("cd")

	// Now read the malformed packet from ep
	v, _, _ := ep.Read(nil)
	println(string(v)) // prints 'cd'
}
```

**Comment by hbhasker** [comment]
Clone is a shallow copy. The backing bytes are considered immutable once injected into the stack. That said we are working towards making backing buffer ownership clearer.

In general though to avoid copies we don't copy the backing bytes when cloning the packetbuffer.

This is WAI.

**Comment by rip-create-your-account** [comment]
The copy of the backing bytes is not something that I'm expecting to see. Copy of the []buffer.View where the immutable byte slices are stored is what I expect. To me the documentation implies that `pkt.Data.Clone()` or equivalent is done by the stack when it wants to store the packet for later consumption, such as in the receive buffer of the UDP endpoint. That shallow copy doesn't happen and instead the original backing []buffer.View passed to nic.DeliverNetworkPacket is stored in the UDP receive buffer.

The sample code showcases this on the line `payloadVV[1] = buffer.View("cd")` where the immutable byte slice is changed to another byte slice in the backing vv.

**Comment by hbhasker** [comment]
Ah apologies. Vv.Clone has an odd optimization where it  holds a single view it doesnt copy it. I am reopeningt the issue I will take a look at this tomorrow. Thanks for the report.

**Comment by googleanivia** [comment]
The documentation wasn't great and it has been causing some pain for the developers. `DeliverNetworkPacket` has been changed to take ownership of the input `pkt`.  There are also some changes to APIs to be more zerocopy friendly. For example, `ep.Read` now takes an `io.Writer` instead of returning a pure slice of bytes.

As of now the ownership of objects in your code becomes the following:

```
	payloadVV := pkt.Views()
```

`payloadVV` points to the underlying storage of `pkt`. If `payloadVV` gets moved or modified, `pkt` should not be used again.

```
	pktClone := stack.NewPacketBuffer(stack.PacketBufferOptions{
		Data: buffer.NewVectorisedView(pkt.Size(), payloadVV),
	})
```

`payloadVV` gets moved at `buffer.NewVectorisedView` call, and `stack.NewPacketBuffer` takes ownership of the VV.

```
	payloadVV[1] = buffer.View("cd")
```

The above code now violates the ownership design, though not checked at compile or run time.

**Comment by hbhasker** [comment]
Robert could you take a look at this as part of the packetbuffer cleanup?
