### ISSUE TITLE
"runsc" prefix matching container names is problematic

### ISSUE THREAD

**Issue by majek** [google/gvisor#4553]
I have two containers running, `example` and `example1`:

```
marek@mrnew:~$ sudo runsc list
ID          PID         STATUS      BUNDLE                                                   CREATED                               OWNER
example     24451       running     /home/marek/xxx/bundledir-example    2020-10-19T17:05:13.396188677+02:00   root
example1    24282       running     /home/marek/xxx/bundledir-example1   2020-10-19T17:04:57.024886227+02:00   root
```

I wish to close the `example` container so I run `runsc  kill`:
```
marek@mrnew:~$ sudo runsc kill example SIGKILL
```

This is a valid and specific way of sending signals to container. The effect is that both co
ntainers exit:
```
marek@mrnew:~$ sudo runsc list
ID          PID         STATUS      BUNDLE      CREATED     OWNER
```

This is clearly incorrect. I didn't wish the `example1` container to exit.

The same happens for containers named `a` and `aa`.

I presume the problem is with gvisor prefix matching on container names somewhere deep in the code. If I rename the containers to `example1` and `example2` the problem of  doesn't appear - you can't kill `example` name here, the container must be specific for kill to work.

**Comment by majek** [comment]
This might be a security vulnerbility. If attacker is able to choose a container name, then she can trigger some orchestrator logic to stop that container but potentially send signal to container belonging to another user.

**Comment by prattmic** [comment]
cc @fvoznika

**Comment by fvoznika** [comment]
Hmm, not sure how you're getting it. [cmd.Kill.Execute](https://cs.opensource.google/gvisor/gvisor/+/master:runsc/cmd/kill.go;l=72;drc=be76c7ce6eb8f2a76c876b500aefc6f0fd8e30ba) selects a **single** container and sends the signal to it. The code that [looks up the container](https://cs.opensource.google/gvisor/gvisor/+/master:runsc/container/container.go;l=209;drc=0d54b41e550b452bb990cca55f642169502b82f2), tries to find a single match for the container using prefix match, but it fails if more than one container is found.

Here my failed attempt to repro it:
```shell
$ mkdir rootfs
$ docker export $(docker create alpine) | tar -xf - -C rootfs
$ sudo chown -R root rootfs
$ ./runsc spec -- /bin/sleep 1000
$ sudo ./runsc create example && sudo ./runsc start example
$ sudo ./runsc create example1 && sudo ./runsc start example1
$ sudo ./runsc list
ID          PID         STATUS      BUNDLE      CREATED                               OWNER
example     4168023     running     /tmp/gv5    2020-10-19T15:11:15.930294202-07:00   root
example2    4168121     running     /tmp/gv5    2020-10-19T15:11:27.392128637-07:00   root

$ sudo ./runsc kill example SIGKILL
$ sudo ./runsc list
ID          PID         STATUS      BUNDLE      CREATED                               OWNER
example     -1          stopped     /tmp/gv5    2020-10-19T15:11:15.930294202-07:00   root
example2    4168121     running     /tmp/gv5    2020-10-19T15:11:27.392128637-07:00   root
```

Is it possible that your second container is exiting as a result of the first container being killed? What are they running?

**Comment by majek** [comment]
Blah, as always this is more complex under the hood. Try this vanilla repro. Bootstrap the same as yours:
```
$ sudo runsc list
ID          PID         STATUS      BUNDLE      CREATED     OWNER
$ sudo runsc create example && sudo runsc start example; sudo runsc create example1 && sudo runsc start example1; sudo runsc list
ID          PID         STATUS      BUNDLE      CREATED                              OWNER
example     1370        running     /tmp/y      2020-10-20T13:27:13.64740291+02:00   root
example1    1436        running     /tmp/y      2020-10-20T13:27:13.75764791+02:00   root
$ sudo /home/marek/bin/runsc delete -force example; sudo /home/marek/bin/runsc delete -force example; sudo runsc list
ID          PID         STATUS      BUNDLE      CREATED     OWNER
```

Running successive `runsc delete -force` seems to be the culprit.

**Comment by fvoznika** [comment]
If you call `runsc delete` more than once you're susceptible to kill another sandbox. First call will kill the correct one, the second call will match example1 and kill it.

**Comment by majek** [comment]
Isn't that inherently racy? Does the runtime guarantee that after "runsc delete" the container will exit? If so, why does "runsc delete -force" exist?

**Comment by fvoznika** [comment]
Yes, `runsc delete` returns only after the container has exited. `runsc delete --force` stops and deletes the container even if it's still running.
