### ISSUE TITLE
Pread/Pwrite is not possible on VFS1 /proc SeqFiles

### ISSUE THREAD

**Issue by lnsp** [google/gvisor#4565]
**Description**

On my Linux system and inside the sandbox on VFS2 the /proc files implemented via DynamicBytesSource are Pread-/Pwrite-able, but on VFS1 you always get ESPIPE because `file.Flags().Pread` returns false.

**Steps to reproduce**

1. Compile the following C with `gcc -o pread pread.c`
```C
#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include <string.h>

int main() {
  char buf [1024];
  int fd = open("/proc/self/maps", O_RDONLY);
  int res = pread(fd, buf, sizeof(buf), 0);
  if (res < 0) {
    printf("error: %s\n", strerror(-res));
  } else {
    printf("success: read %d bytes\n", res);
  }
  close(fd);
}
```
2. Do `./pread` on your local machine, see success
3. Do `sudo runsc -vfs2 do $(pwd)/pread`, see success
4. Do `sudo runsc do $(pwd)/pread`, see `error: Operation not permitted`

**Environment**

Please include the following details of your environment:

*   `runsc -version`
```
runsc version release-20201005.0-99-g9e95a7463960
spec: 1.0.1-dev
```
*   `uname -a`
```
Linux buster 5.8.0-2-amd64 #1 SMP Debian 5.8.10-1 (2020-09-19) x86_64 GNU/Linux
```
*   `git describe` (if built from source)
```
release-20201005.0-108-g34a6e9576
```

**Comment by fvoznika** [comment]
Thanks for the report. We're not investing in VFS1 anymore and will be switching to VFS2 soon. Is this blocking you in any way? Can you use VFS2?

**Comment by ayushr2** [comment]
VFS1 is deleted and VFS2 is now default.
