### ISSUE TITLE
Update route when NAT-ing packets

### ISSUE THREAD

**Issue by ghananigans** [google/gvisor#4612]
Currently a packet may be redirected or have some other type of NAT performed on it.

In this case, the source or destination, or both, may be updated but the `stack.Route` never gets updated. 

UDP:
https://github.com/google/gvisor/blob/6e6a9d3f3dd6dd9ce290952406ba7ca7c5570311/pkg/tcpip/stack/iptables_targets.go#L205

TCP:
https://github.com/google/gvisor/blob/6e6a9d3f3dd6dd9ce290952406ba7ca7c5570311/pkg/tcpip/stack/conntrack.go#L362

**Comment by ghanan94** [comment]
cc: @nybidari @kevinGC
