### ISSUE TITLE
RedirectTarget is not thread safe

### ISSUE THREAD

**Issue by ghanan94** [google/gvisor#4613]
It is possible to have two interleaving goroutines use the same `RedirectTarget` to modify a packet, which ends up update the `RedirectTarget`'s `Addr` field.

b49a17fc3d33068a1235d97efd8cc8bc9f0f3ccf is the cause of this since before that change, `Action` was implemented on a value receiver for `RedirectTarget`. 

However, we should probably not even have `RedirectTarget.Addr` and instead make it a function scoped variable - there doesn't seem to be any need for it to be a member of `RedirectTarget`

https://github.com/google/gvisor/blob/6e6a9d3f3dd6dd9ce290952406ba7ca7c5570311/pkg/tcpip/stack/iptables_targets.go#L177

**Comment by kevinGC** [comment]
If we want `RedirectTarget` to be reusable for other redirection (i.e. not only to localhost), I believe we want to keep `RedirectTarget.Addr`, but set it at initialization and treat the field as immutable. Currently, `Action` is performing initialization that could lead to this data race.

**Comment by kevinGC** [comment]
Nevermind. I tried what I suggested, and it's incompatible with Linux. In Linux, the action sets a local variable as you suggested, enabling the same REDIRECT rule to be reached from either the PREROUTING or OUTPUT hooks.
