### ISSUE TITLE
NUD tests incorrectly report `cmp.Diff`

### ISSUE THREAD

**Issue by tamird** [google/gvisor#4664]
Per the example in https://godoc.org/github.com/google/go-cmp/cmp#Diff the form should be:
```
if diff := cmp.Diff(want, got); diff != "" {
    t.Errorf("MakeGatewayInfo() mismatch (-want +got):\n%s", diff)
}
```
however, NUD tests (and possibly others) are littered with the reverse, e.g.:
https://github.com/google/gvisor/blob/8fa18e8ecb3e3da2015e5c73db9e46494dcfeff7/pkg/tcpip/stack/neighbor_cache_test.go#L252-L254

Fix this.

@puradox cc @ghanan94

**Comment by puradox** [comment]
Does this break anything? Looks like we use (-) with got and (+) with want, which is preference with nothing necessarily broken.

**Comment by tamird** [comment]
The output is backwards, when tests fail "got" is presented as "want" and vice versa.

**Comment by tamird** [comment]
On second thought, this might be fine. I think I was confused by this output when I was attempting #4663.

Feel free to close this if you find the current output satisfactory.

**Comment by puradox** [comment]
I feel this output is satisfactory, as it states its definition of (+) and (-), but I see your point. I don't mind changing this, but have higher priority items to work on right now. Let's mark this as a good first bug if anyone else wants to take this on.
