### ISSUE TITLE
Having trouble executing make commands in gVisor dev environment

### ISSUE THREAD

**Issue by mattbonnell** [google/gvisor#4684]
**Description**
I'm sure this is an issue with what I'm doing but wasn't sure where else to ask.
I'm trying to configure a dev environment to begin contributing to the project. I'm running a container with the Ubuntu 20.04.1 image and mounting the gvisor repo and the docker daemon socket into the container. Inside the container, when I attempt to run `make` commands in the gvisor repo, I invariably get an error output of the following form:
```
❯ make build
id: 'gvisor': no such user
id: 'gvisor': no such user
Error: No such container: gvisor-bazel-fac53c1e
make[1]: Entering directory '/usr/dev/go/github.com/google.com/gvisor'
id: 'gvisor': no such user
id: 'gvisor': no such user
make -C images load-default
make[2]: Entering directory '/usr/dev/go/github.com/google.com/gvisor/images'
make pull-default || make rebuild-default
make[3]: Entering directory '/usr/dev/go/github.com/google.com/gvisor/images'
docker pull  gcr.io/gvisor-presubmit/default_x86_64:b633fc901d737471
b633fc901d737471: Pulling from gvisor-presubmit/default_x86_64
Digest: sha256:e8e02db66c2a6412f41ead9960e4fa9f9a6038540dfa37823dd5f6588d745682
Status: Image is up to date for gcr.io/gvisor-presubmit/default_x86_64:b633fc901d737471
gcr.io/gvisor-presubmit/default_x86_64:b633fc901d737471
make[3]: Leaving directory '/usr/dev/go/github.com/google.com/gvisor/images'
docker tag gcr.io/gvisor-presubmit/default_x86_64:b633fc901d737471 gvisor.dev/images/default
make[2]: Leaving directory '/usr/dev/go/github.com/google.com/gvisor/images'
e658a0b6eadc        gvisor.dev/images/default   "sh -c 'groupadd --g…"   5 minutes ago       Exited (3) 5 minutes ago                       gvisor-builder-fac53c1e
gvisor-builder-fac53c1e
docker run --user 0:0 --entrypoint "" --name gvisor-builder-fac53c1e \
	gvisor.dev/images/default \
	sh -c "groupadd --gid  --non-unique gvisor && \
	       groupadd --gid 0 --non-unique docker-fac53c1e && \
	       useradd -l --uid  --non-unique --no-create-home \
	               --gid   --groups 0 -d /root gvisor && \
	       if [[ -e /dev/kvm ]]; then chmod a+rw /dev/kvm; fi"
groupadd: invalid group ID '--non-unique'
make[1]: *** [tools/bazel.mk:101: bazel-image] Error 3
make[1]: Leaving directory '/usr/dev/go/github.com/google.com/gvisor'
make: *** [tools/bazel.mk:152: bazel-server] Error 2
```

First, the `id: 'gvisor': no such user` which seems to reoccur a few times but the script keeps running, and then the `groupadd: invalid group ID '--non-unique'`.

**Steps to reproduce**

See above

**Environment**

Please include the following details of your environment:

*   `runsc -version`
*   `docker version` or `docker info` (if available)
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
*   `kubectl version` and `kubectl get nodes` (if using Kubernetes)
*   `uname -a`
```
Linux 0bd91cd0862f 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
*   `git describe` (if built from source)
*   `runsc` debug logs (if available)

**Comment by amscanne** [comment]
Hi Matt!

Note that the default build scripts are already using a build container (so you don't need any dependencies on your local system, and nothing will be installed there other than the bazel cache in ~/.cache/bazel).

If you're rather run your own development container, you could either:
- Just use the container in images/default/Dockerfile
- Or install the dependencies there (mostly bazel) for your own configuration

You won't be able to use the convenient targets in the Makefile, but you can just use bazel directly to build & run targets.

With respect to this specific issue, I'm not sure the build container will work well with volume configurations, etc. from within a container, but it's worth a shot. It doesn't seem to be have a valid user. Can you try changing the "USER ?= gvisor" line in tools/bazel.mk to "USER := $(shell whoami)" and see if that fixes the issue? (If it does, you can send a PR, or I will do.)

**Comment by mattbonnell** [comment]
Thank you so much for getting back.
I was seeking to use a container for my development because I'm running macOS locally, and so thought I'd need to work in a container on-top of Docker Desktop's Linux VM.

Sure enough, when I try to run `make` commands locally, I get output like this (eg `make build`):
```
❯ make build
readlink: illegal option -- m
usage: readlink [-n] [file ...]
readlink: illegal option -- m
usage: readlink [-n] [file ...]
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
/bin/bash: md5sum: command not found
readlink: illegal option -- m
usage: readlink [-n] [file ...]
Error: No such container: gvisor-bazel-
readlink: illegal option -- m
usage: readlink [-n] [file ...]
readlink: illegal option -- m
usage: readlink [-n] [file ...]
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
make -C images load-default
/bin/sh: sha256sum: command not found
xargs: sha256sum: No such file or directory
/Library/Developer/CommandLineTools/usr/bin/make pull-default || /Library/Developer/CommandLineTools/usr/bin/make rebuild-default
/bin/sh: sha256sum: command not found
xargs: sha256sum: No such file or directory
docker pull  gcr.io/gvisor-presubmit/default_x86_64:
invalid reference format
make[3]: *** [pull-default] Error 1
/bin/sh: sha256sum: command not found
xargs: sha256sum: No such file or directory
docker pull  fedora:31 && \
	T=$(mktemp -d) && cp -a default/* $T && \
		docker build  \
			-f "$T/$(if [ -f "default/Dockerfile.x86_64" ]; then echo Dockerfile.x86_64; else echo Dockerfile; fi)" \
			-t "gcr.io/gvisor-presubmit/default_x86_64:" \
			$T && \
		rm -rf $T
31: Pulling from library/fedora
Digest: sha256:ba4fe6a3da48addb248a16e8a63599cc5ff5250827e7232d2e3038279a0e467e
Status: Image is up to date for fedora:31
docker.io/library/fedora:31
invalid argument "gcr.io/gvisor-presubmit/default_x86_64:" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
make[3]: *** [rebuild-default] Error 125
make[2]: *** [load-default] Error 2
make[1]: *** [load-default] Error 2
make: *** [bazel-server] Error 2
```

I know I must be missing something.

**Comment by mattbonnell** [comment]
> Can you try changing the "USER ?= gvisor" line in tools/bazel.mk to "USER := $(shell whoami)" and see if that fixes the issue? (If it does, you can send a PR, or I will do.)

Will try this with the dev container set up. As an aside, I'm not tied to any one environment for this, just looking for whatever's most straightforward.

**Comment by amscanne** [comment]
The PR #4686 may help, it avoids trying to add the user and group if they are redundant.

**Comment by mattbonnell** [comment]
Awesome, I'll check that out and give it a try. Is the assumption I outlined above correct, that I would indeed need to run the build commands from within a Linux VM (eg Docker Desktop's) if I'm on mac?

**Comment by mattbonnell** [comment]
So that does indeed resolve the user/group issues. The issue I'm experiencing now is that I get the following error when the container tries to mount the Bazel cache into the build containers:
```
❯ make runsc
make build OPTIONS="-c opt" TARGETS="//runsc"
make[1]: Entering directory '/usr/dev/go/github.com/google.com/gvisor'
Error: No such container: gvisor-bazel-fac53c1e
make[2]: Entering directory '/usr/dev/go/github.com/google.com/gvisor'
make -C images load-default
make[3]: Entering directory '/usr/dev/go/github.com/google.com/gvisor/images'
make pull-default || make rebuild-default
make[4]: Entering directory '/usr/dev/go/github.com/google.com/gvisor/images'
docker pull  gcr.io/gvisor-presubmit/default_x86_64:b633fc901d737471
b633fc901d737471: Pulling from gvisor-presubmit/default_x86_64
Digest: sha256:e8e02db66c2a6412f41ead9960e4fa9f9a6038540dfa37823dd5f6588d745682
Status: Image is up to date for gcr.io/gvisor-presubmit/default_x86_64:b633fc901d737471
gcr.io/gvisor-presubmit/default_x86_64:b633fc901d737471
make[4]: Leaving directory '/usr/dev/go/github.com/google.com/gvisor/images'
docker tag gcr.io/gvisor-presubmit/default_x86_64:b633fc901d737471 gvisor.dev/images/default
make[3]: Leaving directory '/usr/dev/go/github.com/google.com/gvisor/images'
docker run --user 0:0 --entrypoint "" --name gvisor-builder-fac53c1e \
	gvisor.dev/images/default \
	sh -c " \
	        \
	       if [[ -e /dev/kvm ]]; then chmod a+rw /dev/kvm; fi"
docker commit gvisor-builder-fac53c1e gvisor.dev/images/builder
sha256:c4ccdb202a6b31fcc2146327dd35973e068fffe8d68f654dc0fd172653fd2872
gvisor-builder-fac53c1e
# This command runs a bazel server, and the container sticks around
# until the bazel server exits. This should ensure that it does not
# exit in the middle of running a build, but also it won't stick around
# forever. The build commands wrap around an appropriate exec into the
# container in order to perform work via the bazel client.
docker run -d --rm --name gvisor-bazel-fac53c1e \
	-v "/usr/dev/go/github.com/google.com/gvisor:/usr/dev/go/github.com/google.com/gvisor" \
	--workdir "/usr/dev/go/github.com/google.com/gvisor" \
	 --user 0:0 --entrypoint "" --init -v "/root/.cache/bazel:/root/.cache/bazel" -v "/root/.config/gcloud:/root/.config/gcloud" -v "/tmp:/tmp" -v "/var/run/docker.sock:/var/run/docker.sock" -v "/etc/docker/daemon.json:/etc/docker/daemon.json" --privileged \
	gvisor.dev/images/builder \
	sh -c "tail -f --pid=\$(bazel  info server_pid) /dev/null"
b791229cb9102a1f779594e91375f9c6fe2e506ec61995bd9adb0687c9c0d987
docker: Error response from daemon: Mounts denied: 
The path /root/.cache/bazel is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/docker-for-mac for more info
```
I'm trying to figure out if there's a way of putting the cache in a shared volume that my containers and host can both see and access, but before I go any further, I just want to take a step back and ask if this is the best approach for contributing to the project from a macOS native environment. With the way the build system is set up on this project, would there be another way to go that would make more sense?

**Comment by amscanne** [comment]
The easiest way is definitely to either:
- Use a Linux VM (with Docker running there) and the standard "make" container.
- Use a Linux VM with bazel native natively.

That said, if we can fix up these Makefile/scripts to make them robust enough that it supports Docker for Mac, then I'm good with that. Did you have specific areas that you were looking at for contributions?

**Comment by mattbonnell** [comment]
I've been looking at getting involved with a Go kernel project to complement the embedded RTOS course I'm taking at school,  and this one is pretty exciting. Just want to help build out the functionality, planning to start with some unit test tickets and whatnot and go from there.

As you allude to, I think there's a nice opportunity here to buff the build scripts up to make them compatible with a Docker for Mac/Windows workflow. 

The issue I'm having at the moment stems from this call to the Docker daemon which is executed by `tools/bazel.mk`:
```
docker run -d --rm --name gvisor-bazel-fac53c1e \
	-v "[path to repo]/google.com/gvisor:[path to repo]/google.com/gvisor" \
	--workdir "/usr/dev/go/github.com/google.com/gvisor" \
	 --user 0:0 --entrypoint "" --init -v "/root/.cache/bazel:/root/.cache/bazel" -v "/root/.config/gcloud:/root/.config/gcloud" -v "/tmp:/tmp" -v "/var/run/docker.sock:/var/run/docker.sock" -v "/etc/docker/daemon.json:/etc/docker/daemon.json" --privileged \
	gvisor.dev/images/builder \
	sh -c "tail -f --pid=\$(bazel  info server_pid) /dev/null"
b791229cb9102a1f779594e91375f9c6fe2e506ec61995bd9adb0687c9c0d987
docker: Error response from daemon: Mounts denied: 
The path /root/.cache/bazel is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/docker-for-mac for more info
```
The best practice way of issuing Docker commands from inside a container is to mount the host's Docker socket into the container so that the requests are made to the host daemon. 

However, all the paths are specified as absolute paths from the container's context, which of course the host doesn't recognize.

Looking around, there doesn't seem to be an accepted solution to this problem beyond ensuring that those paths are also valid on the host.
