### ISSUE TITLE
Make packetimpact tests from the same file to be able to run in separate docker containers

### ISSUE THREAD

**Issue by toshikik** [google/gvisor#4730]
Looks like packetimpact tests from the same file are always executed in the same docker container. This makes it difficult to move multiple similar tests into a single file without exceeding the execution time limit per container. Similar tests being defined in multiple files tends to cause duplicate codes.

**Comment by zeling** [comment]
Hi Toshi, I don't remember a time limit is added to the container; I also tried combining ipv6_fragment_reassembly_test.go and ipv4_fragment_reassembly_test.go into a single file (I assume this is the kind of "move similar tests into a single file" in your comments) and it ran successfully for me. Could you provide more details please? That would be helpful, thanks!

**Comment by zeling** [comment]
The timeout was in presubmit and we need to parallelize some tests to be able to finish within timeout (also it saves time when running locally), by allowing separate docker containers, we can achieve the parallelization and also making tests more robust.

**Comment by zeling** [comment]
Fixed in 4d59a5a62223b56927b37a00cd5a6dea577fe4c6
