### ISSUE TITLE
syscall issue: setrlimit(RLIMIT_RSS): Operation not permitted

### ISSUE THREAD

**Issue by ahmetb** [google/gvisor#4746]
**Description**

Seeing error `sudo: setrlimit(RLIMIT_RSS): Operation not permitted` when running `sudo date` or `sudo -s`.

Not fatal. It could be a cosmetics issue, but would be great not to run into this as `sudo` is about privileges and seeing `sudo` show "not permitted" is not great.

I'm fully aware that by default user is `root` in this mode and it's already privileged enough.

**Steps to reproduce**

1. Run alpine container on Cloud Run.
2. `apk add --no-cache sudo`
3. exec `sudo date`
4. observe output

	```
	$ sudo date
	sudo: setrlimit(RLIMIT_RSS): Operation not permitted
	sudo: setrlimit(RLIMIT_RSS): Operation not permitted
	Thu Nov  5 21:53:09 UTC 2020
	```

**Environment**

Cloud Run sandbox.

**Comment by fvoznika** [comment]
Setting RLIMIT_RSS is not yet supported in gVisor. [These](https://cs.opensource.google/gvisor/gvisor/+/master:pkg/sentry/syscalls/linux/sys_rlimit.go;l=85;drc=d201feb8c5e425bfa8abc905f24d49b268520aec) are the limits that can be set.

**Comment by fvoznika** [comment]
RLIMIT_RSS is not supported in Linux anymore:
```
RLIMIT_RSS
              This is a limit (in bytes) on the process's resident set (the
              number of virtual pages resident in RAM).  This limit has ef‐
              fect only in Linux 2.4.x, x < 30, and there affects only calls
              to madvise(2) specifying MADV_WILLNEED.
```

So we can simply ignore these calls.

**Comment by ahmetb** [comment]
@fvoznika you mean capture and noop to suppress?

**Comment by fvoznika** [comment]
We can allow it to be set, but not enforce RSS.
