### ISSUE TITLE
udp_icmp_error_propagation_test.go is flaky

### ISSUE THREAD

**Issue by hbhasker** [google/gvisor#4841]
**Description**

Observed a flake when running the packetimpact tests

 dut.go:271: test error: process terminated with status: 1, expect failure: false

        ====== Begin of DUT Logs ======

        posix_server is starting.
        Got IP 0.0.0.0 and port 40000.
        Server listening on 0.0.0.0:40000

        ====== End of DUT Logs ======

        ====== Begin of Testbench Logs ======

        --- FAIL: TestUDPICMPErrorPropagation (7.41s)
            --- FAIL: TestUDPICMPErrorPropagation/Connected/PortUnreachable/SockOpt (0.47s)
                udp_icmp_error_propagation_test.go:191: SO_ERROR sockopt after ICMP error is (0) errno 0, expected (111) connection refused
        FAIL

        ====== End of Testbench Logs ======

I believe the reason for this is the test sends an ICMP error and immediately issues an RPC to read the socket options. But the ICMP error may not have been processed yet by the UDP endpoint. We should probably poll the UDP endpoint to make sure the error has been observed before issuing getsockopt(..SO_ERROR).

**Comment by jelischer** [comment]
sorry, no longer working on this project
