### ISSUE TITLE
Restore route on s/r for raw endpoints

### ISSUE THREAD

**Issue by ghananigans** [google/gvisor#4906]
Currently in `raw.endpoint.Resume` we restore a route incorrectly.

`e.route` is marked with `state:"manual"` so it will not be serialized and deserialized as part of s/r:
https://github.com/google/gvisor/blob/60ae6c4d83d432ff5b352a649757c7bd92073053/pkg/tcpip/transport/raw/endpoint.go#L87

We we are restoring the route by using the route's remote address when finding a new route but this will always be the empty address since the route is the thing we are trying to restore:
https://github.com/google/gvisor/blob/60ae6c4d83d432ff5b352a649757c7bd92073053/pkg/tcpip/transport/raw/endpoint_state.go#L76

This is effectively:
```
var r stack.Route
route, err := stack.FindRoute(nicID, localAddr, r.RemoteAddress, ...)
```

Here, r.RemoteAddress is always `""`

**Comment by GG-Sheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.
