### ISSUE TITLE
TCP_CONGESTION not supported using network passthrough

### ISSUE THREAD

**Issue by DavideAG** [google/gvisor#4949]
**Description**

Using iperf3 network benchmark using runsc with network [passthrough](https://gvisor.dev/docs/user_guide/networking/#network-passthrough) option isn't possible to complete the test. 
The error presented by iperf3 is:
`iperf3: error - unable to set TCP_CONGESTION: Supplied congestion control algorithm not supported on this host`

Maybe similar to https://github.com/google/gvisor/issues/195 that was resolved in  https://github.com/google/gvisor/commit/70578806e8d3e01fae2249b3e602cd5b05d378a0 but why we have this error using the host network stack? 🤔 

**Steps to reproduce**
Using the [iperf3 docker hub image](https://hub.docker.com/r/networkstatic/iperf3/)
Launch an iperf3 server using runsc w/ passthrough option as container runtime
`docker run -it --rm --name=iperf3-server --runtime=runsc-passthrough -p 5201:5201 networkstatic/iperf3 -s`
then a client
`docker run -it --runtime=runc --rm networkstatic/iperf3 -c <server_ip_address>`

**Environment**

<details><summary>runsc -version</summary>
<p>
runsc version release-20201030.0
spec: 1.0.1-dev
</p>
</details>

<details><summary>docker info</summary>
<p>
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 9
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runsc-passthrough kata-acrn kata-clh runsc kata-qemu-virtiofs runc crun kata-fc kata-qemu
 Default Runtime: crun
 Init Binary: docker-init
 containerd version: 
 runc version: 7d650b35bbc8e09361e4ae4b63a7931749697120
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-123-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.666GiB
 Name: performance
 ID: QFDP:4WC6:5FSX:Q3DZ:FCLT:NGOX:6S7Y:W5YN:4O23:F57G:6KW6:5TJX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
</p>
</details>

<details><summary>uname -a</summary>
<p>
Linux performance 4.15.0-123-generic #126-Ubuntu SMP Wed Oct 21 09:40:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
</p>
</details>

<details><summary>lsb_release -a</summary>
<p>
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
</p>
</details>

**Comment by iangudger** [comment]
This is more or less working as intended. See https://gvisor.dev/blog/2020/04/02/gvisor-networking-security/ for the reasoning.

**Comment by DavideAG** [comment]
Fine, thank you for your answer @iangudger . I'm closing this issue
