### ISSUE TITLE
presubmit packetimpact failure on ipv4 reassembly tests

### ISSUE THREAD

**Issue by arthurpi** [google/gvisor#4971]
**Description**

When trying to add new packetimpact test cases for IPv4 reassembly, they always fail during the presubmit phase. However when ran locally, they always pass.
Logs of the failure are copied below. For some reason, the test runner receives some (very unexpected!) IPv6 packets which might be why it fails the test.

The same tests for IPv6 reassembly do not exhibit the same problem.

**Steps to reproduce**

In the following files, set `skip` to `false` and run the presubmit to see them fail.
test/packetimpact/tests/ipv4_fragment_reassembly_test.go
test/packetimpact/tests/ipv6_fragment_reassembly_test.go

**Test output during presubmits**

        --- FAIL: TestIPv4FragmentReassembly (5.78s)
            --- FAIL: TestIPv4FragmentReassembly/duplicated_fragments (1.19s)
                ipv4_fragment_reassembly_test.go:153: received 0 bytes out of 3000, then conn.ExpectFrame(_, _, time.Second) failed with got frames Ether: SrcAddr: 02:42:d6:ae:eb:14 02:42:d6:ae:eb:0a
                           DstAddr: 02:42:d6:ae:eb:0a 02:42:d6:ae:eb:14
                     IPv4: SrcAddr:    214.174.235.20    214.174.235.10
                           DstAddr:    214.174.235.10    214.174.235.20
                    (Payload matches missing)
                    ; Ether: SrcAddr: 02:42:d6:ae:eb:14 02:42:d6:ae:eb:0a
                           DstAddr: 02:42:d6:ae:eb:0a 02:42:d6:ae:eb:14
                     IPv4: SrcAddr:    214.174.235.20    214.174.235.10
                           DstAddr:    214.174.235.10    214.174.235.20
                    (Payload matches missing)
                    ; Ether: SrcAddr: 02:42:d6:ae:eb:14 02:42:d6:ae:eb:0a
                           DstAddr: 02:42:d6:ae:eb:0a 02:42:d6:ae:eb:14
                     IPv4: SrcAddr:    214.174.235.20    214.174.235.10
                           DstAddr:    214.174.235.10    214.174.235.20
                    (Payload matches missing)
                    ; Ether: SrcAddr: 02:42:d6:ae:eb:14 02:42:d6:ae:eb:0a
                           DstAddr: 02:42:d6:ae:eb:0a 02:42:d6:ae:eb:14
                     IPv4: SrcAddr:    214.174.235.20    214.174.235.10
                           DstAddr:    214.174.235.10    214.174.235.20
                    (Payload matches missing)
                    ; Ether:       SrcAddr:       02:42:d6:ae:eb:14 02:42:d6:ae:eb:0a
                                 DstAddr:       33:33:00:00:00:02 02:42:d6:ae:eb:14
                    (IPv6 doesn't match IPv4)
                     IPv6:  TrafficClass:                       0
                               FlowLabel:                       0
                           PayloadLength:                      16
                              NextHeader:                      58
                                HopLimit:                     255
                                 SrcAddr: fe80::42:d6ff:feae:eb14
                                 DstAddr:                 ff02::2
                     IPv4:       SrcAddr:                            214.174.235.10
                                 DstAddr:                            214.174.235.20
                    (ICMPv6 matches missing)
                     want [&testbench.Ether{} &testbench.IPv4{}] during 627.933027ms

**Comment by zeling** [comment]
The IPv6 packets you are seeing are probably router solicitations that is broadcasted to all routers, I don't know why we have been added to the all-routers group in the first place, but this should not interfere with the tests. The packet capture suggests we have actually never received any reply for pkt #25, #30, these corresponds to the unexpected failure for the "duplicated_fragments" and "fragment subset" sub tests.

[eth2.pcap.zip](https://github.com/google/gvisor/files/5626853/eth2.pcap.zip)
