### ISSUE TITLE
Create SCTP socket fail. Error: invalid argument

### ISSUE THREAD

**Issue by balyuyiop** [google/gvisor#5000]
**Description**

I am doing a project using gvisor and the programme needs to create a SCTP socket. However,  the socket return -1 and **"invalid argument"** error present when using gvisor. Without using gvisor, the socket is created successfully when using docker runc. 
Is it a bug or any workaround? Thank you

**Steps to reproduce**
The golang code is shown below: 
```
sock, err := syscall.Socket(
                syscall.AF_INET,
                syscall.SOCK_STREAM,
                syscall.IPPROTO_SCTP,
        )

```
**Environment**

Runsc version:
```
$ runsc -version
runsc version release-20201117.0-78-ge813008664ff
spec: 1.0.1-dev
```

Docker version:
```
~$ docker version
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275d40
 Built:             Tue Dec  1 19:20:17 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275d40
  Built:            Tue Dec  1 19:18:45 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Linux version:
```
~$ uname -r
5.4.0-56-generic
```

**Comment by hbhasker** [comment]
SCTP is not supported by gVisor. We have no plans to add support for it. Do you have a use-case for this?

**Comment by balyuyiop** [comment]
Yes. We are developing a 5G core network. The protocol between gnodeb and AMF is using SCTP. We are using gvVisor container to deploy our network function programme to apply the container isolation. It is useful to add support for SCTP.

**Comment by hbhasker** [comment]
@balyuyiop Thanks for the context. That said I am not sure we have resources to tackle supporting SCTP at the moment. If this is something you really need we would be happy to accept contributions and guide any person willing to develop it.

**Comment by balyuyiop** [comment]
Thank you. I really need this in my project and I am willing to contribute with it and help to develop it if there is some guides. Is there any guidelines? Or is it similar to the implementation of TCP ,state machine/method invocation/buffer manipulation?

**Comment by hbhasker** [comment]
We don't have guidelines on how to add a new protocol but yes it would be similar to TCP but we should try and not repeat a mistake from TCP of using a goroutine per endpoint and make sure we implement the State machine as per RFC from the start.

We made these mistakes when implementing TCP and it has taken a lot of effort to fix the bugs retroactively.

What we can do is I can probably create a shell framework that allows creation of SCTP sockets but with no actual implementation of the protocol itself. Then you could work on adding the actual implementation. WDYT?

**Comment by hbhasker** [comment]
@balyuyiop Please let me know if this is something you will be willing to work on. Because this is not a priority for us at the moment.

**Comment by balyuyiop** [comment]
@hbhasker Thank you for replying and sorry. We still do not figure out how to implement the SCTP in gvisor. As there are other problems of our project which are need to focus, we might not have time to work on this. We are happy to hear any updates of SCTP implement from you and others although this is not a priority for your team at the moment. Thank you

**Comment by hbhasker** [comment]
@balyuyiop I am going to mark this closed for now as we have no intention of implementing SCTP in gVisor. Please feel free to reopen if you have cycles to contribute towards this work and we can figure out how to get this added.
