### ISSUE TITLE
Sentry seccomp violation

### ISSUE THREAD

**Issue by dqminh** [google/gvisor#5038]
**Description**

We saw seccomp violation message in a few of our containers, which triggered SIGSYS

For example

```
Dec 07 18:53:04 131m1 audispd[35473]: type=SECCOMP msg=audit(1607367184.013:1738156): auid=4294967295 uid=0 gid=0 ses=4294967295 subj=kernel pid=3783138 comm="exe" exe=2F7573722F6C6F63616C2F62696E2F72756E7363202864656C6574656429 sig=31 arch=c000003e syscall=13 compat=0 ip=0x4720fb code=0x80000000
Dec 07 18:53:04 131m1 audispd[35473]: type=ANOM_ABEND msg=audit(1607367184.013:1738157): auid=4294967295 uid=0 gid=0 ses=4294967295 subj=kernel pid=3783138 comm="exe" exe=2F7573722F6C6F63616C2F62696E2F72756E7363202864656C6574656429 sig=31 res=1
Dec 07 18:53:11 131m1 systemd-coredump[3609420]: Process 3783138 (exe) of user 0 dumped core.

                                                 Stack trace of thread 19:
                                                 #0  0x00000000004720fb sync.(*Map).Load (/usr/local/bin/runsc (deleted) + 0x720fb)

                                                 Stack trace of thread 1:
                                                 #0  0x00000000004894aa time.parse (/usr/local/bin/runsc (deleted) + 0x894aa)
                                                 #1  0x000000c0002fee80 n/a (n/a + 0x0)

...

Dec 07 18:54:58 131m1 audispd[35473]: type=SECCOMP msg=audit(1607367298.584:1738728): auid=4294967295 uid=0 gid=0 ses=4294967295 subj=kernel pid=1117396 comm="exe" exe=2F7573722F6C6F63616C2F62696E2F72756E7363202864656C6574656429 sig=31 arch=c000003e syscall=13 compat=0 ip=0x4720fb code=0x80000000
Dec 07 18:54:58 131m1 audispd[35473]: type=ANOM_ABEND msg=audit(1607367298.584:1738729): auid=4294967295 uid=0 gid=0 ses=4294967295 subj=kernel pid=1117396 comm="exe" exe=2F7573722F6C6F63616C2F62696E2F72756E7363202864656C6574656429 sig=31 res=1
Dec 07 18:55:00 131m1 systemd-coredump[3625482]: Process 1117396 (exe) of user 0 dumped core.

                                                 Stack trace of thread 1:
                                                 #0  0x00000000004720fb sync.(*Map).Load (/usr/local/bin/runsc (deleted) + 0x720fb)

                                                 Stack trace of thread 17:
                                                 #0  0x00000000004894aa time.parse (/usr/local/bin/runsc (deleted) + 0x894aa)

                                                 Stack trace of thread 15:
                                                 #0  0x00000000004894aa time.parse (/usr/local/bin/runsc (deleted) + 0x894aa)

                                                 Stack trace of thread 57:
                                                 #0  0x00000000004894aa time.parse (/usr/local/bin/runsc (deleted) + 0x894aa)
                                                 #1  0x00000000007374d5 gvisor.dev/gvisor/pkg/sentry/device.(*Registry).StateLoad (/usr/local/bin/runsc (deleted) + 0x3374d5)
                                                 #2  0x0000000000f25a4e gvisor.dev/gvisor/runsc/cmd.makeFile (/usr/local/bin/runsc (deleted) + 0xb25a4e)

                                                 Stack trace of thread 20:
                                                 #0  0x00000000004894aa time.parse (/usr/local/bin/runsc (deleted) + 0x894aa)
                                                 #1  0x000000c0002e6ec0 n/a (n/a + 0x0)

```

The stacktrace looks weird considering that SECCOMP terminates us at syscall=13 ( rt_sigaction ). Am i reading this right ?

**Environment**

Please include the following details of your environment:

*   `runsc -version`: `runsc version 64dde8ff3421`

**Comment by fvoznika** [comment]
gVisor sandbox is allowed to call [rt_sigaction](https://cs.opensource.google/gvisor/gvisor/+/master:runsc/boot/filter/config.go;l=264;drc=1336af78d5dc2a6bc54d22ed45f4dd4793c2f964), so it's likely that it's the [gofer process](https://cs.opensource.google/gvisor/gvisor/+/master:runsc/fsgofer/filter/config.go) that is hitting it. The Go Runtime calls `rt_sigaction`, but it normally does during startup, before the seccomp rules are installed. The stacks above are not symbolized correctly, so I wouldn't look much into that.

Do you have a way to repro it? What version of Go compiler are you using? We could add `rt_sigaction` to the list of allowed syscalls, but I'd like to first understand where the call is coming from.

**Comment by dqminh** [comment]
@fvoznika we are still seeing this, indeed it's coming from gofer

```
Core was generated by `runsc-gofer --root=/var/run/runsc --traceback=single --panic-log=/proc/148497/f'.
```

But stacktrace when viewing with delve doesn't quite make sense

```
~/dlv core ./runsc core.exe.0.5147da1df1534b03a85af17ca7dec714.151183.1612960049000000
Type 'help' for list of commands.
(dlv) bt
0  0x00000000004720fb in runtime.rt_sigaction
   at src/runtime/sys_linux_amd64.s:365
1  0x0000000000489485 in syscall.Syscall6
   at src/syscall/asm_linux_amd64.s:41
2  0x000000000070dbbe in gvisor.dev/gvisor/pkg/sentry/socket/unix/transport.(*messageList).StateSave
   at bazel-out/k8-fastbuild-ST-5e46445d989a/bin/pkg/sentry/socket/unix/transport/transport_state_autogen.go:150
```

We don't have a reproducer at the moment. Go version should be 1.15.2, same as set in gvisors' WORKSPACE i think.

**Comment by prattmic** [comment]
One possibility is that the gofer is trying to panic. The Go runtime will [change sigaction](https://cs.opensource.google/go/go/+/master:src/runtime/signal_unix.go;drc=ed3e4afa12d655a0c5606bcf3dd4e1cdadcb1476;bpv=1;bpt=1;l=780?q=rt_sigaction&ss=go) as a fallback if the process fails to die.

I don't recall how difficult it is to get at the gofer's stderr to see if it has printed a panic before getting killed?

**Comment by fvoznika** [comment]
If you run with [`--debug-log=/tmp/runsc/`](https://gvisor.dev/docs/user_guide/debugging/), the panic message will be written to `/tmp/runsc/*.gofer`. @dqminh can you try?

**Comment by dqminh** [comment]
@fvoznika debug-log is too verbose for us as this is not deterministically reproducible as far as i can see, but we can run https://github.com/google/gvisor/pull/5509 and see if it gives us any sane panic log.

**Comment by fvoznika** [comment]
I'm closing the bug because the fix above addresses the seccomp failures. But I'm curious to find out if the gofer is panic'ing. Please create another bug if you find out.
