### ISSUE TITLE
Backwards compatibility is broken with /var/run/runsc/ state files

### ISSUE THREAD

**Issue by prestonp** [google/gvisor#5052]
**Description**

There appears to be a breaking change in https://github.com/google/gvisor/commit/764504c38fb589738f42a852c9288725dcf0f9f9 for the .state files in /var/run/runsc. Note the change in typing for Cgroup struct

Upgrading runsc after this commit seems to break compability with the old .state schema.

Expected behavior: 

1. Run container on old runsc
2. Run container on new runsc (>=https://github.com/google/gvisor/commit/764504c38fb589738f42a852c9288725dcf0f9f9 ) 
3. Both containers should run fine

Observed behavior: In practice, we had running containers, handled a gvisor upgrade but afterwards `runsc run` was broken

```
starting container: loading sandbox containers: loading container "982a25d1-6108-a598-f41b-992bb45a32e8": reading container metadata file "/var/run/runsc/1eace16a-2b79-3443-30dd-ef4205b5e94c.state": json: cannot unmarshal bool into Go struct field Cgroup.sandbox.cgroup.own of type map[string]bool
```

Here, 1eace16a-2b79-3443-30dd-ef4205b5e94c.state is using schema from old version, so we can't manage new containers. `runsc list` also breaks with similar unmarshal error

**Steps to reproduce**

First setup OCI bundle and configure with sleep 9999 to keep it alive

```
mkdir bundle
cd bundle
mkdir rootfs
docker export $(docker create alpine) | tar -xf - -C rootfs
runsc spec -- sleep 9999
```

1. `make runsc` at commit 3a16b829c511757701d4370b8b38d162acb8ba9c
2. `sudo runsc run test1`, let this container run in background
3. `make runsc` at commit 764504c38fb589738f42a852c9288725dcf0f9f9
2. `sudo runsc run test2` fails with following err

**Error**

```
running container: starting container: loading sandbox containers: loading container "test2": reading container metadata file "/var/run/runsc/test1.state": json: cannot unmarshal bool into Go struct field Cgroup.sandbox.cgroup.own of type map[string]bool
```

**Environment**

Please include the following details of your environment:

*   `runsc -version` `runsc version release-20201117.0-37-g764504c38fb5 spec: 1.0.1-dev`
*   `docker version` or `docker info` N/A
*   `kubectl version` and `kubectl get nodes` N/A
*   `uname -a` Linux devbox 5.8.0-23-generic #24~20.04.1-Ubuntu SMP Sat Oct 10 04:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
*   `git describe` (if built from source) release-20201117.0-37-g764504c38
*   `runsc` debug logs (if available) N/A

**Comment by hbhasker** [comment]
@avagin I believe had a fix for this issue.

**Comment by hbhasker** [comment]
Does that fix your issue?

**Comment by prestonp** [comment]
@hbhasker yeah opened PR which resolved for me

**Comment by hbhasker** [comment]
Thanks. Closing
