### ISSUE TITLE
Support OCI field oomScoreAdj

### ISSUE THREAD

**Issue by ianlewis** [google/gvisor#512]
The oomScoreAdj for the container should be used. This is important for QoS for Kubernetes etc.
https://github.com/opencontainers/runtime-spec/blob/master/config.md#linux-process

**Comment by ianlewis** [comment]
Related to #511

**Comment by ianlewis** [comment]
We may have issues if the gofer process is killed via the OOM killer but not the sandbox. #601

**Comment by ianlewis** [comment]
Still doing some work on this.

**Comment by ianlewis** [comment]
One thing that needs more investigation is init containers. We should make sure gVisor adjusts the oom_score_adj for the sandbox on RemoveContainer. However, a cursory look indicates that Kubernetes will do a CreateContainer request for init containers but may not do a RemoveContainer request. Which means that oomScoreAdj for init containers could affect the sandbox for regular pod containers if the score is lower than the pod's containers.

So we may need to make changes in the kubelet to issue a RemoveContainer request when init containers have finished, or have some kind of special processing in runsc.

**Comment by ianlewis** [comment]
Fixed by 0bfffbcb0163cc7ebb0cbf47fa91247d208502be

**Comment by fvoznika** [comment]
There are TODOs still referencing it:

**Comment by fvoznika** [comment]
There TODOs still referencing this bug:
https://github.com/google/gvisor/blob/ca90dad0e21c758925968d217ad15a05015bd82c/runsc/container/container.go#L1087
