### ISSUE TITLE
Support container v2 config format in doc?

### ISSUE THREAD

**Issue by inductor** [google/gvisor#5170]
**Description**

Currently [the official doc](https://gvisor.dev/docs/user_guide/containerd/configuration/) describes how to configure containerd with their config v1 format.

Now contained recommend v2 format
Ref. https://github.com/containerd/containerd/issues/4783

**Is this feature related to a specific bug?**

Please include a bug references if yes.

**Do you have a specific solution in mind?**

Please include any details about a solution that you have in mind, including any
alternatives considered.

**Comment by inductor** [comment]
@kevinGC @ianlewis Could I have some update on it? :)

**Comment by ianlewis** [comment]
I'll look at it when I get a chance.

**Comment by inductor** [comment]
@ianlewis I tried this setup procedure and it worked like a charm thank you friend!
