### ISSUE TITLE
tcp doesn't build on 386 or other 32-bit platforms

### ISSUE THREAD

**Issue by bradfitz** [google/gvisor#5241]
The `tcpip/transport/tcp` package doesn't build on 386 or other 32-bit platforms:

```
../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210109011639-2fb7a49fea98/pkg/tcpip/transport/tcp/snd.go:339:16: constant 9223372036854775807 overflows int
```

Because of this assignment of `math.MaxInt64` to a struct field of type `int`:

https://github.com/google/gvisor/blob/0c92b3782ae641b59d512a922f766721a34d7e9e/pkg/tcpip/transport/tcp/snd.go#L339

struct field:
https://github.com/google/gvisor/blob/0c92b3782ae641b59d512a922f766721a34d7e9e/pkg/tcpip/transport/tcp/snd.go#L129

Add some 32-bit CI too?

**Comment by hbhasker** [comment]
See: Pending PR https://github.com/google/gvisor/pull/814 I will try and revive that and get it merged.

**Comment by prattmic** [comment]
Duplicate of #1446.
