### ISSUE TITLE
runsc restore documentation/cmd is contradictory

### ISSUE THREAD

**Issue by travigd** [google/gvisor#5266]
**Description**

The documentation (at https://gvisor.dev/docs/user_guide/checkpoint_restore/) suggests that the `runsc restore` command is meant to mirror `runsc start`:

> restore is a command which parallels start

but it actually mirrors `runsc run`.

The easy solution is to update the docs (a one word change), but seems like `runsc restore` **should** be like `start` (since `run` is effectively just `create` and `start` together).

**Comment by ayushr2** [comment]
> but it actually mirrors runsc run

Why do you say so? `runsc run` is equivalent to `Create + Start + Wait`. `runsc restore` and `runsc start` are alike, they just "start" an already-created container.

`runsc restore` is invoked by `docker start --checkpoint CHECKPOINT_ID` when using docker. I think it is correct to say that it is like `runsc start`.
