### ISSUE TITLE
sched_setattr: Function not implemented

### ISSUE THREAD

**Issue by Ox24** [google/gvisor#53]
Hey there, 
wanted to test some realtime scheduling and tried to measure some timings and overhead caused by gvisor. 

Using the debug flag on gvisor, i noticed that i get:

` write(0x4, 0x7facec000af0 "sched_setattr: Function not implemented\n", 0x28)`

therefore i cannot run and test my application. Any advices?

docker command : docker run --runtime=runsc --cap-add SYS_NICE -i -d -t simple-interpolation
docker version: Docker version 18.03.1-ce
uname -a : 4.9.84-rt62 SMP PREEMPT RT Tue May 8 18:11:18 CEST 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Ox24** [comment]
sadly that is not an option for me. We are running different RT applications on our system using docker and wanted to isolate some of them. Do you guys have a in-depth descritption on how gvisor works?

**Comment by ianlewis** [comment]
I suggest changing the bug title to "sched_setattr: Function not implemented"

**Comment by fvoznika** [comment]
Closing as this is something unlikely to be supported.
