### ISSUE TITLE
Unix datagram sockets not working with socat

### ISSUE THREAD

**Issue by Gasparila** [google/gvisor#5323]
**Description**
Sending unix datagram does not appear to be working when using gvisor+docker.
Unix domain (stream) sockets, on the other hand, appear to work

**Steps to reproduce**
This works (unix domain socket):
```
process 1: socat UNIX-LISTEN:test.sock,fork - # prints "test"
process 2: echo "test" | socat - UNIX-CONNECT:test.sock
```
But this does not (unix datagram socket):
```
process 1: socat UNIX-RECV:test.sock - 
process 2: echo "test | socat - UNIX-SENDTO:test.sock # hangs
```

If I remove the `--runtime=runsc` from my `docker run` command, both of these 2 examples work

**Environment**

Please include the following details of your environment:

*   `runsc -version`: Tried on `runsc version release-20210112.0-47-g7ff5ceaeae66` and `runsc version release-20200622.1-1-g8c82d75f989d`

*   `docker version` or `docker info` (if available): `Docker version 20.10.2, build 2291f61`
*   `uname -a`: `Linux 4.4.0 #1 SMP Sun Jan 10 15:06:54 PST 2016 x86_64 x86_64 x86_64 GNU/Linux`

Docker daemon.json config:
```
{
    "runtimes": {
        "runsc": {
            "path": "runsc",
            "runtimeArgs": [
                "--network=none",
                "--fsgofer-host-uds"
            ]
        }
    }
}
```

**Comment by jackloomen** [comment]
Hopefully I'm doing something wrong but I'm unable to get unix stream sockets to work with --fsgofer-host-uds.

The Wayland socket is not functional:
oci config.json:

```
        {
            "destination": "/run/user/1000/wayland-0",
            "source": "/run/user/1000/wayland-0",
            "type": "rbind",
            "options": ["rw"]
        }
```

**Comment by ayushr2** [comment]
I can still reproduce this issue.
