### ISSUE TITLE
Report pod limits inside Sentry

### ISSUE THREAD

**Issue by fvoznika** [google/gvisor#5358]
Forked from https://github.com/google/gvisor/issues/190#issuecomment-767203156

When deploying a pod with limits, k8s sets up a cgroup for the pod with the aggregate of all container's limits. However, this information is not passed down to the runtime. Only the piece meal, container by container limit is passed down as containers are created. This leads to the correct limits for the pod being respected, but not reported correctly inside the sandbox.

It's possible to keep track of the limits, aggregating then inside the container manager and updating what's reported inside the sentry based on it. Special care need to be take when containers are restarted so that the limits are applied correctly.

**Comment by fvoznika** [comment]
This has been fixed with a combination of d96499d17deb4fcf4cec949d90a48b1673198867 and 33b41d8fe98e7820118e8d42b0cfbec4ca159d62.

**Comment by nsoubelet** [comment]
> This has been fixed with a combination of [d96499d](https://github.com/google/gvisor/commit/d96499d17deb4fcf4cec949d90a48b1673198867) and [33b41d8](https://github.com/google/gvisor/commit/33b41d8fe98e7820118e8d42b0cfbec4ca159d62).
> 
> /cc @nsoubelet

That's amazing! Thanks
