### ISSUE TITLE
platform=kvm not stable in nested KVM setup

### ISSUE THREAD

**Issue by majek** [google/gvisor#5395]
**Description**

For testing, I'm attempting to run gvisor with --platform=kvm inside a KVM virtual machine on linux. It often works, but sometimes hangs or fails to start. I suspect there is some instability in kvm inner workings.

Host CPU i7-5557U CPU, host kernel 5.10.0-rc3, guest kernel 5.9.0-0.bpo.5-amd64. Runsc version: 18bb9fc5205e spec: 1.0.1-dev.

**Steps to reproduce**

Run kvm with debian on host:
```
$ kvm -hda xxx.img -m 2048 -net nic -net user -cpu host
```

In kvm guest run the "runsc do":
```
guest@guest:~$ sudo runsc --debug --platform=kvm do echo hello world
hello world
```

Most often it works. But sometimes I see
```
guest@guest$ sudo runsc --debug --platform=kvm do echo hello world
creating container: waiting for sandbox to start: EOF
```

Running with strace produces different result - in the bad case I can see plenty of SIGSEGV in strace logs:
```
guest@guest$ sudo strace -f -o log.txt runsc --debug --platform=kvm do echo hello world
<hangs>

$ cat log.txt
2402  nanosleep({tv_sec=0, tv_nsec=40000},  <unfinished ...>
2398  rt_sigreturn({mask=[]})           = 14488992
2408  <... nanosleep resumed> NULL)     = 0
2408  nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
2398  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffff80c0002800f8} ---
2402  <... nanosleep resumed> NULL)     = 0
2402  nanosleep({tv_sec=0, tv_nsec=80000},  <unfinished ...>
2398  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffff80c000280100} ---
2408  <... nanosleep resumed> NULL)     = 0
2408  nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
2398  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffff80c000280100} ---
2398  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffff80c000280100} ---
2398  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffff80c000280100} ---
2398  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffff80c000280100} ---
2398  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffff80c000280100} ---
...
```

Ideally I would expect runsc --platform=kvm to be stable/deterministic in nested kvm environment.

**Comment by amscanne** [comment]
Hm, I'll try to give this a shot when I have some free cycles. Nested can be quite a bit different than non-nested, and has historically required some workarounds for weird/broken kernel behavior. (See the old retryInGuest, and comments in kvm/allocator.go, for example.) This stems primarily from the fact that the kernel must resort to shadowing, and... there are bugs. These bugs typically manifest as the guest state being inconsistent or corrupt.

Based on the strace logs, this could be something like that since the 0xffff80c000280100 address seems like a fault must have occurred in an entrypoint, which "should never happen" (tm).

**Comment by majek** [comment]
I was told that running "5.8.0-23-generic" inside guest alleviates the problem. I haven't had time to validate yet. This gets very interesting.

**Comment by majek** [comment]
I was preparing a better repro and I noticed a couple things. First, setup is easiest with [virtme](https://github.com/amluto/virtme) on native linux:
```
$ ./virtme-run --cpus 4 --rw --pwd --kimg ../linux/arch/x86/boot/bzImage  --memory 1G --script-exec ./repro.sh 
**** runsc --platform=kvm do echo hello world
hello world
***** 0
creating container: waiting for sandbox to start: EOF
***** 128
```

This means first run was ok, and the problem happened on second run.

This requires two things:
 - guest kernel config
 - repro script

Linked here:
https://gist.github.com/majek/d983858629540ac559363d5081e45164

So...
it seems ptrace platform is ok. But... but it's consistently not ok when under strace. I wonder if it's the same problem. Anyhow "runsc do echo hello" (ie: ptrace) works fine under kvm guest, but "strace -f -o log runsc do echo hello" consistently fails.
