### ISSUE TITLE
Incorrect NFS fsstat values (capacity and usage) when doing a 'df -h'

### ISSUE THREAD

**Issue by nsoubelet** [google/gvisor#5457]
**Description**

I have a container with a NFS volume mounted. NFS server is running in a different container.
Driver I am using is the following: https://github.com/kubernetes-csi/csi-driver-nfs

In the NFS server, exported root path has a size limit. When testing NFS server alone, readings obtained using `df -h` were correct, that is, it shows the correct capacity (limit) and current usage.
However, when doing the same operation from within a sandboxed container, readings are incorrect. In fact, something strange is that shows always the same size, 30M, however NFS server is replying the real size, which is 1GB when calling fsstats.

I tried with popular base images: Debian, Ubuntu, Alpine, Busybox, etc.. and for all of them I see the same behavior.

At this point, I am almost sure it is gVisor, since I could not find issues in other layers, that's why I wanted to check with you whether I am the only one experiencing this or it is a known issue/limitation.

**Steps to reproduce**

1. Install plugin [https://github.com/kubernetes-csi/csi-driver-nfs](https://github.com/kubernetes-csi/csi-driver-nfs) in the k8s cluster.
2. Run a nfs server in the cluster. For example this one [https://github.com/ehough/docker-nfs-server](https://github.com/ehough/docker-nfs-server)
3. Create a service to expose the nfs server.
4. Create a PV with driver `nfs.csi.k8s.io` and with the following `volumeAttributes`:
```
server: [service-ip]
  share: [nfs-share-dir]
```
5. Create a PVC to match the recently-created PV.
6. Create a Pod with the PVC mounted.
7. Get container's bash and type `df -h [dir-mounted]`

Value it returns should not be necessarily what NFS is actually replying.

**Environment**

*   `runsc -version`
*   `docker version` or `docker info` (if available)
Using containerd:
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.4.3-k3s1
RuntimeApiVersion:  v1alpha2
*   `kubectl version` and `kubectl get nodes` (if using Kubernetes)
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5+k3s2", GitCommit:"746cf4031370f443bf1230272bc79f2f72de2869", GitTreeState:"clean", BuildDate:"2020-12-18T01:41:55Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
*   `uname -a`
Linux XYZ 4.15.0-130-generic #134-Ubuntu SMP Tue Jan 5 20:46:26 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
*   `git describe` (if built from source)
*   `runsc` debug logs (if available)

**Comment by nsoubelet** [comment]
Sorry, just wanted to highlight something interesting.
The relationship between `size`, `used` and `available` is correct but numbers are not. 
For example:
```
Filesystem      Size  Used Avail Use% Mounted on
none             30M   30M  416K  99% /mnt
```
99% of use is correct (although not precise), but it is not 30M, it is 1GB.
NFS server shows (in bytes):
```
Capacity 1000000000 
Current usage 986377019
```

**Comment by fvoznika** [comment]
gVisor is passing the [information straight from the host](https://cs.opensource.google/gvisor/gvisor/+/master:runsc/fsgofer/fsgofer.go;l=594;drc=9b4f4655ed5ddcbe34806a28b2bc5d8f61fbb215), so I suspect the host is not passing the information correctly for some reason. Did you test it running a container without gVisor?

Please run the repro and collect debug logs.

**Comment by fvoznika** [comment]
gVisor is passing statfs(2) [information straight from the host](https://cs.opensource.google/gvisor/gvisor/+/master:runsc/fsgofer/fsgofer.go;l=594;drc=9b4f4655ed5ddcbe34806a28b2bc5d8f61fbb215), so I suspect the host is not setting the values correctly for some reason.

1. Did you test the same command running in a container without gVisor?
1. Please run the repro and collect debug logs. [Here are instructions](https://gvisor.dev/docs/user_guide/containerd/configuration/) to set debug flags in runsc. In `runsc.toml`, you just need the portion under `[runsc_config]`. Ex:

```toml
[runsc_config]
  debug = "true"
  debug-log = "/tmp/runsc/"
```

If you are using [GKE Sandbox](https://cloud.google.com/kubernetes-engine/docs/concepts/sandbox-pods), this file is in `/run/containerd/runsc/config.toml`. I'm particularly interested in the `*.boot` and `*.gofer` files.

**Comment by nsoubelet** [comment]
Hi @fvoznika 
I am not quite sure that in this case storage was related to host's. Container has a NFS mount in a directory, therefore what is replying to filesystem commands is the NFS server via RPC. I traced it and NFS server is giving correct stats and numbers.

Maybe gVisor statfs does not quite support NFS?

**Comment by fvoznika** [comment]
When statfs(2) is called on a file, the host will figure out the mount and make the correct call, in this case to NFS filesystem which will send an RPC to the server. The logs will show the exact value returned from the statfs(2) call so we can see if the host is returning the correct value or not. Also, confirming that the same case works without gVisor is useful to check if this is not caused by the way volumes are mounted for the container.

**Comment by nsoubelet** [comment]
Understood, thanks @fvoznika 
Give me please a couple of days since to me now it is more difficult to create a container without gVisor, I've got it fully integrated so need to workaround.

**Comment by fvoznika** [comment]
Just checking if you were able to test it. Please reopen if it is still an issue.

**Comment by nsoubelet** [comment]
Hi @fvoznika sorry for not coming back with a comment before. It still does not work, NFS server is working OK, so I guess it is related to gVisor but since I am not currently able to properly demonstrate that, I am OK with closing this.
Thanks for your support!
