### ISSUE TITLE
Implement syscall epoll_pwait2, close_range

### ISSUE THREAD

**Issue by milantracy** [google/gvisor#5500]
**Description**

Implement syscall epoll_pwait2 and close_range for gvisor.

Reference: https://lwn.net/Articles/837816/

**Is this feature related to a specific bug?**

N/A

**Do you have a specific solution in mind?**

N/A

**Comment by milantracy** [comment]
plan to work on the implementation, can anyone assign the issue to me?

**Comment by hbhasker** [comment]
Done.
