### ISSUE TITLE
network=sandbox error when route default via dev wireguard - getting routes for interface "wg0": default route with no gateway

### ISSUE THREAD

**Issue by ghost** [google/gvisor#5568]
runsc binary master head
linux void glibc (kernel 5.10.15_1)

network namespace setup:
rc.local (on boot) part:

```
ip netns add vpn_ny7
ip -n physical link add wg1 type wireguard
ip -n physical link set dev wg1 mtu 1420
ip -n physical link set wg1 netns vpn_ny7
ip -n vpn_ny7 link set wg1 name wg0
ip -n vpn_ny7 link set dev lo up
ip netns exec vpn_ny7 iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
```

service start part:

```
ip -n vpn_ny7 addr add 10.11.10.77/32 dev wg0
ip netns exec vpn_ny7 wg setconf wg0 /etc/wg/vpn_ny7.conf
ip -n vpn_ny7 link set wg0 up
ip -n vpn_ny7 route add default dev wg0
```

oci config.json relevant part:

```
            {
                "type": "network",
                "path": "/var/run/netns/vpn_ny7"
            }
```

command: sudo /custom_bin/runsc run test

output:

`running container: starting container: setting up network: creating interfaces from net namespace "/proc/28100/ns/net": getting routes for interface "wg0": default route with no gateway "wg0": {Ifindex: 4 Dst: <nil> Src: <nil> Gw: <nil> Flags: [] Table: 254}`

--network=host works fine.

**Comment by hbhasker** [comment]
Kevin,

Could you take a look at the report.
