### ISSUE TITLE
Check for getcwd when size is zero but addr is not NULL

### ISSUE THREAD

**Issue by chanwit** [google/gvisor#56]
I added more checks for `getcwd`. From the man page:

```
       EINVAL The size argument is zero and buf is not a null pointer.

       EINVAL getwd(): buf is NULL.

       ENAMETOOLONG
              getwd(): The size of the null-terminated absolute pathname
              string exceeds PATH_MAX bytes.
```
The first `EINVAL` check seems to be OK to me, but I'm not sure if the second `EINVAL` and the third `ENAMETOOLONG` checks are necessary?

**Comment by chanwit** [comment]
Revert to be only one check as the second and the third check were fr `getwd`, not `getcwd`.

**Comment by prattmic** [comment]
That `EINVAL` check is actually a glibc feature, not a kernel feature. (Note that most syscall man pages are for the glibc wrapper, technically not the actual syscall.)

Consider:

```c
#include <errno.h>
#include <stdio.h>
#include <unistd.h>
#include <asm/unistd.h>

int main(void) {
  char buf[256] = {};

  errno = 0;
  getcwd(buf, 0);
  printf("libc getcwd errno = %d\n", errno);

  errno = 0;
  syscall(__NR_getcwd, buf, 0);
  printf("kernel getcwd errno = %d\n", errno);

  return 0;
}
```

```
$ ./getcwd
libc getcwd errno = 22
kernel getcwd errno = 34
```

[Kernel code](https://elixir.bootlin.com/linux/latest/source/fs/dcache.c#L3477)
[glibc code](https://github.com/bminor/glibc/blob/master/sysdeps/unix/sysv/linux/getcwd.c#L46) (the `EINVAL` return is on L57)

**Comment by chanwit** [comment]
Thank you @prattmic. I shall close this then.
I'm now getting more idea on how to check the compatibility. Thanks again.
