### ISSUE TITLE
Free Memory

### ISSUE THREAD

**Issue by cerenarpaci** [google/gvisor#5608]
**Description**
runc:
<img width="460" alt="runsc" src="https://user-images.githubusercontent.com/43756284/109838728-7ad96a80-7c57-11eb-8f58-b036f27846bc.png">
runsc:
<img width="434" alt="runc" src="https://user-images.githubusercontent.com/43756284/109838736-7d3bc480-7c57-11eb-9e4b-575cabd48cd0.png">

When I compare the total memory inside a standard Docker container and Docker with gVisor, there is a significant difference that affect the performance of my application. Main question is how do I increase the free memory for my gvisor secured containers?

**Steps to reproduce**

Start a Docker container, inside the container check "cat /proc/meminfo". Do the same with a container that uses runsc as runtime. 
**Environment**

Please include the following details of your environment:

*   gVisor version `runsc version release-20210201.0
spec: 1.0.1-dev`
*   Docker version `20.10.2`

**Comment by fvoznika** [comment]
It seems that the screenshots above are mixed. gVisor always reports MemFree and MemeAvailable the same, so the top one must be for runsc (gVisor) and the bottom one for runc. gVisor is actually reporting more free memory that runc, so I'm not sure this is the cause of the performance problems you're having.

If you can, please provide more details about the application and what kind of performance problems you see.

**Comment by cerenarpaci** [comment]
Hi There, apologies for the confusion with the images. Could you confirm with me if the runsc is using the maximum memory available on the host?

**Comment by fvoznika** [comment]
> Hi There, apologies for the confusion with the images. Could you confirm with me if the runsc is using the maximum memory available on the host?

Yes, gVisor will be able to use all memory available on the machine, respecting memory limits that may have been set to the container. gVisor is hiding the amount of free memory on the machine so that host information is not leaked to the container. Granted that this may cause problems for applications that use this information to size themselves. Docker on the other hand reports the total free memory on the machine, ignoring container limits that may exist, which can also confuse applications.

If your application is using free memory value to change runtime behavior, I'd like to learn more about how it's using it and how we can change memory reporting to work well with it.

**Comment by blockTokenTech** [comment]
I've also run into this same issue trying to run xmrig within a docker container (https://xmrig.com/)
Here is the docker container https://hub.docker.com/r/metal3d/xmrig or https://github.com/metal3d/docker-xmrig

When xmrig initialises it looks for available memory as the faster hashing implementations require a lot more memory.  Irrespective of actual memory available it thinks that there is only 2 gigs so it uses the slower implementation.

**Comment by blockTokenTech** [comment]
FYI the Akash network (https://akash.network/) is using gvisor so if you spin up an instance on Akash you suffer from this problem. I think. New to Akash and gvisor

**Comment by cerenarpaci** [comment]
Hi there, apologies for the late response. My application checked the free memory available on the machine in runtime, and since gVisor does not report the actual value due to security reasons, my application could not use all available space. I have stop working on the application so I if you like to close the issue it wouldn't be a problem from my side. Thanks for the guidance @fvoznika

**Comment by pkit** [comment]
> Docker on the other hand reports the total free memory on the machine, ignoring container limits that may exist, which can also confuse applications.

Doesn't it mean that the better course of action would be to really use the container limits instead of machine limits?
