### ISSUE TITLE
faile to build with `gvisor/pkg/tcpip/stack`

### ISSUE THREAD

**Issue by sbilly** [google/gvisor#5636]
**Description**

faile to build with `gvisor/pkg/tcpip/stack`.

**Steps to reproduce**

```
# go mod init main
# go mod tidy
# go mod vendor
# go build main.go
vendor/gvisor.dev/gvisor/pkg/linewriter/linewriter.go:21:2: found packages sync (aliases.go) and seqatomic (generic_atomicptr_unsafe.go) in /<SOMEDIR>/vendor/gvisor.dev/gvisor/pkg/sync

```

the `main.go` :

```go
package main

import (
        "gvisor.dev/gvisor/pkg/tcpip/stack"
)

type VirtualNetwork struct {
        stack         *stack.Stack
}

func main() {
        return
}

```

the `go.mod`:

```go
module main

go 1.16

require gvisor.dev/gvisor v0.0.0-20210309044034-abbdcebc5432
```

if modify `go.mod` to use different version `gvisor/pkg/tcpip/stack`, `go build` works fine.

```go
module main

go 1.16

require gvisor.dev/gvisor v0.0.0-20210106030213-99534ddb4e66
```

```
# go mod tidy
# go mod vendor
# go build main.go
```

**Environment**

```
# go version
go version go1.16 linux/amd64
```

**Comment by sbilly** [comment]
any help?

**Comment by amscanne** [comment]
The main branch is built with bazel. If you want to use the Go tools, you'll need to use the Go branch, as described here:
https://github.com/google/gvisor#using-go-get

Your second commit is on the Go branch, and the first one isn't.

**Comment by amscanne** [comment]
Feel free to reopen if there are any issues with the Go branch itself, but the primary branch does not support the Go tools alone. (There are many are parts that are built in other languages, etc.)
