### ISSUE TITLE
tcpip bad atomic alignment 32-bit ARM

### ISSUE THREAD

**Issue by abarisani** [google/gvisor#5692]
Hello.

While https://github.com/google/gvisor/issues/1446 addresses compilation of the tcpip package on 32-bit systems, its execution still fails (at least on 32-bit ARM) due to [sync/atomic known limitations](https://golang.org/pkg/sync/atomic/#pkg-note-BUG).

Here is one example (the stack trace is from http://inet.af/netstack fork but the code base is gvisor one):

panic: unaligned 64-bit atomic operation

```
goroutine 1 [running]:
runtime/internal/atomic.panicUnaligned()
        runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Store64(0x82f264ac, 0x8000, 0x0)
        runtime/internal/atomic/asm_arm.s:278 +0x14
inet.af/netstack/tcpip.(*SocketOptions).SetSendBufferSize(0x82f26440, 0x8000, 0x0, 0x0)
        inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/socketops.go:607 +0x17c
inet.af/netstack/tcpip/transport/icmp.newEndpoint(0x82c36380, 0x800, 0x1, 0x82c0b2c0, 0x96, 0x0, 0x97, 0x20)
        inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/icmp/endpoint.go:102 +0x118
inet.af/netstack/tcpip/transport/icmp.(*protocol).NewEndpoint(0x82c0e888, 0x800, 0x82c0b2c0, 0x82c4039c, 0x803fe201, 0x1, 0x82c0b2c0)
        inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/icmp/protocol.go:66 +0x70
inet.af/netstack/tcpip/stack.(*Stack).NewEndpoint(0x82c36380, 0x1, 0x800, 0x82c0b2c0, 0x0, 0x0, 0x0, 0x0)
        inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/stack/stack.go:885 +0x68
main.startICMPEndpoint(0x82c36380, 0x82c1793c, 0x4, 0x82c30000, 0x1)
```

There are at least two occurrences of unaligned 64-bit atomic operations that we had to work around:

* https://github.com/google/gvisor/blob/master/pkg/tcpip/socketops.go#L598
* https://github.com/google/gvisor/blob/master/pkg/tcpip/tcpip.go#L1222

(Our crude work arounds are linked at https://github.com/google/gvisor/issues/1446#issuecomment-801861414).

**Comment by kevinGC** [comment]
@abarisani I like your workaround. I'm thinking it might be good to wrap this in it's own type too -- I'll give it a try.

**Comment by abarisani** [comment]
It appears that the fix is incomplete, this currently happens with `gvisor.dev/gvisor v0.0.0-20210515002610-8665ce2587e9`

```
panic: unaligned 64-bit atomic operation

goroutine 1 [running]:
runtime/internal/atomic.panicUnaligned()
        runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Store64(0x82c621dc, 0x8000, 0x0)
        runtime/internal/atomic/asm_arm.s:278 +0x14
gvisor.dev/gvisor/pkg/tcpip.(*SocketOptions).SetReceiveBufferSize(0x82c6215c, 0x8000, 0x0, 0x0)
        gvisor.dev/gvisor@v0.0.0-20210515002610-8665ce2587e9/pkg/tcpip/socketops.go:662 +0x1ac
gvisor.dev/gvisor/pkg/tcpip/transport/icmp.newEndpoint(0x82c36380, 0x800, 0x1, 0x82c0b220, 0x91, 0x0, 0x92, 0x20)
        gvisor.dev/gvisor@v0.0.0-20210515002610-8665ce2587e9/pkg/tcpip/transport/icmp/endpoint.go:105 +0x13c
gvisor.dev/gvisor/pkg/tcpip/transport/icmp.(*protocol).NewEndpoint(0x82c0e880, 0x800, 0x82c0b220, 0x82c403ec, 0x80401901, 0x1, 0x82c0b220)
        gvisor.dev/gvisor@v0.0.0-20210515002610-8665ce2587e9/pkg/tcpip/transport/icmp/protocol.go:66 +0x70
gvisor.dev/gvisor/pkg/tcpip/stack.(*Stack).NewEndpoint(0x82c36380, 0x1, 0x800, 0x82c0b220, 0x0, 0x0, 0x0, 0x0)
        gvisor.dev/gvisor@v0.0.0-20210515002610-8665ce2587e9/pkg/tcpip/stack/stack.go:611 +0x68
```

**Comment by kevinGC** [comment]
I've made another change in #6009.

In the future, it would be really helpful to receive pull requests for this issue. A small pull request (like #6009) is likely the fastest way to resolve the issue. gVisor doesn't officially support 32-bit ARM, so this is all being done on a best-effort basis.

The underlying reason for these breakages is that there are no automated tests for the relevant architectures (ARM32, MIPS, and i386) because we don't *officially* support them. So when an issue pops up, it won't be caught immediately.
