### ISSUE TITLE
Reading 128 bytes from /proc/net/route makes file appear truncated

### ISSUE THREAD

**Issue by DentonGentry** [google/gvisor#5732]
**Description**

In Cloud Run, /proc/net/route has two entries. Each line is 128 bytes long (padded with spaces as needed), 384 bytes total including the header line.

```
Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRTT
eth0 8008FEA9 00000000 0001 0 0 0 01FFFFFF 0 0 0
eth1 00000000 00000000 0001 0 0 0 00000000 0 0 0
```

If I read the whole 384 bytes at once, everything is fine:
```
openat(AT_FDCWD, "/proc/net/route", O_RDONLY|O_CLOEXEC) = 7
read(7, "Iface\tDestination\tGateway\tFlags\t"..., 512) = 384
read(7, "", 128) = 0
```

If I read the first 128 bytes and try to go back for the next 128 bytes, read returns 0 instead.
```
openat(AT_FDCWD, "/proc/net/route", O_RDONLY|O_CLOEXEC) = 3
read(3, "Iface\tDestination\tGateway\tFlags\t"..., 128) = 128
read(3, "", 128) = 0
```

It seems like I can do a series of small reads until we reach the end of the first line with the column headers, which is 128 bytes long. Once we reach the end of the first line, any subsequent read will return 0 and set EOF. The lines with route entries can only be read as a single large read.

**Steps to reproduce**

If available, please include detailed reproduction steps.

If the bug requires software that is not publicly available, see if it can be
reproduced with software that is publicly available.

I wrote a small Go program as a minimal test case:

```
package main

import (
        "flag"
        "fmt"
        "io"
        "os"
)

func main() {
        n1 := flag.Int("bytes1", 128, "nbytes for first read.")
        n2 := flag.Int("bytes2", 128, "nbytes for second read.")
        flag.Parse()

        f, err := os.Open("/proc/net/route")
        if err != nil {
                panic(err)
        }
        defer f.Close()

        buf := make([]byte, *n1)
        rc, err := f.Read(buf)
        if err != nil {
                panic(err)
        }
        fmt.Printf("#1: read(%d) = %d\n", *n1, rc)

        buf = make([]byte, *n2)
        rc, err = f.Read(buf)
        if err == io.EOF {
                fmt.Printf("#2: read(%d) = EOF\n", *n2)
        } else if err != nil {
                panic(err)
        } else {
                fmt.Printf("#2: read(%d) = %d\n", *n2, rc)
        }
}
```

When run with various arguments on a Google Cloud Run system on 25 Mar 2021, it returned:

proc_route --bytes1=128 --bytes2=128
#1: read(128) = 128
#2: read(128) = EOF

proc_route --bytes1=1 --bytes2=1
#1: read(1) = 1
#2: read(1) = 1

proc_route --bytes1=1 --bytes2=127
#1: read(1) = 1
#2: read(127) = 127

proc_route --bytes1=256 --bytes2=256
#1: read(256) = 256
#2: read(256) = EOF

proc_route --bytes1=512 --bytes2=128
#1: read(512) = 384
#2: read(128) = EOF

**Environment**

Please include the following details of your environment:

*   `runsc -version`
Unknown (Cloud Run)

*   `docker version` or `docker info` (if available)
Unknown (Cloud Run)

*   `kubectl version` and `kubectl get nodes` (if using Kubernetes)
N/A

*   `uname -a`
Linux localhost 4.4.0 #1 SMP Sun Jan 10 15:06:54 PST 2016 x86_64 Linux

*   `git describe` (if built from source)
N/A

*   `runsc` debug logs (if available)
N/A

**Comment by prattmic** [comment]
cc @hbhasker

**Comment by prattmic** [comment]
cc @fvoznika @nlacasse @nixprime This might be a VFS1 or VFS2 only bug?

**Comment by nixprime** [comment]
I'm fairly sure this is a VFS1-only bug.

Certain dynamically-generated files in VFS1, including `/proc/net/route`, use `fs/proc/seqfile.SeqFile` in their implementation. This utility has a fairly complex interface. The actual contents of the file are generated by interface method `SeqSource.ReadSeqFileData()`, which returns a slice of records of type `SeqData`. Each `SeqData` consists a `string` containing the record's data, as well as a `seqfile.SeqHandle == interface{}` "handle". Every read from the `SeqFile` returns data through the end of the last incompletely-read `SeqData`, then (if `SeqSource.NeedsUpdate()` returns true, which is the case for ~every implementation) calls `SeqSource.ReadSeqFileData()` with the handle of said last `SeqData` to get new records, expecting `ReadSeqFileData()` to return updated records after the given handle.

Many users of `SeqFile` only return a single `SeqData`, so the presence of any handle indicates that the single `SeqData` was read and EOF has been reached. For example, the implementation of `/proc/[pid]/stat` does:

```
func (s *taskStatData) ReadSeqFileData(ctx context.Context, h seqfile.SeqHandle) ([]seqfile.SeqData, int64) {
	if h != nil {
		return nil, 0
	}
	// ...
	return []seqfile.SeqData{{Buf: buf.Bytes(), Handle: (*taskStatData)(nil)}}, 0
}
```

However, many `/proc/net/` files return one `SeqData` for each interface (and often one for each header line as well). In this case, copying the `if h != nil { return nil, 0 }` logic is incorrect, and causes EOF to be indicated after having read *any* `SeqData` to completion.

The equivalent of `proc.SeqFile` in VFS2 is `vfs.DynamicBytesFileDescriptionImpl`, which despite the much longer name has a much simpler interface: when necessary (roughly speaking, on first read or after `lseek()`), interface method `vfs.DynamicBytesSource.Generate()` is called to emit the file's contents in its entirety, with no handles or slices of records involved. So this bug shouldn't exist in VFS2.
