### ISSUE TITLE
loader.loadPath overuses remainingTraversals

### ISSUE THREAD

**Issue by prattmic** [google/gvisor#574]
loadPath (https://github.com/google/gvisor/blob/753da9604efc74dced3055bb2f5c6bef2d98fe6c/pkg/sentry/loader/loader.go#L141) is passed a single version of remainingTraversals to track symlink traversals. However, that count is used for:

1. Initial file path resolution.
2. ELF interpreter path resolution.
3. (or) Interpreter script interpreter path resolution.
4. (and then) that interpreter's ELF interpreter (and so on...).

We need to double check, but I think that each of these path resolutions should get their own symlink traversal limit.

Not high priority, as the default limit (40) is high enough that hitting the limit is unlikely.

**Comment by cedric05** [comment]
shall i look?

**Comment by Liloyoung** [comment]
Am 03.08.2019 8:15 AM schrieb Shiva Prasanth <notifications@github.com>:shall i look?

**Comment by prattmic** [comment]
@cedric05 sure, feel free to take a stab at it! I don't think that anyone has started work on this.
