### ISSUE TITLE
createAt should return permission denied when trying to overwrite /proc/cpuinfo from inside a container

### ISSUE THREAD

**Issue by chanwit** [google/gvisor#58]
I developed a test case like this, try to overwrite `/proc/cpuinfo` from inside a container:
```
	filename := "/proc/cpuinfo"
	log.Infof("filename = %s", filename)

	fd, err := raw.Open(filename, s.O_CREAT | s.O_WRONLY | s.O_TRUNC, s.S_IRUSR | s.S_IWUSR)
	log.Infof("fd = %v", fd)
	log.Infof("err = %d", err)

	if fd != -1 {
		t.Fatal("Expect FD = -1")
	}
	if fmt.Sprintf("%d", err) != "13" {
		t.Fatal("Expect Err = 13")
	}
```
When running this test case in `runc` (as root inside a container) via `docker run`, the test case returned 13, permission denied.

But with gVisor, it returned 22, invalid operation.

To check this, I put some breakpoints to runsc.
![gdlv_open_createat](https://user-images.githubusercontent.com/10666/40435283-874fde2c-5eda-11e8-9b00-5baaa2073147.png)

What I have found is that:
Permission checking at:
https://github.com/google/gvisor/blob/master/pkg/sentry/syscalls/linux/sys_file.go#L314
should return 13, but return nil.

Then it pass through to:
https://github.com/google/gvisor/blob/master/pkg/sentry/syscalls/linux/sys_file.go#L321
because there's a check for the flag `O_TRUNC`. This is where it returns 22.

**Comment by cedric05** [comment]
can i work on it?

**Comment by amscanne** [comment]
Absolutely! Let us know if you have any questions (here or on the gvisor-dev mailing list).

**Comment by cedric05** [comment]
@amscanne i raised pr

**Comment by ianlewis** [comment]
@cedric05 @chanwit The patch was merged so I'm going to go ahead and close this issue. Please reopen if there are still issues outstanding.

**Comment by chanwit** [comment]
Hi @cedric05 this is great! I'm glad it get fixed.

It's a very long opened bug report of mine and I almost forget how to reproduce it because this test case was mechanically generated :-)
