### ISSUE TITLE
Debian package seems to overwrite local changes to runsc.toml

### ISSUE THREAD

**Issue by dseomn** [google/gvisor#5817]
**Description**

My changes to /etc/containerd/runsc.toml seemed to have been overwritten with the default version of that file. I noticed it right after a package upgrade, but I didn't check before the upgrade, so I guess it's possible something else caused it. I did check https://github.com/google/gvisor/blob/master/debian/BUILD though and I didn't see anything about protecting the config file.

**Steps to reproduce**

Here's what I think happened, but I'm not positive:

1. Install runsc from https://storage.googleapis.com/gvisor/releases
2. Modify /etc/containerd/runsc.toml
3. Upgrade runsc

**Environment**

Distribution: Debian GNU/Linux bullseye/sid

Line from `apt dist-upgrade` that I think caused the issue:
```
Unpacking runsc (20210408.0) over (20210315.0) ... 
```

**Comment by amscanne** [comment]
I think you're right. That's annoying, sorry about that. I'm pushing a fix and it should be merged soon.
