### ISSUE TITLE
Pods stuck in terminating

### ISSUE THREAD

**Issue by travigd** [google/gvisor#5861]
**Description**

I think this has only started happening since we switched to gVisor.

Occasionally, pods will get stuck in a terminating state. Interestingly, I see there are currently two pods stick in terminating, both on the same node, and both from approximately the same time (they've been stuck for 7h52m and 7h35). I'm running on GKE with the stock gVisor option (nothing exotic).

It seems we have this sequence of events (to the best of my understanding from looking at the logs, attached below):
* K8s kills container
* containerd sends `StopContainer`
* containerd sends kill ten seconds later (corresponding to grace period)
* lots and lots of `context deadline exceeded` messages
* ???
* K8s retries killing, and then gets lots of `cannot kill a deleted process` messages

Logs: https://pastebin.com/tWnG38tb

**Steps to reproduce**

Not sure how to reproduce.

**Environment**

Please include the following details of your environment:

*   `runsc -version` -- whatever version GKE comes with
*   `kubectl version` and `kubectl get nodes` (if using Kubernetes)
    ```
    Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-gke.502", GitCommit:"a2a88ab32201dca596d0cdb116bbba3f765ebd36", GitTreeState:"clean", BuildDate:"2021-03-08T22:06:24Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
    ```
    All nodes running `v1.18.16-gke.502`

**Comment by fvoznika** [comment]
If this is still happening and you have access to the node, please run the command below just to check if runsc or gvisor containerd shim are running. Most likely they are not, but just to confirm: `ps -e f | grep runsc`

If you can repro them occasionally, would it be possible to change `/run/containerd/runsc/config.toml` in some gVisor nodes? This should not affect runtime performance significantly, unless you're starting lots of short lived pods. When it happens again, please collect the logs and send them to us:

```
root = "/run/containerd/runsc"
log_path = "/var/log/runsc/%ID%/shim.log"
log_level = "debug"
[runsc_config]
  platform = "xemu"
  net-raw = "true"
  debug = "true"
  debug-log = "/var/log/runsc/%ID%/gvisor.%COMMAND%.log"
```

**Comment by travigd** [comment]
I see one pod that's stuck in terminating.

Interestingly, it seems to be an init container that's failing to terminate? I'm not sure that this is the same issue as before (I don't remember that being an init container, but those seem to have been cleaned up, perhaps by a node shutting down, so I can't confirm). All of these pods have a brief init container that runs alpine and downloads a binary from GCS.

Running `ps -e f | grep <containerid>` doesn't show any results, so presumably it has successfully shutdown? (`runsc --root ... list` also doesn't show that container).

Re: config change:
Sure, I can. I'm not entirely sure how to do that on GKE (since it's fully managed). Should I install a daemonset on the gvisor nodes to do that? Does it require reloading containerd or anything? And does _send them to us_ just mean another pastebin link?

Thanks for the support! :)

**Comment by travigd** [comment]
@fvoznika I've uploaded the logs for a container that got stuck in this terminating state: https://storage.googleapis.com/user-content.mynerva.io/gvisor-logs-2021-05-03.tar.gz

Also happy to share other logs (from K8s, etc., via stackdriver) if necessary.

**Comment by fvoznika** [comment]
Thanks for the logs. The pod has 4 containers: 
- 4be2a37185b44ff517d284ed60ffe66c7726ce8c66272757415d895cd53e9889 => user container (logs above)
- 3f2082b03d871a073224f3f6184daec1f9a2e1c4562e990b6c96d27e2fb9d768 => user container
- 9a5c68a5e902ed764ba605f2ba0df39814e10d3a81d152d560116619c002d22f => user container
- c9edccd222e61a3765ab4dd2ee3ffa62fe50ff7f5e7efb5fcbbc10bd1693c819 => init container (added by K8s, aka. pause container)

The logs for `4be2a...` look fine, the container was killed and deleted successfully. After deletion, containerd continues to call `events` and `state` for the container, which indicates that containerd still thinks that the container is running. Do you happen to have logs for the other containers in the pod? Most importantly the init container which controls the pod lifecycle.

**Comment by travigd** [comment]
It took a while to re-occur, but I got more logs from a different pod that's exhibiting this behavior: https://storage.googleapis.com/user-content.mynerva.io/gvisor-logs-2021-06-01.tar.gz. Includes logs for the pause container (`sandbox-` folder), the K8s init container (i.e., `spec.initContainers`) (`init-` folder), and the main container (`user-kernel-` folder).

**Comment by fvoznika** [comment]
Thanks for the logs. The init container completes and is deleted correctly. The pause container (sandbox) is never told to be terminated. I believe the problem is a race in containerd with the user container. After the user container is told to stop (kill + delete), containerd continues to call state, stat and kill every few seconds. None of these operations succeed because the container isn't running anymore. I think we need to return "stopped" as the state in this case to get containerd unstuck. We can also make kill return success for SIGTERM and SiGKILL in case the container is already stopped. I need to go through containerd code to check if this theory holds (since I cannot repro it locally) and will implement the changes.

**Comment by fvoznika** [comment]
Travis, the fix above should fix the problem, although I wasn't able to reproduce it myself to check the fix. It would be great if you could test it and let us know if it indeed fixed the issue for you.

**Comment by travigd** [comment]
Thanks. "Testing" as far as I'm concerned is just waiting a while and seeing if it re-occurs. 😎

Not sure if you'd happen to know this, but since I'm running on GKE with GKE Sandbox, I'm not sure how often the gVisor installation is updated there. Is it just included with the usual K8s version updates?

**Comment by fvoznika** [comment]
Great to hear you're using GKE Sandbox! It takes about 2-4 weeks for a change in gVisor to show up in GKE. New changes go to the [Rapid channel](https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels), so you might need to upgrade to a more recent K8s version to get it.
