### ISSUE TITLE
runsc need support cgroup2

### ISSUE THREAD

**Issue by unknowndev233** [google/gvisor#5888]
**Description**

runsc works fine with all cgroup v1 controllers disabled (cgroup v2 may be mounted to /sys/fs/cgroup at this point)

~~Given that mainstream OCI runtime supports cgroup v2, such as runc, and that recent systemd uses cgroup v2 by default to manage services and other things, it is necessary for runsc to support cgroup v2~~

**Is this feature related to a specific bug?**

No. But if this is a must, I can provide

**Do you have a specific solution in mind?**

No.

**Comment by dqminh** [comment]
Duplicate with #3481 i have some wip here https://github.com/google/gvisor/pull/5453, which i'm going to spend some time next week to try to complete it.

cc @fvoznika
