### ISSUE TITLE
track all trackable connections (UDP/ICMP/etc.)

### ISSUE THREAD

**Issue by ghananigans** [google/gvisor#5915]
Tracking connections loosely with UDP/ICMP/etc. is required so iptables can block all incoming connections but allow connections that the host initiated

E.g, rules can look like:

```
ALLOW UDP WHERE CONNECTION IS ESTABLISHED,RELATED
DENY UDP
```

As of writing, we only support TCP

**Comment by ghanan94** [comment]
Still need to track ICMP echo (ping) packets
