### ISSUE TITLE
runsc flag to enable dumping pcaps

### ISSUE THREAD

**Issue by oliverchang** [google/gvisor#5968]
Hi!

Today there is --log-packets, but no way to dump entire pcaps.

Would it be possible to add a flag to runsc to enable dumping pcaps?

**Comment by kevinGC** [comment]
Yep. runsc [has support for pcap logging](https://github.com/google/gvisor/blob/47bc115158397024841aa3747be7558b2c317cbb/pkg/tcpip/link/sniffer/sniffer.go#L126), but there's no command line flag. Adding support would be a small change:

1. Add a flag (maybe `--log-packets-pcap=<filename>`).
2. Send a file descriptor to the sentry during launch.
3. Initialize `sniffer.endpoint` with `NewWithWriter` and that file descriptor.

(Adding @hbhasker in case this is implemented somewhere that I missed)

**Comment by oliverchang** [comment]
Thanks for explaning! Does the the sentry still represent a security boundary for code running within the sandbox though? We are also relying on gVisor for syscall monitoring via strace dumps.

I'm assuming that the "considered untrusted" part is an additional layer of defence due to the its attack surface, rather than untrusted code being easily able to tamper with it?

**Comment by ianlewis** [comment]
@oliverchang Yes. Applications should not be able to tamper with the Sentry under normal circumstances, however they could given a single bug something the Sentry depends on. e.g. it's own code (particularly "unsafe" or platform related code) or the Go runtime.

For that reason, after the untrusted application code starts running, the second layer that the host provides (e.g. seccomp, namespaces) is considered a boundary where you can reasonably assume things haven't been tampered with.
