### ISSUE TITLE
Is `bazel test //...` running in sandbox or host?

### ISSUE THREAD

**Issue by WhoisZihan** [google/gvisor#599]
The README page says I could run tests with `bazel test //...`, I tried and the success/fail/skio rate is 536/12/111.

But it seems to me that all tests are directly running on host instead of sandbox under runsc?

If so, why are the tests running on host if they were meant to test the sandbox?

If not, then this is exactly what I wanted despite the interface is a little vague.

Thanks

**Comment by prattmic** [comment]
Bazel is just the build system, so everything it runs directly is running on the hosts. Tests which must run inside the sandbox need to launch a sandbox themselves. That said, the common case would be system call unit tests, where we have test infrastructure to do this automatically. Any tests wrapped in a [syscall_test rule](https://github.com/google/gvisor/blob/master/test/syscalls/BUILD) will have a target that runs the test on the host (to verify test correctness) and a target that runs in the sandbox.

https://groups.google.com/forum/#!msg/gvisor-users/DVfdi6iSAsU/FHIcCHFnAQAJ

**Comment by ianlewis** [comment]
I think this question is addressed but feel free to follow up if not.
