### ISSUE TITLE
Link-local IPv6 route is treated as a second default route

### ISSUE THREAD

**Issue by 1-z** [google/gvisor#60]
In sandbox/network.go, the logic assumes that there is either a default route for IPv4 or a default route for IPv6. In dual-stack containers, there are default routes for both IPv4 and IPv6, leading to sandbox startup failure.

**Comment by fvoznika** [comment]
Oops, my bad. runsc doesn't support IPv6 at the moment and should be ignoring IPv6 addresses and routes for now.
