### ISSUE TITLE
Stop container when gofer is terminated

### ISSUE THREAD

**Issue by fvoznika** [google/gvisor#601]
Currently, when the gofer process terminates, the container continues to run and returns I/O error for file operations that require the gofer. Instead, the  affected container should be stopped when this happens. If the container to be stopped is the root container, then the entire sandbox should be torn down.

**Comment by ianlewis** [comment]
It's worth noting that the opposite isn't true. If the sandbox terminates unexpectedly the gofer terminates itself properly.
