### ISSUE TITLE
PacketImpact doesn't work with gotsan

### ISSUE THREAD

**Issue by puradox** [google/gvisor#6018]
**Description**

Specifying `--config=gotsan` to a PacketImpact test returns with an error on the test runner:
```
OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: no such file or directory: unknown
```

**Steps to reproduce**

1. Run test `//third_party/gvisor/test/packetimpact/tests:tcp_info_native_test` with Go's thread sanitizer.

**Comment by zeling** [comment]
verified that --config=gotsan works now.
