### ISSUE TITLE
Support adding and removing route via netlink

### ISSUE THREAD

**Issue by liornm** [google/gvisor#6026]
I am currently trying to run OpenVPN client in gVisor environment. OpenVPN requires setting the routing table using /sbin/ip which uses the netlink interface. Specifically, RTM_NEWROUTE and RTM_DELROUTE requests are unimplemented.
Related: #578

**Comment by ianlewis** [comment]
We plan to support RTM_NEWROUTE and RTM_DELROUTE as part of #578 so I think we can close this as a duplicate and you can follow progress made on #578.
