### ISSUE TITLE
Inefficient copy of epoll events

### ISSUE THREAD

**Issue by tanjianfeng** [google/gvisor#606]
We find a performance issue in copyOutEvents(). Copy events one by one, each with a heavy t.CopyOutBytes(), is too slow according to our profiling.

We'd like to optimize it with one-shot copy-out. Even though this way may introduce malloc/gc in some cases, from our limited test, it performs much better than the original code.

**Comment by DarcySail** [comment]
@tanjianfeng I send a pull request here.
#607 Combine multiple epoll events copies

**Comment by hbhasker** [comment]
https://github.com/google/gvisor/pull/607 has been merged. Closing issue.
