### ISSUE TITLE
Huge amount of log lines in Cloud Run Logs when using `dig` command

### ISSUE THREAD

**Issue by AndreiIgna** [google/gvisor#6123]
Continuing from here https://github.com/google/gvisor/issues/1643

**Description**

Some projects deployed to Google Cloud Run generate huge amount of log lines like:
<img width="1109" alt="120392207-742ec200-c330-11eb-8c89-1232b1b86fad" src="https://user-images.githubusercontent.com/263021/120793911-c857c300-c537-11eb-9575-3c75efe3d8f9.png">
This makes it really difficult to check other logs (requests, warnings, etc) and there's no easy way to hide these. Sometimes there are hundreds continuous lines that start with "Container Sandbox: Unsupported syscall setsockopt..."

After doing some checking & debugging, I noticed that these logs appear specifically when executing [`dig` command](https://linux.die.net/man/1/dig) for DNS queries.
The project from where the screenshot is taken uses this library [@layered/dns-records](https://github.com/LayeredStudio/dns-records/blob/master/index.js#L67)

I've tried changing configs for `dig`, Docker or NodeJS, but those log lines are always shown.

**Steps to reproduce**

Deploy code that runs `dig` command.

**Environment**

Docker image is built & deployed by Google Cloud Build, from this config:

```
FROM node:14-alpine

# Install dig command
RUN apk update && apk add bind-tools

...
```

**Comment by nlacasse** [comment]
Those unimplemented syscall errors are for setsockopt(*, SOL_SOCKET, SO_OOBINLINE (10)).  Netstack behaves as if SO_OOBINLINE is always set.  We should probably just disable the log here.  PR coming.
