### ISSUE TITLE
Buildkite does not allow creation of ICMP or ICMPv6 sockets

### ISSUE THREAD

**Issue by puradox** [google/gvisor#6126]
**Description**

While creating a syscall test for binding ICMP/ICMPv6 sockets, I found that Builldkite is not configured to allow for ICMP sockets to be created: `socket(AF_INET, SOCK_DGRAM, IPPROTO_ICMP)` returns `EACCES`. The same applies for ICMPv6 sockets.

This is definitely not expected and should be fixed.

**Steps to reproduce**

```
make syscall-native-tests
```

**Comment by puradox** [comment]
Looks like the syscall tests are running on the local machine, without Docker. I've created a little C program that demonstrates creation of ICMP and ICMPv6 sockets fail without modifying the `net.ipv4.ping_group_range` sysctl. After modifying the sysct to `$(id -g)`, the C program works but the syscall tests continue to fail. I'm puzzled.

**Comment by kevinGC** [comment]
Do you have a link to the buildkite failure?

**Comment by puradox** [comment]
Previous buildkite failure: https://buildkite.com/gvisor/pipeline/builds/6246

For reproduction, remove `GSKIP` from `//test/syscalls/linux/ping_socket.cc`. I had to add it to get #6031 submitted

**Comment by ayushr2** [comment]
@kevinGC has fixed this with an internal change (change in BuildKite configuration).
