### ISSUE TITLE
Bitnami/Nginx-Ingress-Controller - error.log symlink bug

### ISSUE THREAD

**Issue by liornm** [google/gvisor#6180]
**Description**

I am trying to run bitnami/nginx-ingress-controller k8s pod with gvisor runtime.
On startup the pod goes into a crash-loop with the following error message:
<pre>
W0613 12:47:16.992364       1 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0613 12:47:16.995021       1 main.go:241] "Creating API client" host="https://10.43.0.1:443"
I0613 12:47:17.026649       1 main.go:285] "Running in Kubernetes cluster" major="1" minor="21" git="v1.21.1+k3s1" state="clean" commit="75dba57f9b1de3ec0403b148c52c348e1dee2a5e" platform="linux/amd64"
I0613 12:47:17.102958       1 main.go:105] "SSL fake certificate created" file="/etc/ingress-controller/ssl/default-fake-certificate.pem"
I0613 12:47:17.103977       1 main.go:115] "Enabling new Ingress features available since Kubernetes v1.18"
W0613 12:47:17.106837       1 main.go:127] No IngressClass resource with name nginx found. Only annotation will be used.
W0613 12:47:17.119513       1 store.go:620] Unexpected error reading configuration configmap: resource name may not be empty
I0613 12:47:17.130736       1 nginx.go:254] "Starting NGINX Ingress controller"
I0613 12:47:18.333599       1 nginx.go:296] "Starting NGINX process"
I0613 12:47:18.333852       1 leaderelection.go:243] attempting to acquire leader lease default/ingress-controller-leader-nginx...
I0613 12:47:18.346115       1 controller.go:146] "Configuration changes detected, backend reload required"
I0613 12:47:18.370302       1 leaderelection.go:253] successfully acquired lease default/ingress-controller-leader-nginx
I0613 12:47:18.370419       1 status.go:84] "New leader elected" identity="my-release-nginx-ingress-controller-69cc94865c-pwznf"
<b>nginx: [alert] could not open error log file: open() "/opt/bitnami/nginx/logs/error.log" failed (13: Permission denied)
I0613 12:47:18.383115       1 status.go:204] "POD is not ready" pod="default/my-release-nginx-ingress-controller-69cc94865c-pwznf" node="user"
2021/06/13 12:47:18 [emerg] 22#22: open() "/opt/bitnami/nginx/logs/error.log" failed (13: Permission denied)</b>
W0613 12:47:18.419671       1 nginx.go:34] 
-------------------------------------------------------------------------------
NGINX master process died (1): exit status 1
-------------------------------------------------------------------------------
</pre>
**Steps to reproduce**

Download and run the official bitnami/nginx-ingress-controller pod inside of a k8s cluster.

**Suspicious Log Lines**

In gVisor gofer log I can see the following suspicious log line
`fsgofer.go:310] Attempt 0 to open file failed, mode: 0xa0800, path: "//opt/bitnami/nginx/logs/error.log", err: too many levels of symbolic links`

[gvisor.gofer.log](https://github.com/google/gvisor/files/6643895/gvisor.gofer.log)

**Comment by prattmic** [comment]
cc @fvoznika

**Comment by fvoznika** [comment]
The message above is just a debug message, it means that error.log is a symlink and needs to be opened using O_PATH in the gofer. The next message shows that the file was opened correctly:

```
D0613 12:45:01.440571       1 transport_flipcall.go:234] recv [channel @0xc000340240] Twalkgetattr{FID: 117, NewFID: 118, Names: [error.log]}
D0613 12:45:01.440588       1 fsgofer.go:310] Attempt 0 to open file failed, mode: 0xa0800, path: "//opt/bitnami/nginx/logs/error.log", err: too many levels of symbolic links
D0613 12:45:01.440612       1 transport_flipcall.go:127] send [channel @0xc000340240] Rwalkgetattr{Valid: AttrMask{with: Mode NLink UID GID RDev ATime MTime CTime Size Blocks}, Attr: Attr{Mode: 0o120777, UID: 0, GID: 0, NLink: 1, RDev: 0, Size: 11, BlockSize: 4096, Blocks: 0, ATime: {Sec: 1621702566, NanoSec: 0}, MTime: {Sec: 1621702566, NanoSec: 0}, CTime: {Sec: 1622622728, NanoSec: 531759349}, BTime: {Sec: 0, NanoSec: 0}, Gen: 0, DataVersion: 0}, QIDs: [QID{Type: 2, Version: 0, Path: 30675104}]}
```

Do you happen to have the `*.boot` log?

**Comment by liornm** [comment]
Yup, here it is [gvisor.boot.log](https://github.com/google/gvisor/files/6654138/gvisor.boot.log).

**Comment by liornm** [comment]
Yup, here it is
[gvisor.boot.log](https://github.com/google/gvisor/files/6654301/gvisor.boot.log)

Note that its from a different run.

**Comment by liornm** [comment]
I have done a different test in order to isolate the issue.

Here I simply exec `touch` on `/dev/stdout` in a bitnami/mongodb and get **Permission denied**.
```
$ docker run --runtime=runsc --name mongodb -it bitnami/mongodb:latest bash; docker rm mongodb
mongodb 16:21:43.90 
mongodb 16:21:43.91 Welcome to the Bitnami mongodb container
mongodb 16:21:43.92 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 16:21:43.93 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 16:21:43.94 

I have no name!@83eb2bd0bf7a:/$ touch /dev/stdout 
touch: setting times of '/dev/stdout': Permission denied
I have no name!@83eb2bd0bf7a:/$ exit
```
Here I rerun the command without gVisor and it succeeds.
```
$ docker run --name mongodb -it bitnami/mongodb:latest bash; docker rm mongodb
mongodb 16:21:53.82 
mongodb 16:21:53.82 Welcome to the Bitnami mongodb container
mongodb 16:21:53.82 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 16:21:53.82 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 16:21:53.82 

I have no name!@334f4f99a8b3:/$ touch /dev/stdout 
I have no name!@334f4f99a8b3:/$ 
```

**Comment by fvoznika** [comment]
Nice debugging! Indeed `/opt/bitnami/nginx/logs/error.log` points to `/dev/stderr`:

```
D0615 10:46:56.326337       1 transport_flipcall.go:127] send [channel @0xc0006d83c0] Twalkgetattr{FID: 117, NewFID: 119, Names: [error.log]}
D0615 10:46:56.326682       1 transport_flipcall.go:127] send [channel @0xc0006d83c0] Treadlink{FID: 119}
D0615 10:46:56.326779       1 transport_flipcall.go:234] recv [channel @0xc0006d83c0] Rreadlink{Target: /dev/stderr}
```

gVisor is failing to update the timestamp on `/dev/stdout` because it runs with as user `nobody` with all capabilities stripped. Outside the sandbox stdout is owned by `root`. I see that `runc` adjusts ownership based on the user that is running the container:

```
> docker run --rm --user nobody debian stat -L /proc/1/fd/1
  File: /proc/1/fd/1
  Size: 0               Blocks: 0          IO Block: 4096   fifo
Device: ch/12d  Inode: 215519098   Links: 1
Access: (0600/prw-------)  Uid: (65534/  nobody)   Gid: (    0/    root)
...

> docker run --rm --user nobody -ti debian stat -L /proc/1/fd/1
  File: /proc/1/fd/1
  Size: 0               Blocks: 0          IO Block: 1024   character special file
Device: 53h/83d Inode: 3           Links: 1     Device type: 88,0
Access: (0620/crw--w----)  Uid: (65534/  nobody)   Gid: (    5/     tty)
...
```

We would need to do something similar with gVisor:
1. Change stdios owner to nobody so the sandbox has full access over them.
1. Mimic owner to be equal to `user` inside the sandbox. Sort of an overlay on top of the stdios.

Do you mind if I ask for one extra log, just to be sure what operation is failing with `bitnami/nginx-ingress-controller`? Just run the same repro as above with one extra option `--strace` enabled and collect `*.boot` log file.

**Comment by liornm** [comment]
Sure [here](https://github.com/google/gvisor/files/6661471/gvisor.boot.zip).

Here are some relevant lines.
```
I0616 08:19:39.728430  241146 strace.go:625] [  23] nginx X openat(AT_FDCWD /opt/bitnami/nginx-ingress-controller, 0x55f5e63d4590 /opt/bitnami/nginx/logs/error.log, O_WRONLY|O_APPEND|O_CREAT, 0o644) = 0x0 errno=13 (permission denied) (311.504µs)
I0616 08:19:39.728516  241146 strace.go:584] [  24] clean-nginx-con E fcntl(0xff (bad FD), 0x1, 0x7f79165b8154)
I0616 08:19:39.728524  241146 strace.go:622] [  24] clean-nginx-con X fcntl(0xff (bad FD), 0x1, 0x7f79165b8154) = 0x0 errno=9 (bad file descriptor) (611ns)
I0616 08:19:39.728531  241146 strace.go:584] [  23] nginx E write(0x2 host:[6], 0x7fa13f391f30 "nginx: [alert] could not open error log file: open() \"/opt/bitnami/nginx/logs/error.log\" failed (13: Permission denied)\n", 0x78)
```

**Comment by liornm** [comment]
Using `stat -L` in my container clearly shows the difference:
```
$ docker run --rm --runtime=runsc --name mongodb -it bitnami/mongodb:latest stat -L /proc/self/fd/1
...
  File: /proc/self/fd/1
  Size: 0         	Blocks: 0          IO Block: 1024   character special file
Device: 9h/9d	Inode: 1           Links: 1     Device type: 0,0
Access: (0620/crw--w----)  Uid: (65534/  nobody)   Gid: (65534/ nogroup)
Access: 2021-06-16 12:06:52.989733232 +0000
Modify: 2021-06-16 12:06:52.989733232 +0000
Change: 2021-06-16 12:06:52.989733232 +0000
 Birth: -
$ docker run --rm --name mongodb -it bitnami/mongodb:latest stat -L /proc/self/fd/1
...
  File: /proc/self/fd/1
  Size: 0         	Blocks: 0          IO Block: 1024   character special file
Device: 1000a4h/1048740d	Inode: 3           Links: 1     Device type: 88,0
Access: (0620/crw--w----)  Uid: ( 1001/ UNKNOWN)   Gid: (    5/     tty)
Access: 2021-06-16 12:06:58.121654383 +0000
Modify: 2021-06-16 12:06:58.121654383 +0000
Change: 2021-06-16 12:06:58.137654138 +0000
 Birth: -
```

**Comment by liornm** [comment]
> We would need to do something similar with gVisor:
> 
> 1. Change stdios owner to nobody so the sandbox has full access over them.
> 2. Mimic owner to be equal to `user` inside the sandbox. Sort of an overlay on top of the stdios.

Where would you add this? :)

**Comment by liornm** [comment]
I believe I found the relevant code of [runc](https://github.com/opencontainers/runc/commit/c0c8edb9e801c499f2b7c7a3342c252cb47b6411).

As stated in runc:
```
		// The reason why we don't just leave the default uid=X mount setup is
		// that users expect to be able to actually use their console. Without
		// this code, you couldn't effectively run as a non-root user inside a
		// container and also have a console set up.
```

**Comment by fvoznika** [comment]
> Where would you add this? :)
This is something we need to fix in runsc.

There are a few possible workarounds for now:
1. Disable VFS2. VFS1 wrongly skips permission checks when opening files from `/proc/[pid]/fd` [1]
2. Create an image that deletes `/opt/bitnami/nginx/logs/error.log` so that it doesn't get redirected to `/dev/stderr`. Or configure nginx to use a different path.
3. Run the container as root. Not ideal, but since the container is running inside gVisor, it's not a big difference.

[1]
```
> docker run --rm --runtime=runsc --user 1001 debian /bin/sh -c "echo 123 >> /proc/1/fd/1"
123
> docker run --rm --runtime=runsc-vfs2 --user 1001 debian /bin/sh -c "echo 123 >> /proc/1/fd/1"
/bin/sh: 1: cannot create /proc/1/fd/1: Permission denied
```

**Comment by liornm** [comment]
Thanks for the workarounds!
I am would like to contribute a fix this issue.

Would you give me a hint where this should go? :)

**Comment by nirweiner2** [comment]
We also ran into this problem.
I really wish it will be fixed soon.

**Comment by fvoznika** [comment]
Could you please take a look at #6272 and verify that it fixes the issue for you?

**Comment by liornm** [comment]
> Could you please take a look at #6272 and verify that it fixes the issue for you?

It works great! Thanks :)
