### ISSUE TITLE
Question about scheduler and resource constrains  of gVisor

### ISSUE THREAD

**Issue by IT-huang** [google/gvisor#62]
I wonder if  gVisor  has its own scheduler like CFS or CFQ? Or processes of the sandbox are still scheduled by host kernel  scheduler? Traditional docker or k8s  perform resource constrains(such as cpu and memory) based on  CGroups and Namespace , How gVisor implements  resource constrains of the sanbox ?

**Comment by fvoznika** [comment]
gVisor delegates scheduling decisions to the Go runtime. You can find more details in this [email thread](https://groups.google.com/d/msg/gvisor-users/TCF1iM6knb0/TrSMlN59AQAJ).

Regarding CPU and memory limits, right now runsc ignores the [control group](https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#control-groups) part of the spec completely. But we do plan to implement it, we just didn't have time for it yet. Help is welcome :-)

**Comment by IT-huang** [comment]
@fvoznika  Thank you very much!
