### ISSUE TITLE
UNIX sockets with setuid flag cannot be mounted (?)

### ISSUE THREAD

**Issue by DimanNe** [google/gvisor#6211]
### Description

In short: I was trying to run a GUI app (`xeyes`) via gvisor and got an error:
```
I0619 19:16:04.118411  3470394 strace.go:588] [   8] xeyes E connect(0x3 socket:[5], 0x7f150f3e1190 {Family: AF_UNIX, Addr: "\x00/tmp/.X11-unix/X0"}, 0x14)
I0619 19:16:04.118420  3470394 strace.go:626] [   8] xeyes X connect(0x3 socket:[5], 0x7f150f3e1190 {Family: AF_UNIX, Addr: "\x00/tmp/.X11-unix/X0"}, 0x14) = 0x0 errno=111 (connection refused) (3.086µs)
```

More info:
I run some apps in (normal, non gvisor) docker. This is my usual docker command-line:
```
docker run -it --shm-size 32G --rm --user (id -u) \
             --env DISPLAY --env TERM --env COLORTERM \
             --volume /tmp/.X11-unix:/tmp/.X11-unix \
             --volume $HOME/.Xauthority:$HOME/.Xauthority:rw \
             (whoami)/kile /bin/bash
```
after which I can start, for example, `xeyes`.

But when I tried doing the same with gvisor (I added `--runtime ` option to the docker) `xeyes` printed this:
```
Error: Can't open display: :0
```

I also tried using gvisor with debugging option (as it is described [here](https://gvisor.dev/docs/user_guide/debugging/)), and this is what I got:
```
cat /tmp/runsc/runsc.log.20210619-201600.601540.boot | grep "X11-unix"
      "destination": "/tmp/.X11-unix",
      "source": "/tmp/.X11-unix",
D0619 19:16:01.020590  3470394 fs.go:686] Mounting "/tmp/.X11-unix" to "/tmp/.X11-unix", type: bind, options: [rbind rprivate]
D0619 19:16:01.022474  3470394 transport_flipcall.go:127] send [channel @0xc0003463c0] Twalkgetattr{FID: 5, NewFID: 6, Names: [.X11-unix]}
D0619 19:16:01.022520  3470394 transport_flipcall.go:127] send [channel @0xc0003463c0] Tgetxattr{FID: 5, Name: trusted.overlay.whiteout..X11-unix, Size: 1}
I0619 19:16:01.022558  3470394 fs.go:920] Mounted "/tmp/.X11-unix" to "/tmp/.X11-unix" type: bind, internal-options: ["trans=fd" "rfdno=10" "wfdno=10" "privateunixsocket=true" "cache=remote_revalidating"]
D0619 19:16:01.049002  3470394 transport_flipcall.go:234] recv [channel @0xc0003463c0] Rreaddir{Count: 33, Entries: [Dirent{QID: {128 0 72057594039241092}, Offset: 1, Type: 0x80, Name: .X11-unix}]}
D0619 19:16:01.049075  3470394 transport_flipcall.go:127] send [channel @0xc0003463c0] Tgetxattr{FID: 5, Name: trusted.overlay.whiteout..X11-unix, Size: 1}
I0619 19:16:04.118411  3470394 strace.go:588] [   8] xeyes E connect(0x3 socket:[5], 0x7f150f3e1190 {Family: AF_UNIX, Addr: "\x00/tmp/.X11-unix/X0"}, 0x14)
I0619 19:16:04.118420  3470394 strace.go:626] [   8] xeyes X connect(0x3 socket:[5], 0x7f150f3e1190 {Family: AF_UNIX, Addr: "\x00/tmp/.X11-unix/X0"}, 0x14) = 0x0 errno=111 (connection refused) (3.086µs)
I0619 19:16:04.118509  3470394 strace.go:588] [   8] xeyes E connect(0x3 socket:[6], 0x7f150f3e1190 {Family: AF_UNIX, Addr: "/tmp/.X11-unix/X0"}, 0x6e)
I0619 19:16:04.118780  3470394 strace.go:626] [   8] xeyes X connect(0x3 socket:[6], 0x7f150f3e1190 {Family: AF_UNIX, Addr: "/tmp/.X11-unix/X0"}, 0x6e) = 0x0 errno=1 (operation not permitted) (265.36µs)
```

`/tmp/.X11-unix` is a directory that contains a UNIX socket that GUI applications use in order to talk to X11. And as far as I understand `xeyes` failed to open it.

### More info
`.X11-unix` directory contains this interesting file:
```
ls -al /tmp/.X11-unix/X0
srwxrwxrwx 1 root root 0 Jun 18 19:18 /tmp/.X11-unix/X0=
```
`s` means setuid/setguid flag.

And here is what happens when I try to mount it and `ls` from within container:
```
docker run -it --rm --runtime runsc --user (id -u) \
             --volume /tmp/.X11-unix/X0:/tmp/.X11-unix/X0 (whoami)/kile \
             ls /tmp/.X11-unix/X0
docker: Error response from daemon: OCI runtime start failed: starting container: starting root container:
starting sandbox: mount submount "/tmp/.X11-unix/X0": creating mount with source "/tmp/.X11-unix/X0":
input/output error: you may be encountering a Linux kernel bug; see https://gvisor.dev/faq#memlock for
more details: unknown.
```

### Environment

Please include the following details of your environment:

*   `runsc -version`
```
runsc version release-20210614.0
spec: 1.0.2
```
*   `docker version` or `docker info` (if available)
```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:17:52 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
*   `kubectl version` and `kubectl get nodes` (if using Kubernetes)
*   `uname -a`
```
Linux Impedance 5.11.0-18-generic #19-Ubuntu SMP Fri May 7 14:22:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
*   `git describe` (if built from source)
*   `runsc` debug logs (if available)
[runsc.log.20210619-201600.577440.create](https://gist.githubusercontent.com/DimanNe/930aa6b39eedaf7f09bd23a8034a6648/raw/6417ae12b816cb89323e24940ba2ca95b823fb10/runsc.log.20210619-201600.577440.create)
[runsc.log.20210619-201600.600904.gofer](https://gist.githubusercontent.com/DimanNe/f63de0d1c29ad6c184fcd23da28514da/raw/23b2c8ae9e06210e5629f05b0798e0f13a7e6cc1/runsc.log.20210619-201600.600904.gofer)
[runsc.log.20210619-201600.601540.boot](https://gist.githubusercontent.com/DimanNe/e5b8e1bde034a9b09b36f72691e8714f/raw/2013afc2a403ddd814f5efe487cb846614c40315/gistfile1.txt)
[runsc.log.20210619-201600.845185.start](https://gist.githubusercontent.com/DimanNe/2a89e896de3384d0b5b41367d04809d2/raw/fa6d8ba6917beeee796567a760b129f4396f50fe/runsc.log.20210619-201600.845185.start)

**Comment by ianlewis** [comment]
I think this might just be a duplicate of #5299 and that the issue is that setuid bit is not supported in gVisor right now.

**Comment by fvoznika** [comment]
gVisor is isolating the container from the host and by default doesn't allow the container connect to host backed UDS. That's the reason the container is getting `Error: Can't open display: :0`. The flag `--fsgofer-host-uds` allows gVisor to connect to host UDS when set. Here you can see the file in your example:

```
> docker run --rm --runtime=gv1-uds -it --volume /tmp/.X11-unix:/tmp/.X11-unix debian ls -lh /tmp/.X11-unix
total 0
srwxrwxrwx 1 root   root  0 Jun 22 21:37 X0
srwxrwxrwx 1 183048 89939 0 Jun 22 21:37 X20
```
Please give it a try with this flag and let us know if it fixed the problem for you.

**Note**: the `s` in the output is not `setuid`, it's indicating that the file is a `s`ocket instead. `s` for setuid is at the end user's mode, replacing the `x` (yes, very confusing):

```
> ls -l /usr/bin/sudo
-rwsr-xr-x 1 root root 179K Feb 27 00:28 /usr/bin/sudo
```

**Comment by DimanNe** [comment]
Sorry for the "delay" (and changing username :) )
The option worked perfectly - thanks!

For the record:

/etc/docker/daemon.json
```
            "runtimeArgs": [
                "--host-uds=open"
            ]
        }
```

and before docker run, you probably need to do `xhost +`.
