### ISSUE TITLE
Makefile error - make: *** [Makefile:167: runsc] Error 127

### ISSUE THREAD

**Issue by Preethi951** [google/gvisor#6227]
**Description**

After running 'make runsc' , it gives the following Makefile error
make: *** [Makefile:167: runsc] Error 127

**Environment**

Please include the following details of your environment:

*   `runsc -version`
*   `docker version - 20.10.7
*   `uname -a`- Linux sdl55384 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
*   `git describe` (if built from source)- release-20210614.0-10-g04a81bc33

Attaching the log here.

make runsc
--- PULL default
674208604c6d35de: Pulling from gvisor-presubmit/default_x86_64
83ee3a23efb7: Pull complete 
db98fc6f11f0: Pull complete 
f611acd52c6c: Pull complete 
41ea287ead91: Pull complete 
b247c73e3979: Pull complete 
15f1aec7b3f3: Pull complete 
4c91c707d1b2: Pull complete 
0fb9b27be758: Pull complete 
5ff1657204bc: Pull complete 
31329a3c5a17: Pull complete 
Digest: sha256:bfca9a84ffef31a1f3daf579a4cbb0740569b9b7419b21e6e16009ad6b0eca8b
Status: Downloaded newer image for gcr.io/gvisor-presubmit/default_x86_64:674208604c6d35de
gcr.io/gvisor-presubmit/default_x86_64:674208604c6d35de
--- DOCKER BUILD
sha256:90abb40259f09498be91132bcbe304c4bf1b2cdd0bf5672998f0e2efd546934e
--- DOCKER RUN
39d8bf20e27499238be860e24135691b64908d62859526fbe50e72a4c7801a26
--- BUILD -c opt //runsc
/bin/bash: strings: command not found
Another command holds the client lock: 
pid=8
owner=client
cwd=/data/gvisor

Waiting for it to complete...
Another command (pid=8) is running. Waiting for it to complete on the server (server_pid=18)...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/a0761ed101b939e19d83b2da5f59034bffc19c12.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: target //runsc:runsc (2 packages loaded, 0 targets configured)
INFO: SHA256 (https://golang.org/dl/?mode=json&include=all) = 6efc06a1bd0a710df5cbaa2fd314f9a3f702f7d9cd59ee2bd53c2a02aa8c4475
Analyzing: target //runsc:runsc (11 packages loaded, 6 targets configured)
Analyzing: target //runsc:runsc (11 packages loaded, 6 targets configured)
Analyzing: target //runsc:runsc (11 packages loaded, 6 targets configured)
Analyzing: target //runsc:runsc (12 packages loaded, 6 targets configured)
Analyzing: target //runsc:runsc (30 packages loaded, 7095 targets configured)
Analyzing: target //runsc:runsc (49 packages loaded, 7195 targets configured)
Analyzing: target //runsc:runsc (49 packages loaded, 7195 targets configured)
Analyzing: target //runsc:runsc (69 packages loaded, 7649 targets configured)
INFO: Analyzed target //runsc:runsc (348 packages loaded, 11602 targets configured).
INFO: Found 1 target...
[0 / 4] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[43 / 69] GoStdlib external/io_bazel_rules_go/stdlib_/pkg; 6s linux-sandbox ... (2 actions, 1 running)
[137 / 285] GoStdlib external/io_bazel_rules_go/stdlib_/pkg; 16s linux-sandbox ... (2 actions, 1 running)
[199 / 346] GoCompilePkg external/org_golang_google_protobuf/reflect/protoreflect/protoreflect.a; 0s linux-sandbox ... (2 actions, 1 running)
INFO: From go_marshal: //pkg/sentry/loader:loader_abi_autogen:
stdout (/root/.cache/bazel/_bazel_root/e0bf2de80ca3a11759ed344c1babad4d/execroot/__main__/bazel-out/_tmp/actions/stdout-519) exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
[634 / 734] GoCompilePkg pkg/tcpip/header/header.a; 0s linux-sandbox ... (2 actions, 1 running)
[814 / 917] go_marshal: //pkg/abi/linux:linux_abi_autogen [for host]; 0s linux-sandbox ... (2 actions, 1 running)
[1,189 / 1,204] GoCompilePkg external/in_gopkg_yaml_v2/yaml_v2.a; 0s linux-sandbox ... (2 actions, 1 running)
Target //runsc:runsc up-to-date:
  bazel-out/k8-opt-ST-4c64f0b3d5c7/bin/runsc/runsc_/runsc
INFO: Elapsed time: 155.811s, Critical Path: 47.38s
INFO: 1364 processes: 38 internal, 1326 linux-sandbox.
INFO: Build completed successfully, 1364 total actions
INFO: Build completed successfully, 1364 total actions
make: *** [Makefile:167: runsc] Error 127

**Comment by ianlewis** [comment]
I couldn't reproduce this. Is there any more info you could provide as to what might be causing the issue?

**Comment by Preethi951** [comment]
Hello Lewis,

Thanks for your reply. Not sure why it is causing this error, when I build the gvisor from source using the following command make runsc command, I get the make file error.

Thanks,
Preethi
________________________________
From: Ian Lewis ***@***.***>
Sent: Friday, June 25, 2021 8:48 PM
To: google/gvisor ***@***.***>
Cc: Santhanam, Preethi <Preethi.Santhanam@Teradata.com>; Author ***@***.***>
Subject: [EXTERNAL] Re: [google/gvisor] Makefile error - make: *** [Makefile:167: runsc] Error 127 (#6227)


[CAUTION: External Email]


I couldn't reproduce this. Is there any more info you could provide as to what might be causing the issue?

**Comment by kevinGC** [comment]
What does the output of `make -n runsc` look like?

**Comment by Preethi951** [comment]
Thanks for your input. I got the gVisor installed from apt repository and it works now. 
But I want to install gVisor on aws ec2 instance with the Linux version 4.4.140-96.63.TDC-default. Could anyone please let me know how to install it since the required linux version is 4.14.17 for gVisor?

**Comment by kevinGC** [comment]
There's not a lot we can do about an old kernel. It's possible that if you run gVisor on that machine, you'll get an idea of what kernel features are missing. However, you'd likely have to modify the gVisor code to accommodate the older kernel.

**Comment by Preethi951** [comment]
Ok, in the gVisor documentation it says the following for older linux

"If your Linux is older than 4.14.17, you can disable Generic Segmentation Offload (GSO) to run with a kernel that is newer than 3.17. Add the --gso=false flag to your Docker runtime configuration (/etc/docker/daemon.json) and restart the Docker daemon:"

Reference: https://gvisor.dev/docs/user_guide/networking/#gso

**Comment by ianlewis** [comment]
Just be aware that we don't test older kernels much and it's possible that we may be using features now from kernels newer than 3.17.
