### ISSUE TITLE
mmu

### ISSUE THREAD

**Issue by Anjali05** [google/gvisor#624]
Hi,
I have a workload that does mmap call with different page sizes(4KB, 8KB ..1mb), total of 1GB memory. I want to see the ratio of mamp calls to the sentry to the mmap calls to the host from the sentry. After some debugging, it looks like every mmap call to the host requests memory in 16MB of chuck size. So for my workload, if I run it with 1MB page size, the mmap call to the host happens after every 16th mmap call to the sentry(for total of 1 GB memory requested) with a total of 64 mmap calls to the host. I was wondering what is the security/performance benefit of this design. I would really appreciate if someone can shed some light on this.
Thanks

**Comment by ianlewis** [comment]
Hi, Thanks for the question. These kind of questions will likely get a better answer on the mailing list. You might try there. https://groups.google.com/forum/#!forum/gvisor-users

**Comment by ianlewis** [comment]
This was sent to the mailing list: https://groups.google.com/forum/#!topic/gvisor-users/EUwOv1qxZks
