### ISSUE TITLE
runsc quits when unmount gofer filesystem when VFS2 is enabled

### ISSUE THREAD

**Issue by btw616** [google/gvisor#6259]
**Description**

runsc will quit unexpectedly when unmount gofer filesystem inside container when VFS2 is enabled.

**Steps to reproduce**

```
$ docker run -it --runtime=runsc -v /tmp/test:/test --cap-add=SYS_ADMIN ubuntu
root@20adaa2616dd:/# umount /test       # runsc will quit unexpectedly
```

This happens because the connection will be shutdown when filesystem is released:

https://github.com/google/gvisor/blob/5b2afd24a7ed6d626ede2d06d04378f95c3b62f8/pkg/sentry/fsimpl/gofer/gofer.go#L617

https://github.com/google/gvisor/blob/5b2afd24a7ed6d626ede2d06d04378f95c3b62f8/pkg/p9/client.go#L572

And gofer monitor will notice this and kill the container:

https://github.com/google/gvisor/blob/5b2afd24a7ed6d626ede2d06d04378f95c3b62f8/runsc/boot/loader.go#L825-L850

**Comment by fvoznika** [comment]
Good catch, we should have a test for that. VFS1 didn't close the connection on when the volume was unmounted. We fixed that in VFS2, but it has side effects. We should either unsubscribe the gofer watcher on disconnect (preferred) or only monitor the rootfs FD.

Just for the record, here is the log:
```
I0629 17:28:04.647491   87244 strace.go:585] [   1] umount E umount2(0x56070529f940 /test, 0x0)
D0629 17:28:04.647526   87244 transport_flipcall.go:127] send [channel @0xc00030c600] Tmultigetattr{FID: 1, Names: []}
D0629 17:28:04.647804   87244 transport_flipcall.go:234] recv [channel @0xc00030c600] Rmultigetattr{Stats: [{QID{Type: 128, Version: 0, Path: 1578021} AttrMask{with: Mode NLink UID GID RDev ATime MTime CTime Size Blocks} Attr{Mode: 0o40755, UID: 0, GID: 0, NLink: 2, RDev: 0, Size: 4096, BlockSize: 4096, Blocks: 8, ATime: {Sec: 1624987556, NanoSec: 593927544}, MTime: {Sec: 1624987556, NanoSec: 593927544}, CTime: {Sec: 1624987556, NanoSec: 593927544}, BTime: {Sec: 0, NanoSec: 0}, Gen: 0, DataVersion: 0}}]}
I0629 17:28:04.647890   87244 loader.go:846] Gofer socket disconnected, killing container "50d5ba8556eef8eaf6d9aea66364d3c3de173bd00c2502131ea03c3fc702dc8d"
I0629 17:28:04.647963   87244 strace.go:623] [   1] umount X umount2(0x56070529f940 /test, 0x0) = 0x0 (442.484µs)
```
