### ISSUE TITLE
apt gpg signing key expired (https://gvisor.dev/archive.key)

### ISSUE THREAD

**Issue by quinndiggity** [google/gvisor#6323]
`https://gvisor.dev/archive.key`
```
pub   rsa4096 2019-07-10 [SC] [expired: 2021-07-09]
      6F1D F85E 3A71 C249 18E7  27D5 6FC6 D554 E32B D943
uid           [ expired] The gVisor Authors <gvisor-bot@google.com>
```
`Failed to update apt cache: W:GPG error: https://storage.googleapis.com/gvisor/releases release InRelease: The following signatures were invalid: EXPKEYSIG 6FC6D554E32BD943 The gVisor Authors <gvisor-bot@google.com>, E:The repository 'https://storage.googleapis.com/gvisor/releases release InRelease' is not signed.`

**Comment by quinndiggity** [comment]
```
curl -fsSL https://gvisor.dev/archive.key > archive.key
gpg --list-packets --with-fingerprint archive.key | grep expire
```
```
	version 4, algo 1, created 1562802182, expires 0
	hashed subpkt 9 len 4 (key expires after 2y0d0h0m)
```
`expired: 2021-07-09`

**Comment by amscanne** [comment]
Thanks for reaching out. The key has been updated and the latest releases and being signed with the newer key. The key on the website is scheduled to push tonight (ca255741c92e04899ac2f49226d1abec6589cb8c).
