### ISSUE TITLE
About GR3 -> GR0 code comments

### ISSUE THREAD

**Issue by DarcySail** [google/gvisor#637]
Hi guys, the following comments of the link says that when the execution flow returns from GR3 to GR0, it returns to vcpu.Switch, but my understanding is that it should return to CPU.SwithToUser is not it?
comment:
https://github.com/google/gvisor/blob/master/pkg/sentry/platform/ring0/entry_amd64.s#L184
CPU.SwithToUser:
https://github.com/google/gvisor/blob/master/pkg/sentry/platform/ring0/kernel_amd64.go#L204

**Comment by ianlewis** [comment]
I'm pretty sure you're right but adding Adin to verify.

**Comment by DarcySail** [comment]
@ianlewis Well, thanks for reply:)

**Comment by DarcySail** [comment]
@amscanne :)
