### ISSUE TITLE
ApplicationCores is always initiated with 8

### ISSUE THREAD

**Issue by ShiruRen** [google/gvisor#64]
I am currently using gVisor with Docker. I found the number of processors in /proc/cpuinfo is always 8, which limits the the amount of CPUs that some applications can use (e.g., TensorFlow). When I step through the code I found that the ApplicationCores is always initiated with 8 when initiating the Kernel object [https://github.com/google/gvisor/blob/7049f4480dabac4b95a9117eafc47f4b2b3f24f5/runsc/boot/loader.go#L172]. I am wondering if it would be possible to set the value straight from host /proc/cpuinfo like the func initCPUFreq() does.

I am also wondering if there are any known solutions to limit the amount of resources (like CPUs and memory) that a container can use.

Docker version: 18.03.1-ce
The command run was docker run --runtime=runsc -it ubuntu /bin/bash

Thanks.

**Comment by prattmic** [comment]
w.r.t. resource isolation, see #62 (runsc will eventually put itself inside of appropriate cgroups according to the spec).

**Comment by fvoznika** [comment]
We need to get the number of processor from cgroups when we add support for it. But for now, we could use the number of processors on the machine.

**Comment by ShiruRen** [comment]
Many thanks, @fvoznika @prattmic . It works fine now.
