### ISSUE TITLE
do not restart docker on debian postinst

### ISSUE THREAD

**Issue by khimaros** [google/gvisor#6408]
### Description

restarting docker is disruptive, as it restarts all containers as well.

this has bitten me and caused downtime.

one solution would be to add a `/etc/defaults/runsc` which would be consulted about whether to restart docker.

### Steps to reproduce

`apt upgrade` on a system with runsc installed

### uname

n/a

**Comment by amscanne** [comment]
Thanks for the report. I think this can be easily changed to just reload the configuration, which should avoid issues. I'll send something out.
