### ISSUE TITLE
External HTTP Request Failure Rate 0.7%

### ISSUE THREAD

**Issue by Champ-Goblem** [google/gvisor#6441]
### Description

We have been experiencing an issue where HTTP connections that reuse a TCP connection (keep-alive connections) fail when talking to external services. We have seen sporadic time-out, connection reset and unexpected end-of-file (EOF) errors when deployments running on gVisor with istio-proxy sidecars talk to external endpoints such as Shopify, Cloudflare, PyPi and more. 

In order to investigate the issue further a Cloudflare worker was setup, acting as a dummy API which we then subsequently called from both k6 (Golang) and Nodejs testing scripts. From these tests it was determined that 0.7-0.9% of the requests would fail, mostly with timeout errors and the occasional unexpected EOF/connection resets. 

Break-pointing runsc with delve we noticed that k6 by default reused the same TCP connection for successive requests whereas Nodejs did not and when setting both tests to reuse connections we started to experience the timeout issues mentioned above. On the other hand, when disabling the HTTP keep-alive functionality the tests succeeded with no failures. When running with connection reuse, failures would start after a small period of time, roughly around 2min.

The problem presented above sounds somewhat similar to an issue we previously created (https://github.com/google/gvisor/issues/6317) where raw TCP connections to a database would fail, but after a longer period of time (20mins+ vs 2min+ for this issue).

This is consistent across multiple Kubernetes versions, Istio versions, cloud providers, k3s, baremetal and containerd versions. We also tried the same setup on Cloud Run and experienced the same failure rate.

We are happy to demonstrate the issues live over google meets/zoom if needs be.

### Steps to reproduce

- Provision a new cluster with gVisor installed
- Deploy istio with `istio/deploy.sh`
- Label a namespace for testing with `istio-injection: enabled`
- [Optional] Build the two apps with `app/k6-test/build.sh <tag>` and `app/nodejs-test/build.sh <tag>` providing the argument `<name>:<tag>` to tag the image with (some prebuilt images are already provided)
- Deploy the apps with `app/deploy-k6.sh <url> <reuse-connections>` and `app/deploy-nodejs.sh <url> <reuse-connections>`
  - `<url>` in the arguments for the script is the cloudflare worker we have deployed for testing, the url we will send over private message
  - `<reuse-connections>` in the arguments sets whether the script will reuse the connections or not (`true/false`)
  - An optional third argument can be used to specify a different tag
  - Uses two public images built beforehand and published to dockerhub `champgoblem/gvisor-k6-test:latest` and `champgoblem/gvisor-nodejs-test:latest` unless specifying a different image
  - Each deployment also has a set of configurable enviroment variables that are detailed in each of the deploy.sh scripts
- Wait for the reuse connection pods to fail

The Cloudflare worker code is attached in the setup scripts for analysis/recreation `worker/cloudflare-worker.js`.

The Cloudflare worker endpoint has been omitted from the setup scripts so as to not advertise it publicly, we will happily send this over when needed.

The debug scripts are available publicly at [https://github.com/northflank/http-connection-failure-gvisor](https://github.com/northflank/http-connection-failure-gvisor) or in the attached zip
[submission.zip](https://github.com/google/gvisor/files/6970272/submission.zip)

### runsc version

```shell
- Latest on go and main branches
- `google-380056102`
- And potentially more
```

### docker version (if using docker)

```shell
Containerd versions:
- `1.4.3`
- `1.4.8`
- And potentially more
```

### uname

Linux 5.4.104+ #1 SMP Mon Jun 7 21:53:49 PDT 2021 x86_64 Intel(R) Xeon(R) CPU @ 2.00GHz GenuineIntel GNU/Linux

### kubectl (if using Kubernetes)

```shell
K8s versions:
- `v1.20.8-gke.900`
- `v1.21.3+k3s1`

Istio Versions:
- 1.9.5
- 1.9.6
- 1.9.7
- 1.10.3
```

**Comment by DeciderWill** [comment]
@hbhasker @kevinGC @nybidari - any updates? It's over a month since this was opened and 2 months since https://github.com/google/gvisor/issues/6317 was filed. If we can assist or provide additional context please communicate as there has been zero communication.

This issue affects Cloud Run, App Engine, Digital Ocean App platform - not just Northflank.

Next JS a popular React / Node JS framework is enabling keep-alive connections by default. I expect a lot of Next code runs in gvisor.

https://nextjs.org/blog/next-11-1

Let alone the huge number of frameworks and languages that already use keep-alive by default as advised in the above ticket.

**Comment by hbhasker** [comment]
@DeciderWill Sorry this fell off my radar. I will take a look today and see if I can repro the issue.

I will also sync with @kevinGC and @nybidari  and see post updates once I have something concrete to share.

**Comment by Champ-Goblem** [comment]
@hbhasker thanks again for picking this up, as the two pcaps are too large to be uploaded to github I have made them available on a storage bucket (client: https://storage.googleapis.com/networking-pcaps/http/client.pcap and server: https://storage.googleapis.com/networking-pcaps/http/server.pcap).

If you still require, we are more than happy to demonstrate the problem over a call and provide any support we can.

\<firstname\>@northflank.com is my email if you need to get in touch

**Comment by hbhasker** [comment]
Thanks for the pcaps. Let me take a look at the pcaps and see if something is obvious from the pcaps. If not I will reach out and maybe setup a conf to do some live debugging.

**Comment by hbhasker** [comment]
NOTE: I opened an issue for a bug I observed in our tcp_conntrack which may also cause some of these odd behaviours. 

See: https://github.com/google/gvisor/issues/6734

**Comment by hbhasker** [comment]
Thanks for the new caps, for some reason I can't correlate the client and server pcaps. The client pcaps clearly show some streams stuck for a long time and the remote end retransmitting with no response but I can't find the same streams on the server pcap. None of the streams in the server pcap are stuck like that and all have some retransmissions but are making forward progress.

**Comment by Champ-Goblem** [comment]
Hi hbhasker, it might be worth if we setup that conf next week for some live debugging of the HTTP issue?

**Comment by Champ-Goblem** [comment]
Please contact myself and cc @DeciderWill on our emails <firstname>@northflank.com and we will be as flexible as possible with scheduling

**Comment by hbhasker** [comment]
I believe we may have found a bug that could be causing the RSTs and timeouts. It is fixed @ head when making an unrelated change.(https://github.com/google/gvisor/commit/3bab5e56677942c19d0777a1d6aee38a25a05bbb#diff-a2e3792cda772de19b2a342f8e75b976a53e2ab22e0e72286458aebce30b2087R287).

The bug was that reapLocked was messing up the list as we remove the very entry  on which we are calling Next() in the loop iteration ( that commit changed the code to just skip expired entries). 

Could you test w/ a runsc built from HEAD and see if the issue still occurs?

**Comment by joshma** [comment]
Hi folks, I'm trying to track down something similar and noticed that the repro I have (more on that later) only works on when we run with gvisor enabled (via GKE sandbox).

The repro basically reads and writes from key A to key B in Firebase using the Python admin SDK, and we're seeing `urllib3.exceptions.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2627)` when that happens.

We're seeing it a bit more than 1%, maybe 5%, although I need to do some more tests to get a more accurate number. Does this seem like a related issue? (Is this issue still known / open?)

**Comment by joshma** [comment]
Ah interesting, we upgraded from `1.21.5-gke.1302` to `1.21.6-gke.1500` and that may have fixed this...noting in case it helps at all / sorry for the noise.

**Comment by hbhasker** [comment]
@joshma Thanks for the update. Glad to hear that the issue resolved after the upgrade.

@Champ-Goblem I am going to close this issue as resolved, please reopen if you are still experiencing the timeouts.
