### ISSUE TITLE
[Feature Request] Support CRI-o

### ISSUE THREAD

**Issue by jcrowthe** [google/gvisor#648]
This is a request to provide support for CRI-o, in addition to the currently support containerd and docker (directly).

In running tests with RuntimeClass in kubernetes, pods are properly launched as-is with the exception of an annotation issue preventing the NIC from being attached (documented in #626). As such, this may be a small lift, but further investigation will be necessary.

**Comment by fvoznika** [comment]
Let's use #626 to track this work.
