### ISSUE TITLE
How is the information of procfs and sysfs from?

### ISSUE THREAD

**Issue by IT-huang** [google/gvisor#65]
docker version :Docker version 18.05.0-ce, build f150324
uname -a:Linux crane23 4.12.3 #1 SMP Fri Nov 24 16:03:12 CST 2017 x86_64 x86_64 x86_64 GNU/Linux
Question 1: My host machine have 20 cores and 120G memory totally. When i use 'sudo docker run --runtime=runsc -it ubuntu /bin/bash' to run a container with gVisor, I find /proc/cpuinfo shows 8 cores totally,Why just 8 cores? And i also find MemTotal of /proc/meminfo is just 2G. I have never find some parameters to set that.
Question 2: In my opinion, I think gVisor is just use Go to rewrite most of linux syscalls. gVisor have not 
realize  any resource limitation or resource scheduler . So what's the difference between gVisor and seccomp?gVisor is just like a syscall filter and even the performance of gVisor is worse because it is a complete user space solution. It seems gVisor virtual some device for container? Can you show me some details?

**Comment by hugelgupf** [comment]
gVisor virtualizes procfs and sysfs -- I'm not sure we expose a setting for the number of cores and the memory, but we probably should.

re q2: seccomp filters mean that the application must not filtered syscalls (or use filtered arguments). this usually means modifying an application to work around the seccomp filter. gVisor does not filter syscalls -- it lets you make them anyway, just not to the host kernel; which means the untrusted application can remain unmodified.

**Comment by IT-huang** [comment]
@hugelgupf  Thank you！However，I still confused with how gVisor virtualizes procfs and sysfs and where are the information of procfs and sysfs from? Such as cores number ,available memory, loadavg? Those information are important to applications in containers.

**Comment by fvoznika** [comment]
Re q1: No particular reason for 8. We need to get the number of processor from cgroups when we add support for it. But for now, we could use the number of processors on the machine.

Re q2: I think part of the confusion is that gVisor doesn't simply filter syscalls and send them to the host. gVisor implements a full kernel and handles the syscalls itself. It only calls the host for basic infrastructure services like memory allocation, blocking, etc. Consequently, gVisor can virtualize procfs and sysfs to provide only the information it wants the container to see. If you're curious, [here](https://github.com/google/gvisor/blob/2677457eeabcc66591f1a6e2491b6d6d253d5a42/pkg/sentry/fs/proc/proc.go#L83) is the procfs implementation. sysfs is just empty directories (code [here](https://github.com/google/gvisor/blob/2677457eeabcc66591f1a6e2491b6d6d253d5a42/pkg/sentry/fs/sys/sys.go#L41)).
