### ISSUE TITLE
Unable to use runsc-kvm platorm

### ISSUE THREAD

**Issue by DilipRenkila** [google/gvisor#652]
dilip@atlas:~$ runsc -version
runsc version release-20190529.1-311-g960a5e5536d5
spec: 1.0.1-dev

ilip@atlas:~$ sudo docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        2d0083d
 Built:             Wed Jul  3 12:13:54 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       2d0083d
  Built:            Mon Jul  1 19:14:14 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**i am unable to use runsc-kvm platform. Following errors are being reported in docker service**

aug 05 03:33:11 atlas dockerd[12979]: time="2019-08-05T03:33:11.670051092+02:00" level=error msg="stream copy error: reading from a closed fifo"
aug 05 03:33:11 atlas dockerd[12979]: time="2019-08-05T03:33:11.670053523+02:00" level=error msg="stream copy error: reading from a closed fifo"
aug 05 03:33:11 atlas dockerd[12979]: time="2019-08-05T03:33:11.879947528+02:00" level=error msg="2e595e07475c664a6ba1ae9d039fb05342f5a6d01e3bbc79a4d32c43b76135cd cleanup: failed to delete container from containerd: no such container"
aug 05 03:33:11 atlas dockerd[12979]: time="2019-08-05T03:33:11.900803843+02:00" level=error msg="Handler for POST /v1.39/containers/2e595e07475c664a6ba1ae9d039fb05342f5a6d01e3bbc79a4d32c43b76135cd/start returned error: OCI runtime create failed: creating container: waiting for sandbox to start: EOF: unknown"
aug 05 03:33:17 atlas dockerd[12979]: time="2019-08-05T03:33:17.674146856+02:00" level=error msg="stream copy error: reading from a closed fifo"
aug 05 03:33:17 atlas dockerd[12979]: time="2019-08-05T03:33:17.674221765+02:00" level=error msg="stream copy error: reading from a closed fifo"
aug 05 03:33:17 atlas dockerd[12979]: time="2019-08-05T03:33:17.891815509+02:00" level=error msg="8d3a2313aa268502257fd9b1e1e50de1b497b74c9e518c2ecd51adcbffdf5ea8 cleanup: failed to delete container from containerd: no such container"
aug 05 03:33:17 atlas dockerd[12979]: time="2019-08-05T03:33:17.912728817+02:00" level=error msg="Handler for POST /v1.39/containers/8d3a2313aa268502257fd9b1e1e50de1b497b74c9e518c2ecd51adcbffdf5ea8/start returned error: OCI runtime create failed: creating container: waiting for sandbox to start: EOF: unknown"
aug 05 03:33:21 atlas dockerd[12979]: time="2019-08-05T03:33:21.583792034+02:00" level=error msg="stream copy error: reading from a closed fifo"
aug 05 03:33:21 atlas dockerd[12979]: time="2019-08-05T03:33:21.586654205+02:00" level=error msg="stream copy error: reading from a closed fifo"
aug 05 03:33:21 atlas dockerd[12979]: time="2019-08-05T03:33:21.772864967+02:00" level=error msg="3d44eeb0eec5f4da0145e5bfe0477f1ba0b87f1632a873d3140f4b325f31412c cleanup: failed to delete container from containerd: no such container"
aug 05 03:33:21 atlas dockerd[12979]: time="2019-08-05T03:33:21.800731455+02:00" level=error msg="Handler for POST /v1.39/containers/3d44eeb0eec5f4da0145e5bfe0477f1ba0b87f1632a873d3140f4b325f31412c/start returned error: OCI runtime create failed: creating container: waiting for sandbox to start: EOF: unknown"
aug 05 03:33:24 atlas dockerd[12979]: time="2019-08-05T03:33:24.344601625+02:00" level=error msg="stream copy error: reading from a closed fifo"
aug 05 03:33:24 atlas dockerd[12979]: time="2019-08-05T03:33:24.347621176+02:00" level=error msg="stream copy error: reading from a closed fifo"
aug 05 03:33:24 atlas dockerd[12979]: time="2019-08-05T03:33:24.579098489+02:00" level=error msg="ccd4efe5919068c106eec4310f837bb5eabd58d07455496be1631b1e476def13 cleanup: failed to delete container from containerd: no such container"
aug 05 03:33:24 atlas dockerd[12979]: time="2019-08-05T03:33:24.605326860+02:00" level=error msg="Handler for POST /v1.39/containers/ccd4efe5919068c106eec4310f837bb5eabd58d07455496be1631b1e476def13/start returned error: OCI runtime create failed: creating container: waiting for sandbox to start: EOF: unknown"
aug 05 03:33:44 atlas dockerd[12979]: time="2019-08-05T03:33:44.440475240+02:00" level=error msg="stream copy error: reading from a closed fifo"
aug 05 03:33:44 atlas dockerd[12979]: time="2019-08-05T03:33:44.668508590+02:00" level=error msg="cbd5ed5374afa4969984099e9277564e0be0e0c714817fbeae3a4bdf4de85dc1 cleanup: failed to delete container from containerd: no such container"
aug 05 03:33:44 atlas dockerd[12979]: time="2019-08-05T03:33:44.668552653+02:00" level=error msg="Handler for POST /v1.39/containers/cbd5ed5374afa4969984099e9277564e0be0e0c714817fbeae3a4bdf4de85dc1/start returned error: OCI runtime create failed: creating container: waiting for sandbox to start: EOF: unknown"

**Comment by ianlewis** [comment]
You installed the prerequisites for KVM right? https://gvisor.dev/docs/user_guide/platforms/#prerequisites

Can you post the relevant parts of the runsc debug logs?

**Comment by ianlewis** [comment]
I'm going to close this issue since it's old but feel free to reach out on our gitter channel if you have more questions: https://gitter.im/gvisor/community
