### ISSUE TITLE
Avoid allocating when writing packets

### ISSUE THREAD

**Issue by ghanan94** [google/gvisor#6538]
Currently when writing packets, the netstack will allocate a new buffer. 

Ideally we avoid this allocation.

E.g. https://github.com/google/gvisor/blob/927ea16dd384f675a2ce1456be457a371109c488/pkg/tcpip/transport/udp/endpoint.go#L513

**Comment by milantracy** [comment]
iiuc, it still has to allocate the byte slice because it has to load data into the buf.

e.g.
https://github.com/google/gvisor/blob/927ea16dd384f675a2ce1456be457a371109c488/pkg/tcpip/transport/udp/endpoint.go#L514

**Comment by tamird** [comment]
It might not be possible in UDP because the packet has to go into the send queue, but it should be possible for packet sockets that write directly to the NIC.

**Comment by hbhasker** [comment]
It should be possible , UDP has no send queue. This is required because of the tcpip.Payloader interface and us using ReadTo. If we can request the whole Payload then it's trivial to avoid the allocation.

**Comment by hbhasker** [comment]
Actually with qDisc now inline in most cases this is almost impossible to avoid as the qdisc.

**Comment by hbhasker** [comment]
Closing as Won't fix. As with qdisc enabled this is never safe.
