### ISSUE TITLE
Annotate lock-protected fields with checklocks

### ISSUE THREAD

**Issue by ghananigans** [google/gvisor#6566]
Now that we have the `checklocks` analyzer, we should annotate values that are lock-protected with an appropriate `checklocks` attribute.

**Comment by BLasan** [comment]
@ghanan94 Hi, I'm new to the community. Does this issue need a prior knowledge on this project? Or is it ok me to take up this issue?
Thanks !!

**Comment by BLasan** [comment]
@ghanan94 Is this resolved?

**Comment by manninglucas** [comment]
Addressed in #7315
