### ISSUE TITLE
Gofer is inefficient in processing directories with a large number of files

### ISSUE THREAD

**Issue by Heatherchan2** [google/gvisor#6578]
### Description

Gofer is very inefficient in processing directories with a large number of files.

### Steps to reproduce

The overall idea is to create a multi-file directory on the host (create n files with a size of 1k), mount to the container /mnt directory, execute time ls /mnt, observe whether there is a hang phenomenon, and the operation duration

[gofertest.tar.gz](https://github.com/google/gvisor/files/7159341/gofertest.tar.gz)

test result:
n=10000
real 0m13.388s
user 0m0.070s
sys 0m1.790s
n=20000
real 1m31.835s
user 0m0.410s
sys 0m1.280s
n=30000
real 4m53.930s
user 0m0.510s
sys 0m6.240s
n=40000
real 11m27.049s
user 0m0.660s
sys 0m11.660s

**Comment by hbhasker** [comment]
@ayushr2 could you take a look?

**Comment by ayushr2** [comment]
I did exactly that with docker:
- Created a host directory with n files each of size 1k.
- `docker run --runtime=${RUNTIME} --rm -v ${PWD}/bigdir:/bigdir -v ${PWD}/bigdir2:/bigdir2 -v ${PWD}/bigdir3:/bigdir3 -v ${PWD}/bigdir4:/bigdir4 -it ubuntu bash`
- Ran `time ls bigdir` on each of them.

I don't seem to notice the exponential growth you are seeing. These are my observations:
| **Protocol/n**   | 10000  | 20000  | 30000  | 40000   |
|--------------|--------|--------|--------|---------|
| 9P (default) | 2.383s | 4.933s | 7.326s | 10.086s |
| Lisafs       | 1.81s  | 3.45s  | 5.095s | 6.85s   |
| Improvement  | 24%    | 30%    | 30%    | 32%     |

Note that lisafs is a new protocol being built that will replace 9p to communicate more efficiently with the gofer process. It is not checked in yet.

**Comment by amscanne** [comment]
Is the original report VFS1 or VFS2? Perhaps there is a difference there already.

**Comment by ayushr2** [comment]
@amscanne you are right, the demo uses VFS1.
This was fixed in VFS2. VFS1 degrades exponentially because the time increases more than double each time.

Please use VFS2. See https://groups.google.com/g/gvisor-users/c/rP-RCBDFKoY/m/qY2ZaYgEAgAJ.
