### ISSUE TITLE
Report a bug that mutates a not-used copy of a struct.

### ISSUE THREAD

**Issue by guodongli-google** [google/gvisor#6643]
### Description

At: https://github.com/google/gvisor/blob/master/runsc/boot/vfs.go#L171-L175

When  `procArgs` is dereferenced to `rootProcArgs`, `rootProcArgs` is a clone with its own memory since type `kernel.CreateProcessArgs` is a struct. Here `rootProcArgs` is a copy that is not used elsewhere, and mutating it doesn't do anything to the original `procArgs`. As a consequence, this mutation has no meaningful effect.
```
type CreateProcessArgs struct {
	Filename string
	...
}
    
rootProcArgs := *procArgs
rootProcArgs.WorkingDirectory = "/"
rootProcArgs.Credentials = rootCreds
```

A fix is to use the original pointer `procArgs`,  or replace all instances of `rootProcArgs` with `procArgs`:

```
rootProcArgs := procArgs
```
Perhaps the correct logic is (https://github.com/google/gvisor/blob/master/runsc/boot/vfs.go#L176):
```
rootCtx := rootProcArgs.NewContext(c.k)
```

Found by #deepgo.

**Comment by prattmic** [comment]
cc @zkoopmans
