### ISSUE TITLE
gVisor follows strong host but Linux is a weak host

### ISSUE THREAD

**Issue by ghananigans** [google/gvisor#6686]
Should gVisor follow the weak host model to follow Linux? https://datatracker.ietf.org/doc/html/rfc1122#page-62

**Comment by ghanan94** [comment]
Note that on stacks with only 1 interface, the choice in model has no observable difference in the stack.

**Comment by mikma** [comment]
The stack seems to be a mix between the strong and weak host model when IP forwarding is enabled.

If you add non-loopback addresses to the "lo" interface, then those addresses can be pinged from the outside, and they can be used by for example sshd. But you can't bind to a non-loopback address on one interface and make an outbound connnection which uses a route on another interface, for example with ssh -b, or ping -I.
