### ISSUE TITLE
Cgroupfs support tasks migration

### ISSUE THREAD

**Issue by DarcySail** [google/gvisor#6755]
### Description

Hi Mahmood @mrahatm , I notice that in current implementation, cgroupfs doesn't support task migration from one cgroup to another cgroup.
Are you working on this issue or having a plan for it?

**Comment by ayushr2** [comment]
@milantracy do you know if task migration from one cgroup to another is supported now? IIRC you worked on something similar recently?

**Comment by milantracy** [comment]
this was done by the PR at https://github.com/google/gvisor/pull/7213

I will close the the issue since it was completed, feel free to reopen it if there is anything missing
