### ISSUE TITLE
Get "cni plugin not initialized" when running node with gVisor on EKS

### ISSUE THREAD

**Issue by liyaka** [google/gvisor#6844]
### Description

I created a VM built from the latest official AMI for EKS node (amazon-eks-node-1.20-v20211101-2021-11-01T08-17-15Z) and I run the steps from this [tutorial](https://blog.vgs.dev/secure-compute-part-2#Putting-it-all-together:-Demo-my-Cluster) and then created an AMI that i use to create nodes in my cluster.
The nodes come up but appear "Not Ready"
This is what I see in describe node:
```runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized```

### runsc version

```shell
runsc version release-20211101.0
spec: 1.0.2
```

### kubectl (if using Kubernetes)

```shell
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:15:16Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by kevinGC** [comment]
Can you try with a newer version of gVisor? This may be #3301, which was fixed a couple weeks ago.

**Comment by liyaka** [comment]
The problem was with flags passed to kubelet in order to run containerd.
