### ISSUE TITLE
Makefile failed to generate help.

### ISSUE THREAD

**Issue by cnnblike** [google/gvisor#6887]
### Description

the make help is failing to generate human-readable result.

cnnblike@linux-dev-box:~/gvisor-latest$ sudo make help
[sudo] password for cnnblike: 
--- TAG default
--- DOCKER BUILD
gvisor-builder-14468cb7-x86_64
sha256:fbab31ef5e8307ed914bf53fc22027f0b7df0619da11b8891dc731182488a200
--- DOCKER RUN
gvisor-bazel-14468cb7-x86_64
90881745d66b661b2bc92645801780c23ab3a6b9f267e3e8948f46d5e1bba7e7
awk: run time error: regular expression compile failed (missing operand)
(:.*?|)## ?
	FILENAME="" FNR=0 NR=0
make: *** [Makefile:49: help] Error 2

### Steps to reproduce

1. pull latest gvisor from git.
2. do `sudo make help`
3. bam.

### runsc version

```shell
runsc version release-20211108.0-31-gb318556f83c0
spec: 1.0.2
```

### docker version (if using docker)

```shell
Docker version 20.10.7, build 20.10.7-0ubuntu5~21.04.2
```

### uname

Linux linux-dev-box 5.11.0-40-generic #44-Ubuntu SMP Wed Oct 20 16:16:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ianlewis** [comment]
Hmm, It works for me (though we are dubiously pulling the presubmit image even for targets like help). What version of make & awk are you using?

**Comment by cnnblike** [comment]
the versions I'm having is like below:
```
cnnblike@linux-dev-box:~/gvisor-latest$ git status
On branch master
Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	bin/

nothing added to commit but untracked files present (use "git add" to track)
cnnblike@linux-dev-box:~/gvisor-latest$ awk -W version
mawk 1.3.4 20200120
Copyright 2008-2019,2020, Thomas E. Dickey
Copyright 1991-1996,2014, Michael D. Brennan

random-funcs:       srandom/random
regex-funcs:        internal
compiled limits:
sprintf buffer      8192
maximum-integer     2147483647
cnnblike@linux-dev-box:~/gvisor-latest$ make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by ianlewis** [comment]
I think using mawk is causing it. I think the majority of users are going to be using GNU awk on linux machines. You're likely to run into other problems in the Makefile and various scripts.
