### ISSUE TITLE
Add Reordering detection to Netstack

### ISSUE THREAD

**Issue by hbhasker** [google/gvisor#691]
Netstack today does loss detection using a static nDupACK value of 3. This works fine most of the time but on networks where there can be significant reordering but not loss a static value of 3 is not ideal.  Before we can make adjustments to Netstack to account for reordering a good first step will be to add a metric that is updated everytime reordering is detected and maybe also emit a distribution metric of the degree of reordering detected.

**Comment by hbhasker** [comment]
Sending to @iangudger as he is going to be working on adding support for this.

**Comment by nybidari** [comment]
With the implementation of RACK, reordering is detected. The packet loss is identified based on the reorder timer expiry if reordering is seen in the connection. When reordering is not seen, 3 duplicate ACK mechanism is used to identify loss.
