### ISSUE TITLE
Enable leak checking for packet buffers

### ISSUE THREAD

**Issue by ghanan94** [google/gvisor#6910]
### Description

Leak checking is only available to things that enable leak checking via https://github.com/google/gvisor/blob/72e222cd661477de4a9d15b01fe84e3fc4046dac/pkg/refs/refcounter.go#L395.

We should look into using `refs.AtomicRefCounter` for reference counting packet buffers so that we can have leak checking

**Comment by manninglucas** [comment]
I'm not sure I understand this issue. Leak checking is already possible in the current implementation with `refsvfs2.RefCounter` and `refs.AtomicRefCounter` is deprecated.

**Comment by hbhasker** [comment]
Leak checking is being added to all networking tests. Transport/link tests already enable leak checker and we will be enabling network and other misc packages shortly. I will update this bug with the changes.

**Comment by hbhasker** [comment]
I believe this is done? Is there something else left to do here?
