### ISSUE TITLE
Wrong len in FUSEHeaderIn when sending write request with a payload

### ISSUE THREAD

**Issue by YaroslavLitvinov** [google/gvisor#6964]
### Description

When sending FUSEHeaderIn request with a FUSE_WRITE data containing a payload, current implementation of fuse in gvisor incorrectly calculates `FUSEHeaderIn.Len` field, taking into account a fixed size of marshaled data structure only, which is  - [payload.SizeBytes()](https://github.com/google/gvisor/blob/master/pkg/sentry/fsimpl/fuse/request_response.go#L117), and not using here size of actual payload, though sending it.

For instance: When writing 100 bytes file, the overall packet length should be 40 + 40 + 100, where 40 is the size of FUSEHeaderIn, 40 - FUSEWriteIn, 100 - file size, and not just 80 bytes as currently.

It looks to me that the test/fuse/linux/write_test.cc test is testing exactly this behavior.

This leads to errors related to receiving excessive data on server side when it attempts to read that data.

Point me if I am wrong.

**Comment by pkit** [comment]
@avagin Hi again, I'm not sure if `fuse` support is any priority. But if so, what's the supposed write support next steps?

**Comment by ayushr2** [comment]
@avagin seems like you already have a fix for this? Do you want to rebase & merge that?

**Comment by avagin** [comment]
https://github.com/google/gvisor/pull/6937/commits/b7ccfa5084e252f3b159aa3d44c007b889cd4287
