### ISSUE TITLE
Use network protocol default ttl instead of a hardcoded one

### ISSUE THREAD

**Issue by arthurpi** [google/gvisor#6973]
### Description

In sentry, instead of defining a local DefaultTTL of 64, we should retrieve the configured DefaultTTL (via the DefaultTTLOption).

In pkg/sentry/socket/netstack/netstack.go

This can be done by using stack.NetworkProtocolOption(protocolNumber, DefaultTTL)

**Comment by milantracy** [comment]
Seems to be an easy fix.

I am not sure if there is any design decision for the constant. I could pick this up if no one else is working on the issue.

**Comment by milantracy** [comment]
closed the issue as the commit [2b2f9ea914bd52b7155f5643d7975f38b3331b58](https://github.com/google/gvisor/commit/2b2f9ea914bd52b7155f5643d7975f38b3331b58) is merged
