### ISSUE TITLE
Idea: host-OS-independence with alternate syscall interface

### ISSUE THREAD

**Issue by adamierymenko** [google/gvisor#7]
I have an idea for this that builds on an idea I've had for a long time but have never had (and probably will not have) the time to implement.

The idea is to pseudo-virtualize Linux binaries by rebuilding them to call a function in user-space instead of executing CPU-level syscalls. This would require apps to be rebuilt from source, making it effectively a different "hardware architecture" (e.g. x86_64-uvirt or something) from standard Linux, but would otherwise be fully compatible. This would eliminate the ptrace requirement to make it portable and also might be faster.

It seems like it would be borderline trivial to do this with gVisor.

This would open up the possibility of embedding Linux hosts inside anything including desktop and mobile apps or server processes for other OSes like Windows. You could port, desktop-ify, or even mobile-ify any complex Linux application.

**Comment by littleq0903** [comment]
it would be like what WSL does in Windows.

**Comment by hugelgupf** [comment]
If you ported gVisor to other OS', i.e. came up with a kvm-like platforms using an OS X / Windows / whatever hypervisor, and moved some Linux-specific bits in the sentry around, you wouldn't even need to modify the binaries you want to run. 

You could have to rebuild if you want to skip the hypervisor/syscall-interception-platform and move only the Linux-specific bits around. But that's kind of a totally different project than what gVisor is targeted at.

**Comment by bluecmd** [comment]
Isn't the point of gVisor to secure untrusted workloads though? If so, that is stopping the unknown software from embedding syscalls and not play nice?

**Comment by adamierymenko** [comment]
@hugelgupf Yes that could work, but the thought I had was to make it possible to run Linux environments anywhere with no elevated permissions.

**Comment by fvoznika** [comment]
Closing old bugs. Please reopen if you'd like to continue the discussion.

**Comment by archerbroler** [comment]
bluepill can be done on linux too. perhaps its not such hard to port gvisor to win.

**Comment by amscanne** [comment]
I'm not familiar with the Windows hypervisor APIs, is there good reference documentation?
