### ISSUE TITLE
File handler leakage when making fuse_operations.Create call

### ISSUE THREAD

**Issue by YaroslavLitvinov** [google/gvisor#7001]
### Description

Current implementation of (*inode) NewFile, that is based on [newEntry](https://github.com/google/gvisor/blob/master/pkg/sentry/fsimpl/fuse/fusefs.go#L609)  is not handling returned file descriptor that is supposedly fits [FUSEOpenOut](https://github.com/google/gvisor/blob/master/pkg/abi/linux/fuse.go#L429). In overall that is leading to a file handler leakage inside of gvisor.

In practice when user uses something like open(...,O_CREAT) gvisor fuse makes two calls: create & open. After file is created by `create` it just eats returned file descriptor and makes `open` call to acquire another file handle that will be returned to a caller.

**Comment by avagin** [comment]
@YaroslavLitvinov //test/fuse:create_test_runsc_ptrace_shared_vfs2_fuse fails with these changes.
