### ISSUE TITLE
Share control message logic between network Endpoint

### ISSUE THREAD

**Issue by arthurpi** [google/gvisor#7012]
### Description

UDP, RAW & ICMP endpoints all need similar code to handle receiving control messages (they share SOL_SOCKET, SOL_IP, SOL_IPV6 cmsgs). To avoid duplication, they should use common facilities to populate these control messages.

**Comment by milantracy** [comment]
maybe to generalize https://github.com/google/gvisor/blob/ce194f2c1c1443de9c1efa374dcf6d6554457a4c/pkg/tcpip/transport/raw/endpoint.go#L96 for reuse?
