### ISSUE TITLE
Not Sending 'Destination Unreachable' for UDP Traceroute

### ISSUE THREAD

**Issue by chunyingw** [google/gvisor#703]
Traceroute to the Fuchsia device over a direct connection seems to work on everything except UDP.
$ sudo traceroute -6 -T $(fx netaddr --fuchsia)
traceroute to fe80::4607:bff:febb:3063%enx44070bbb3062 (fe80::4607:bff:febb:3063%enx44070bbb3062), 30 hops max, 80 byte packets
 1  fe80::4607:bff:febb:3063%enx44070bbb3062 (fe80::4607:bff:febb:3063%enx44070bbb3062)  0.319 ms  0.293 ms  0.300 ms
$ sudo traceroute -6 -I $(fx netaddr --fuchsia)
traceroute to fe80::4607:bff:febb:3063%enx44070bbb3062 (fe80::4607:bff:febb:3063%enx44070bbb3062), 30 hops max, 80 byte packets

$ traceroute -6 $(fx netaddr --fuchsia)
traceroute to fe80::4607:bff:febb:3063%enx44070bbb3062 (fe80::4607:bff:febb:3063%enx44070bbb3062), 30 hops max, 80 byte packets
 1  * * *
 2  * * *
 3  * * *
 4  * * *
 5  * * *
 .... 30 hops ....

**Comment by tamird** [comment]
@mrahatm is this your area?
