### ISSUE TITLE
Building master branch in aws aarch64 failed 

### ISSUE THREAD

**Issue by jeyaprabhuj-tts** [google/gvisor#7089]
### Description
Ubuntu 20.04.3 LTS (GNU/Linux 5.11.0-1023-aws aarch64)

steps followed as per build instructions

`make copy TARGETS=runsc DESTINATION=bin/`

INFO: Repository bazel_gazelle_go_repository_tools instantiated at:
  /home/ubuntu/golang/master/WORKSPACE:67:21: in <toplevel>
  /home/ubuntu/.cache/bazel/_bazel_ubuntu/414ccf448066191dd8ceb195229a5ef0/external/bazel_gazelle/deps.bzl:68:24: in gazelle_dependencies
Repository rule go_repository_tools defined at:
  /home/ubuntu/.cache/bazel/_bazel_ubuntu/414ccf448066191dd8ceb195229a5ef0/external/bazel_gazelle/internal/go_repository_tools.bzl:117:38: in <toplevel>
ERROR: An error occurred during the fetch of repository 'bazel_gazelle_go_repository_tools':
   Traceback (most recent call last):
        File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/414ccf448066191dd8ceb195229a5ef0/external/bazel_gazelle/internal/go_repository_tools.bzl", line 103, column 13, in _go_repository_tools_impl
                fail("failed to build tools: " + result.stderr)
Error in fail: failed to build tools: go build github.com/bazelbuild/bazel-gazelle/language/proto: /home/ubuntu/.cache/bazel/_bazel_ubuntu/414ccf448066191dd8ceb195229a5ef0/external/go_sdk/pkg/tool/linux_arm64/compile: signal: killed
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/414ccf448066191dd8ceb195229a5ef0/external/bazel_gazelle/internal/go_repository_tools.bzl", line 103, column 13, in _go_repository_tools_impl
                fail("failed to build tools: " + result.stderr)
Error in fail: failed to build tools: go build github.com/bazelbuild/bazel-gazelle/language/proto: /home/ubuntu/.cache/bazel/_bazel_ubuntu/414ccf448066191dd8ceb195229a5ef0/external/go_sdk/pkg/tool/linux_arm64/compile: signal: killed
ERROR: /home/ubuntu/golang/master/runsc/cli/BUILD:5:11: no such package '@com_github_google_subcommands//': no such package '@bazel_gazelle_go_repository_config//': no such package '@bazel_gazelle_go_repository_tools//': failed to build tools: go build github.com/bazelbuild/bazel-gazelle/language/proto: /home/ubuntu/.cache/bazel/_bazel_ubuntu/414ccf448066191dd8ceb195229a5ef0/external/go_sdk/pkg/tool/linux_arm64/compile: signal: killed
 and referenced by '//runsc/cli:cli'
ERROR: Analysis of target '//runsc:runsc' failed; build aborted: Analysis failed
INFO: Elapsed time: 74.855s
INFO: 0 processes.

**Comment by jwright-stripe** [comment]
I had the same issue and it turned out to be from https://github.com/bazelbuild/bazel-gazelle/pull/1333. In short, since gvisor is currently using bazel-gazelle 0.27.0 (which doesn't have this fix), building the proto library can exhaust the resources of small hosts.

Upgrading locally to v0.28.0 fixed the issue for me. I'll see if I can put up a PR soon.
