### ISSUE TITLE
 ICMP: Resolve incorrect Checksum. 

### ISSUE THREAD

**Issue by globaledgesoftware-ltd** [google/gvisor#709]
[0001-ICMP-Resolve-incorrect-Checksum.docx](https://github.com/google/gvisor/files/3509157/0001-ICMP-Resolve-incorrect-Checksum.docx)

ICMP: Resolve incorrect Checksum.
   
The ICMP Echo Reply message should be generate correct checksum.
   
This CL adds a fix to send ICMP Echo Reply message with correct checksum.

**Comment by jelischer** [comment]
I believe this was  fixed. I see correct checksums these days.
