### ISSUE TITLE
tcpip/link/fdbased: socket operation on non-socket

### ISSUE THREAD

**Issue by xjasonlyu** [google/gvisor#7125]
### Description

Since commit e511fc90927639b8c74652738112969e6a626d16 removed the `WritePacket` method from tcpip/link/fdbased package, this error may occur under some certain circumstances.

e.g. When we use tcpip/link/tun to open a TUN device:

```go
fd, err := tun.Open(t.name)
if err != nil {
	return nil, fmt.Errorf("create tun: %w", err)
}
```

Then pass the TUN fd as a fdbased.Option and add the endpoint to stack:

```go
ep, err := fdbased.New(&fdbased.Options{
	FDs: []int{fd},
	...
})
```

The `WritePackets` method would be called to write back packets:
https://github.com/google/gvisor/blob/e511fc90927639b8c74652738112969e6a626d16/pkg/tcpip/link/fdbased/endpoint.go#L671

Then the `sendBatch`:
https://github.com/google/gvisor/blob/e511fc90927639b8c74652738112969e6a626d16/pkg/tcpip/link/fdbased/endpoint.go#L689

However, in the the `sendBatch`, the `else` would be hit and call the `rawfile.NonBlockingSendMMsg(batchFD, mmsgHdrs)`:
https://github.com/google/gvisor/blob/e511fc90927639b8c74652738112969e6a626d16/pkg/tcpip/link/fdbased/endpoint.go#L637-L657

So the issue happens here, the `SENDMMSG` syscall is used on a non-socket fd (TUN fd instead) and cause the `socket operation on non-socket` error:
https://github.com/google/gvisor/blob/e511fc90927639b8c74652738112969e6a626d16/pkg/tcpip/link/rawfile/rawfile_unsafe.go#L135-L142

### Steps to reproduce

Mentioned above.

### runsc version

```shell
null
```

### docker version (if using docker)

```shell
null
```

### uname

null

### kubectl (if using Kubernetes)

```shell
null
```

### repo state (if built from source)

null

### runsc debug logs (if available)

```shell
null
```

**Comment by hbhasker** [comment]
Thanks for the detailed report. I will take a look.

**Comment by hbhasker** [comment]
We just need to store that the underlying FD is not a socket and degrade WritePackets to writePacket always.

We do the socket check fdbased.New() but its not plumbed through to the write path. We should do that.
