### ISSUE TITLE
make: *** [Makefile:67: copy] Error 1

### ISSUE THREAD

**Issue by saikiran2021** [google/gvisor#7132]
### Description

i tried to keep some logs to understand the code .i found the below error while build. FYI i am attaching an image.
![Screenshot from 2022-02-02 12-33-18](https://user-images.githubusercontent.com/79690321/152108955-45123bf8-32b9-4bd7-bbc9-d13ad1ccfef9.png)

**Comment by dhana22222** [comment]
Is it possible to import another packages into gvisor?
