### ISSUE TITLE
` ip a` shows no network devices with `nerdctl run --runtime=io.containerd.runsc.v1` (because gVisor lacks  support for OCI `createRuntime` hooks)

### ISSUE THREAD

**Issue by AkihiroSuda** [google/gvisor#7149]
### Description

Network doesn't work with `nerdctl run --runtime=io.containerd.runsc.v1`.
`ip a` doesn't show any network device.

Not sure whether this is an issue of gVisor or nerdctl, though.

### Steps to reproduce

`ip a` doesn't show any network device.

```console
# nerdctl run -it --rm --runtime io.containerd.runsc.v1 alpine 
/ # ip a
/ #
```

### runsc version

```shell
runsc version release-20220131.0
spec: 1.0.2-dev
```

### ~docker~ containerd/nerdctl version

```shell
# nerdctl version
Client:
 Version:       v0.16.1
 Git commit:    c4bd56b3aa220db037cc6c0a4e0c8cc062f2cc4c

Server:
 containerd:
  Version:      v1.6.0-rc.1
  GitCommit:    ad771115b82a70cfd8018d72ae489c707e63de16

# nerdctl info
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v1.6.0-rc.1
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Log: json-file
  Storage: native overlayfs stargz
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-28-generic
 Operating System: Ubuntu 21.10
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.59GiB
 Name: suda-ws01
 ID: 49042c58-0800-45ce-9de8-fd150bb173c6
```

### uname

Linux suda-ws01 5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by AkihiroSuda** [comment]
CNI info:
```console
# nerdctl network inspect --mode=native bridge
[
    {
        "CNI": {
            "cniVersion": "0.4.0",
            "name": "bridge",
            "nerdctlID": 0,
            "nerdctlLabels": {},
            "plugins": [
                {
                    "type": "bridge",
                    "bridge": "nerdctl0",
                    "isGateway": true,
                    "ipMasq": true,
                    "hairpinMode": true,
                    "ipam": {
                        "ranges": [
                            [
                                {
                                    "gateway": "10.4.0.1",
                                    "subnet": "10.4.0.0/24"
                                }
                            ]
                        ],
                        "routes": [
                            {
                                "dst": "0.0.0.0/0"
                            }
                        ],
                        "type": "host-local"
                    }
                },
                {
                    "type": "portmap",
                    "capabilities": {
                        "portMappings": true
                    }
                },
                {
                    "type": "firewall"
                },
                {
                    "type": "tuning"
                },
                {
                    "type": "isolation"
                }
            ]
        },
        "NerdctlID": 0,
        "NerdctlLabels": {}
    }
]
```

CNI is configured during the OCI `createRuntime` event.
https://github.com/containerd/nerdctl/blob/c4bd56b3aa220db037cc6c0a4e0c8cc062f2cc4c/pkg/ocihook/ocihook.go#L318

**Comment by fvoznika** [comment]
@AkihiroSuda you're spot on. gVisor is still using the deprecated `Prestart` hook. Changing it to use `CreateRuntime` shouldn't be a problem. However, `CreateContainer` and `StartContainer` can't be implemented because they need to run inside the sandbox process in order to execute in container namespace. Do you need them?

**Comment by AkihiroSuda** [comment]
> @AkihiroSuda you're spot on. gVisor is still using the deprecated `Prestart` hook. Changing it to use `CreateRuntime` shouldn't be a problem. However, `CreateContainer` and `StartContainer` can't be implemented because they need to run inside the sandbox process in order to execute in container namespace. Do you need them?

No, nerdctl only need createRuntime and postStop (as of v0.16.1)
https://github.com/containerd/nerdctl/blob/v0.16.1/pkg/ocihook/ocihook.go#L75-L82

**Comment by fvoznika** [comment]
If you have a chance, please give the PR above a try and let me know if it fixes the problem.

**Comment by AkihiroSuda** [comment]
Thank you @fvoznika 

In addition to support `createRuntime` hook, runsc has to propagate the annotations from `config.json` to the `State` object for the hooks. https://github.com/opencontainers/runtime-spec/blob/v1.0.2/runtime.md#state

Can be worked around on the nerdctl side, though: https://github.com/containerd/nerdctl/pull/788/commits/a7aa9e90e6d33bf52346d0eb3f14a561409a3642

**Comment by AkihiroSuda** [comment]
I also noticed that runsc doesn't bring up the loopback network interface unless CNI `loopback` plugin is enabled.

Not sure if it is a bug or expected behavior, but at least it differs from runc.
https://github.com/containerd/nerdctl/pull/788/commits/c2b8906727e0859eb4cb1d41d5b317f6da84ef9b

**Comment by fvoznika** [comment]
I've updated the PR with annotations from the spec added to the `State` object.

As for the loopback, runsc copies the network setup from the host to the sandbox. If the host doesn't have a loopback interface, then we assume that the sandbox shouldn't have one either. [Here is where we handle the looback interface](https://cs.opensource.google/gvisor/gvisor/+/master:runsc/sandbox/network.go;l=154;drc=3141bf7a245795969685e7f7f4ef09a0dcde19f8).
