### ISSUE TITLE
Syscall docs reporting based on vfs1

### ISSUE THREAD

**Issue by ianlewis** [google/gvisor#7161]
### Description

I believe that the syscall docs at https://gvisor.dev/docs/user_guide/compatibility/linux/amd64/ are still reporting based on support in vfs1. This should be switched over to vfs2 since that's the default now.

For example, renameat2 should be implemented but is listed as unimplemented.

**Comment by ayushr2** [comment]
We should probably fix this, since this is on our website and makes the compatibility issue appear worse than it really is.

**Comment by ianlewis** [comment]
Pretty sure this is fixed by ed35016d99e345ca8fc9adecc00f5c03970756dc since we don't even have syscall tables for vfs1 anymore.
