### ISSUE TITLE
IPv4 should do longest prefix match for src ip selection

### ISSUE THREAD

**Issue by hbhasker** [google/gvisor#7227]
### Description

When a NIC has multiple suitable IP addresses the stack should select the best address. In case of IPv6 the stack does a proper source IP selection based on the IPv6 RFC. But for IPv4 the stack today picks the first IP address on the NIC. 

The stack should do a longest prefix match to find the most suitable IPv4 address when picking the src IP.

See: https://github.com/google/gvisor/blob/ae089adbb223bc1600321ac0563c6fd4c26db97c/pkg/tcpip/network/ipv4/ipv4.go#L1085

vs

https://github.com/google/gvisor/blob/94b1c1657e60849aab2743eb4257770306645b55/pkg/tcpip/network/ipv6/ipv6.go#L1714

**Comment by kevinGC** [comment]
Fixed by fd95313e832310b4f495bc0e438f6928778e2e68, baf097a14df6bfdcf1868e63de749a624fc2ea10, and 19399cd60bd45ec7cb072b5adb9997e74d348949.
