### ISSUE TITLE
epoll_wait does not return EPOLLHUP events on remote close

### ISSUE THREAD

**Issue by brianquinlan** [google/gvisor#7331]
### Description

`epoll_wait` does not generate `EPOLLHUP` events when the server closes the associated file descriptor.

gVisor output:
```
main: running
server: running
server: waiting for a connection...
client: running
client: fd is: 4
client: connected.
Events received: 4
server: connected with 6.
Events received: 5
server: closed fd 6
```

Linux output:
```
main: running
server: running
server: waiting for a connection...
client: running
client: fd is: 5
server: connected with 4.
server: closed fd 4
client: connected.
Events received: 8213
Got close!
```

Note that the `Got close!` output is not present when run under gVisor, which corresponds to the lack of `EPOLLHUP` event.

The repro was reduced from the original bugs, where Postgres could not be used correctly on Google Cloud Run:
https://github.com/dart-lang/sdk/issues/47899
https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/302

### Steps to reproduce

[repro.cc.zip](https://github.com/google/gvisor/files/8354049/repro.cc.zip)
```
$ c++ -pthread repro.cc
$ ./a.out
```

### runsc version

```shell
$ runsc --version
runsc version google-436818345
spec: 1.0.2-dev
```
```


### docker version (if using docker)

_No response_

### uname

Linux <host> 5.15.15-1rodete2-amd64 #1 SMP Debian 5.15.15-1rodete2 (2022-02-23) x86_64 GNU/Linux

### kubectl (if using Kubernetes)

_No response_

### repo state (if built from source)

_No response_

### runsc debug logs (if available)

_No response_

**Comment by hbhasker** [comment]
@nlacasse looks like UDS implementation maybe is missing a notify.

**Comment by ayushr2** [comment]
I can still reproduce this.

**Comment by ayushr2** [comment]
Thanks for investigating these Cloud Run issues and providing a reproducer, that was really helpful. I think #9870 should fix this issue.
