### ISSUE TITLE
gvisor #b8fa96e201bf79d9012ab60fddc560ff4a39165c not working w/ systemd-cgroups + cgroupsv2 + containerd

### ISSUE THREAD

**Issue by gpl** [google/gvisor#7334]
### Description

We're trying to get gvisor working with cgroupsv2 and systemd-cgroup as we saw this cl: https://github.com/google/gvisor/commit/bf86207401cab99d859b25acd4911038608f0d33

However, we're unable to get a functioning result.

### Steps to reproduce

On a Ubuntu 21.10 system, running kernel Linux 5.13.0-37-generic:

git clone https://github.com/google/gvisor; cd gvisor;
echo "module runsc" > go.mod
GO111MODULE=on go get gvisor.dev/gvisor/runsc@go
CGO_ENABLED=0 GO111MODULE=on sudo -E go build -o /usr/local/bin/runsc gvisor.dev/gvisor/runsc
GO111MODULE=on sudo -E go build -o /usr/local/bin/containerd-shim-runsc-v1 gvisor.dev/gvisor/shim

Then following the quick start steps here:

https://gvisor.dev/docs/user_guide/containerd/quick_start/

Invoking `sudo crictl runp --runtime runsc sandbox.json` results in:
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: OCI runtime create failed: creating container: finding current cgroups: Rel: can't make . relative to /: unknown
```

### runsc version

```shell
Commit b8fa96e201bf79d9012ab60fddc560ff4a39165c
```

### uname

Linux 5.13.0-37-generic #42-Ubuntu SMP Tue Mar 15 14:34:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### kubectl (if using Kubernetes)

```shell
1.23.3
```

### repo state (if built from source)

release-20220321.0-15-gb8fa96e20

**Comment by gpl** [comment]
We believe it could be related to having two paths:

```
34 24 0:29 / /sys/fs/cgroup rw,nosuid,nodev,noexec,relatime shared:9 - cgroup2 cgroup2 rw
1479 28 0:29 / /run/cilium/cgroupv2 rw,relatime shared:650 - cgroup2 none rw
```

**Comment by gpl** [comment]
Yep, this current configuration works fine with runc+containerd; the second path is introduced by an extension to Kubernetes (cilium.io) that we use.

**Comment by manninglucas** [comment]
@gpl Let us know if the issue persists; I believe #7343 should take care of the bug you reported.

**Comment by gpl** [comment]
The fix works perfectly for us; thank you!
