### ISSUE TITLE
Can't test pkg/tcpip

### ISSUE THREAD

**Issue by FH0** [google/gvisor#7351]
### Description

![image](https://user-images.githubusercontent.com/32861476/160973202-9bef35d5-e1c8-4462-b5ba-681db2a31a4b.png)

### uname

Linux AIR-14-PLUS 5.10.60.1-microsoft-standard-WSL2+ #1 SMP Fri Oct 15 12:42:02 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

### repo state (if built from source)

release-20220328.0-9-gfcd82c8eb

**Comment by hbhasker** [comment]
You need to use bazel to build and run tests as those are references to definitions to generated files.
