### ISSUE TITLE
Two Go packages ("transport" and "datagram") in the same directory

### ISSUE THREAD

**Issue by ivoronin** [google/gvisor#7392]
### Description

Can't build my project using newer gvisor versions.

### Steps to reproduce

1. Checkout https://github.com/ivoronin/wiresocks
2. Run `go build`: project builds successfully (using gvisor `v0.0.0-20211020211948-f76a604701b6`)
3. Run `go get -u`: gvisor version bumps to `v0.0.0-20220407222715-423589b41ac7` 
4. Run `go build` again. Error occurs: `../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220407222715-423589b41ac7/pkg/tcpip/transport/raw/endpoint.go:38:2: found packages transport (datagram.go) and datagram (datagram_test.go) in /Users/ivoronin/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220407222715-423589b41ac7/pkg/tcpip/transport`

Seems like a problem in gvisor source to me (two different packages in the same directory).
Not sure why it's not reported yet.
Am I doing something wrong?

### uname

Darwin macbook.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

**Comment by dimuls** [comment]
[This line](https://github.com/google/gvisor/blob/master/pkg/tcpip/transport/datagram_test.go#L16) should be
```
package transport_test
```

**Comment by hbhasker** [comment]
I will send a pr tomorrow to fix this. Apologies for the trouble.
