### ISSUE TITLE
docker run alpine failed with runsc runtime .

### ISSUE THREAD

**Issue by tianburg** [google/gvisor#74]
hi team,

I changed docker daemon json file as same as which showed in ReadMe.md  .

the command is :

> docker run --runtime=runsc  -it --rm alpine

> $ ls -lth /tmp/runsc/
> total 20K
> -rw-r--r-- 1 root root 7.0K 6月  18 17:10 runsc.log.20180618-171023.140523.create
> -rw-r--r-- 1 root root 5.1K 6月  18 17:10 runsc.log.20180618-171023.184570.gofer
> -rw-r--r-- 1 root root 1.8K 6月  18 17:10 runsc.log.20180618-171023.155798.gofer

the error msg :

>  FATAL ERROR: error creating container: unexpected error waiting for sandbox "7e999450105cfbe148a10d378b6d627691126ba2c7e1c7f08c5a0f82a33a1180", err: process (12659) is not running, err: <nil>

> FATAL ERROR: P9 server returned error. Gofer is shutting down. FD: 3, err: EOF

> FATAL ERROR: P9 server returned error. Gofer is shutting down. FD: 5, err: EOF

> docker: Error response from daemon: OCI runtime create failed: /var/lib/docker/runtimes/runsc did not terminate sucessfully: P9 server returned error. Gofer is shutting down. FD: 6, err: EOF
> error creating container: unexpected error waiting for sandbox "a48adda0775a48a5f5d9fe599482b512108597f34d91fad0aa4613a844621f4c", err: process (22356) is not running, err: <nil>
: unknown.

> Execve "/opt/usr/tmp/gvisor/runsc" again, bye!

Other useful information to include is:
- `docker version` or `docker info` if more relevant

> Client:
>  Version:	17.12.1-ce
>  API version:	1.35
>  Go version:	go1.10.1
>  Git commit:	7390fc6
>  Built:	Wed Apr 18 01:23:11 2018
>  OS/Arch:	linux/amd64

> Server:
> Engine:
>   Version:	17.12.1-ce
>   API version:	1.35 (minimum version 1.12)
>   Go version:	go1.10.1
>   Git commit:	7390fc6
>   Built:	Wed Feb 28 17:46:05 2018
>   OS/Arch:	linux/amd64
>   Experimental:	false

- `uname -a`
>  Linux myubuntu 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- `git describe`
- Full docker command you ran
> docker run --runtime=runsc  -it --rm alpine

**Comment by fvoznika** [comment]
This was a regression added on Friday. d509d6c fixed it. Sorry for the trouble.
