### ISSUE TITLE
Slow startup of kube-web-view

### ISSUE THREAD

**Issue by prattmic** [google/gvisor#746]
This is forked from [this Twitter thread](https://twitter.com/AngelBarrera92/status/1162649686588690437), and [this gist](https://gist.github.com/javierprovecho/d1ece672e8deb4cfe519c0d4f57cc3a7) with a repro.

I ran this repro, and I'm actually a bit surprised how fast the results in the gist are. I wonder if the CPU quota was actually enabled for those strace runs?

Without a CPU quota, I get ~0.8s (Linux) vs ~2.7s (runsc, ptrace).

With the 0.1 CPU quota, I get ~16s (Linux) vs ~64s (runsc, ptrace).

Similar ratios, though gVisor does seem to scale a bit worse with limited CPU quota than Linux.

I don't see any renames under gVisor, so I'm not sure where those are coming from. Could we get [full debug logs](https://gvisor.dev/docs/user_guide/debugging/) (just the runsc.###.boot file) from one of those runs?

In the second run, you can see the huge benefit of our caching (2.7s -> 1.0s), but cold starts won't get that advantage.

**Comment by hjacobs** [comment]
Thanks for the follow-up! Looking forward to seeing news on improved startup times of [kube-web-view](https://codeberg.org/hjacobs/kube-web-view/) (which uses Python aiohttp).
