### ISSUE TITLE
Debian package always overwrites Docker daemon.json

### ISSUE THREAD

**Issue by fffe** [google/gvisor#7517]
### Description

The Debian package for gvisor has a post-install script. This script checks for the existence of /etc/docker/daemon.json and, if found, runs `runsc install` which overwrites daemon.json with a basic file adding runsc but without any options.

I’m not sure if the test should be inverted (create daemon.json only if it doesn’t exist), the behaviour of `runsc install` improved to modify instead of overwrite, or removed entirely (I like this, personally, just document what’s required…) but the current behaviour seems wrong.

### Steps to reproduce

Customize /etc/docker/daemon.json (perhaps to include runtime args for gvisor)

Install or update gvisor from the Debian package.

Observe that the custom daemon.json has been overwritten.

### runsc version

```shell
Any/Current
```

### docker version (if using docker)

```shell
Any/Current
```

### uname

N/A

### kubectl (if using Kubernetes)

```shell
N/A
```

### repo state (if built from source)

N/A

### runsc debug logs (if available)

```shell
N/A
```

**Comment by fffe** [comment]
Unfortunately that answer isn’t satisfactory.

One problem is that it triggers on a package upgrade, not just install… realistically I may forget to run the above command after, but the update may also be performed by an automated process I can’t easily trigger other commands after.

The other is that I have other runtimes configured that aren’t runsc.

Effectively, to accommodate new users for whom you don’t know what configuration they might want, you’re overwriting the configuration of people who do.

Perhaps your post install script could just print a message pointing to the quick start documentation?

**Comment by zkoopmans** [comment]
@fffe: Huh, I thought I ran that case. 

The offending lines are here: https://github.com/google/gvisor/blob/86b29f5074897f075f5d2b49c16c6685304ca324/runsc/cmd/install.go#L109

I think the default behavior should probably be that, if given no arguments and an existing runtime of that name, we don't overwrite. Feel free to submit a PR or I can see if I can get to it soon. That *is* annoying.
