### ISSUE TITLE
Release builds not updated since 20220425

### ISSUE THREAD

**Issue by crappycrypto** [google/gvisor#7545]
### Description

See issue https://github.com/google/gvisor/issues/7327

Release builds are still not updated automatically. A tag with 20220502 was made, but no releases where pushed to 
- https://storage.googleapis.com/gvisor/releases/release/latest/x86_64/runsc
- The debian repository

### Steps to reproduce

```
wget https://storage.googleapis.com/gvisor/releases/release/latest/x86_64/runsc
chmod +x runsc
./runsc --version

**Comment by amscanne** [comment]
I suspect that the BuildKite release pipeline is filtering these tags. I'm rerunning those commits and updating the filter settings. Hopefully this fixes the issue.

**Comment by amscanne** [comment]
I backfilled the releases, hopefully the filter will allow future releases to be built. I'll check and close when that happens.

**Comment by SunRed** [comment]
The same problem is occurring again with tag 20220516.0.

**Comment by kevinGC** [comment]
It looks like `git tag` shows that nothing has been tagged since that release. `latest/x64_64/runsc` is being updated, but the latest tag is old.

**Comment by kevinGC** [comment]
Fixed and verified via the above commands.

The script in charge of tagging releases was failing.
