### ISSUE TITLE
Downloading previous versions of gvisor

### ISSUE THREAD

**Issue by dgageot** [google/gvisor#76]
The documentation says how to download the latest nightly of visor but can previous versions be downloaded? I would make sense to attach a version number to each bug report.

**Comment by fvoznika** [comment]
Yes, you can find older versions here: 
`https://storage.googleapis.com/gvisor/releases/nightly/<date>/runsc`.

Example:
```
https://storage.googleapis.com/gvisor/releases/nightly/2018-06-18/runsc
https://storage.googleapis.com/gvisor/releases/nightly/2018-06-18/runsc.sha512
```
