### ISSUE TITLE
Add stats per transport endpoint to improve debuggability.

### ISSUE THREAD

**Issue by iyermi** [google/gvisor#763]
Currently, we have aggregated stats across netstack. Along with that, we need to make some of these stats granular into each endpoint object and also add new stats for errors encountered in the packet read/write path.
For memory scalability, we can keep these as 32-bit stats unlike the current 64-bit aggregate stat.

**Comment by hbhasker** [comment]
Fixed in https://github.com/google/gvisor/commit/bf870c1a423063eb86a62c6268fe5d83fb6b87ba
