### ISSUE TITLE
No error on invalid command

### ISSUE THREAD

**Issue by ydjainopensource** [google/gvisor#77]
Try starting a container with an invalid command. 
runc correctly returns an error 
>docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"apt-get update\": executable file not found in $PATH": unknown.

However, runsc does not produce an output.  I can't get the terminal prompt again without sending `SIGINT`

In the logs, I could find this 
> I0621 02:34:28.669510    4573 x:0] Error opening apt-get update: no such file or directory
> I0621 02:34:28.669566    4573 x:0] Failed to load apt-get update: no such file or directory

Looks like gvisor kills the container but does not signal the docker daemon.

Moreover, I am experiencing uncharacteristically long waiting time for `systemctl stop docker` and ` sysemctl restart docker`

I could trace this till [this function](https://github.com/google/gvisor/blob/master/pkg/sentry/loader/loader.go#L197). Can someone give me a hint what to do next?

**Comment by ydjainopensource** [comment]
I ran the following command 
> docker run -it --runtime=runsc ubuntu:trusty "ifconfig -a"

Interestingly, if I run without the `-it` flag, I am getting the following error

>docker: Error response from daemon: OCI runtime start failed: /var/lib/docker/runtimes/runsc did not terminate sucessfully: error starting container: error starting root container [ifconfig -a]: failed to create init process: no such file or directory
: unknown.
ERRO[0001] error waiting for container: context canceled 

I am attaching the logs for your reference

[runsc.log.20180623-150707.617232.kill.txt](https://github.com/google/gvisor/files/2129805/runsc.log.20180623-150707.617232.kill.txt)
[runsc.log.20180623-150707.591997.state.txt](https://github.com/google/gvisor/files/2129806/runsc.log.20180623-150707.591997.state.txt)
[runsc.log.20180623-150707.324602.start.txt](https://github.com/google/gvisor/files/2129807/runsc.log.20180623-150707.324602.start.txt)
[runsc.log.20180623-150707.319893.state.txt](https://github.com/google/gvisor/files/2129808/runsc.log.20180623-150707.319893.state.txt)
[runsc.log.20180623-150707.278733.gofer.txt](https://github.com/google/gvisor/files/2129809/runsc.log.20180623-150707.278733.gofer.txt)
[runsc.log.20180623-150707.276271.boot.txt](https://github.com/google/gvisor/files/2129810/runsc.log.20180623-150707.276271.boot.txt)
[runsc.log.20180623-150707.275649.gofer.txt](https://github.com/google/gvisor/files/2129811/runsc.log.20180623-150707.275649.gofer.txt)
[runsc.log.20180623-150707.272561.create.txt](https://github.com/google/gvisor/files/2129812/runsc.log.20180623-150707.272561.create.txt)

**Comment by nlacasse** [comment]
I think you are just running into a quote issue.  Runsc is failing because it can't find a binary called "ifconfig -a".

Try running without the quotes around ifconfig:

```
docker run -it --runtime=runsc ubuntu:trusty ifconfig -a
```

**Comment by nlacasse** [comment]
Whoops! Totally misunderstood the point of this bug :( 

I also get a long timeout from Docker when I run with an invalid command.

**Comment by fvoznika** [comment]
There is a bit of a race condition trying to send the error message back to docker run from within the sandbox before the sandbox process exits and closes the communication channel. The code works pretty reliably without -it, but I've also noticed that it hangs with -it on the same command. I haven't had a chance to debug it yet though.

**Comment by fvoznika** [comment]
This works now. The error message is bit too verbose, I send a fix to make more readable:

```
> docker run --rm --runtime=runsc -ti alpine notfound
docker: Error response from daemon: OCI runtime start failed: /usr/local/google/docker/runtimes/gv2 did not terminate sucessfully: error starting container: error starting root container [notfound]: failed to start sandbox: error setting executable path for {Filename: Argv:[notfound] Envv:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=cc39815084fa TERM=xterm] WorkingDirectory:/ Credentials:0xc00021a120 FDMap:     fd:0 => name host:[1]
        fd:1 => name host:[1]
        fd:2 => name host:[1]
 Umask:18 Limits:0xc00022c090 MaxSymlinkTraversals:40 UTSNamespace:0xc000226480 IPCNamespace:0xc0002203a0 AbstractSocketNamespace:0xc00022c050 Root:<nil> ContainerID:cc39815084fa57a23e91f0ca915462acc2b42ef8277ac4d82d0200fbf5c6f98a}: no such file or directory
```
