### ISSUE TITLE
usleep and alikes do not work as expected when host clock goes backward

### ISSUE THREAD

**Issue by human3** [google/gvisor#7775]
### Description

When the clock on the host is adjusted, say 10s backward, the statement below will actually wait 10s instead of the requested 1s:

```
struct timespec delay;                                                                            
delay.tv_sec = 1;                                                                      
delay.tv_nsec = 0;
nanosleep(&delay, nullptr);
```

The video below shows a simple program logging current time every second (on the left panel). When the time is manually set backward 10s on the host (see right panel), one can see that the program no more prints anything for about 10s before resuming.

https://user-images.githubusercontent.com/15265841/176554439-f1dfd019-2292-4b90-b1f4-acd83086ec8c.mov

NOTES from https://man7.org/linux/man-pages/man2/nanosleep.2.html

       POSIX.1 specifies that nanosleep() should measure time against
       the CLOCK_REALTIME clock.  However, Linux measures the time using
       the CLOCK_MONOTONIC clock.  This probably does not matter, since
       the POSIX.1 specification for clock_settime(2) says that
       discontinuous changes in CLOCK_REALTIME should not affect
       nanosleep():

              Setting the value of the CLOCK_REALTIME clock via
              clock_settime(2) shall have no effect on threads that are
              blocked waiting for a relative time service based upon
              this clock, including the nanosleep() function; ...
              Consequently, these time services shall expire when the
              requested relative interval elapses, independently of the
              new or old value of the clock.

### Steps to reproduce

Save the following 4 files in a folder:

**repro.cc**
```c++
#include <iostream>
#include <unistd.h>

std::ostream& operator<<(std::ostream& os, const struct timespec& ts) {
  os << ts.tv_sec << " " << ts.tv_nsec;
  return os;
}

int main() {
  std::cout << "Running gvisor bug repro" << std::endl;

  struct timespec delay;
  delay.tv_sec = 1;
  delay.tv_nsec = 0;

  for (;;) {
    struct timespec now;
    clock_gettime(CLOCK_MONOTONIC, &now);
    std::cout << now << std::endl;

    // When the host clock is set backward, say 10s, any of the 3
    // statements below waits 10s instead of the requested 1s.

    clock_nanosleep(CLOCK_REALTIME, 0, &delay, nullptr);
    //nanosleep(&delay, nullptr);
    //usleep(1000000);


    // Conversely, the statement below always properly waits 1s, even
    // when host clock goes backward

    //clock_nanosleep(CLOCK_MONOTONIC, 0, &delay, nullptr);
  }

  // never reached
  return 0;
}
```
**Makefile**
```makefile
IMAGE=gvisor-bug
CT=$(IMAGE)-name
DOCKERRUN=docker run --rm --name $(CT)

default: a.out
	docker pull linuxcontainers/debian-slim
	docker build -t $(IMAGE) .

a.out: repro.cc
	g++ repro.cc

run: default
	$(DOCKERRUN) $(IMAGE)

runsc: default
	$(DOCKERRUN) --runtime=runsc $(IMAGE)

runsc-kvm: default
	$(DOCKERRUN) --runtime=runsc-kvm $(IMAGE)

kill:
	- docker kill $(CT)

goback10s:
	timedatectl set-ntp no
	date
	date --set="$(shell date --date '10 seconds ago')"

reset:
	timedatectl set-ntp yes
```

**CONTEXT**
```
a.out
```

**Dockerfile**
```
FROM linuxcontainers/debian-slim
COPY a.out .
ENTRYPOINT ["./a.out"]
```

Then:
* Launch the program with `make runsc`
* In another shell, sets the host clock backward (e.g. using `sudo make goback10s`)

### runsc version

```shell
runsc version release-20220606.0
spec: 1.0.2-dev
```

### docker version (if using docker)

```shell
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:48 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.13
  GitCommit:        9cc61520f4cd876b86e77edfeb88fbcd536d1f9d
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### uname

Linux velocity2 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux

**Comment by ayushr2** [comment]
Is this related to #8118? Are you using KVM?

**Comment by ayushr2** [comment]
^ issue was fixed in https://github.com/google/gvisor/commit/edc16b49e3b4302620231460f6155c3636ab9e51. But that was KVM specific and your reproducer is not using KVM, so I assume they are not the same issue.
