### ISSUE TITLE
Cannot run Julia: ftruncate on /dev/shm file returns errno 28 (no space left on device)

### ISSUE THREAD

**Issue by travigd** [google/gvisor#7827]
### Description

I'm trying to run Julia and it's failing to initialize consistently with `init_shared_map: No space left on device`. This does not happen outside of gVisor (or even on older versions of gVisor -- see below).

Running with `--debug` and `--strace`, I see this (added an attempt at emphasis to show the root of the problem):
```
tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.861674  215349 strace.go:590] [   1:   1] julia E statfs(0x7f93454f1040 /dev/shm/, 0x7fa970c10740)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.861695  215349 strace.go:628] [   1:   1] julia X statfs(0x7f93454f1040 /dev/shm/, 0x7fa970c10740) = 0 (0x0) (13.36µs)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.861721  215349 strace.go:602] [   1:   1] julia E futex(0x7f93454fa410, FUTEX_WAKE|FUTEX_PRIVATE_FLAG, 0x7fffffff, null, 0xca, 0x1)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.861728  215349 strace.go:640] [   1:   1] julia X futex(0x7f93454fa410, FUTEX_WAKE|FUTEX_PRIVATE_FLAG, 0x7fffffff, null, 0xca, 0x1) = 0 (0x0) (549ns)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.861761  215349 strace.go:596] [   1:   1] julia E openat(AT_FDCWD /, 0x7fa970c10a40 /dev/shm/julia-codegen-1-846930886, O_RDWR|O_CLOEXEC|O_CREAT|O_EXCL|O_NOFOLLOW, 0o700)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.861788  215349 strace.go:634] [   1:   1] julia X openat(AT_FDCWD /, 0x7fa970c10a40 /dev/shm/julia-codegen-1-846930886, O_RDWR|O_CLOEXEC|O_CREAT|O_EXCL|O_NOFOLLOW, 0o700) = 13 (0xd) (18.836µs)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.861814  215349 strace.go:593] [   1:   1] julia E fcntl(0xd /dev/shm/julia-codegen-1-846930886, 0x2, 0x1)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.861822  215349 strace.go:631] [   1:   1] julia X fcntl(0xd /dev/shm/julia-codegen-1-846930886, 0x2, 0x1) = 0 (0x0) (1.443µs)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.861845  215349 strace.go:590] [   1:   1] julia E fchmod(0xd /dev/shm/julia-codegen-1-846930886, 0o700)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.861855  215349 strace.go:628] [   1:   1] julia X fchmod(0xd /dev/shm/julia-codegen-1-846930886, 0o700) = 0 (0x0) (3.848µs)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt:I0722 04:53:05.861878  215349 strace.go:590] [   1:   1] julia E ftruncate(0xd /dev/shm/julia-codegen-1-846930886, 0x1000)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt:I0722 04:53:05.861887  215349 strace.go:628] [   1:   1] julia X ftruncate(0xd /dev/shm/julia-codegen-1-846930886, 0x1000) = 0 (0x0) (2.091µs)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.861912  215349 strace.go:602] [   1:   1] julia E mmap(0x0, 0x1000, PROT_READ|PROT_EXEC, MAP_SHARED, 0xd /dev/shm/julia-codegen-1-846930886, 0x0)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.861929  215349 strace.go:640] [   1:   1] julia X mmap(0x0, 0x1000, PROT_READ|PROT_EXEC, MAP_SHARED, 0xd /dev/shm/julia-codegen-1-846930886, 0x0) = 140270499991552 (0x7f9345531000) (9.935µs)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.861952  215349 strace.go:590] [   1:   1] julia E munmap(0x7f9345531000, 0x1000)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.861963  215349 strace.go:628] [   1:   1] julia X munmap(0x7f9345531000, 0x1000) = 0 (0x0) (5.387µs)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.861986  215349 strace.go:587] [   1:   1] julia E unlink(0x7fa970c10a70 /dev/shm/julia-codegen-1-846930886)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.861998  215349 strace.go:625] [   1:   1] julia X unlink(0x7fa970c10a70 /dev/shm/julia-codegen-1-846930886) = 0 (0x0) (5.665µs)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.862020  215349 strace.go:596] [   1:   1] julia E prlimit64(0x0, 0x1, 0x0, 0x7fa970c10ae0)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.862028  215349 strace.go:634] [   1:   1] julia X prlimit64(0x0, 0x1, 0x0, 0x7fa970c10ae0) = 0 (0x0) (1.847µs)

vvv failed ftruncate vvv

/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt:I0722 04:53:05.862050  215349 strace.go:590] [   1:   1] julia E ftruncate(0xd /dev/shm/julia-codegen-1-846930886 (deleted), 0x8000000)
ftruncate(0xd /dev/shm/julia-codegen-1-846930886 (deleted), 0x8000000)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt:I0722 04:53:05.862058  215349 strace.go:628] [   1:   1] julia X ftruncate(0xd /dev/shm/julia-codegen-1-846930886 (deleted), 0x8000000) = 0 (0x0) errno=28 (no space left on device) (871ns)

^^^ failed ftruncate ^^^

/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.862082  215349 strace.go:587] [   1:   1] julia E dup(0x2 host:[1])
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.862089  215349 strace.go:625] [   1:   1] julia X dup(0x2 host:[1]) = 14 (0xe) (1.709µs)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.862112  215349 strace.go:593] [   1:   1] julia E fcntl(0xe host:[1], 0x3, 0x7f934549e1f8)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.862118  215349 strace.go:631] [   1:   1] julia X fcntl(0xe host:[1], 0x3, 0x7f934549e1f8) = 2 (0x2) (470ns)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.862153  215349 strace.go:590] [   1:   1] julia E fstat(0xe host:[1], 0x7fa970c0fe60)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.862188  215349 strace.go:628] [   1:   1] julia X fstat(0xe host:[1], 0x7fa970c0fe60 {dev=7, ino=1, mode=S_IFCHR|0o620, nlink=1, uid=0, gid=0, rdev=0, size=0, blksize=1024, blocks=0, atime=2022-07-22 04:53:05.292159747 +0000 UTC, mtime=2022-07-22 04:53:05.292159747 +0000 UTC, ctime=2022-07-22 04:53:05.292159747 +0000 UTC}) = 0 (0x0) (10.874µs)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.862219  215349 strace.go:593] [   1:   1] julia E ioctl(0xe host:[1], 0x5401, 0x7fa970c0fdc0)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.862232  215349 strace.go:631] [   1:   1] julia X ioctl(0xe host:[1], 0x5401, 0x7fa970c0fdc0) = 0 (0x0) (6.634µs)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.862266  215349 strace.go:593] [   1:   1] julia E write(0xe host:[1], 0x7dd1d0 "init_shared_map: No space left on device\n", 0x29)
/tmp/runsc/runsc.log.20220722-045305.295311.boot.txt-I0722 04:53:05.862289  215349 strace.go:631] [   1:   1] julia X write(0xe host:[1], ..., 0x29) = 41 (0x29) (15.729µs)
```

Seems that `init_shared_map` is being called [here in the Julia source code](https://github.com/JuliaLang/julia/blob/3897667e57cd211eb803028ca823cc06c8ba6c3a/src/cgmemmgr.cpp#L252).

I was looking at the [diff that introduced this bug](https://github.com/google/gvisor/compare/release-20220425.0...release-20220502.1) but I'm not even remotely familiar with this codebase so I didn't see anything obvious.

### Steps to reproduce

I've narrowed this down to being introduced in `release-20220502.1`, everything before that seems to work okay and everything after (including `latest`) produces this error.

Can easily be reproduced (at least on my box):
```
$ docker run --runtime runsc -it --rm julia:1.6 julia -e '@show 1+1'
init_shared_map: No space left on device
```

### uname

`Linux dualnic-1 5.10.0-16-cloud-amd64 #1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux`

**Comment by travigd** [comment]
Update: `git bisect` has narrowed it down to https://github.com/google/gvisor/commit/ce91143bdc77ccdebf7aaae9ee8eb4843aa5f880 (cc @sshambhavi-252).

**Comment by ayushr2** [comment]
Thanks for the reproducer and the bisection.

**Comment by ayushr2** [comment]
Most likely it has something to do with doing a `ftruncate(2)` on a deleted file in tmpfs. `/dev/shm` is of type tmpfs.

Running `mount(1)` in the mentioned Julia container shows:
```
$ docker run -it --rm julia:1.6 bash
root@0253751eeaae:/# mount | grep dev/shm
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k,inode64)
```

So that is a tmpfs mount with the size option set. cc @sshambhavi-252

**Comment by travigd** [comment]
Incidentally, Julia doesn't try to do the same thing under runc. Not sure if it's detecting something different under gVisor.

**Comment by ayushr2** [comment]
> Incidentally, Julia doesn't try to do the same thing under runc. Not sure if it's detecting something different under gVisor.

@travigd could you clarify what you mean by "same thing" here? As in it is not deleting `/dev/shm/julia-codegen-1-846930886` and then calling ftruncate(2) with a size larger than the tmpfs's size limit.

Anyway, I think I understand what is happening. The deletedness of the file is a red herring. Linux accounts for pages against tmpfs size limit option when pages are allocated/deallocated for files in tmpfs. But our implementation accounts for pages when file size changes. However, file size can increase **without** any allocations. This happens on ftruncate(2). When the newly created file range from ftruncate is read, tmpfs just returns 0s. It only allocates the memory when writing to that range.

fallocate(2) is different. Unlike ftrucate(2) it actually allocates pages when increasing file size. All our testing was done using fallocate(2) and so this difference slipped through the cracks.

Two things need to happen:
- Fix our tmpfs fallocate implementation to actually allocate pages from the memory file so that writes in that region do not fail with ENOSPC. fallocate(2) man page mentions 
> After a successful call, subsequent writes into the range
> specified by offset and len are guaranteed not to fail because of
> lack of disk space.

- We need to fix our tmpfs regular file implementation to account for pages when [regularFile.data](https://cs.opensource.google/gvisor/gvisor/+/master:pkg/sentry/fsimpl/tmpfs/regular_file.go;l=79;drc=ea45573148e0656e5e3412f5a5db9cd823f5a2a0) is modified.

**Comment by ayushr2** [comment]
We are working on the fix. It is a little involved since we need to change things in our mm layer (which allocates pages).

In the meantime, a workaround could be to remount your /dev/shm mount with an absurdly large size option.
```
mount -o remount,size=10G,nosuid,nodev,noexec,relatime,inode64 /dev/shm
```

**Comment by travigd** [comment]
> @travigd could you clarify what you mean by "same thing" here? As in it is not deleting /dev/shm/julia-codegen-1-846930886 and then calling ftruncate(2) with a size larger than the tmpfs's size limit.

I just examined the output between running a Docker container with `runsc` and `runc`. For `runc`, it didn't seem to do anything with `/dev/shm`.

Thanks for the workaround.

**Comment by ayushr2** [comment]
> I just examined the output between running a Docker container with runsc and runc.

Your output from runsc is with debug logging enabled. Which includes strace logging. Strace logs include every system call that the application makes. That is why you can see the application use `/dev/shm`.

Just curious, how did you get a similar output from runc? It shows all the syscalls that the application (julia in this case) is making?

**Comment by travigd** [comment]
You're right about not seeing /dev/shm, but I ran both and only saw an ftruncate syscall at all when running under runsc.
