### ISSUE TITLE
20220801 release not available on mirrors

### ISSUE THREAD

**Issue by rlex** [google/gvisor#7871]
### Description

Hello!
Looks like recent releases wasn't uploaded to https://storage.googleapis.com/gvisor/releases/release/
...nor does [release-20220718.0](https://github.com/google/gvisor/releases/tag/release-20220718.0).
Latest available is [20220713.0](https://github.com/google/gvisor/releases/tag/release-20220713.0) it seems. 

FAILED! => {"changed": false, "dest": "/usr/local/bin/runsc", "elapsed": 12, "gid": 0, "group": "root", "mode": "0755", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "size": 36390078, "state": "file", "status_code": 404, "uid": 0, "url": "https://storage.googleapis.com/gvisor/releases/release/20220801/x86_64/runsc"}

**Comment by avagin** [comment]
It was fixed:
https://storage.googleapis.com/gvisor/releases/release/20221107.0/x86_64/runsc
