### ISSUE TITLE
compilation error in netstack repo with golang 1.17 onward

### ISSUE THREAD

**Issue by vikaspushkar** [google/gvisor#7878]
### Description

netstack which is being maintained as part of this repo is not getting compiled after the 1.17 golang version it throws the following error
# github.com/google/netstack/sleep
vendor/github.com/google/netstack/sleep/commit_amd64.s:14: (register+register) not supported on this architecture
asm: assembly of vendor/github.com/google/netstack/sleep/commit_amd64.s failed
# github.com/google/netstack/sleep
vendor/github.com/google/netstack/sleep/commit_amd64.s:14: (register+register) not supported on this architecture
asm: assembly of vendor/github.com/google/netstack/sleep/commit_amd64.s failed
# github.com/google/netstack/sleep
vendor/github.com/google/netstack/sleep/commit_amd64.s:14: (register+register) not supported on this architecture
asm: assembly of vendor/github.com/google/netstack/sleep/commit_amd64.s failed

I have tried to compile it on arm64 and amd64 based Mac machine.

### Steps to reproduce

take the latest version on netsatck and golang, compile it.

**Comment by amscanne** [comment]
Good news: this specific issue was fixed years ago and this file has not existed for a long time. You are definitely not any version of this repository from the latest couple years.

**Comment by vikaspushkar** [comment]
yea i am using it from netstack repo, is there any guideline for the user of netstack repo to upgrade  to latest code? any documentation ?
