### ISSUE TITLE
'@rules_cc' could not be resolved

### ISSUE THREAD

**Issue by tanjianfeng** [google/gvisor#788]
Compile issue:

$ bazel test test/syscalls/linux:proc_net_test
INFO: Invocation ID: f6a74cdd-6c58-415e-a036-87d125fd068e
ERROR: /root/git/gvisor-github/test/syscalls/linux/BUILD:110:1: error loading package '@com_google_absl//absl/time': Unable to find package for @rules_cc//cc:defs.bzl: The repository '@rules_cc' could not be resolved. and referenced by '//test/syscalls/linux:socket_test_util'
ERROR: Analysis of target '//test/syscalls/linux:proc_net_test' failed; build aborted: error loading package '@com_google_absl//absl/time': Unable to find package for @rules_cc//cc:defs.bzl: The repository '@rules_cc' could not be resolved.

The issue commit is: commit 31f05d5d4f6 ("Internal change.").

**Comment by amscanne** [comment]
I'm now getting this as well. I wasn't getting it yesterday. Trying to figure out what the heck is happening (looks like a bazel issue of some kind?).

**Comment by amscanne** [comment]
Somehow we broken this in 31f05d5d4f62c4cd4fe3b95b333d0130aae4b2c1. There should be a fix submitted shortly.
