### ISSUE TITLE
snifer.logPacket() out of bounds with raw packets

### ISSUE THREAD

**Issue by fvoznika** [google/gvisor#797]
`--log-packets` panics when raw endpoint is used.

Repro:
```shell
# Enable --log-packets in /etc/docker/daemon.json
docker run --rm --runtime=runsc alpine ping google.com
```

The problem is that part of the header is in the payload. The IP header is in `hdr` and ICMP header is in the payload. When `snifer.logPacket()` tries to parse the ICMP portion, it takes an out of bounds error. One possible solution is to always merge header and payload before calling `snifer.logPacket()`.

**Comment by kevinGC** [comment]
Fixed by #1232.
