### ISSUE TITLE
Loopback LinkEndpoint teardown can race with WritePackets

### ISSUE THREAD

**Issue by ewilden** [google/gvisor#7998]
### Description

Loopback LinkEndpoints are usually nested within an Ethernet endpoint when added to a gVisor Stack (this is true in [all non-test occurrences of loopback.New()](https://cs.opensource.google/search?q=loopback.New&sq=&ss=gvisor%2Fgvisor) in the gVisor repo). 

However, this is insufficient to safeguard against races. `nested`'s `Attach` implementation [releases its lock](https://cs.opensource.google/gvisor/gvisor/+/master:pkg/tcpip/link/nested/nested.go;l=77;drc=4fcd3c77eadd392471fbfaba6c625335a3fc69a0) before calling through to its child's `Attach`, so this can race with WritePackets, which is neither synchronized [in `nested`](https://cs.opensource.google/gvisor/gvisor/+/master:pkg/tcpip/link/nested/nested.go;l=116;drc=4fcd3c77eadd392471fbfaba6c625335a3fc69a0) nor [in `loopback`](https://cs.opensource.google/gvisor/gvisor/+/master:pkg/tcpip/link/loopback/loopback.go;l=77;drc=1f2b30d70c06acf07a0c40119fabbaf67c0c6937).

This was uncovered as a flaky panic in the Fuchsia Netstack (https://fxbug.dev/106034).

**Comment by ewilden** [comment]
I don't have the ability to assign this to myself, but I'll mail a CL for this shortly.

**Comment by avagin** [comment]
@ewilden any news?
