### ISSUE TITLE
status of save/restore?

### ISSUE THREAD

**Issue by matti** [google/gvisor#80]
I was listening to https://kubernetespodcast.com/episode/003-gvisor/ where at time 10:45 (remaining) @nlacasse and Yoshi Tamura talk about save restore as it would work and exist today - to me it looks like it does not really exist yet (https://github.com/google/gvisor/blob/master/runsc/main.go#L73-L95)

**Comment by nlacasse** [comment]
The gVisor libraries support save/restore today, but that functionality is not exposed through `runsc` yet.

We are actively working on this, and will update this bug as work progresses.  Stay tuned.

**Comment by nlacasse** [comment]
We now have experimental support for checkpoint/restore, although it does not work with Docker yet.

Please see the documentation for how to use checkpoint/restore in runsc:
https://gvisor.googlesource.com/gvisor/+/master/g3doc/checkpoint_restore.md

**Comment by matti** [comment]
@nlacasse opened #103 because I have no idea how could I test this without that.
