### ISSUE TITLE
Error with Makefile when building as root 

### ISSUE THREAD

**Issue by ZiluTian** [google/gvisor#801]
In Makefile, please add -o to the following line (already included) when building as root, otherwise build fails with "GID 0 already exists"
```docker exec --user 0:0 -i gvisor-bazel sh -c "groupadd --gid $(GID) -o gvisor && useradd --uid $(UID) --gid $(GID) -d $(HOME) gvisor"```

**Comment by ianlewis** [comment]
This was fixed by https://github.com/google/gvisor/commit/e31686500db56a5fcd4070561643d702a94da0c3
