### ISSUE TITLE
GCP Cloud Run: Various Unsupported syscall setsockopt

### ISSUE THREAD

**Issue by marcelsauer4711** [google/gvisor#8011]
### Description

hi, 

not sure if this is a bug on gvisor side but our gcp logs get spammed with these entries. in the last 7 days we got roughly 30k entries in the logs (see screens attached) across all our services.

stack:

- JDK17
- Spring Boot + Google Cloud Libraries
- @Scheduled Job that runs every 300ms and produces these logs on every tick
- Cloud Run First Generation Runtime

Errors in the logs ...

```
Container Sandbox: Unsupported syscall setsockopt(0xdc,0x29,0x12,0x3e45757fdacc,0x4,0x0).
Container Sandbox: Unsupported syscall setsockopt(0xda,0x10e,0x3,0x3e33da1fd770,0x4,0x3e342e00ce50).
Container Sandbox: Unsupported syscall setsockopt(0xce,0x10e,0x3,0x3e07dfffd770,0x4,0x0)
```
![gvisor_gcp](https://user-images.githubusercontent.com/51816780/191917271-4ec03ef0-d29e-44a9-85f1-2df200c28b88.png)
![gvisor_gcp2](https://user-images.githubusercontent.com/51816780/191917770-b5712d9c-22d9-4b86-8850-2429f16d5e3e.png)

some matches from the logs ...
```bash
grep textPayload downloaded-logs-20220923-101002.json | perl -pe 's/.*Unsupported syscall (.*). It is.*/\1/' | sort | uniq > gvisor.log
```
[gvisor.log](https://github.com/google/gvisor/files/9631976/gvisor.log)

**Comment by nlacasse** [comment]
The `setsockopt` calls some in 3 flavors:
```
setsockopt(FD, 0x11 = SOL_UDP, 0x67 =  UDP_SEGMENT)
setsockopt(FD, 0x29 = SOL_IPV6, 0x12 = SO_RCVLOWAT)
setsockopt(FD, 0x10e = SOL_NETLINK, 0x3 = SO_TYPE)
```

**Comment by nlacasse** [comment]
These log lines have been removed.  The fix will make it to Cloud Run within a few weeks.
