### ISSUE TITLE
Runtime monitoring can't get the path of write syscall

### ISSUE THREAD

**Issue by terenceli** [google/gvisor#8092]
### Description

I want to monitor the file write syscall using gVisor. 
I setup the test env in the 'Full example' section in here -->
https://github.com/google/gvisor/blob/master/pkg/sentry/seccheck/README.md

Then I add the '"syscall/sysno/1/enter"' to session.json file to configure trace write syscall.
The secchek can't print write path, it seems the 'write' syscall don't support 'fd_path'.

But your blog example seems support to get the file path of write syscall in here-->:
https://gvisor.dev/docs/tutorials/falco/        "Configuring Falco with gVisor"

Detect the file write in '/etc/' dir.

So is there anything wrong with my test?

Thanks,
Li Qiang

**Comment by fvoznika** [comment]
The `fd_path` optional field is not available for raw syscalls, because they all share the same schema and can't distinguish each are valid FDs and which are not. Below it shows the valid option fields for `syscall/sysno/1/enter` (which is the same for all `syscall/sysno/*` trace points):

```shell
$ ./runsc trace metadata | grep sysno/1/
Name: syscall/sysno/1/enter, optional fields: [], context fields: [time|thread_id|task_start_time|group_id|thread_group_start_time|container_id|credentials|cwd|process_name]
Name: syscall/sysno/1/exit, optional fields: [], context fields: [time|thread_id|task_start_time|group_id|thread_group_start_time|container_id|credentials|cwd|process_name]
```

I'll add an schematized write syscall trace point with the corresponding optional fields.

**Comment by fvoznika** [comment]
BTW, regarding the tutorial, the detection is done by monitoring `open*` syscalls for writable options, rather than monitoring each individual write to the system, which can be quite expensive.

**Comment by terenceli** [comment]
@fvoznika Thanks, I thank adding write syscall is reasonable just like the read syscall. It's expensive but it's more accurate to find the analysis the sandboxed process' behavior.
