### ISSUE TITLE
Download resources is limited by  tcpip. TCPSendBufferSizeRangeOption

### ISSUE THREAD

**Issue by Ficklecode** [google/gvisor#8093]
### Description

I was writing a proxy application using Windivert+gvisor and had a network error while downloading proxy resources from my browser.
When I set TCPSendBufferSize to 20<<20, the resource download reaches 40-55mb and a network error interrupts the download.
When I set TCPSendBufferSize to 100<<20, the resource was downloaded successfully.
And when I download, I look at the memory footprint, which goes up by the size of the downloaded file.
I'm concerned that the cache may have affected the results.

### runsc version

```shell
gvisor: release-20220926.0
golang:  1.18
```

**Comment by hbhasker** [comment]
Could you provide a simple repro?

**Comment by Ficklecode** [comment]
> Could you provide a simple repro?

I checked the code and found that there was a bug in my code🥲. Thank you for your assistance🍺
