### ISSUE TITLE
Could I use gVisor as a universal executable file launcher, without docker?

### ISSUE THREAD

**Issue by Just4test** [google/gvisor#81]
Hi, I'm creating an online judge system which run in AWS lambda.
To run unsafe code from user, I need a sandbox.
I think gVisor can help me. But lambda is already run in container, so I can't run docker in lambda code.
Cloud I use gVisor as a launcher? Just like:
> gvisor node unsafe.js

**Comment by amscanne** [comment]
FWIW, I don't think either of the platforms would work in Lambda (ptrace or KVM). Is the intent to just communicate with the unsafe code via stdin & stdout?
