### ISSUE TITLE
vdso: time goes backwards on amd machines under load

### ISSUE THREAD

**Issue by gabivlj** [google/gvisor#8118]
### Description

We’ve detected in AMD machines (e.g AMD EPYC 7642 48-Core Processor cpu) under load that the VDSO time access (including monotonic time) can return timestamps that go back in time. We can reliably reproduce this in specific machines every single time.

### Steps to reproduce

- You need an amd machine with a heavy load.
- Then run a program that uses the VDSO and calculates time with it, in our case we can provide this one that reliably reproduces it with clock_gettime(CLOCK_MONOTONIC). 

Note that if we do raw syscalls we can’t reproduce as VDSO is not being accessed in those cases.

clock.cc to reproduce easily:
```cpp
#include <chrono>
#include <iostream>
#include<thread>
#include <time.h>
#include <unistd.h>
#include <sys/syscall.h>
#include <sys/types.h>
int main() {

    std::cout << "Attempting std::chrono::steady_clock" << std::endl;
    while (1) {
        const auto before = std::chrono::steady_clock::now();
        const auto after = std::chrono::steady_clock::now();
        if (before > after) {
            std::cout << "Repro'd it with steady_clock " << before.time_since_epoch().count() << " > " << after.time_since_epoch().count() << std::endl;
            break;
        }
    }
    
    std::cout << "Attempting std::chrono::system_clock" << std::endl;

    while (1) {
        const auto before = std::chrono::system_clock::now();
        const auto after = std::chrono::system_clock::now();
        if (before > after) {
            std::cout << "Repro'd it with system_clock " << before.time_since_epoch().count() << " > " << after.time_since_epoch().count() << std::endl;
            break;
        }
    }

    std::cout << "Attempting clock_gettime(CLOCK_MONOTONIC)" << std::endl;
    while (1) {
        timespec before, after;
        clock_gettime(CLOCK_MONOTONIC, &before);
        clock_gettime(CLOCK_MONOTONIC, &after);
        if (before.tv_sec >= after.tv_sec && before.tv_nsec > after.tv_nsec) {
            std::cout << "Repro'd it with clock_gettime(CLOCK_MONOTONIC) " << before.tv_sec << "." << before.tv_nsec << " > " << after.tv_sec << "." << after.tv_nsec << std::endl;
            break;
        }
    }

    std::cout << "Attempting CLOCK_MONOTONIC raw syscall" << std::endl;
    // notice that it's stuck on this loop because it's not accessing VDSO
    while (1) {
        timespec before, after;
        syscall(SYS_clock_gettime, CLOCK_MONOTONIC, &before);
        syscall(SYS_clock_gettime, CLOCK_MONOTONIC, &after);
        if (before.tv_sec >= after.tv_sec && before.tv_nsec > after.tv_nsec) {
            std::cout << "Repro'd it with syscall CLOCK_MONOTONIC " << before.tv_sec << "." << before.tv_nsec << " > " << after.tv_sec << "." << after.tv_nsec << std::endl;
            break;
        }
    }    
}
```

Setup a rootfs of debian to run with runsc
```
docker export $(docker create debian) -o rootfs.tar.gz
mkdir -p bundle/rootfs
cd bundle
tar -xf ~/rootfs.tar.gz -C rootfs
mv path-to-your-repro /bin/repro-program
runsc spec -- /bin/bash
sudo runsc --platform=kvm run -bundle . testclock

```
Run the container with runsc
```
sudo runsc -debug-log ./logs --platform=kvm run -bundle . testclock
 repro-program
```
Sample output: 
```
sudo /tmp/runsc --platform=kvm --debug --strace --debug-log=/home/gvillalongasimon/runsc-log run -bundle . gvillatestclock
repro
Attempting std::chrono::steady_clock
Repro'd it with steady_clock 13467454019 > 13000757544
Attempting std::chrono::system_clock
Repro'd it with system_clock 1666705897822619998 > 1666705897119938264
Attempting clock_gettime(CLOCK_MONOTONIC)
Repro'd it with clock_gettime(CLOCK_MONOTONIC) 13.935826758 > 13.757544
```

* We can repro with CLOCK_REALTIME as well, see attached script with output on affected machine:
```
while true; do prevdate=`date +"%T,%3N"` prevs=`echo $prevdate |cut -d',' -f1|cut -d':' -f3` prevms=`echo $prevdate |cut -d',' -f2`; sleep 0.01; nowdate=$(date +"%T,%3N") ; nows=`echo $nowdate |cut -d',' -f1|cut -d':' -f3`; nowms=`echo $nowdate|cut -d',' -f2` ; diffms=`expr $nowms - $prevms` ; diffs=`expr $nows - $prevs`; if [ $diffms -lt 0 ] && [ $diffs -eq 0 ]; then echo prevdate: $prevdate nowdate: $nowdate; fi; done
prevdate: 10:29:56,995 nowdate: 10:29:56,912
prevdate: 10:30:45,921 nowdate: 10:30:45,911
prevdate: 10:31:09,950 nowdate: 10:31:09,911
prevdate: 10:31:47,943 nowdate: 10:31:47,911
prevdate: 10:31:55,994 nowdate: 10:31:55,911
prevdate: 10:33:29,998 nowdate: 10:33:29,911
```

Notice that it always prints ~911 in the milliseconds part. If we run the script again we would find another constant milliseconds being printed.

### Impact
Workloads such as which rely on stable time semantics misbehave. An example is video encoding which relies on time for next-frame prediction and does not expect this prediction to produce a negative number - can lead to really hard to reason about behavior.

### runsc version

release-20221003.0-2
(We’ve also seen it in release-20221017.0)

### uname

Linux - 5.15.74-cloudflare-kasan-2022.10.4 #1 SMP Mon Sep 27 00:00:00 UTC 2010 x86_64 GNU/Linux

### repo state (if built from source)
release-20221003.0

### runsc debug logs (if available)
```
D1025 14:34:48.046052       1 sampler.go:191] Time: Adjusting syscall overhead down to 875
D1025 14:34:49.046031       1 sampler.go:191] Time: Adjusting syscall overhead down to 766
D1025 14:34:50.047009       1 sampler.go:191] Time: Adjusting syscall overhead down to 671
D1025 14:34:51.046122       1 sampler.go:191] Time: Adjusting syscall overhead down to 588
D1025 14:34:52.046500       1 sampler.go:191] Time: Adjusting syscall overhead down to 515
D1025 14:34:52.046580       1 sampler.go:191] Time: Adjusting syscall overhead down to 875
D1025 14:34:53.046586       1 sampler.go:191] Time: Adjusting syscall overhead down to 451
D1025 14:34:56.046030       1 sampler.go:191] Time: Adjusting syscall overhead down to 766
D1025 14:34:57.046683       1 sampler.go:191] Time: Adjusting syscall overhead down to 671
D1025 14:34:58.046249       1 sampler.go:191] Time: Adjusting syscall overhead down to 588
D1025 14:34:59.046606       1 sampler.go:191] Time: Adjusting syscall overhead down to 515
D1025 14:35:00.046278       1 sampler.go:191] Time: Adjusting syscall overhead down to 451
```

We can try adding any logs you might see convenient, we can also test any ideas or make code changes that you recommend.

**Comment by amscanne** [comment]
Interesting, great report thank you. This nerd sniped me, as I thought "oh, this would be simple to defend against in the parameters" but indeed, we do already. I believe that this is a KVM-specific issue, because we can't just set the absolute guest TSC offset, and instead need to "calibrate" it. Can you confirm that this is only observed in KVM? Also, does that processor support TSC scaling? That would be an explanation for why it might only happen there, since we use a worst mode for calibration if TSC scaling is not supported [1]. I will give this a think and see if I can come up with any ideas for how to fix this situation.

[1] https://cs.opensource.google/gvisor/gvisor/+/master:pkg/sentry/platform/kvm/machine_amd64.go;l=217;drc=db4a71af39abddf01d6a7ff6f00314e0b88c8717;bpv=1;bpt=1

**Comment by amscanne** [comment]
Turns out that an API that allows setting the offset has made its way upstream (hurray!) as 5.16. I hacked up a quick sketch (#8121), but I'm not sure it works yet (or does what I expect it to). I'll carve off some time to validate at some point, but could you also see if the problem reproduces with that change.

**Comment by gabivlj** [comment]
Hi! Thank you so much for jumping on this. TSC scaling is supported on that processor. Sadly, I tried these changes and I'm still being able to replicate with both methods on KVM. 
I can confirm that I'm unable to replicate on ptrace at the moment.
