### ISSUE TITLE
nosplit stack error when using the debugger with Mac M1

### ISSUE THREAD

**Issue by knlambert** [google/gvisor#8149]
### Description

I'm trying to contribute to the [telepresence opensource](https://github.com/telepresenceio/telepresence) project (which uses gvisor) with the debugger (in goland), and I get the following stack trace:

![image](https://user-images.githubusercontent.com/16439060/199754943-1e085b0e-8868-4133-8f23-38aa88195414.png)

```bash
# command-line-arguments
gvisor.dev/gvisor/pkg/refs.(*AtomicRefCount).DecRef: nosplit stack over 792 byte limit
gvisor.dev/gvisor/pkg/refs.(*AtomicRefCount).DecRef<1>
    grows 48 bytes, calls gvisor.dev/gvisor/pkg/refs.(*AtomicRefCount).DecRefWithDestructor<1>
        grows 144 bytes, calls gvisor.dev/gvisor/pkg/refs.(*weakRefList).Remove<1>
            grows 128 bytes, calls gvisor.dev/gvisor/pkg/refs.(*weakRefEntry).SetNext<1>
                grows 16 bytes, calls runtime.gcWriteBarrier<1>
                    grows 224 bytes, calls runtime.wbBufFlush<0>
                        grows 32 bytes, calls runtime.wbBufFlush<1>
                            grows 32 bytes, calls runtime.cgoCheckWriteBarrier<1>
                                [...]
```

I only get the issue with a Mac M1, and it builds correctly on anything running amd64 (linux & mac).

### Steps to reproduce

Clone and build the project:

```bash
git clone git@github.com:telepresenceio/telepresence.git
make build
```

The error seems to be caused by the -N flag added by goland, so just building the project with it causes the issue.

```bash
go build -o telepresence -gcflags=all="-N" cmd/telepresence/*
```

### runsc version

```shell
Not relevant for this issue, but the project uses this version:

gvisor.dev/gvisor v0.0.0-20220925003544-1e2f1a11bf64
```

### uname

Darwin MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 arm64

**Comment by andig** [comment]
Opened as https://github.com/golang/go/issues/56917, should I close the Go issue?

**Comment by andig** [comment]
Same problem with tailscale, Go issue closed by Go team.

**Comment by andig** [comment]
Now it doesn't compile for me, this time due to https://github.com/google/gvisor/issues/8237.
