### ISSUE TITLE
statx syscall is not supported before Linux 4.11

### ISSUE THREAD

**Issue by terenceli** [google/gvisor#8229]
### Description

When the guest application open a file as append. And later write to this file, the sentry will go the function 'refreshSizeLocked' in some case. This function calls 'startx' which introduced in Linux 4.11. Before 4.11 the 'unix.Startx' will return -ENOSYS.

https://github.com/google/gvisor/blob/master/pkg/sentry/fsimpl/gofer/gofer.go#L1337

Any options for this in lower kernel version?

**Comment by avagin** [comment]
> Any options for this in lower kernel version?

The fstat syscall can be used in this case.

**Comment by ayushr2** [comment]
https://gvisor.dev/docs/user_guide/install/ says that "gVisor supports only x86_64 and requires Linux 4.14.77+". But I think that is because of GSO support, as documented [here](https://gvisor.dev/docs/user_guide/networking/#gso).

Should be reasonable to fix this as suggested by @avagin.

**Comment by avagin** [comment]
I don't think that we need to fix anything here. All kernels older 4.14 reached EOL: https://www.kernel.org/category/releases.html.
