### ISSUE TITLE
runsc can't run python interactively

### ISSUE THREAD

**Issue by terenceli** [google/gvisor#8232]
### Description

runsc can run sh interactively, but can't can python interactively.

The 'args' is 'sh':
root@test-VirtualBox:/home/test/runsc# ./runsc run test1
sh: turning off NDELAY mode
echo $$
1
sh
echo $$
2
sh   
echo $$ 
3
exit
exit
exit

When 'args' is 'python3':
root@test-VirtualBox:/home/test/runsc# ./runsc run test1
a = "abc"
print(a)
exit() //Then ctrl-D
abc 

It seems that python buffered the output, also input?
but when I change 'args' from ['python3'] to ['python3', '-u'], it still doesn't work. 

### Steps to reproduce

1. get runsc by
wget https://storage.googleapis.com/gvisor/releases/release/latest/x86_64/runsc

2. use following config.json

{
    "ociVersion": "1.0.0",
    "process": {
        "user": {
            "uid": 0,
            "gid": 0
        },
        "args": [
            "python3"
        ],
        "env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "TERM=xterm"
        ],
        "cwd": "/",
        "capabilities": {
            "bounding": [
                "CAP_AUDIT_WRITE",
                "CAP_KILL",
                "CAP_NET_BIND_SERVICE"
            ],
            "effective": [
                "CAP_AUDIT_WRITE",
                "CAP_KILL",
                "CAP_NET_BIND_SERVICE"
            ],
            "inheritable": [
                "CAP_AUDIT_WRITE",
                "CAP_KILL",
                "CAP_NET_BIND_SERVICE"
            ],
            "permitted": [
                "CAP_AUDIT_WRITE",
                "CAP_KILL",
                "CAP_NET_BIND_SERVICE"
            ]
        },
        "rlimits": [
            {
                "type": "RLIMIT_NOFILE",
                "hard": 1024,
                "soft": 1024
            }
        ]
    },
    "root": {
        "path": "/",
        "readonly": true
    },
    "hostname": "runsc",
    "mounts": [
        {
            "destination": "/proc",
            "type": "proc",
            "source": "proc"
        },
        {
            "destination": "/dev",
            "type": "tmpfs",
            "source": "tmpfs"
        },
        {
            "destination": "/sys",
            "type": "sysfs",
            "source": "sysfs",
            "options": [
                "nosuid",
                "noexec",
                "nodev",
                "ro"
            ]
        }
    ],
    "linux": {
        "namespaces": [
            {
                "type": "pid"
            },
            {
                "type": "network"
            },
            {
                "type": "ipc"
            },
            {
                "type": "uts"
            },
            {
                "type": "mount"
            }
        ]
    }
}

3. ./runsc run test

**Comment by avagin** [comment]
If you want to run python interactively, you need to run it with a terminal:

```
...
  "process": {
    "terminal": true,
    "user": {
      "uid": 0,
      "gid": 0
    },
    "args": [
      "python3"
    ],
...
```
