### ISSUE TITLE
gVisor should ignore unset seccompProfile or when it's set to RuntimeDefault

### ISSUE THREAD

**Issue by dprotaso** [google/gvisor#8248]
### Description

Knative started setting seccompProfile.type=RuntimeDefault for it's Pods as per the guidance of [K8s documentation](https://kubernetes.io/docs/tutorials/security/seccomp/). Generally it's also good security practice because the default (empty string) currently means `Unconfined`.

A user reported that this prevents our Pods to start on gVisor nodes - https://github.com/knative/serving/issues/13471

With the error `Seccomp is not supported`

It would be great if gVisor error out if the seccomp profile type is set to the `RuntimeDefault` constant

**Comment by kevinGC** [comment]
I believe this is a GKE bug rather than a gVisor one. Filing a bug with GKE is probably the best way to get it fixed.

That said, IIUC `RuntimeDefault` seems compatible with gVisor if allowed.

**Comment by dprotaso** [comment]
Where do I file GKE bugs?

**Comment by kevinGC** [comment]
Looks like you can search for an existing bug or create a new one under the Kubernetes Engine category [here](https://cloud.google.com/support/docs/issue-trackers#trackers-list).

**Comment by dprotaso** [comment]
Done - https://issuetracker.google.com/issues/260968397

Any chance you can advocate for this change internally?

**Comment by kevinGC** [comment]
Thanks. And I can make sure it gets seen.

**Comment by kevinGC** [comment]
Per the [GKE bug](https://issuetracker.google.com/issues/260968397) this is fixed starting in 1.26.

Please reopen if you run into this again,

**Comment by dprotaso** [comment]
thanks for the help!
