### ISSUE TITLE
Container Sandbox: Unsupported syscall UNKNOWN[435/0x1b3] in Google Cloud Functions

### ISSUE THREAD

**Issue by loicmathieu** [google/gvisor#8287]
### Description

Hello,

In Java 17 Google Cloud Functions 2nd gen with a Quarkus application I saw a lot of logs `Container Sandbox: Unsupported syscall UNKNOWN[435/0x1b3]`.

I check with the Quarkus team and the Netty team (Quarkus uses Netty) and they didn't think it comes from Quarkus or Netty.
Reading this doc https://gvisor.dev/docs/user_guide/compatibility/linux/amd64/#clone3 it seems it's the syscall clone3 that causes this issue.

**Comment by akoscz** [comment]
I'm seeing this same log message with a Python 3.10 Google Cloud Function 2nd Gen deployment.
```
"Container Sandbox: Unsupported syscall UNKNOWN[435/0x1b3](0x3e332a7fb1c0,0x58,0x3e3331294850,0x8,0x3e330fe00640,0x3e332a7fb2df). It is very likely that you can safely ignore this message and that this is not the cause of any error you might be troubleshooting. Please, refer to https://gvisor.dev/docs/user_guide/compatibility/linux/amd64/#UNKNOWN[435/0x1b3] for more information."
```

In addition, there I have a hand full of log messages about `rseq` as well.
```
"Container Sandbox: Unsupported syscall rseq(0x3e33315e30e0,0x20,0x0,0x53053053,0x0,0x0). It is very likely that you can safely ignore this message and that this is not the cause of any error you might be troubleshooting. Please, refer to https://gvisor.dev/docs/user_guide/compatibility/linux/amd64/#rseq for more information."
```

My Python 3.10 cloud function depends on the following libraries:
```
functions-framework==3.3.0
google-cloud-firestore==2.9.0
google-cloud-storage==2.7.0
pandas==1.5.2
numpy==1.24.1
pytz==2022.7.1
```

**Comment by josesuero** [comment]
@loicmathieu I'm seeing the same issue on the exact same framework (Quarkus/java17/gen2), one question, does your function work? I get same errors but function doesn't seem to trigger

**Comment by dimonb** [comment]
Have the same issue in python3.10 and it's annoying. A lot of useless log messages which trashing log output

**Comment by kevinGC** [comment]
Syscall 435 is `clone3()`, which seems like a simple API change around `clone()` with a few new features. If Java and Python aren't using the new features, this is probably a small change. If they are, it'll be a bit larger.

As with other Cloud bugs, reporting the issue via Cloud is probably going to be most effective. It just means more eyeballs and a greater likelihood of moving up the priority list.

**Comment by vgattuso** [comment]
I'm getting the same issue with runtime Go 1.19

**Comment by Satendra-SR** [comment]
I'm also getting the same issue with
1.  Cloud function 2nd gen 
2. Python 3.10

<img width="613" alt="image" src="https://user-images.githubusercontent.com/39792899/221431829-ebb8afa4-580f-4608-b55f-e7ba048aff42.png">

**Comment by nlacasse** [comment]
These logs are probably not impacting your application (please let us know if the app is actually broken), but they certainly can be annoying.  I am looking into getting rid of the logs in Cloud Run, since they are not very useful.

We are also planing to implement `clone3()` soon, the work is tracked in #8585.

**Comment by thaniyarasu** [comment]
getting the same issue at go120 runtime
  
"textPayload": "Container Sandbox: Unsupported syscall rseq(0x3ec6220310e0,0x20,0x0,0x53053053,0x0,0x0). It is very likely that you can safely ignore this message and that this is not the cause of any error you might be troubleshooting. Please, refer to https://gvisor.dev/docs/user_guide/compatibility/linux/amd64/#rseq for more information.",


But the application is working fine...
