### ISSUE TITLE
Is there a plan to improve performance?

### ISSUE THREAD

**Issue by lubinsz** [google/gvisor#83]
Currently, we tested the performance in x86 platform , and the performance seems not so good.
So, is there any plan to improve performance for kvm mode or ptrace mode?
What do we need to do for this support? Maybe I can help to work on it.
Our test report:
 scenario:  network performance between two gvisors connected via virtual switch.
         Docker: 24.3 Gbps
         Gvisor/ptrace: 624 Mbps
         Gvisor/kvm: 331 Mbps

**Comment by amscanne** [comment]
Hi -- I'm not clear on the exact test setup. 25 Gbps seems like it might be loopback performance, where most of the network stack is actually avoided (just becomes a test of how fast can bits be copied). In the default sandbox configuration, you will have a network stack inside the sandbox boundary that generates packets, meaning extra copies and two full network stacks at work. Assuming this is iperf, there are two easy ways to have apples-to-apples benchmarks:

- Run one of the client or server on a separate machine.
- Run the sandbox with --network=host (described on the README, will also result in loopback).

That said, the in-sandbox network stack could definitely use work on the performance side. But is it the goal to maximize inter-sandbox throughput on a single host? I think that most work is related to improving higher-latency throughput, and nothing will beat the "host" network mode in the loopback case (it's a rather fundamental trade-off).
