### ISSUE TITLE
Support /proc/sys/net/ipv4/conf/lo/forwarding

### ISSUE THREAD

**Issue by iangudger** [google/gvisor#8414]
### Description

It looks like the .NET standard library depends on `/proc/sys/net/ipv4/conf/lo/forwarding`. I checked the gVisor source and it looks like the issue isn't an out of date sentry and gVisor still doesn't support this file.

https://github.com/dotnet/orleans/issues/8271

**Comment by ElanHasson** [comment]
Hi @iangudger, curious how you found this :)

**Comment by bradygaster** [comment]
@ElanHasson is this what you're considering an equivalent to what you planned on filing over here or have you plans to file an additional issue on this one?

**Comment by ElanHasson** [comment]
👋 @bradygaster,

I logged [an issue in dotnet/runtime](https://github.com/dotnet/runtime/issues/81061) for it in `dotnet/runtime`. I believe this change in behavior between .NET 7 vs .NET 6 on Linux to be a regression as the gVisor version on my end has remained the same.

gVisor doesn't support everything (yet 😊), and .NET  should handle this issue gracefully, like it did before IMO (i.e returning `false`). That said, I would love to see more support within gVisor  for many things.

Thanks @iangudger for logging this issue!

**Comment by bradygaster** [comment]
@ElanHasson - does that other issue resolve this one?

**Comment by ElanHasson** [comment]
@bradygaster yes it does. It's been accepted to 7.0.4 and merged into the release branch.
