### ISSUE TITLE
StdIn Exception with PTY running Java

### ISSUE THREAD

**Issue by mpass99** [google/gvisor#8544]
### Description

Containerized Java programs that try to read from the `StdIn` throw the `java.util.NoSuchElementException` when providing input via an interactive session in a pseudo-TTY when using `runsc` (not with `runc`).

### Steps to reproduce

1. Create the [Dockerfile](https://github.com/google/gvisor/files/10771835/Dockerfile.txt)

    ``` Dockerfile
    FROM openjdk:latest
    
    LABEL description='gVisor Input Exception'
    WORKDIR /tmp
    
    RUN echo -e 'import java.util.Scanner;\n\
    \n\
    public class HelloWorld {\n\
        public static void main(String[] args) {\n\
            System.out.println("Output on stdout");\n\
            System.err.println("Output on stderr");\n\
    \n\
            System.out.print("Your Input: ");\n\
            Scanner scanner = new Scanner(System.in);\n\
            String line = scanner.nextLine();\n\
            System.out.println("Received: " + line);\n\
        }\n\
    }\n' > HelloWorld.java
    
    RUN javac HelloWorld.java
    
    CMD java HelloWorld
    ```

2. Build and run the Dockerfile: 
    ``` sh
    docker run --rm --runtime=runsc -it $(docker build -q .)
    ```

3. Provide and submit input

    The following exception occurs:
    ```
    Exception in thread "main" java.util.NoSuchElementException: No line found
    	at java.base/java.util.Scanner.nextLine(Scanner.java:1656)
    	at HelloWorld.main(HelloWorld.java:10)
    ```

Repeating the same example with `runc` works as expected. Also, testing the same scenario with Python (instead of Java) works as expected.

### runsc version

```shell
runsc version release-20230130.0
spec: 1.0.2-dev
```

### docker version (if using docker)

```shell
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:47:01 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:47:01 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### uname

Linux mp 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### runsc debug logs (if available)

[`runsc.log.*.gofer.txt`:](https://github.com/google/gvisor/files/10772047/runsc.log.20230217-211828.277437.gofer.txt)
``` log
D0217 21:18:33.372411       1 connection.go:127] sock read failed, closing connection: EOF
```

[`runsc.log.*.boot.txt`:](https://github.com/google/gvisor/files/10772052/runsc.log.20230217-211828.278541.boot.txt)
``` log
I0217 21:18:33.357451   91846 strace.go:567] [   1:   2] java E write(0x2 host:[1], 0x7ffb6b218140 "java.util.NoSuchElementException: No line found\n", 0x30)
```
- [runsc.log.*.create.txt](https://github.com/google/gvisor/files/10772056/runsc.log.20230217-211828.220888.create.txt)
- [runsc.log.*.start.txt](https://github.com/google/gvisor/files/10772057/runsc.log.20230217-211828.548907.start.txt)
- [runsc.log.*.delete.txt](https://github.com/google/gvisor/files/10772059/runsc.log.20230217-211833.428571.delete.txt)
- [runsc.log.*.delete.txt](https://github.com/google/gvisor/files/10772060/runsc.log.20230217-211833.508054.delete.txt)

**Comment by kevinGC** [comment]
Looking at the `.boot.txt` file, my guess is that the underlying error is this:

```
java X ioctl(0x0 host:[1], 0x541b, 0x7ffb6b21a30c) = 0 (0x0) errno=25 (not a typewriter) (4.33µs)
```

This is Java getting the number of input bytes via `ioctl(pty_fd, FIONREAD, &intptr)`. This usually works because stdin is a terminal, but maybe we haven't marked it correctly.

@nlacasse do you have a better sense of why this would fail?

**Comment by mpass99** [comment]
Is there any further information we can provide you with, or help you in any other way?

**Comment by fvoznika** [comment]
`FIONREAD` is implemented for regular host FDs (`host.fileDescription.Ioctl()`) but not TTY (`host.TTYFileDescription.Ioctl()`).

**Comment by mpass99** [comment]
We can confirm that [`release-20230529.0`](https://github.com/google/gvisor/releases/tag/release-20230529.0) solves our issue. Thank you!
