### ISSUE TITLE
Why didn't you succeed?

### ISSUE THREAD

**Issue by aogg** [google/gvisor#8557]
### Description

Why didn't you succeed?

root@root:/home/onyx# docker run --runtime=runsc-kvm --rm -it ubuntu sh -c "apt update"
Segmentation fault
root@root:/home/onyx# docker run --runtime=runsc-kvm --rm -it ubuntu sh -c "ps -ef"
UID        PID  PPID  C STIME TTY          TIME CMD
Signal 11 (SEGV) caught by ps (3.3.17).
root         1     0  0ps:ps/display.c:70: please report this bug
Segmentation fault

/ # docker run --runtime=runsc-kvm --rm -d ubuntu sh -c "apt update"
a3fe23fe8d37023ae2cd7555db5513163a31e5b53e78c7c9267b025de503932f
time="2023-02-18T02:54:57.237550218Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-02-18T02:54:57.237591785Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-02-18T02:54:57.237605651Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-02-18T02:54:57.237779206Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/a3fe23fe8d37023ae2cd7555db5513163a31e5b53e78c7c9267b025de503932f pid=1512 runtime=io.containerd.runc.v2
/ # INFO[2023-02-18T02:54:57.862243147Z] shim disconnected                             id=a3fe23fe8d37023ae2cd7555db5513163a31e5b53e78c7c9267b025de503932f
INFO[2023-02-18T02:54:57.862270559Z] ignoring event                                container=a3fe23fe8d37023ae2cd7555db5513163a31e5b53e78c7c9267b025de503932f module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
WARN[2023-02-18T02:54:57.862298190Z] cleaning up after shim disconnected           id=a3fe23fe8d37023ae2cd7555db5513163a31e5b53e78c7c9267b025de503932f namespace=moby
INFO[2023-02-18T02:54:57.862310233Z] cleaning up dead shim                        
WARN[2023-02-18T02:54:57.890327050Z] cleanup warnings time="2023-02-18T02:54:57Z" level=info msg="starting signal loop" namespace=moby pid=1637 runtime=io.containerd.runc.v2 

### Steps to reproduce

```
{
    "runtimes": {
        "runsc": {
            "path": "/usr/local/bin/runsc"
        },
        "runsc-ptrace": {
            "path": "/usr/local/bin/runsc",
            "runtimeArgs": [
                "--platform=ptrace"
            ]
        },
        "runsc-kvm": {
            "path": "/usr/local/bin/runsc",
            "runtimeArgs": [
                "--platform=kvm"
            ]
        }
    }
}
```

```
FROM adockero/docker:dind-sshd


RUN echo '安装' \
    && ARCH=$(uname -m) && \
    URL=https://storage.googleapis.com/gvisor/releases/release/latest/${ARCH} && \
    wget ${URL}/runsc ${URL}/runsc.sha512 \
        ${URL}/containerd-shim-runsc-v1 ${URL}/containerd-shim-runsc-v1.sha512 && \
    sha512sum -c runsc.sha512 \
        -c containerd-shim-runsc-v1.sha512 && \
    rm -f *.sha512 && \
    chmod a+rx runsc containerd-shim-runsc-v1 && \
    mv runsc containerd-shim-runsc-v1 /usr/local/bin && \
    runsc install && \
  echo '结束'
```

docker run --runtime=runsc-kvm --rm -d ubuntu sh -c "apt update"

### runsc version

```shell
/ # runsc -version
runsc version release-20230214.0
spec: 1.0.2-dev
```

### docker version (if using docker)

```shell
/ # docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.2)
  compose: Docker Compose (Docker Inc., v2.15.1)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.23
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runsc runsc-kvm runsc-ptrace io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc version: v1.1.4-0-g5fd4c4d1
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.0-139-generic
 Operating System: Alpine Linux v3.17 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 62.76GiB
 Name: 37911d66e143
 ID: CUJC:FTXC:ZQOM:VWG2:MV6W:N4JI:NREW:26K4:AVPV:AAAJ:KF46:JUGN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No swap limit support
```

### uname

/ # uname -a Linux 37911d66e143 5.4.0-139-generic #156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023 x86_64 Linux

**Comment by aogg** [comment]
lscpu |grep 'Model name'
Model name:                      AMD Ryzen 9 5950X 16-Core Processor

**Comment by aogg** [comment]
docker run --runtime=runsc-kvm --rm -it ubuntu sh -c "apt update"



        "runsc-kvm": {
            "path": "/usr/local/bin/runsc",
            "runtimeArgs": [
                "--platform=kvm",
                "--debug-log=/tmp/runsc", 
                "--debug", 
                "--strace" 
            ]
        }



/tmp/runsc


[runsc.log](https://github.com/google/gvisor/files/10774061/runsc.log)

**Comment by aogg** [comment]
root@dxw:/home/dxw# docker run --runtime=runsc-kvm --rm -it ubuntu sh -c "apt update"
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
677076032cca: Pull complete 
Digest: sha256:9a0bdde4188b896a372804be2384015e90e3f84906b750c1a53539b585fbbe7f
Status: Downloaded newer image for ubuntu:latest
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
0% [1 InRelease 146 kB/270 kB 54%]^Croot@dxw:/home/dxw# ^C      


amd run not success
but
inter run success

**Comment by avagin** [comment]
It looks like https://github.com/google/gvisor/issues/7450.

**Comment by aogg** [comment]
must

```

lscpu |grep 'Model name'
Model name: AMD Ryzen 9 5950X 16-Core Processor
```

> It looks like #7450.

**Comment by avagin** [comment]
@aogg could you give ssh access to this hardware?
