### ISSUE TITLE
Fail to set hostname

### ISSUE THREAD

**Issue by tanjianfeng** [google/gvisor#861]
The imlementation of sethostname() syscall is broken:

     $ strace hostname abc
      ...
      sethostname("abc", 3) = -1 ENAMETOOLONG (File name too long)
      ...

**Comment by ianlewis** [comment]
I'll look into this.

**Comment by tanjianfeng** [comment]
> I'll look into this.

In case you are not aware of this, a fix has been sent out for review: https://github.com/google/gvisor/pull/864.
