### ISSUE TITLE
Hard links in user namespace cause gVisor to ENOENT

### ISSUE THREAD

**Issue by ekzhang** [google/gvisor#8688]
### Description

Trying to create a hard link with the `ln` command fails with ENOENT, when gVisor is run in a user namespace. Minimal reproduction is given below.

(Hard links are used by commands like `apt-get install libc6`, so these commands also fail as a result.)

### Steps to reproduce

Create a running gVisor container following the instructions in the runc README.

```bash
# create the top most bundle directory
mkdir mycontainer
cd mycontainer

# create the rootfs directory
mkdir rootfs

# export busybox via Docker into the rootfs directory
docker export $(docker create busybox) | tar -C rootfs -xvf -
```

Create a spec, equivalent to the default `runc spec`, but give it three changes:

- Change the file system to be `"readonly": false`
- Add `uidMappings` and `gidMappings` set to `0:0:1` each.
- Add a namespace of `{ "type": "user" }`.

[Here](https://gist.github.com/ekzhang/c2663c4e8455e8ec9cd472e7a1fbbe4f) is the final spec.

```bash
wget https://gist.githubusercontent.com/ekzhang/c2663c4e8455e8ec9cd472e7a1fbbe4f/raw/39b53a87179e76a6fe1d904d793039b2941d60f6/config.json

sudo runsc run mycontainerid
```

Then, inside the container try to create a hard link.

```sh-session
/ # touch foo
/ # ln foo bar
ln: bar: No such file or directory
```

This command works fine on vanilla `runc`, and it also works in gVisor if `runsc` is run with no user namespace. But with the user namespace, it doesn't work in gVisor.

### runsc version

```shell
runsc version release-20230306.0
spec: 1.1.0-rc.1
```

### uname

Linux ip-172-31-21-208 5.13.0-1031-aws #35~20.04.1-Ubuntu SMP Mon Jun 13 22:30:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ekzhang** [comment]
I saw #6739 and can reproduce it, but I created a new issue because this one actually responds with an `ENOENT` rather than just not updating metadata correctly.

**Comment by ekzhang** [comment]
> Create a spec, equivalent to the default `runc spec`, but give it three changes:
> 
> * Change the file system to be `"readonly": false`
> * Add `uidMappings` and `gidMappings` set to `0:0:1` each.
> * Add a namespace of `{ "type": "user" }`.

An alternate way to reproduce the issue only changing one part of the spec, and not the other two steps, is to run the container with `runsc -directfs run mycontainerid`, which seems to cause gVisor to automatically add a user namespace with UID and GID mappings.

https://github.com/google/gvisor/blob/610109e9536f28a488dc9b267c7057018a85b764/runsc/container/container.go#L1579-L1624

**Comment by ayushr2** [comment]
Thanks for the detailed report. Seems like the linkat(2) syscall being made [here](https://cs.opensource.google/gvisor/gvisor/+/master:runsc/fsgofer/lisafs.go;l=673) is failing with ENOENT.

Given the presence of a new user namespace triggers this failure, I assume this is because the gofer process does not have `CAP_DAC_READ_SEARCH`. Quoting link(2) man page:

> ENOENT   AT_EMPTY_PATH was specified in flags, but the caller did not have the CAP_DAC_READ_SEARCH capability.

However, we do explicitly allow the gofer process to retain this capability: https://cs.opensource.google/gvisor/gvisor/+/master:runsc/cmd/gofer.go;l=45...

**Comment by ayushr2** [comment]
The gofer has `CAP_DAC_READ_SEARCH` in the new userns, but not in the root userns. It seems that the kernel is checking for `CAP_DAC_READ_SEARCH` in the root userns: https://elixir.bootlin.com/linux/latest/source/fs/namei.c#L4572. Linux uses `capable(CAP_DAC_READ_SEARCH)`, instead of `ns_capable()` which can check in a particular userns.

**Comment by ekzhang** [comment]
Thanks @ayushr2 for the response. If it helps to provide more details, I've been looking at this bug since it's actually causing `sudo make test TARGETS=runsc/fsgofer:lisafs_test` to fail.

There is a test in lisafs_test that tests if hard links are supported.

https://github.com/google/gvisor/blob/6f769780487e7993a894ca965e92c2dee8678f8b/pkg/lisafs/testsuite/testsuite.go#L480-L505

It creates a file at `$DIR/testFile` and then calls the equivalent of `linkat(fd, "", DIR_INO, "testFile")`. (I think the test should probably use a different string for the name of the link also.) This test is usually skipped unless you have the `CAP_DAC_READ_SEARCH` capability, but if I run the test with `sudo`, it's not skipped anymore and fails with `ENOENT`.

As you mentioned I added some log lines and the failure is right here. Can confirm that the gofer has `CAP_DAC_READ_SEARCH` capabilities at this point using the `github.com/syndtr/gocapability/capability` package.

https://github.com/google/gvisor/blob/6f769780487e7993a894ca965e92c2dee8678f8b/runsc/fsgofer/lisafs.go#L671-L675

**Comment by ayushr2** [comment]
Thanks for reporting this Eric, there was a test bug (like you mentioned) and a ref count bug. Sending a fix for both. But the original issue still stands. I think we will have to avoid `AT_EMPTY_PATH` usage for `linkat(2)`... Let me see how we can do that.

**Comment by ayushr2** [comment]
#8714 should fix this.
