### ISSUE TITLE
gvisor not showing up as a runtime

### ISSUE THREAD

**Issue by Kuvesz** [google/gvisor#87]
Hello!

I'm trying to run gvisor under docker, on it's own it works fine, but docker doesn't even notice it's there.
So I'm running the following:
`docker run --runtime=runsc hello-world`
And the result is:
```
docker: Error response from daemon: Unknown runtime specified runsc.
See 'docker run --help'.
```
My Docker version is the latest, so: 18.03.1-ce
I'm running Ubuntu 16.04
I have added the lines needed to /etc/docker/daemon.json
I have done `systemctl restart docker` and `systemctl daemon-reload`

My `docker info` output is:
```
Containers: 120
 Running: 11
 Paused: 0
 Stopped: 109
Images: 100
Server Version: 18.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-36-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 23
Total Memory: 62.93GiB
Name: bigdata3
ID: XGF3:KEBI:PDTK:BDSR:EAFO:LE7T:S66O:HZZA:A6UZ:OICE:GMQV:QWRJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 172.31.32.91:5000
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
Any help appreciated.

**Comment by nlacasse** [comment]
This should work.  Maybe there is a syntax error in your daemon.json?

**Comment by ydjainopensource** [comment]
Did you forget restarting the docker daemon after installation?

**Comment by Kuvesz** [comment]
Nope and nope, my daemon.json worked just fine up to this point, I even added Kata Runtime in there, than tried this, didn't work, so I deleted Kata Runtime, still does 't work. Oh and yes, I did restart the docker daemon.

**Comment by Kuvesz** [comment]
UPDATE: I tried it on a 18.04 VM I have and it worked just fine. I'm gonna look into Kata, maybe I didn't remove it properly enough.

**Comment by Kuvesz** [comment]
I did it. I had to get rid of Kata Containers yes, but not only that, I had to have the runtimes parts starting my daemon.json, which I didn't, because I had some DNS settings and it didn't work that way. Now I'll have to figure out a way to have runc, runsc and kata usable at the same time somehow.
