### ISSUE TITLE
Build instructions from README.md does not work [master]

### ISSUE THREAD

**Issue by sitano** [google/gvisor#8704]
### Description

Trying to build `master` with instructions from README.md. It seems like they are outdated as `make copy` does not work.

What is the correct way to build `master` branch with `bazel` without cross-compilation (disable aarch64, do only x86_64)?

Specifically for:

```shell
mkdir -p bin
make copy TARGETS=runsc DESTINATION=bin/
``` 

I am getting

```shell
--- COPY runsc bin/
Error response from daemon: No such container: gvisor-bazel-1be52947-x86_64
make: *** [Makefile:67: copy] Error 1
```

Where should I take this `gvisor-bazel-1be52947-x86_64`?

What is the correct way to build it without docker?

### Steps to reproduce

```shell
git@github.com:google/gvisor.git
mkdir -p bin
make copy TARGETS=runsc DESTINATION=bin/
```

and get

```shell
--- COPY runsc bin/
Error response from daemon: No such container: gvisor-bazel-1be52947-x86_64
make: *** [Makefile:67: copy] Error 1
```

### runsc version

```shell
git rev-parse HEAD
9abcf28e601480db39ef99483c747ca6277e2d42
```

**Comment by sitano** [comment]
Also, the `go get` instructions look outdated with the GOMODULE stuff. Considering the `master` branch does not support the native go toolchain its worth rewriting the README.md into something meaningful and actionable like in example:

```
git co go
go build -v -o ./bin/runsc ./runsc/cli/...
```

**Comment by fvoznika** [comment]
The instruction listed in the readme file requires docker to be installed (see requirements section). It uses `make` to build and install images locally to be used during build. If you don't want to install `docker` and prefer to use `bazel`, you can use it directly in the repository. Here a few examples:

```
# Build runsc
bazel build -c opt runsc

# Run all unit tests under pkg/sentry
bazel test pkg/sentry/...

# Run read syscall test using ptrace platform:
bazel test test/syscalls:read_test_runsc_ptrace

# Find all syscalls tests:
bazel query test/syscalls:all
```

**Comment by sitano** [comment]
@fvoznika thanks for the `bazel` instructions. How can I pick only one toolchain (x86_64) and disable aarch64? Also bazel build system expects me to have `x86_64-linux-gnu-objcopy` and `x86_64-linux-gnu-ld` that are not provided by normal packages in the Arch Linux because native versions are x86_64 already.

I do have `docker` installed and it 100% works as I am heavily using it. But the `make copy TARGETS=runsc DESTINATION=bin/` does not work because it tries to use the image that does not exist.

Specifically:

```
$ make -n copy TARGETS=runsc DESTINATION=bin/
echo --- COPY runsc bin/ >&2 && (set -euo pipefail; docker exec --user 1000:1001 --interactive --privileged gvisor-bazel-1be52947-x86_64 bazel  build --color=no --curses=no  runsc && docker exec --user 1000:1001 --interactive --privileged gvisor-bazel-1be52947-x86_64 bazel  cquery --color=no --curses=no  runsc --output=starlark --starlark:file=tools/show_paths.bzl | xargs -r -I {} bash -c 'test -e "{}" || exit 0; realpath -m "{}"' | xargs -r -I {} bash -c 'set -euo pipefail; cp -fa {} bin/')

$ make copy TARGETS=runsc DESTINATION=bin/
--- COPY runsc bin/
Error response from daemon: No such container: gvisor-bazel-1be52947-x86_64
make: *** [Makefile:67: copy] Error 1
```

Why it does expect me to have `gvisor-bazel-1be52947-x86_64`? There is either a bug somewhere or I need to run a command which will create this image somehow that is missing in the README.md.

It can be seen that this image comes from `tool/bazel.mk` and

```
DOCKER_BUILD := true
ifeq ($(DOCKER_BUILD),true)
-include bazel-server
endif

BRANCH_NAME := $(shell (git branch --show-current 2>/dev/null || \
  git rev-parse --abbrev-ref HEAD 2>/dev/null) | \
  xargs -n 1 basename 2>/dev/null)

BUILDER_NAME := gvisor-builder-$(HASH)-$(ARCH)
DOCKER_NAME := gvisor-bazel-$(HASH)-$(ARCH)
``` 

and there is even a target called `bazel-image` that does something like related but how would I know how to call it. Plus I suppose the script must serve itself with everything required.

**Comment by sitano** [comment]
It seems like the missing instruction is:

```
$ make bazel-server
```

**Comment by sitano** [comment]
closing in favor of https://github.com/google/gvisor/pull/8991
