### ISSUE TITLE
netstack: during shutdown endpoints have Attach(nil) called to disconnect the dispatcher, further injections result in nil pointer errors

### ISSUE THREAD

**Issue by raggi** [google/gvisor#8765]
### Description

As seen in Tailscale CI: https://github.com/tailscale/tailscale/actions/runs/4548299564/jobs/8019187385#step:7:843

A somewhat related change in https://github.com/google/gvisor/commit/13d7bf69d8068a0b1939e94bdb9ff08b1cdad913 added more locking around those fields, which makes it safer to guard against this condition along the lines of:

```go
if ep.IsAttached() {
  ep.InjectInbound(...)
}
```

This workaround does not eradicate the bug, as it results in two consecutive acquisitions of the rwlock around dispatcher. InjectInbound could potentially instead guard against a nil dispatcher much more cheaply.

Would such a patch be acceptable, or should we be holding endpoint differently?

### Steps to reproduce

`go test tailscale.com/tsnet -count 100`

### runsc version

```shell
google/gvisor@13d7bf6
tailscale.com/tsnet@cb960d6
```

**Comment by kevinGC** [comment]
I think it'd be good to, as you suggest, guard against nil dispatchers. There're only a couple of `InjectInbound()` implementations, so it'll be a small patch.
