### ISSUE TITLE
How to get the app's stderr output in runsc

### ISSUE THREAD

**Issue by terenceli** [google/gvisor#8873]
### Description

I want to capture the stderr of the app running in runsc.
For example when not running in runsc:
#sh -c 'curl baidu.com -L -o index'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    81  100    81    0     0   1004      0 --:--:-- --:--:-- --:--:--  1025

The '% Total    % Received % Xferd xxx' line is written to stderr and we get it.

But in runsc, we can't capture the stderr. 
#sh -c './runsc --network host run test'
curl: (6) Could not resolve host: antgroup.com; Name or service not known

I want to know how to capture the stderr of app. In this example, it's '%Total xxx' line.

### Steps to reproduce

1. Get the latest runsc.

2. runsc spec to generate config.json

Change the 'args' to 

        "args": [
            "curl",
                        "antgroup.com",
                        "-L",
                        "-o",
                        "index"
        ],
Change the 'rootfs' to '/'

3. Run
sh -c './runsc --network host run test'

**Comment by ayushr2** [comment]
Interesting, I can run this fine with docker:
```
$ docker run --runtime=runsc --rm -it alpine/curl curl antgroup.com -L -o index

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    81  100    81    0     0     51      0  0:00:01  0:00:01 --:--:--    90
100 10535    0 10535    0     0   4337      0 --:--:--  0:00:02 --:--:-- 13916
```

But using your reproducer fails with:
```
$ sudo sh -c './runsc --network host run test'
curl: (6) Could not resolve host: antgroup.com
```
So probably some configuration issue...

**Comment by ayushr2** [comment]
```
$ sudo sh -c './runsc --network host do curl antgroup.com -L -o index'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   284  100   284    0     0    288      0 --:--:-- --:--:-- --:--:--     0
100    81  100    81    0     0     21      0  0:00:03  0:00:03 --:--:--    44
100 10535    0 10535    0     0   2108      0 --:--:--  0:00:04 --:--:--  9790
```

**Comment by ayushr2** [comment]
I think I see why `runsc do` works. It "setups up the sandbox network, including the creation of a network namespace, and iptable rules to redirect the traffic" as done [here](https://cs.opensource.google/gvisor/gvisor/+/master:runsc/cmd/do.go;l=251;drc=7981df85f3e178e1b672670f92da7499b57a9a38). It creates an appropriate `/etc/hosts` file and mounts it into the container.

@kevinGC what is the recommendation for configuring the container network properly when using `runsc run` directly?

**Comment by ayushr2** [comment]
As pointed out by @avagin (internally), you need to add a nameserver in `/etc/resolv.conf`.

`runsc do` [does this step](https://cs.opensource.google/gvisor/gvisor/+/master:runsc/cmd/do.go;l=294;drc=7981df85f3e178e1b672670f92da7499b57a9a38), and thats why it works.
