### ISSUE TITLE
Eager copy-on-write with python multiprocessing 

### ISSUE THREAD

**Issue by benhurdelhey** [google/gvisor#8879]
### Description

When I use multiprocessing in python and fork a process, the memory usage of my gvisor sandbox increases drastically. I suspect that the ref counting in python touches all python dependencies I loaded and triggers COW for basically all pages / memory areas.

I found the discussion in this issue https://github.com/google/gvisor/pull/608. If I understand correctly, the COWUnitSize is currently at 2MB. Furthermore, CPython is working on changes to disable the refcounting (https://peps.python.org/pep-0683/), but it will probably take a while until I can use this.

Does that make sense? Do you know any other workarounds I could use to share the memory pages between the processes and defer the COW? 
For example, could there be a way for me to override the COWUnitSize?

### Steps to reproduce

install gvisor with docker and exec run.sh in https://github.com/benhurdelhey/python-COW-gvisor

This runs a docker container with the runsc runtime and spawns a child process. Before the fork, `docker stats python-cow-example` shows 130MB memory usage, after the fork it's at 200MB.

When I run the exact same code in docker without the runsc runtime, the memory stays at 130MB after the fork.

### runsc version

```shell
runsc version release-20230417.0
spec: 1.1.0-rc.1
```

### docker version (if using docker)

```shell
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:02 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:51 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### uname

Linux ip-10-110-17-66 5.4.0-1045-aws #47~18.04.1-Ubuntu SMP Tue Apr 13 15:58:14 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by stevenewald** [comment]
I don't believe the COWUnitSize is designed to be overridable, so there may not be a good workaround through configuration of gVisor.

The proposal in #608 to make the COWUnitSize modifiable would likely reduce the amount of memory being copied as a result of this issue, but this could have potential ramifications for gVisor's performance and security model and would require thorough testing.

The PR was closed but the proposal at the end never got a response, maybe someone from the gVisor team could take a look?
