### ISSUE TITLE
bazel build error: unrecognized import path: "golang.org/x/sys"

### ISSUE THREAD

**Issue by YellyYU** [google/gvisor#89]
Hi guys:
 
I a new-learner of gVisor and was following the README instructions to look into gVisor these days.

Everything goes well when I download the latest nightly build, move it to /usr/local/bin, configuring docker in /etc/docker/daemon.json, and run the command $ docker run --runtime=runsc ...

And the runsc command such as $ runsc run ... also seems normal.

However, when I sought to compile runsc from source, I got error "unrecognized import path: "golang.org/x/sys"" at $ bazel build runsc.

I googled for possible solutions but none of them can get me out of this.

I am sure I got the contents from sources like https://github.com/golang/sys.git under my $GOPATH/src/golang.org/x/ directory, but the error just won't go.

I hope anyone here could help me. Many thanks.

**Comment by prattmic** [comment]
Hm, it should "just work". Could you include the entire output from bazel build?

**Comment by YellyYU** [comment]
@prattmic first thank you for your prompt reply!

Specifically I run $ bazel build runsc in gvisor directory, the outputs are as follows:

WARNING: ignoring http_proxy in environment.
Starting local Bazel server and connecting to it...
.........
ERROR:  /home/yelly/gvisor/runsc/cmd/BUILD:5:1: no such package '@org_golang_x_sys//unix': failed to fetch org_golang_x_sys: 2018/07/24 19:07:06 unrecognized import path "golang.org/x/sys"
 and referenced by '//runsc/cmd:cmd' 
ERROR: Analysis of target '//runsc:runsc' failed; build aborted: no such package '@org_golang_x_sys//unix': failed to fetch org_golang_x_sys: 2018/07/24 19:07:06 unrecognized import path "golang.org/x/sys"
INFO: Elapsed time: 62.445s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (180 packages loaded)

And here are some information that might be useful:
`$ docker version`
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine: 
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false               

`$ uname -a`
Linux yelly-ipads 4.15.0-24-generic #26~16.04.1-Ubuntu SMP Fri Jun 15 14:35:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux 

Many thanks if you could help me with this prob

**Comment by newmanwang** [comment]
Got the same error by following "Installing from Source" in project README.md

**Comment by newmanwang** [comment]
The problem is gone by setting HTTP_PROXY and HTTPS_PROXY environment before run bazel build.

**Comment by wuqixuan** [comment]
@newmanwang   Would you tell me how and what did you set for HTTP_PROXY and HTTPS_PROXY ?

**Comment by newmanwang** [comment]
Make HTTP_PROXY and HTTPS_PROXY point to a proxy that beat the greate firewall wall, e.g HTTPS_PROXY=192.168.16.1:1080

**Comment by newmanwang** [comment]
@prattmic Try HTTPS_PROXY/HTTP_PROXY instead of https_proxy/http_proxy

**Comment by YellyYU** [comment]
This problem is gone after I pulled the latest source code and rebuild...
