### ISSUE TITLE
error: undefined reference to '__stack_chk_fail' at build

### ISSUE THREAD

**Issue by vkobel** [google/gvisor#9]
When performing `bazel build runsc` under Arch the following error occurs: `error: undefined reference to '__stack_chk_fail'`. 

One can fix this issue by adding `"-fno-stack-protector " +` in the cmd args in `vdso/BUILD` file (between -shared and -nostdlib).

EDIT: disabled stack protector instead of enabling it.

**Comment by amscanne** [comment]
Thanks for the report!

What is the build environment? Since this doesn't happen for us, I'd like to make sure that it can be reproduced to fix it.

**Comment by vkobel** [comment]
https://github.com/vkobel/gvisor/commit/84975669a6a4cbb92a8f4abf2430b70c61b10817

**Comment by vkobel** [comment]
I'm using kernel `x86_64 Linux 4.14.36-1-MANJARO` and bazel 0.12.0

**Comment by dhaavi** [comment]
I am experiencing the same error:

```
/tmp/ccCPNQ0H.o:vdso.cc:function __vdso_gettimeofday: error: undefined reference to '__stack_chk_fail'
/tmp/ccCPNQ0H.o:vdso.cc:function __vdso_time: error: undefined reference to '__stack_chk_fail'
```
System:
Linux 4.16.3-1-ARCH (Antergos)

Bazel:
```
Build label: 0.12.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Aug 13 03:13:23 +50251 (1523620552403)
Build timestamp: 1523620552403
Build timestamp as int: 1523620552403
```

I can supply additional information if needed.

I can also confirm that the patch by @vkobel solves the issue.

**Comment by vkobel** [comment]
I made an AUR package for those interested: https://aur.archlinux.org/packages/gvisor-git/ 
Currently it's based on my forked repo, but I'll change it as soon as this google repo is fixed.

**Comment by prattmic** [comment]
@vkobel could you verify that `-fno-stack-protector` also works? This VDSO shouldn't be using stack protectors at all. (As your build error shows, there is no where to go if there is a problem).

**Comment by vkobel** [comment]
@prattmic yes, it does work with `-fno-stack-protector`. I've update my fork and the arch package.
My original attempt was with this option, but I didn't assume VDSO to require no stack protectors.
