### ISSUE TITLE
Cannot kill process by Ctrl+C in CentOS image

### ISSUE THREAD

**Issue by chenggangqcg** [google/gvisor#90]
I cannot kill a process by Ctrl+C in CentOS image.
`docker run --runtime=runsc -it centos`
`# yes`
Then Ctrl+C will kill nothing.
The version of CentOS image is：7.5.1804
The platform mode is KVM

**Comment by nlacasse** [comment]
I just tested this at HEAD and Ctrl-C seems to work.

I believe it was fixed in 4e6f0892c96c374b1abcf5c39b75ba52d98c97f8.
