### ISSUE TITLE
udp endpoint HandlePacket() does not notify when data is ready to read

### ISSUE THREAD

**Issue by apmattil** [google/gvisor#904]
Before filling an issue, please consult our FAQ:
https://gvisor.dev/docs/user_guide/faq/

Also check that the issue hasn't been reported before.

If you have a question, please email gvisor-users@googlegroups.com rather than filing a bug.

If you believe you've found a security issue, please email gvisor-security@googlegroups.com rather than filing a bug.

If this is your first time compiling or running gVisor, please make sure that your system meets the minimum requirements: https://github.com/google/gvisor#requirements

For all other issues, please attach debug logs. To get debug logs, follow the
instructions here: https://gvisor.dev/docs/user_guide/debugging/

Other useful information to include is:

*   `runsc -v`
*   `docker version` or `docker info` if more relevant
*   `uname -a` - `git describe`
*   Detailed reproduction steps

**Comment by apmattil** [comment]
at udp/endpoint.go:1075 there is comparison

`// Notify any waiters that there's data to be read now.
	
if wasEmpty {
		e.waiterQueue.Notify(waiter.EventIn)
	}
`
should wasEmpty be compared to false instead ?

**Comment by kevinGC** [comment]
`wasEmpty` is set a few lines above, and indicates whether the receive buffer was empty before this current packet was enqueued to be read. So if there's data to be read, and the receive buffer was previously empty, we do notify listeners.

I think this is working as intended -- do you have a test case or reproduction where it fails to work?

**Comment by apmattil** [comment]
oh, I miss misunderstood the meaning of the flag.
sorry for the issue ticket.
