### ISSUE TITLE
need header.ipv6 setsourceaddresswithchecksumupdate

### ISSUE THREAD

**Issue by rookisbusy** [google/gvisor#9107]
### Description

In my program, i need change the src address and send it out. After receiving the ip packet, change the dst address and write it back to the network interface.

ipv4 works with those fun:
rewrite outbound packet `header.IPv4(packet).SetSourceAddressWithChecksumUpdate`
rewrite inbound packet  `header.IPv4(packet).SetDestinationAddressWithChecksumUpdate`

**but ipv6 not work**
`header.IPv6(packet).SetSourceAddress`
`header.IPv6(packet).SetDestinationAddress`

I guess checksum is wrong after edit pakcet address ?

**so is that possible to add this ?**
` header.ipv6.SetSourceAddressWithChecksumUpdate` and ` header.ipv6.SetDestinationAddresswithchecksumupdate`

### Is this feature related to a specific bug?

no

### Do you have a specific solution in mind?

I have tried to regenerate the data packet 
```
import 	tp "tailscale.com/net/packet"

func code(){

    icmph := tp.ICMP6Header{
	    IP6Header: tp.IP6Header{
		    IPProto: ipproto.ICMPv6,
		    Src:     netip.AddrFrom16(my-edited-src-ip),
		    Dst:     netip.AddrFrom16(header.IPv6(packet).DestinationAddress().As16()),
	    },
	    Type: tp.ICMP6EchoRequest,
	    Code: tp.ICMP6NoCode,
    }
    _, payload := tp.ICMPEchoPayload(header.ICMPv6(packet).Payload())
    
    icmpPing := tp.Generate(icmph, payload)

   // icmpPing as outbound packet,can be send out
}
```

**Comment by kevinGC** [comment]
IPv6 doesn't have a checksum, so there's no need to recompute it.

My guess is that the [ICMP6 checksum](https://en.wikipedia.org/wiki/ICMPv6#Checksum) is wrong. That checksum does depend on the source and destination address, so changing one will invalidate the checksum. The ICMP4 checksum doesn't use addresses, so it didn't need to be updated.

**Comment by kevinGC** [comment]
I'm going to close this for now -- feel free to reopen if you see an issue.
