### ISSUE TITLE
Misspelling on the front page

### ISSUE THREAD

**Issue by zelalemMK** [google/gvisor#9111]
### Description

Run untrusted workloads, block container escapes, and mitigate unauthorized host access.

Maybe run trusted workloads?? or am I missing something?

**Comment by ayushr2** [comment]
No, running "untrusted" workloads is correct. :)

gVisor runs containers in a [sandbox](https://en.wikipedia.org/wiki/Sandbox_(computer_security)). Sandboxing is an effective technique for running untrusted workloads, which could potentially be malicious. gVisor will protect the host machine from such an untrusted & potentially-malicious container workload.

**Comment by zelalemMK** [comment]
ah! my i see!
