### ISSUE TITLE
systrap: parallel containers have inadequate overhead 

### ISSUE THREAD

**Issue by sitano** [google/gvisor#9119]
### Description

There is at least x2 difference in the amount of CPU spent (`utime+ktime`) that the new container spend when it is executed lonely with the case when there are more starting containers than the available CPU cores. It is not the case with the `ptrace`. Increasing the parallelism should not affect the CPU time of starting containers.

Measurement
===

1. runsc create (some syscalls heavy container) && runsc start (container)
2. `pgrep 'exe' | xargs -I '{}' cat /proc/{}/stat | awk 'BEGIN {print "pgrp pid cmd name: utime ktime"} { ("cat /proc/"$1"/cmdline") | getline t; print $5 " " $1 " " substr(t, 0, 11) " " $2 ": " $14*10 " " $15*10; a+=$14+$15;} END { print "=" a*10 "ms" }'` # sum utime+ktime for all runsc-* processes and [exe] child - the time the container processes spent to startup.

Example
===

1. Only 1 starting container:

```
root@6d1f97978a0c:/# pgrep 'exe' | xargs -I '{}' cat /proc/{}/stat | awk '{print $14*10 " " $15*10; a+=$14+$15;} END { print "=" a*10 }'
0 0
260 30
0 0
0 0
0 0
0 0
80 150
500 30
=1050
```

2. 2 starting containers:

```
$ docker run --cpuset-cpus 4,5 -it --privileged --rm MY-IMAGE-WITH-GVISOR
# issue creation of 2 containers with runsc create+start in parallel.
root@4d2a8ad01ce9:/# pgrep 'exe' | xargs -I '{}' cat /proc/{}/stat | awk 'BEGIN {print "pgrp pid cmd name: utime ktime"} { ("cat /proc/"$1"/cmdline") | getline t; print $5 " " $1 " " substr(t, 0, 11) " " $2 ": " $14*10 " " $15*10; a+=$14+$15;} END { print "=" a*10 "ms" }'
pgrp pid cmd name: utime ktime
563 563 runsc-gofer (exe): 0 0
565 565 runsc-gofer (exe): 0 10
566 566 runsc-sandb (exe): 1560 150
574 574 runsc-sandb (exe): 1540 150
627 627 runsc-sandb (exe): 0 0
627 628 runsc-sandb (exe): 0 0
630 630 runsc-sandb (exe): 0 0
630 631 runsc-sandb (exe): 0 0
630 654 runsc-sandb (exe): 0 0
630 655 runsc-sandb (exe): 0 0
630 656 runsc-sandb (exe): 280 390
630 657 runsc-sandb (exe): 1000 150
627 666 runsc-sandb (exe): 0 0
627 667 runsc-sandb (exe): 0 0
627 668 runsc-sandb (exe): 280 420
627 669 runsc-sandb (exe): 1030 140
=7100ms

root@4d2a8ad01ce9:/# ps aux --forest
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         166  0.0  0.0   4188  3200 pts/1    Ss   10:00   0:00 bash
root        2063  0.0  0.0   6756  2688 pts/1    R+   10:25   0:00  \_ ps aux --forest
...
root         563  0.0  0.0 738604 23328 ?        Ssl  10:03   0:00 runsc-gofer --root=/var
root         565  0.0  0.0 738860 23628 ?        Ssl  10:03   0:00 runsc-gofer --platform=
root         566  0.1  0.2 1990312 70140 ?       Ssl  10:03   0:01 runsc-sandbox --platfor
root         630  0.0  0.0  16520   176 ?        Ss   10:03   0:00  \_ [exe]
root         631  0.0  0.0  16520   176 ?        S    10:03   0:00      \_ [exe]
root         654  0.0  0.0  16520   112 ?        S    10:03   0:00      \_ [exe]
root         655  0.0  0.0  16520   112 ?        SN   10:03   0:00      |   \_ [exe]
root         656  0.0  0.1 124048 43560 ?        S    10:03   0:00      \_ [exe]
root         657  0.0  0.1 124048 43560 ?        SN   10:03   0:01          \_ [exe]
root         574  0.1  0.2 1990312 71516 ?       Ssl  10:03   0:01 runsc-sandbox --platfor
root         627  0.0  0.0  16520    52 ?        Ss   10:03   0:00  \_ [exe]
root         628  0.0  0.0  16520    52 ?        S    10:03   0:00      \_ [exe]
root         666  0.0  0.0  16520   128 ?        S    10:03   0:00      \_ [exe]
root         667  0.0  0.0  16520   128 ?        SN   10:03   0:00      |   \_ [exe]
root         668  0.0  0.1 124036 43188 ?        S    10:03   0:00      \_ [exe]
root         669  0.0  0.1 124036 43188 ?        SN   10:03   0:01          \_ [exe]
```

I have no ideas how to explain that. There is no such an issue with the `ptrace`. With `ptrace` platform the resulting time is exactly corresponding to the `Total/N`.

### runsc version

```shell
runsc version release-20230605.0-53-ga8d8bdef46a2
spec: 1.1.0-rc.1
```
```


### docker version (if using docker)

```shell
Client:
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfcd85
 Built:             Mon May 29 15:50:06 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f9ee
  Built:            Mon May 29 15:50:06 2023
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.7.2
  GitCommit:        0cae528dd6cb557f7201036e9f43420650207b58.m
 runc:
  Version:          1.1.7
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```


### uname

`Linux rabbit 6.3.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Jun 2023 20:46:20 +0000 x86_64 GNU/Linux`

### kubectl (if using Kubernetes)

_No response_

### repo state (if built from source)

`release-20230605.0-53-ga8d8bdef4`

### runsc debug logs (if available)

_No response_

**Comment by EtiennePerot** [comment]
Can you provide the output of `cat /proc/cpuinfo`, as well as details on what environment you are running this in? Specifically, is there a CPU limit set on the containers, and is `runsc` itself running within a cgroup that limits its max CPU usage?

**Comment by sitano** [comment]
@EtiennePerot I am attaching the log with the `/proc/cpuinfo` [cpuinfo.log](https://github.com/google/gvisor/files/11847575/cpuinfo.log). The environment is as follows:

- local bare metal machine with the latest Arch Linux on board, Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
- I execute `runsc` inside of the `--privileged` docker container, which means that it has no of any security/performance restrictions. I probably can try running the same thing outside of docker. I just faced it by measuring runtime costs for my supervisor daemon that basically just does `exec()` calls to `runsc create + start` in parallel on request. (`docker run -it --privileged --rm MY-IMAGE-WITH-GVISOR`)
- original tests were done with having CPU & Memory cgroups set to 1000000 and 16777216reserve/268435456limit, but I have just rechecked it with all cgroups removed completely and together with the `-ignore-cgroups` flag. 

> Specifically, is there a CPU limit set on the containers

On the docker privileged container cgroup in which I am running gvisor has no constraints. 

> and is runsc itself running within a cgroup that limits its max CPU usage?

It was the case for the runsc containers yesterday (1000000), but I have rechecked everything without cgroups at all, the results are the same.

I can try to build a reproducer, but it will take some time if I will have any success. For now, I hope I made a mistake somewhere. 
 
- [trial2_1.log](https://github.com/google/gvisor/files/11847614/trial2_1.log)
- [trial2_2.log](https://github.com/google/gvisor/files/11847613/trial2_2.log)

To put a bit of more context the container that I am starting with the gvisor is:

- a default Ruby distro 2.7.8
- with the script that
- loads a tree of usual gems dependencies (thousands of syscalls)
- blocks on the stdin reads

so the executions are pretty much deterministic in steps.

**Comment by avagin** [comment]
I can't reproduce this issue. I wrote a small program that execute the specified number of system calls. Here are steps that I used to reproduce the issue: https://gist.github.com/avagin/1dbd7736083e9fe1ad0983832858d7aa.

**Comment by sitano** [comment]
@avagin testing your reproducer with 8 instances of runsc on my local 8 cores CPU:

- ptrace - `~22s/done` in both 1 and 8 instances cases (`26s/done`)
- systrap - `10s/done` when 1, `60s/done` with `8 instances : 8 cores`

https://gist.github.com/sitano/e2ff4a0463bc1fa545c6102110a1ae69

**Comment by EtiennePerot** [comment]
> @EtiennePerot does it makes sense for you? you were asking about the CPU limit, maybe there is a contention I am not aware of ...

I was asking because the way Systrap works involves the Sentry and the sandboxed processes sometimes spin-looping while waiting on each other, as a means to do avoid context-switching and process scheduling overhead during system call handling. When the number of such spinloops exceeds the number of available cores, some contention is to be expected. There are mitigations in place to throttle this behavior when it detects some thrashing, but as this thread shows, it's not perfect. This is something we should probably document in the [Systrap README](https://github.com/google/gvisor/blob/master/pkg/sentry/platform/systrap/README.md).

Does this problem affect your setup in a significant manner, and if so, can you explain why?

**Comment by sitano** [comment]
> Does this problem affect your setup in a significant manner, and if so, can you explain why?

@EtiennePerot yes. I am not sure if what we are doing is the gvisor primary use case but basically, we are using it to protect our host environment from the malicious user code that we are executing. You can think of AWS-Lambda-like serverless compute system that takes user code in different forms and runs it as fast as it can. Currently, we are running it on `gvisor/ptrace` platform.

Those code pieces are not big and usually do not live longer than minutes and sometimes can span just seconds. The primary concern for this system is to ensure the isolation of running code and its security - the inability to escape jails and escalate privileges. The second concern is performance in terms of startup latency and implied overhead.

So speaking of performance the system has almost always more running tasks (gvisor containers) than the available cores. We allow CPU overcommit there as it perfectly balances out the existing workload and the pushback. Considering that you can't usually tell in advance what the workload will be bounded by primarily - CPU, disks, or network. Basically, we are good, if all executed tasks equally receive a fair amount of CPU time that there is allocated to that system. That changes if the platform (systrap ie) starts to suffer from contention.

In our case, the host environment is even worse as we are not just not allocating the whole CPU cores to the gvisor system but we are running nested gvisor containers inside of the Kubernetes without dedicated CPU cores but with CPU Shares and Limits (that can enable artificial throttling sometimes), and those cores are also shared with all the other Pod external processes that exist on the host.

That's why it is very important in our case that the gvisor execution platform does not degrade if there is contention on the available CPU cores to the working processes. At least not that much.

Hope this helps.

**Comment by EtiennePerot** [comment]
Please try out gVisor with [the above change](https://github.com/google/gvisor/commit/cffce1a94a0849a672de65510c7dbd5bca9a64b3); it should help quite a bit.
