### ISSUE TITLE
Can gvisor container enable IPC with host?

### ISSUE THREAD

**Issue by cilto** [google/gvisor#92]
Hi, does gvisor have any option to enable IPC with host?
For example, runc has option like '--ipc=host' to share IPC name space with host.

I tried to do that in runsc with below options, but it did not work.
/dev/shm was not shared with host in containers.

**Settings:**

In  /etc/docker/daemon.json:
- --file-access=direct
- --overlay=true

Executed command to launch container:

- docker run --runtime=runsc --ipc=host -it ubuntu /bin/bash

**Comment by kevinGC** [comment]
We don't support a host IPC option. I think that gVisor, by its nature, wants to prevent sandboxed processes from communicating with the host directly via shared memory. I would recommend using another method (e.g. networking) to communicate between processes on the host and in gVisor.
