### ISSUE TITLE
Build failure with GCC 10 in systrap/sysmsg 

### ISSUE THREAD

**Issue by jseba** [google/gvisor#9201]
### Description

When building gvisor with commit `ffcbc70b9a4a1e54ede828c649fa6e91aaceeaa3`, this fails to build the sysmsg objects due to GCC not respecting the `-mgeneral-regs-only` flag in glibc headers. I tested this on both Bookworm and Bullseye to rule out a glibc version difference, GCC 11 and above do not exhibit this issue.

```
ERROR: /source/gvisor/pkg/sentry/platform/systrap/sysmsg/BUILD:31:11: Executing genrule //pkg/sentry/platform/systrap/sysmsg:sysmsg_lib failed: (Exit 1): process-wrapper failed: error executing command
  (cd /root/.bazel/sandbox/processwrapper-sandbox/3/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    TMPDIR=/tmp \
  /tmp/build_out/install/edecd2b1233e0abfae42ec33ee10b762/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/root/.bazel/sandbox/processwrapper-sandbox/3/stats.out' /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; /usr/bin/x86_64-linux-gnu-gcc    -Wall -Werror -Wno-unused-command-line-argument -fpie -O2 -fno-builtin -ffreestanding -mgeneral-regs-only -g -Wa,--noexecstack -fno-asynchronous-unwind-tables -fno-stack-protector -c $(echo pkg/sentry/platform/systrap/sysmsg/atomic.h pkg/sentry/platform/systrap/sysmsg/sysmsg.h pkg/sentry/platform/systrap/sysmsg/sysmsg_lib.c pkg/sentry/platform/systrap/sysmsg/sysmsg_offsets.h | tr '\'' '\'' '\''
'\'' | grep -v -E '\''.h$'\'') -o bazel-out/k8-fastbuild-ST-7c31dbc243a2/bin/pkg/sentry/platform/systrap/sysmsg/sysmsg_lib.o')
In file included from /usr/include/stdlib.h:1013,
                 from pkg/sentry/platform/systrap/sysmsg/sysmsg_lib.c:23:
/usr/include/x86_64-linux-gnu/bits/stdlib-float.h: In function 'atof':
/usr/include/x86_64-linux-gnu/bits/stdlib-float.h:26:1: error: SSE register return with SSE disabled
   26 | {
      | ^
pkg/sentry/platform/systrap/sysmsg/sysmsg_lib.c: At top level:
cc1: note: unrecognized command-line option '-Wno-unused-command-line-argument' may have been intended to silence earlier diagnostics
Target //runsc:runsc failed to build
```

Further digging revealed this to be due to the optimization level for amd64, which causes glibc to inline functions in headers. The register allocation for inlined functions happens before the target flags are fully processed (see [here](https://patchwork.ozlabs.org/project/gcc/patch/CAFULd4YxXU=wwE0Yygime6RMMWiR3RwrH=vRXeoGsF8CNoOwsQ@mail.gmail.com/) for more info), so later passes in the compiler see an SSE register being used when SSE has been disabled and throw an error. Setting the optimization level to `-Os` fixes this issue, as evidenced by the preprocessor guards for the `__USE_EXTERN_INLINES` flag:

/usr/include/features.h:
```c
#if __GNUC_PREREQ (2, 7) && defined __OPTIMIZE__ \
    && !defined __OPTIMIZE_SIZE__ && !defined __NO_INLINE__ \
    && defined __extern_inline
# define __USE_EXTERN_INLINES   1
#endif
```

Changing the optimization level seems the least benign versus disabling inlines altogether.

### Steps to reproduce

1. `docker run --rm debian:bullseye`
2. `apt update && apt install --no-install-recommends -y git curl ca-certificates patch build-essential crossbuild-essential-arm64 clang`
3. `curl -Lo /usr/local/bin/bazel https://github.com/bazelbuild/bazel/releases/download/6.2.0/bazel-6.2.0-linux-x86_64 && chmod +x /usr/local/bin/bazel`
4. `git clone https://github.com/google/gvisor`
5. `cd gvisor && bazel build //runsc:runsc

**Comment by EtiennePerot** [comment]
Thanks for the detailed and well-researched bug report.

Changing the optimization level of GCC 10 may well fix this problem, but in general gVisor isn't regularly compiled across multiple GCC versions and tested to ensure that all of them work the same way, with the same level of performance, etc. It is for this reason that the gVisor `Makefile` includes all this weird logic around spawning a `bazel server` Docker container and executing all the compilation steps in there; that way the GCC version is determined by the image version used by that container, rather than whatever is on the host.

I suggest adjusting your workflow to use a similar approach (e.g. by using `make` rather than `bazel`) in order to not have this problem. Is this an option for you?

**Comment by jseba** [comment]
Yes and no, we don't have nested docker support in our CI system easily currently, so using the docker builder would take some work to setup.

Is there any sort of guarantee that binaries built from that builder will work on any Linux host system? We don't use Ubuntu for our metals and part of the reason we build from the same OS as we deploy on is that we've run into issues with pretty much every toolchain leaking host details into their artifacts (glibc is especially notorious for this with its symbol versioning). I understand bazel is much better about this than cmake or autotools, but without a sysroot it's still dependent on the host.

**Comment by avagin** [comment]
runsc is a static linked binary and it has to work on any host system. We build runsc in other environment than where we use it and I don't remember any issues with this.
