### ISSUE TITLE
Support Go 1.21

### ISSUE THREAD

**Issue by misha-ridge** [google/gvisor#9202]
### Description

It would be useful for `gvisor` to support Go 1.21. `pkg/gohacks` doesn't support it (maybe needs just a version bump).

**Comment by avagin** [comment]
https://github.com/google/gvisor/pull/9197

**Comment by prattmic** [comment]
What failure do you see with 1.21? #9197 makes building with 1.22 (HEAD in the Go repo) possible. 1.21 should have been working for a long time now.

**Comment by misha-ridge** [comment]
Mea culpa. I misread the build tags in `pkg/gohacks` and didn't verify if the latest version compiles.
