### ISSUE TITLE
Want to know why gvisor doesn't support maskedPaths and readonlyPaths in OCI spec

### ISSUE THREAD

**Issue by terenceli** [google/gvisor#9245]
### Description

It seems that gVisor doesn't support maskedPaths and readonlyPaths in OCI spec.

https://github.com/opencontainers/runtime-spec/blob/main/config-linux.md#masked-paths

Is there any consideration about this?

**Comment by kevinGC** [comment]
I don't think these have been brought up before. `readonlyPaths` support could be added. If I understand the common use case for `maskedPaths` correctly (hiding certain `/proc/` files), I don't think it'll matter much: applications in gVisor see a virtual `/proc/` anyways.

**Comment by terenceli** [comment]
@kevinGC The maskedPaths not only uses for hiding /proc, it can also be used hidden other directory/files. So I think the gvisor needs support it if there are not other consideration.

**Comment by kevinGC** [comment]
I see. We'd definitely accept a PR for the feature. @ayushr2 would know better than me how it might be implemented. I'm guessing this is done efficiently by placing read-only files at those paths in some overlay.

**Comment by ayushr2** [comment]
Hi, thanks for reporting this issue. I don't think overlay will help with this, overlay has the side-effect of making the lower-layer (the mount being overlaid) read-only. But that is not what we would want. Overlays have a concept of whiteouts, which is used to hide files/directories at certain positions. So yeah, that part would have helped.

`maskedPaths` is implemented by runc [like this](https://github.com/opencontainers/runc/blob/74c125d8775e59f3b2d188cc362f4a24d2980e4e/libcontainer/rootfs_linux.go#L1089).
> // For files, maskPath bind mounts /dev/null over the top of the specified path.
> // For directories, maskPath mounts read-only tmpfs over the top of the specified path.

But like Kevin mentioned, many filesystems in gvisor (/proc, /sys, /dev, ...) are generated in the sentry. gVisor does not expose the host procfs, sysfs, devfs, etc mounts. So performing the above mentioned mounts of /dev/null or tmpfs on the host from the container's mount namespace won't help.

I think the right solution would be to perform these mount operations **in the sentry**, after the VFS has initialized. So the sentry's mount table and dentry tree are updated with these mounts and the mentioned paths are effectively hidden.

Similarly, readonlyPaths is implemented in runc by creating a read-only bind mount [like this](https://github.com/opencontainers/runc/blob/74c125d8775e59f3b2d188cc362f4a24d2980e4e/libcontainer/rootfs_linux.go#L1037). But it seems like we [don't support MS_REMOUNT and MS_REC](https://cs.opensource.google/gvisor/gvisor/+/master:pkg/sentry/syscalls/linux/sys_mount.go;l=49-50;drc=46115504ec3221fb9d9863ad4999a1244baea6fc) yet...

NB. I do seem some discrepancy in documentation in runc.

The OCI spec documentation says
> MaskedPaths masks over the provided paths inside the container.

But runc says (see [opencontainers/runc/libcontainer/configs/config.go](https://github.com/opencontainers/runc/blob/main/libcontainer/configs/config.go))
> MaskPaths specifies paths within the container's rootfs to mask over with a bind mount pointing to /dev/null as to prevent reads of the file."

And runc [initializes this rootfs-only variable with the OCI-spec variable](https://github.com/opencontainers/runc/blob/74c125d8775e59f3b2d188cc362f4a24d2980e4e/libcontainer/specconv/spec_linux.go#L420).
