### ISSUE TITLE
Watchdog hang, nested KVM virtualization in libvirt

### ISSUE THREAD

**Issue by benbuzbee** [google/gvisor#9246]
### Description

Hello,

My gVisor containers are hanging on execute (guest binary does not appear to execute) and triggering watchdog panics in my container. 

We compile gVisor ourselves so I can make any debugging changes you'd be interested in me testing, like extra logs or whatever you need.

I am trying to run this in a libvirt vm with nested virtualization if relevant. Have successfully done this in other cases so this isn't completely new.

[Logs for the issue on commit](https://pastebin.com/rkQdRZXa) 1fe063e93332bcb97f18be1c0ba6ae27553f0808 (HEAD, tag: release-20230627.0)

`runsc exec` also hangs.

### repo state (if built from source)

release-20230627.0

**Comment by benbuzbee** [comment]
I couldnt repro this with other containers so let me try to rule out my own settings before re-opening

**Comment by EtiennePerot** [comment]
Note that (with few exceptions) a specific container being able to make the gVisor process `panic` or hang is a bug from our perspective, because it is a DoS vector for sandboxes.
