### ISSUE TITLE
dotnet works under runsc

### ISSUE THREAD

**Issue by salrashid123** [google/gvisor#93]
Verified dotnet coreclr also workes under runsc.

the following is a minimal app that was verified under runsc.  

```
git clone  https://github.com/GoogleCloudPlatform/distroless
cd distroless/examples/dotnet/
docker build -t testapp .

sudo docker run  --runtime=runc testapp
Hello World


sudo docker run  --runtime=runsc testapp
Hello World
```

I'll verify a larger full web framework and update here so we can also list it under README

**Comment by ianlewis** [comment]
@salrashid123 Feel free to submit the CL yourself!

**Comment by salrashid123** [comment]
while the baseline donet helloworld worked, the baseic default MVC app didn't until recently.


```
$ dotnet --version
2.1.402

$ mkdir runsc_dotnet
$ cd runsc_dotnet/

$ dotnet new mvc
```

```
$ more Dockerfile 
```

```dockerfile
FROM microsoft/dotnet:2.1-sdk AS build-env
ADD . /app
WORKDIR /app
RUN dotnet restore -r linux-x64
RUN dotnet publish  -c Release -r linux-x64

FROM gcr.io/distroless/dotnet
WORKDIR /app
COPY --from=build-env /app /app/
#CMD ["dotnet", "bin/Release/netcoreapp2.1/linux-x64/publish/runsc_dotnet.dll"]
CMD ["bin/Release/netcoreapp2.1/linux-x64/publish/runsc_dotnet"]
```


```
 docker build -t runsc_dotnet
 docker run --runtime=runsc -t -e ASPNETCORE_URLS=http://0.0.0.0:8080 -p 8080:8080 runsc_dotnet
```

i don't mind adding in a PR to cite dotnet but whats the criteria to say 'its tested'
 - https://github.com/google/gvisor#what-works

are we running the actual language or app unittests within a gvisor container
- https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/RunningTests.md
