### ISSUE TITLE
Root Mount Propagation Option must Specify Private or Slave: "rshared"

### ISSUE THREAD

**Issue by Patrickmitech** [google/gvisor#9324]
### Description

Installing Docker plugin both CSI based or Docker gives error `root mount propagation option must specify private or slave: "rshared": unknown` 

### Steps to reproduce

docker plugin install < Plugin >

### runsc version

```shell
runsc version release-20230801.0
spec: 1.1.0-rc.1
```

### docker version (if using docker)

```shell
Client:
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfcd85
 Built:             Mon May 29 15:50:06 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f9ee
  Built:            Mon May 29 15:50:06 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.2
  GitCommit:        0cae528dd6cb557f7201036e9f43420650207b58.m
 runsc:
  Version:          release-20230801.0
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### uname

Linux patrick 6.1.38-1-lts #1 SMP PREEMPT_DYNAMIC Thu, 06 Jul 2023 13:07:19 +0000 x86_64 GNU/Linux

### runsc debug logs (if available)

```shell
I0830 23:17:49.312825   23747 main.go:180] ***************************
I0830 23:17:49.312860   23747 main.go:181] Args: [/usr/local/bin/runsc --network=host --debug-log=/tmp/runsc/ --debug --strace --root /var/run/docker/runtime-runc/plugins.moby --log /run/containerd/io.containerd.runtime.v2.task/plugins.moby/3b2c31b141fe62ce44e8ae6e888f565a05c729b57af534b9baec53bc36fe230c/log.json --log-format json --systemd-cgroup create --bundle /run/containerd/io.containerd.runtime.v2.task/plugins.moby/3b2c31b141fe62ce44e8ae6e888f565a05c729b57af534b9baec53bc36fe230c --pid-file /run/containerd/io.containerd.runtime.v2.task/plugins.moby/3b2c31b141fe62ce44e8ae6e888f565a05c729b57af534b9baec53bc36fe230c/init.pid 3b2c31b141fe62ce44e8ae6e888f565a05c729b57af534b9baec53bc36fe230c]
I0830 23:17:49.312887   23747 main.go:182] Version release-20230801.0
I0830 23:17:49.312893   23747 main.go:183] GOOS: linux
I0830 23:17:49.312898   23747 main.go:184] GOARCH: amd64
I0830 23:17:49.312905   23747 main.go:185] PID: 23747
I0830 23:17:49.312914   23747 main.go:186] UID: 0, GID: 0
I0830 23:17:49.312920   23747 main.go:187] Configuration:
I0830 23:17:49.312926   23747 main.go:188] 		RootDir: /var/run/docker/runtime-runc/plugins.moby
I0830 23:17:49.312932   23747 main.go:189] 		Platform: systrap
I0830 23:17:49.312938   23747 main.go:190] 		FileAccess: exclusive
I0830 23:17:49.312945   23747 main.go:191] 		Directfs: true
I0830 23:17:49.312951   23747 main.go:192] 		Overlay: root:self
I0830 23:17:49.312958   23747 main.go:193] 		Network: host, logging: false
I0830 23:17:49.312965   23747 main.go:194] 		Strace: true, max size: 1024, syscalls: 
I0830 23:17:49.312971   23747 main.go:195] 		IOURING: false
I0830 23:17:49.312979   23747 main.go:196] 		Debug: true
I0830 23:17:49.312985   23747 main.go:197] 		Systemd: true
I0830 23:17:49.312991   23747 main.go:198] ***************************
W0830 23:17:49.313751   23747 specutils.go:123] noNewPrivileges ignored. PR_SET_NO_NEW_PRIVS is assumed to always be set.
W0830 23:17:49.313777   23747 util.go:64] FATAL ERROR: reading spec: root mount propagation option must specify private or slave: "rshared"
W0830 23:17:49.313841   23747 main.go:224] Failure to execute command, err: 1
```

**Comment by ayushr2** [comment]
Rootfs mount propagation option (as specified in OCI spec in [`spec.Linux.RootfsPropagation`](https://github.com/opencontainers/runtime-spec/blob/305605aedde9a7170b22e4b99bc9e56810969ff8/specs-go/config.go#L230)) should not be shared. As the error mentions, this option should specify private or slave (if specified at all). Shared propagation would break the sandbox's isolation, as documented [here](https://cs.opensource.google/gvisor/gvisor/+/master:runsc/specutils/fs.go;l=80-83;drc=05bd5da34825b42fb8c3cd6687916a0c3c807d0b).

Related: https://github.com/opencontainers/runc/issues/1755

**Comment by ayushr2** [comment]
In other words, this is working as intended. Do you require the rootfs to have shared propagation? If not, please remove the `RootfsPropagation` option from the container spec and it should work.

**Comment by ayushr2** [comment]
Could you tell which plugin you are trying to use?

> I was testing if the docker plugin can be enabled with gVisor

Is there a "docker" Docker plugin that you are trying to use? Or are you testing if docker plugins in general work or not?

I tried using a [sample plugin](https://docs.docker.com/engine/extend/#debugging-plugins) from Docker documentation. It seemed to work fine with gVisor:
```
$ docker plugin install tiborvass/sample-volume-plugin
latest: Pulling from tiborvass/sample-volume-plugin
Digest: sha256:00b42de88f3a3e0342e7b35fa62394b0a9ceb54d37f4c50be5d3167899994639
eb9c16fbdc53: Complete 
Installed plugin tiborvass/sample-volume-plugin
$ docker plugin ls
ID             NAME                                    DESCRIPTION                         ENABLED
089be7bfac20   tiborvass/sample-volume-plugin:latest   A sample volume plugin for Docker   true
$ docker volume create -d tiborvass/sample-volume-plugin samplevol
samplevol
$ docker run --runtime=runsc --rm -v samplevol:/tmp ubuntu echo hello
hello
```

**Comment by Patrickmitech** [comment]
am trying to install a CSI-compatible plugin `ollijanatuinen/swarm-csi-nfs:v4.1.0`  even with just `vieux/sshfs`.
```
Plugin "ollijanatuinen/swarm-csi-nfs:v4.1.0" is requesting the following privileges:
 - network: [host]
 - mount: [/etc/hostname]
 - capabilities: [CAP_SYS_ADMIN]
Do you grant the above permissions? [y/N] y
v4.1.0: Pulling from ollijanatuinen/swarm-csi-nfs
Digest: sha256:0ea452bf0c8e6b9280c79e23ea39274898d6eac86b93451cdc707d7674a304b9
0d607dafa59e: Complete 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: reading spec: root mount propagation option must specify private or slave: "rshared": unknown
```
It works if I use `runc` but if its `runsc` it will be downloaded but not enabled

**Comment by ayushr2** [comment]
> In my daemon.json I set default-runtime to runsc

I see, that is a very relevant detail. I can now reproduce this too. So when using runsc as your default runtime, installing any docker plugin fails with the above error. The plugin is downloaded alright, but to enable it, Docker spawns a container with `spec.Linux.RootfsPropagation = rshared`, which fails with gVisor.

**Comment by ayushr2** [comment]
The sandbox's mount table is maintained in sentry memory. Mount operations in the container are not propagated to the host. So even if we allow this mount option (i.e. `MS_SHARED|MS_REC`), the mount operations from the container will not appear on the host, as the application might expect. (For example, volume plugins won't work as expected.) So it will lead to wrong behavior. Hence we disallow this option.
