### ISSUE TITLE
Unable to checkpoint containers started with `-nvproxy`

### ISSUE THREAD

**Issue by luiscape** [google/gvisor#9363]
### Description

I am interested in checkpointing containers that have `-nvproxy` enabled. I am currently not interested in restoring GPU state (i.e. no actual GPUs are exposed, `NVIDIA_VISIBLE_DEVICES=none`), and only want to re-map host driver files (the ones exposed via [libnvidia-container](https://github.com/NVIDIA/libnvidia-container)) to the restored container. 

Attempting to checkpoint a container started with `-nvproxy` fails with:

```
struct nvproxy.objsMutex does not implement SaverLoader
```

Complete stack trace attached in debug logs.

### Steps to reproduce

```shell
# Start container
mkdir bundle && cd bundle
docker export $(docker create ubuntu) | sudo tar -xf - -C rootfs --same-owner --same-permissions
runsc spec -- sleep 60
runsc -nvproxy run hello

# Attempt to checkpoint container
runsc checkpoint -image-path ./checkpoint hello
```

### runsc version

```shell
runsc version release-20230904.0
spec: 1.1.0-rc.1
```

### uname

Linux ip-172-31-80-111 5.13.0-1029-aws #32~20.04.1-Ubuntu SMP Thu Jun 9 13:03:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### runsc debug logs (if available)

[runsc.log.20230912-205611.194108.checkpoint.txt](https://github.com/google/gvisor/files/12590972/runsc.log.20230912-205611.194108.checkpoint.txt)

**Comment by luiscape** [comment]
We would be happy to explore this issue and work on a patch. We are wondering if (a) you have any plans for making this kind of checkpointing viable or (b) have any guidance on adding a `SaverLoader` interface to `nvproxy` objects.

**Comment by milantracy** [comment]
iirc @ayushr2 is working on the checkpoint with --nvproxy

**Comment by ayushr2** [comment]
>  I am currently not interested in restoring GPU state

Got it. Yeah restoring GPU state is actually a very tough problem...

This checkpoint error should be an easy fix. (sent #9385)

But I think the restore is the hard part and might fail. Didn't test it yet, will get back to it next week. Also note that you will need to use `--overlay2=none` for checkpoint restore. The default value (--overlay2=root:self) does not support restore yet. I will fix that in the coming months, but for now please use `--overlay2=none`.

**Comment by luiscape** [comment]
I can verify this works. Thank you for the patch!

```
./runsc -nvproxy -nvproxy-docker -overlay2=none restore -image-path ./checkpoint restore-test
Fri Sep 15 22:01:16 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:1E.0 Off |                 ERR! |
| N/A   33C    P8     9W /  70W |      2MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
CompletedProcess(args=['nvidia-smi'], returncode=0)
```

The container was checkpointed only with:
```
./runsc -nvproxy -overlay2=none checkpoint -image-path ./checkpoint restore-test
```

**Comment by ayushr2** [comment]
Oh, well that's wonderful. :)

**Comment by ayushr2** [comment]
@luiscape FYI https://github.com/google/gvisor/commit/2d90b66af1672255e818da9223f44b1354861092 should add S/R support for all overlay configurations, so you don't need `--overlay2=none` anymore.

**Comment by luiscape** [comment]
Sounds good. Thanks for letting me know.
