### ISSUE TITLE
'nvproxy: unknown allocation class' running text-generation-inference on A100

### ISSUE THREAD

**Issue by thundergolfer** [google/gvisor#9372]
### Description

gvisor is returning `Server error: CUDA error: OS call failed or operation not supported on this OS` when running Huggingface's text-generation-inference server ~across multiple GPUs~. 

The root cause appears to be an unhandled allocation class. From the debug logs:

```
I0913 23:53:26.567492   12244 strace.go:605] [  56:  56] text-generation X ioctl(0x4 /dev/nvidiactl, 0xc0b8464a, 0x7edb250a3ef0) = 0 (0x0) (2.287801ms)
I0913 23:53:26.567536   12244 strace.go:567] [  56:  56] text-generation E ioctl(0x4 /dev/nvidiactl, 0xc028462b, 0x7edb250a3f60)
D0913 23:53:26.567544   12244 frontend.go:746] [  56:  56] nvproxy: allocation class 0x000000f8
W0913 23:53:26.567551   12244 frontend.go:786] [  56:  56] nvproxy: unknown allocation class 0x000000f8
```

### Steps to reproduce

These reproduction steps were run on a custom AMI built on Ubuntu 20.04. The instance was a GCP `a2-ultragpu-2g` with this accelerator configuration: 

```json
  "guestAccelerators": [
    {
      "acceleratorCount": 2,
      "acceleratorType": "projects/modal-prod-123456890/zones/us-east4-c/acceleratorTypes/nvidia-a100-80gb"
    }
  ],
```

**1. Install gvisor**

```bash
ARCH="x86_64"  # all workers are x86
URL="https://storage.googleapis.com/gvisor/releases/master/latest/${ARCH}"
wget -nc "${URL}/runsc" "${URL}/runsc.sha512"
chmod +x runsc
sudo cp runsc /usr/local/bin/runsc
sudo /usr/local/bin/runsc install
sudo systemctl reload docker
```

**2. Add GPU enabling gvisor options**

In `/etc/docker/daemon.json`:

```json
{
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        },
        "runsc": {
            "path": "/usr/local/bin/runsc",
	    "runtimeArgs": ["--nvproxy", "--nvproxy-docker", "-debug-log=/tmp/runsc/", "-debug", "-strace"]

        }
    }
}
```

then run `sudo systemctl reload docker` 

```bash
sudo cp /proc/sys/kernel/random/boot_id /tmp/boot_id
sudo docker run \
--env HUGGING_FACE_HUB_TOKEN=hf_1234 \
--env HUGGINGFACE_TOKEN=hf_5678 \
--runtime=runsc \
--gpus all \
 --mount type=bind,source="/proc/sys/kernel/random/boot_id",target=/proc/sys/kernel/random/boot_id \
--shm-size 1g \
-p 8080:8000 \
-v $volume:/data \
ghcr.io/huggingface/text-generation-inference:1.0.3 --model-id "meta-llama/Llama-2-7b-chat-hf" --port 8000
```

### runsc version

```shell
`runsc version release-20230904.0-29-g3dda3741d8eb
spec: 1.1.0-rc.1`
```

### docker version (if using docker)

```shell
sudo docker version
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:12 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:12 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### uname

`Linux jonathon-gcp-a100-80gb-spot-09-13-2023-devbox-1 5.15.0-1021-gcp #28~20.04.1-Ubuntu SMP Mon Oct 17 11:37:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### runsc debug logs (if available)

[runsc.log.20230913-235327.577309.delete.txt](https://github.com/google/gvisor/files/12603132/runsc.log.20230913-235327.577309.delete.txt)
[runsc.log.20230913-235257.974041.create.txt](https://github.com/google/gvisor/files/12603134/runsc.log.20230913-235257.974041.create.txt)
[runsc.log.20230913-235258.006598.gofer.txt](https://github.com/google/gvisor/files/12603135/runsc.log.20230913-235258.006598.gofer.txt)
[runsc.log.20230913-235258.313209.start.txt](https://github.com/google/gvisor/files/12603136/runsc.log.20230913-235258.313209.start.txt)
[runsc.log.20230913-235327.609014.delete.txt](https://github.com/google/gvisor/files/12603133/runsc.log.20230913-235327.609014.delete.txt)
(150MB) https://modal-public-assets.s3.amazonaws.com/runsc.log.20230913-235258.073790.boot.txt

**Comment by ayushr2** [comment]
As usual, thanks for the detailed bug report!!

**Comment by milantracy** [comment]
the issue should be fixed, let us how it is going :)
