### ISSUE TITLE
mips64 crash in checksum_noasm_unsafe.go

### ISSUE THREAD

**Issue by zx2c4** [google/gvisor#9499]
I'm seeing this on MIPS64 consistently:

```
unexpected fault address 0xc00028000a
fatal error: fault
[signal SIGBUS: bus error code=0x1 addr=0xc00028000a pc=0x207314]

goroutine 34 [running]:
runtime.throw({0x292b89, 0x5})
	runtime/panic.go:1077 +0x58 fp=0xc000212bb8 sp=0xc000212b90 pc=0x5bcc8
runtime.sigpanic()
	runtime/signal_unix.go:858 +0x278 fp=0xc000212c18 sp=0xc000212bb8 pc=0x7d7b0
gvisor.dev/gvisor/pkg/tcpip/checksum.calculateChecksum({0xc00028000a, 0x14, 0xfff5}, 0x0, 0x0)
	gvisor.dev/gvisor@v0.0.0-20230927004350-cbd86285d259/pkg/tcpip/checksum/checksum_noasm_unsafe.go:60 +0x134 fp=0xc000212c78 sp=0xc000212c20 pc=0x207314
gvisor.dev/gvisor/pkg/tcpip/checksum.Checksum(...)
```

Looking at the [code in question](https://github.com/google/gvisor/blob/cbd86285d259/pkg/tcpip/checksum/checksum_noasm_unsafe.go#L56C1-L62C3):

```go
	// Compute the checksum 8 bytes at a time.
	var carry uint
	for len(buf) >= 8 {
		acc, carry = bits.Add(acc, *(*uint)(unsafe.Pointer(&buf[0])), carry)
		buf = buf[8:]
	}
```

Presumably `&buf[0]` is sometimes unaligned, causing traps. Also, don't you mean `uint64` rather than `uint`? Or maybe you want to use `sizeof(uint)` instead of `8`?

**Comment by zx2c4** [comment]
CC @raggi - I started seeing this after applying your commit here: https://git.zx2c4.com/wireguard-go/commit/?id=42ec952eadc297efadc70b9911d5a59bcd2db4a6

- https://build.wireguard.com/wireguard-go/42ec952eadc297efadc70b9911d5a59bcd2db4a6/linux-mips64.log
- https://build.wireguard.com/wireguard-go/42ec952eadc297efadc70b9911d5a59bcd2db4a6/linux-mips64le.log

**Comment by zx2c4** [comment]
CC @kevinGC - I think this might be your code.

**Comment by kevinGC** [comment]
Thanks for finding this -- I wish it were easier for us to test on more architectures. I'll send out a fix and have you verify that it solves the problem.

Regarding `uint` vs `uint64`: this is handled by checking `bits.UintSize` at the top of `calculateChecksum`, but I agree that `uint64` adds clarity.

**Comment by kevinGC** [comment]
Can you try #9500? I don't have a MIPS64 machine to test on.

**Comment by zx2c4** [comment]
I'm just using `GOOS=linux GOARCH=mips64 go test -exec qemu-mips64 ./...`. I tested this and it works. Thanks for the quick fix.

**Comment by kevinGC** [comment]
- Glad to know the trick for testing with qemu, thanks.
- Just FYI the checksum function that'll run on MIPS64 isn't the most optimized version, as nobody has ported it to big endian machines yet.
