### ISSUE TITLE
implementation of TCP/UDP connection info in procfs

### ISSUE THREAD

**Issue by YvesChan** [google/gvisor#98]
While using netstack in gvisor, there's no content in `/proc/net/{tcp,udp}` file.  So all commands (e.g. ss) rely on these procfs files won't work until they are implemented in netstack. 

Is there any plan for supporting this feature? Thanks

**Comment by fvoznika** [comment]
Yes, we're focusing on tool support and should start closing the gaps on this front. Patches are also very welcome! :-)

**Comment by mrahatm** [comment]
Fixed by 94a6bfab5d0a2a1950915d7db9cd5e1502de8c13 and 863e11ac4d6a49787cd5e5f6fe1cd771d0ceb100
