### ISSUE TITLE
Unable to connect to sandbox-created Unix domain socket when waiting for connection using epoll_ctl

### ISSUE THREAD

**Issue by gmwiz** [google/gvisor#9848]
### Description

I'm trying to run MongoDB using gVisor in a way that MongoDB will listen on a Unix-domain socket and a connection to it will be made outside of the sandbox. This simple setup does not work on any version of MongoDB I tried so far, but works on pretty much any other application I've tried.
This reproduces easily on the latest gVisor version (20231218.0), and happens also when invoked under `podman` or directly using `runsc` with the default OCI spec emitted by `runsc spec` with the addition of the following block under `mounts`:
```
        {
            "destination": "/shared",
            "type": "bind",
            "source": "shared",
            "options": [
                "rbind"
            ]
        }
```

One thing I've noticed that is specific to MongoDB is that the UDS is marked non-blocking, and that the socket is wrapped using the ASIO library. I was able to reproduce this failure when writing a C program that mimics the behavior demonstrated by MongoDB, as observed by strace (see following comment). Another thing to note is that connecting to the shared socket from within the sandbox works as expected.
Any help or guidance will be highly appreciated.

### Steps to reproduce

```
sudo runsc install --runtime runsc-unix-debug -- \
  --host-uds=all \
  --debug \
  --debug-log=/tmp/runsc-debug/ \
  --strace \
  --log-packets
docker run --runtime=runsc-unix-debug -v $(pwd)/shared:/shared --rm -it --entrypoint '' mongo:4.4.26 mongod --bind_ip=/shared/mongo.sock
sudo mongo "mongodb://shared%2fmongo.sock" --shell --verbose
```

Which will hang indefinetly:
```
connecting to: mongodb://shared%2Fmongo.sock/?compressors=disabled&gssapiServiceName=mongodb
D1 NETWORK  [js] creating new connection to:shared/mongo.sock
D1 NETWORK  [js] connected to server shared/mongo.sock
```

### runsc version

```shell
runsc version release-20231218.0
spec: 1.1.0-rc.1
```

### docker version (if using docker)

```shell
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:02 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### uname

6.6.8-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.6.8-1 (2023-12-22) x86_64 GNU/Linux

### runsc debug logs (if available)

[runsc-debug.log](https://github.com/google/gvisor/files/13805741/runsc-debug.log)

**Comment by ayushr2** [comment]
Thanks for the bug report, and for narrowing it down with the reproducer. That was really helpful.

I think I have fixed the issue in https://github.com/google/gvisor/pull/9849. Lets see if the e2e test concur.

**Comment by ayushr2** [comment]
Hoping to have a release on Jan 3rd. cc @manninglucas

**Comment by ayushr2** [comment]
Ah, we released the Monday candidate (which doesn't contain the fix). You can expect us to make a release for 01/08 candidate next Wednesday.
