### ISSUE TITLE
Istio 1.18 iptable rules fail due to inverted destination port match

### ISSUE THREAD

**Issue by Champ-Goblem** [google/gvisor#9865]
### Description

It was noticed on Istio 1.18 that the init-container, which configures the IP table rules, fails to start in gVisor. After examining the rules one-by-one, the following rule fails to validate in gVisor:

```jsx
iptables-legacy -t nat -A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -p tcp -m tcp ! --dport 15008 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
```

This rule can be reduced further to determine that the `! --dport` flag causes issues:

```jsx
iptables-legacy -t nat -A OUTPUT -o lo -p tcp -m tcp ! --dport 1234
```

Fails with the following error message:

```jsx
iptables: Invalid argument. Run `dmesg' for more information.
```

However, removing the `!` allows the rule to create:

```jsx
iptables-legacy -t nat -A OUTPUT -o lo -p tcp -m tcp --dport 1234
```

**Comment by kevinGC** [comment]
Thanks, I didn't know Istio wrote rules like this. Should be a straightforward change to support.

**Comment by Champ-Goblem** [comment]
Hey @kevinGC I have created a PR with the change already if not seen
