### ISSUE TITLE
deadlineTimer.setDeadline may not cancel pending IO

### ISSUE THREAD

**Issue by snyh** [google/gvisor#9885]
### Description

Consider three calls to deadlineTimer.setDeadline:
1. First call set a timeout of 10 seconds.
2. Second call set a zero value of time.Time(remove the timeout).
3. Third call set an ancient time of time.Time(to cancel pending IO)
pending IO would not be immediately cancelled after the third call, it only got cancelled after the initial 10 seconds timeout.

According to the current implementation:
1. First call would create a timer to close the channel(used to cancel pending IO)
2. Second call would stop the timer, and return earlier
3. Third call would failed to stop the timer(because it's already stopped), thus create a new cancel channel. But the previous channel is not closed yet, thereby the pending IO is not cancelled.

```
// setDeadline contains the shared logic for setting a deadline.
//
// cancelCh and timer must be pointers to deadlineTimer.readCancelCh and
// deadlineTimer.readTimer or deadlineTimer.writeCancelCh and
// deadlineTimer.writeTimer.
//
// setDeadline must only be called while holding d.mu.
func (d *deadlineTimer) setDeadline(cancelCh *chan struct{}, timer **time.Timer, t time.Time) {
	if *timer != nil && !(*timer).Stop() {
		*cancelCh = make(chan struct{})
	}

	// Create a new channel if we already closed it due to setting an already
	// expired time. We won't race with the timer because we already handled
	// that above.
	select {
	case <-*cancelCh:
		*cancelCh = make(chan struct{})
	default:
	}

	// "A zero value for t means I/O operations will not time out."
	// - net.Conn.SetDeadline
	if t.IsZero() {
		return
	}

	timeout := t.Sub(time.Now())
	if timeout <= 0 {
		close(*cancelCh)
		return
	}

	// Timer.Stop returns whether or not the AfterFunc has started, but
	// does not indicate whether or not it has completed. Make a copy of
	// the cancel channel to prevent this code from racing with the next
	// call of setDeadline replacing *cancelCh.
	ch := *cancelCh
	*timer = time.AfterFunc(timeout, func() {
		close(ch)
	})
}

```

### Steps to reproduce

Here's the test code to reproduce this:
```
package gonet

import (
	"sync"
	"testing"
	"time"
)

func TestSetDeadline(t *testing.T) {
	timer := &deadlineTimer{}
	timer.init()

	wg := sync.WaitGroup{}
	ch := timer.readCancel()
	wg.Add(1)
	go func() {
		defer wg.Done()
		select {
		case <-ch:
		case <-time.After(1 * time.Second):
			t.Fail()
		}
	}()
	timer.SetReadDeadline(time.Now().Add(10 * time.Second))
	timer.SetReadDeadline(time.Time{})
	timer.SetReadDeadline(time.Unix(1, 0)) // this should cancel ch immediately
	wg.Wait()
}
```

**Comment by ayushr2** [comment]
Thanks for the reproducer. I think #9890 should fix the bug. The "zero value" case basically means there is no timer. So we should set the timer pointer to nil, so future calls don't try to see timer.Stop() which will incorrectly indicate that the timer has expired.

I added your test as-is and added you as a co-author.
