### ISSUE TITLE
file permission problem while using file-access=direct

### ISSUE THREAD

**Issue by YvesChan** [google/gvisor#99]
Is file-access an experimental option of daemon.json in gvisor?  I found this option in code, but not in documentations.
When I try to use file-access=direct to bypass gofer, the official nginx image cannot work properly. It seems like the file relative syscalls fail due to `Operation not permitted`.

### problem details

$ docker run -d --runtime=runsc --rm nginx   // container fail to bootup

try to debug inside container:
$ docker run -it --runtime=runsc --rm --entrypoint bash nginx

```
$ nginx -c /etc/nginc/nginx.conf
[emerg] 45#45: chown("/var/cache/nginx/client_temp", 101) failed (1: Operation not permitted)
nginx: [emerg] chown("/var/cache/nginx/client_temp", 101) failed (1: Operation not permitted)
```

It's `SetOwner`'s implementation in  host(direct) mode which cannot change owner.

**Comment by fvoznika** [comment]
Yes, `file-access=direct` is only experimental and we're about to remove it from the code.

**Comment by YvesChan** [comment]
@fvoznika So is it impossible for user to bypass gofer for performance purpose?

**Comment by amscanne** [comment]
Is this performance purely in the context of nginx?

**Comment by YvesChan** [comment]
@amscanne Nginx is one of our benchmark model.

**Comment by fvoznika** [comment]
Bypassing the gofer requires the sandbox to run with less strict security. Many of the things we do to limit what a compromised sandbox could do to the host are incompatible with `--file-access=direct`. The sandbox would need to join the user namespace and apply the same capabilities (at least for the FS related ones, like CAP_FOWNER). In addition, the seccomp profile applied to the sandbox would need to be loosen up to allow extra syscalls. Most importantly, with a gofer, the sandbox is not allowed to call open(2) to gain information about the system. The sandbox is required to ask the gofer, which is isolated from the untrusted application, to validate the request and open the file.

**Comment by fvoznika** [comment]
For nginx benchmarks specifically, the gofer is called to walk directories and open files. Once the file is open, the sandbox reads and writes directly to/from files (i.e. the gofer is not involved). Assuming that your workload is not constantly opening new files, the performance of `--file-access=direct` and `--file-access=exclusive` should be similar.
