### ISSUE TITLE
Unchecked memory size allocation in `state.Load()`

### ISSUE THREAD

**Issue by fish98** [google/gvisor#9916]
### Description

The memory allocation could be triggered by the `state.Load` function with specific input file, leading to excessive memory allocation request in the `loadArray` function at Line 433 of `pkg/state/wire/wire.go`. This request is facilitated by the built-in `make` function call. After confirming that the bug is not security-related (via email), I believe the bug still deserve a fix, which requires a simple range check of the variables being requested.

### Steps to reproduce

```go
// pov.go
package main

import (
        "bytes"
        "io/ioutil"
        "context"
        "gvisor.dev/gvisor/pkg/buffer"
        "gvisor.dev/gvisor/pkg/state"
        "log"
)

func main() {
        ctx := context.Background()
        filename := "path-to-the-input"
        data, err := ioutil.ReadFile(filename)
        if err != nil {
                log.Fatalf("Failed to read file: %s", err)
        }
        var toLoad *buffer.View
        _, _ = state.Load(ctx, bytes.NewReader(data), toLoad)
}
```
The example input file could be as follows:
```bash
$ hexdump input-file                                          
0000000 e0ff fbdc ffde dcff 01dc ff09 fffe ffff
0000010 0000 ffff 00ff 06ff dc00 01dc ff09 00dc
000001f
```
The example input file could result in the allocation of 34359738239 gvisor.Object instances.

### runsc version

The bug exists in the latest stable release (release-20240115.0) and latest master branch.

### runsc debug logs (if available)

```bash
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0x4f0cb2?, 0x7f19e7aa8000?})
        /usr/lib/go/src/runtime/panic.go:1077 +0x5c fp=0x7ffff59f90c8 sp=0x7ffff59f9098 pc=0x43267c
runtime.sysMapOS(0xc000400000, 0x8000000000?)
        /usr/lib/go/src/runtime/mem_linux.go:167 +0x116 fp=0x7ffff59f9110 sp=0x7ffff59f90c8 pc=0x415bf6
runtime.sysMap(0x5d2440?, 0x428ec0?, 0x5e2608?)
        /usr/lib/go/src/runtime/mem.go:155 +0x34 fp=0x7ffff59f9140 sp=0x7ffff59f9110 pc=0x415674
runtime.(*mheap).grow(0x5d2440, 0x4000000?)
        /usr/lib/go/src/runtime/mheap.go:1533 +0x236 fp=0x7ffff59f91b0 sp=0x7ffff59f9140 pc=0x425d76
runtime.(*mheap).allocSpan(0x5d2440, 0x4000000, 0x0, 0x38?)
        /usr/lib/go/src/runtime/mheap.go:1250 +0x1b0 fp=0x7ffff59f9250 sp=0x7ffff59f91b0 pc=0x425490
runtime.(*mheap).alloc.func1()
        /usr/lib/go/src/runtime/mheap.go:968 +0x5c fp=0x7ffff59f9298 sp=0x7ffff59f9250 pc=0x424f3c
traceback: unexpected SPWRITE function runtime.systemstack
runtime.systemstack()
        /usr/lib/go/src/runtime/asm_amd64.s:509 +0x4a fp=0x7ffff59f92a8 sp=0x7ffff59f9298 pc=0x45d9ea
exit status 2
```

**Comment by kevinGC** [comment]
Thanks for the report, but we still think this isn't a bug. Panicking is what we _want_ to do here:

- A statefile causing a too-large allocation is, in every place that `state.Load()` is called, an unrecoverable failure. So a panic is warranted.
- Checking the allocation size before [the call to make](https://github.com/google/gvisor/blob/8555e4139829b883a4785f596c1b872df41d9e6f/pkg/state/wire/wire.go#L433) to avoid running out of memory also poses problems:
  - If we check against a too-small value, we'll cause unnecessary failures.
  - If we check against a too-large value, we'll still just panic as we do now.
  - Trying to guess the "right" value is impossible: we don't know how much is available or what counts as "too much". If users do have a maximum in mind they can use cgroups to enforce it; doing so inside gVisor itself is futile.

Please let me know if I'm misunderstanding or you had a different solution in mind, but the OOM panic behavior seems best to me.
