### ISSUE TITLE
Can netstack obtain the raw TCP/IP data? I want to get the raw data.

### ISSUE THREAD

**Issue by anan-lee** [google/gvisor#9952]
### Description

FYI

**Comment by EtiennePerot** [comment]
Use the `--log-packets` to log packets in human-readable format to the debug log, or `--pcap-log` to log to a PCAP file.

Closing this issue as this is not a bug report. Please use the [gVisor-users mailing list](https://groups.google.com/forum/#!forum/gvisor-users) for support questions.
