### ISSUE TITLE
Printing an empty string to a PTY in Python with `-u` causes the program to hang

### ISSUE THREAD

**Issue by thecodingwizard** [google/gvisor#9955]
### Description

If I make the following Python file:

```
print("")
```

and I run this Python file from within a PTY with the `-u` flag (ie. `python -u main.py` from within a PTY), the program will hang indefinitely.

I think you can run the Python file from within a pty with `import pty; pty.spawn(["python", "-u", "main.py"])`. I used `docker run --rm -it --runtime=runsc python3.11-bullseye /bin/bash` and manually created + ran the file to test.

I suspect it's because this line of code is being run: https://github.com/google/gvisor/blob/2c8e77f5c1d20b376d13467381c2c65bae27172e/pkg/sentry/fsimpl/devpts/line_discipline.go#L241

I believe Python will make a `write()` syscall that writes an empty string to stdout, causing the issue.

I think this also means that `print("something", file=sys.stderr, end="")` won't work, which means that if an exception is raised in a Python script running within a PTY, it will hang forever.

```
raise Exception("hello")
```

^ This will never finish when run inside a PTY with the `-u` flag; I think it's because it makes a `print()` call with `end=""`.

**Comment by kevinGC** [comment]
Thanks for another PR. Similar to the other one, could you add a test to [test/syscalls/linux/pty.cc](https://github.com/google/gvisor/blob/master/test/syscalls/linux/pty.cc)?

I don't like to be too nitpicky about tests for very small changes, but the PTY code especially is finnicky and difficult. Behavior is complex and I just want to ensure we're doing the same thing as Linux.
